### ISSUE TITLE
scratch base image does not apper in the sources list of the build information

### ISSUE THREAD

**Issue by developer-guy** [docker/buildx#1006]
Hello, I'm not sure whether it was done on purpose but when I build my container image from an alpine based image, then inspect the build information, I see the alpine image in the sources list but when I build my image from a scratch image, I couldn't see the scratch image in the list, is that a bug or something? Thanks.

✅ Alpine based image: `devopps/hello-world:buildinfo`
❌ Scratch based image: `devopps/hello-world:buildinfoscratch`

![Screen Shot 2022-03-16 at 13 07 42](https://user-images.githubusercontent.com/16693043/158567197-314a8865-d73a-417f-a2ac-923bcabd742c.png)

**Comment by crazy-max** [comment]
On purpose. `scratch` is not a valid image that can be used as source for reproducibility:

> Using the scratch "image" signals to the build process that you want the next command in the Dockerfile to be the first filesystem layer in your image.

**Comment by developer-guy** [comment]
Okay, but what if I want to know if the image was built from scratch or not.

**Comment by developer-guy** [comment]
Or would you mind explaining a bit more about where I should use this information? What do you mean by reproducibility?
