### ISSUE TITLE
linux/amd64/v2 vs. linux/amd64?

### ISSUE THREAD

**Issue by tricktron** [docker/buildx#1019]
What is the difference between these two? Which one to choose?

**Comment by tonistiigi** [comment]
https://en.wikipedia.org/wiki/X86-64#Microarchitecture_levels

If you don't know why you would need `v2` then always use `linux/amd64`

**Comment by celesteking** [comment]
How do I know what arch level my docker will build for? Is `linux/amd64` symlinked to proper level on my machine? If not, how do I make it so? If yes, how do I check?

**Comment by tonistiigi** [comment]
This was not meant as rude as it might sound. Just that you should always stick to `v1`. The only time you shouldn't is if you specifically build your binary with requiring support for one of the features in the microarchitecture levels link. Do not think that your container is more modern or runs faster from passing a higher version. If you do pass a variant you most likely will need a cross-compiling Dockerfile with `ARG TARGETVARIANT` for it to have any effect on your build at all.
