### ISSUE TITLE
Resolve group failed with v0.8.0

### ISSUE THREAD

**Issue by yifan-gu-anchorage** [docker/buildx#1020]
Hi guys, we hit some target resolving issue after upgrading to v0.8.0 from v0.7.1

version: **v0.8.0**

```
cat buildtest.hcl
group "a" {
  targets = ["b", "c"]
}
group "b" {
  targets = ["d"]
}
group "c" {
  targets = ["b"]
}
target "d" {
  context = "."
  dockerfile = "./testdockerfile"
}

docker buildx bake a -f buildtest.hcl
[+] Building 0.0s (0/0)
error: failed to find target b
```

**Comment by crazy-max** [comment]
@yifan-gu-anchorage what happens here is `d` target cannot be solved twice because it has been already visited by `b` in group `a` so `c` fails to find it. will fix that, thanks for your report.
