### ISSUE TITLE
[feature request] `--mount=type=jobserver`

### ISSUE THREAD

**Issue by kunaltyagi** [docker/buildx#1023]
# Context
Imagine a simple dockerfile:
```dockerfile
FROM Base as stage 1

RUN make large_project_1 -j4

FROM Base as stage_2

RUN make large_project_2 -j4

FROM Base as stage_3

COPY --from stage_1 bin/ bin/
COPY --from stage_2 bin/bin/
```
# Issue faced
Here, each make runs independently. Similarly, if we are running some tests inside (post build, for verification), we can't use [`pytest --jobserver`](https://pypi.org/project/pytest-jobserver/) to get the intended results.

# Details

## Invocation
* Default: `docker buildx build --jobserver=default`, identifies if there is a master job server, else performs the usual behavior
* Custom: `docker buildx build --jobserver=[<id>[=<socket>|R,W]]`

## Usage in Dockerfile

* Artificially limit max parallelism to `N` jobs: `--mount=type=jobserver,jobs=N`
* Select specific jobserver: `--mount=type=jobserver,id=[<socket>|R,W]`

# Useful links
* https://www.gnu.org/software/make/manual/html_node/POSIX-Jobserver.html
* https://www.gnu.org/software/make/manual/html_node/Job-Slots.html

PS: It would be great if docker buildx itself could be a good jobserver citizen. Will allow integration of multiple docker files via a makefile or similar

**Comment by tonistiigi** [comment]
This should be opened in buildkit.

I think `build --jobserver=` is unlikely to get support. `--mount=type=jobserver` maybe connected to the `max-parallelism`  option (and resource controls) could be considered. I'm not quite sure how popular this thing is. We don't really add flags for things that are purely app specific.

**Comment by kunaltyagi** [comment]
> We don't really add flags for things that are purely app specific.
I was wondering how this is app specific? It's a protocol followed cross platform by a lot of "build" applications
