### ISSUE TITLE
 => ERROR [internal] load metadata for docker.io/library/php:1.8.4-apache-buster 

### ISSUE THREAD

**Issue by ZendyGUwU** [docker/buildx#1031]
Build an image from a Dockerfile
PS C:\CN> docker build -t hola-mundo .
[+] Building 2.5s (3/3) FINISHED
 => [internal] load build definition from Dockerfile                                                               0.1s
 => => transferring dockerfile: 102B                                                                               0.0s
 => [internal] load .dockerignore                                                                                  0.1s
 => => transferring context: 2B                                                                                    0.0s
 => ERROR [internal] load metadata for docker.io/library/php:1.8.4-apache-buster                                   2.3s
------
 > [internal] load metadata for docker.io/library/php:1.8.4-apache-buster:
------
failed to solve with frontend dockerfile.v0: failed to create LLB definition: docker.io/library/php:1.8.4-apache-buster: not found

**Comment by tonistiigi** [comment]
That image indeed seems to not exist

```
> docker buildx imagetools inspect docker.io/library/php:1.8.4-apache-buster
error: docker.io/library/php:1.8.4-apache-buster: not found
```
