### ISSUE TITLE
Please release buildx-v0.8.x.linux-arm-v8

### ISSUE THREAD

**Issue by raphaelmatto** [docker/buildx#1059]
The newest Amazon Linux Arm containers use `linux/arm64/v8`, & to use the cheapest EC2 tier (t4g), you can only use Arm. So getting a binary for `buildx` for that arch seems like it would help a lot of people—including me :)

**Comment by thaJeztah** [comment]
I think the arm64 ones should work on that (arm64 = arm/v8)

**Comment by raphaelmatto** [comment]
Perfect, that works—thanks @thaJeztah!
