### ISSUE TITLE
`bake`: build certain targets after their base targets

### ISSUE THREAD

**Issue by skaldesh** [docker/buildx#1064]
According to https://github.com/docker/buildx/blob/master/docs/reference/buildx_bake.md#defining-additional-build-contexts-and-linking-targets one can build multiple targets in a certain order.  

I have the following file `bake.hcl`:
```
group "default" {
    targets = ["builder-base", "builder-avr", "builder-static", "runtime-cuda"]
}

target "builder-base" {
    context = "."
    dockerfile = "builder/.base.dockerfile.gen"
    platforms = ["linux/amd64", "linux/arm64"]
    tags = ["docker.company.m/nlab/builder:dev"]
}

target "builder-avr" {
    context = "."
    dockerfile = "builder/.avr.dockerfile.gen"
    platforms = ["linux/amd64", "linux/arm64"]
    tags = ["docker.company.m/nlab/builder-avr:dev"]
}

target "builder-static" {    
    context = "."
    dockerfile = "builder/.static.dockerfile.gen"
    platforms = ["linux/amd64"]
    tags = ["docker.company.m/nlab/builder-static:dev"]
}

target "runtime-cuda" {
    context = "."
    dockerfile = "runtime/.cuda.dockerfile.gen"
    platforms = ["linux/amd64", "linux/arm64"]
    tags = ["docker.company.m/nlab/runtime-cuda:dev"]
    contexts = {
        "docker.company.m/nlab/builder:dev" = "target:builder-base"
    }
}
```

The `runtime-cuda` image depends on the `builder-base` image.  
First line of the cuda dockerfile is: `FROM --platform=linux/amd64 docker.company.m/nlab/builder:dev AS builder-amd64`

When I then run `docker buildx bake --file bake.hcl --push` it starts building all containers, including `runtime-cuda` right away. What I wanted/expected was, that first `builder-base` (and the other builders concurrently) are being built, and once it's finished, `runtime-cuda` starts to build.

Can somebody help me there please?

EDIT: I have built all of those containers already once, that is why the `builder-base:dev` exists in the registry and the runtime-cuda container can built anyway.

**Comment by tonistiigi** [comment]
Can you post the progress logs you are getting for such build? Or ideally a runnable example. Afaics this should work as expected.

If `runtime-cuda` has other Dockerfile stages that need to be built as well then it is expected that these start to build right away. But it should not use `docker.company.m/nlab/builder:dev` image from registry, but the result of the other target for  `builder-amd64` stage.

**Comment by skaldesh** [comment]
Ah, I think you are right that there is a another stage it can start with right away.  
The third stage of the cuda file is based on a public image and some software gets installed. This can be executed concurrently with the builder stages.  

I have to say, that is impressive! 
Closing this
