### ISSUE TITLE
`bake`: Share build context?

### ISSUE THREAD

**Issue by skaldesh** [docker/buildx#1068]
I have ~10 images in my bake file that all need the same build context.  
Is it possible that instead of transferring the same context 10 times, they share it? So buildx only transfers the context once?

**Comment by tonistiigi** [comment]
Buildkit API does support this but it isn't implemented on buildx side. The cases that need refactoring are the ones where 2 targets could use the same build context but different secrets etc.

background and old wip branch https://github.com/moby/buildkit/pull/934

**Comment by skaldesh** [comment]
Understood, thanks for the answer.  

I have not yet contributed to docker in any form, but my main language is Go. You think I could add this feature or is it not very beginner friendly?

**Comment by tonistiigi** [comment]
Closing in favor of https://github.com/docker/buildx/issues/92
