### ISSUE TITLE
Proposal: flag to list bake targets

### ISSUE THREAD

**Issue by crazy-max** [docker/buildx#1072]
Atm the bake definition needs to be opened to find out available targets. This is not practical and should be available through the cli.

Suggest to add a `--targets` or `--list` flag for `bake` cmd that would list the available targets.

Targets would need a `description` field to be displayed:

```hcl
variable "GO_VERSION" {
  default = "1.17"
}

target "_common" {
  args = {
    GO_VERSION = GO_VERSION
  }
}

target "lint" {
  description = "Validate using golangci-lint and yamllint linters"
  inherits = ["_common"]
  dockerfile = "./hack/dockerfiles/lint.Dockerfile"
  output = ["type=cacheonly"]
}

target "test" {
  description = "Runs tests suite" 
  inherits = ["_common"]
  target = "test-coverage"
  output = ["./coverage"]
}

target "binaries" {
  description = "Build binaries for the current platform"
  inherits = ["_common"]
  target = "binaries"
  output = ["./bin"]
  platforms = ["local"]
}

target "binaries-cross" {
  description = "Build binaries for multi platform"
  inherits = ["binaries"]
  platforms = [
    "darwin/amd64",
    "darwin/arm64",
    "linux/amd64",
    "linux/arm/v6",
    "linux/arm/v7",
    "linux/arm64",
    "linux/ppc64le",
    "linux/riscv64",
    "linux/s390x",
    "windows/amd64",
    "windows/arm64"
  ]
}
```

```
$ docker buildx bake --list
lint:           Validate using golangci-lint and yamllint linters
test:           Runs tests suite
binaries:       Build binaries for the current platform
binaries-cross: Build binaries for multi platform
```

Targets that don't specify a `description` will not be displayed.

This flag cannot be used if a target is specified.

For compose it might be tricky as there is no such field in the compose spec that we could use. Maybe a comment can work in this case but not supported with JSON format:

```hcl
# Build binaries for the current platform
target "binaries" {
  inherits = ["_common"]
  target = "binaries"
  output = ["./bin"]
  platforms = ["local"]
}
```

```yml
services:
  binaries: # Build binaries for the current platform
    build:
      target: binaries
```

Or an extra arg to target:

```hcl
target "binaries" "Build binaries for the current platform" {
  inherits = ["_common"]
  target = "binaries"
  output = ["./bin"]
  platforms = ["local"]
}
```

But again not suitable for a JSON representation as well as a compose file.

Open to suggestions.

**Comment by thaJeztah** [comment]
This looks useful, but wondering if we want to limit it to just targets; variables could be important as well (?) Perhaps a command that (pretty)prints information about the bake file?

**Comment by skaldesh** [comment]
Why exclude targets without a description? I think its useful to have them printed regardless

**Comment by crazy-max** [comment]
We should also take a look at what is currently done in just: https://github.com/casey/just#command-line-options

**Comment by thaJeztah** [comment]
> I think this is a slightly different case than printing out the targets/groups, as far as I'm aware the variables are an hcl-level concept, and are removed upon parsing?

Possibly, yes. My view on this was; _"what information would I be looking for (as a user) that I can pass to `buildx bake` to control the build?"_; one of that is the target to build, but other parameters can be variables that it takes.
