### ISSUE TITLE
failed to compute cache key: failed to calculate checksum of ref

### ISSUE THREAD

**Issue by lucacome** [docker/buildx#1075]
We started getting this error when running our workflow
```
Error: buildx failed with: error: failed to solve: failed to compute cache key: failed to calculate checksum of ref vseuhyvqn4l8k1dz9mg7kjmgb::d29fvtefjg5fqipg4a6jo3lrp: "/dist/kubernetes-ingress_linux_amd64/nginx-ingress": not found
```
that is a binary that is cached and then retrieved using `actions/cache@v3` but now it looks like it's not able to find it. There wasn't any change to the workflow but this error started a couple of days ago. Any ideas on how to get it working?

**Comment by lucacome** [comment]
Hi @crazy-max you can see it here https://github.com/nginxinc/kubernetes-ingress/runs/6096068252?check_suite_focus=true let me know if that's enough.

**Comment by crazy-max** [comment]
> `"/dist/kubernetes-ingress_linux_amd64/nginx-ingress": not found`

Issue with GoReleaser. See https://github.com/goreleaser/goreleaser/issues/3057

**Comment by lucacome** [comment]
Thanks for pointing me to that, I wasn't aware of this new feature in GoReleaser!
