### ISSUE TITLE
builder instance with multiple nodes

### ISSUE THREAD

**Issue by skaldesh** [docker/buildx#1081]
I was wondering, what exactly happens when I create a builder instance with, lets say, two endpoints that support the same platforms.  
Now running a `docker buildx --builder multiendpoint bake --push`, what will happen? Is only the first endpoint getting work, or is it distributed in some way?

**Comment by tonistiigi** [comment]
The node that manually specified `--platform` is chosen first. Then it is based on node order.

**Comment by skaldesh** [comment]
So if my bake file has 10 targets, then it would build 5 on each (assuming both nodes did not specify `--platform` and all targets are for the same platform)

**Comment by tonistiigi** [comment]
No. All on the same node then if they are all for a single platform.

**Comment by skaldesh** [comment]
Thank you!
