### ISSUE TITLE
Error when building arm64 image on x86-64 machine, but no error when building on actual arm64 machine

### ISSUE THREAD

**Issue by sando38** [docker/buildx#1101]
Hello friends,

I have a strange error. When building an ejabberd image with this [Dockerfile](https://github.com/processone/ejabberd/blob/master/.github/container/Dockerfile) and buildx on an x86-64 machine, with this command

`docker buildx build       --platform linux/amd64,linux/arm64    --build-arg VERSION=master  -t "some.registry/name:tag" --push .` 

I get an error for the arm64 part:

`#0 2.122 autogen.sh: applet not found`

However, I am able to build the image on a raspberry pi arm64 with this command and no error:
`docker buildx build       --platform linux/arm64    --build-arg VERSION=master  -t "some.registry/name:tag" --push .` 

I also performed building other images from that particular x86-64 machine for both amd64 and arm64 and they succeed.

Do you guys have any ideas?

Thanks in advance and have a great weekend!

P.S.

Docker version:
```
Client:
 Version:           20.10.15
 API version:       1.41
 Go version:        go1.18.1
 Git commit:        fd82621d35
 Built:             Thu May  5 23:16:45 2022
 OS/Arch:           linux/amd64
 Context:           default
 Experimental:      true

Server:
 Engine:
  Version:          20.10.14
  API version:      1.41 (minimum version 1.12)
  Go version:       go1.18
  Git commit:       87a90dc786
  Built:            Thu Mar 24 08:56:03 2022
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          v1.6.2
  GitCommit:        de8046a5501db9e0e478e1c10cbcfb21af4c6b2d.m
 runc:
  Version:          1.1.1
  GitCommit:        
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0
```

**Comment by Rongronggg9** [comment]
Did you set up QEMU?
```sh
docker run --rm --privileged tonistiigi/binfmt:latest --install all
```

**Comment by sando38** [comment]
Yes, I did. Otherwise it would not work with other images:

> I also performed building other images from that particular x86-64 machine for both amd64 and arm64 and they succeed.

**Comment by pranjaldoshi96** [comment]
Not sure if you've tried the installing `qemu 7.0`. 
IF not follow instructions on https://github.com/docker/buildx/issues/1170 and it should work.

**Comment by sando38** [comment]
Thanks, I will give it a try.

**Comment by crazy-max** [comment]
If someone is willing to make some test with https://github.com/tonistiigi/binfmt/pull/93#issuecomment-1180409687, that would be nice. Thanks.

**Comment by sando38** [comment]
yes, thanks, now I build the image with linux/arm64 on the amd64 machine!
