### ISSUE TITLE
Q: Asterisk in buildx inspect output

### ISSUE THREAD

**Issue by MiroslavMikus** [docker/buildx#1105]
Hey, Im just wondering what the `*` could mean in the buildx inspect output ([Docs](https://docs.docker.com/engine/reference/commandline/buildx_inspect/) somehow misses this info):

![image](https://user-images.githubusercontent.com/29312172/167589068-d9da16f2-12c7-4866-a063-16f45aee09be.png)

Builder was created with:
```
docker buildx create --name buildero --platform linux/arm,linux/arm64,linux/amd64 --use
docker buildx inspect --bootstrap
```

Back story: I have some issues building our .NET app on Windows/WSL2/x64 for Ubuntu/RPI4 linux/arm64 and wondering if this `asterisk` could have something to do with my issue.

My build command:
```
docker buildx build --no-cache --platform linux/arm64 -t sc-be-ed-s:arm -f "docker-be-ed-s" "../." --progress=plain --load
```
The exact issue is: 
```
The RuntimeIdentifier platform 'linux-arm64' and the PlatformTarget 'x64' must be compatible.
```
Which sounds to me like some missing part on the build platform site.

Build for linux/amd64:
```
docker buildx build --no-cache --platform linux/amd64 -t sc-be-ed-s:arm -f "docker-be-ed-s" "../." --progress=plain --load
```
works like a charm.

Any hints?

Thanks up front

**Comment by tonistiigi** [comment]
`*` means the platform was manually set one `buildx create`. The others were automatically detected. If you have multiple nodes in one builder instance then manually set platforms take precendence.

**Comment by MiroslavMikus** [comment]
Thanks @tonistiigi,
I will open a new issue in the docker docs repo :)
