### ISSUE TITLE
Support multiple build contexts in x-bake

### ISSUE THREAD

**Issue by ciaranmcnulty** [docker/buildx#1107]
I can't see any way to do this in the docs / compose-test.go

**Comment by ciaranmcnulty** [comment]
I guess this is maybe something compose should implement?

**Comment by basicdays** [comment]
Just ran into this too. The `x-bake` extension handles a bunch of other `bake` related config parameters, but [the docs](https://docs.docker.com/build/bake/compose-file/#extension-field-with-x-bake) seems to be missing this one.

Not sure how long docker/compose#9461 will take, so at least having a way to pass through values from the compose file to the build would be extremely helpful.

The way the announcement on the Docker blog was worded, I would have expected Docker Compose files under bake to also support multiple build contexts. See wording under heading "Named Contexts in buildx bake" at [the blog post](https://www.docker.com/blog/dockerfiles-now-support-multiple-build-contexts/).

Currently working around this by duplicating build configs in an `hcl` file.
