### ISSUE TITLE
bake doesn't pass env vars to replace values in docker-compose.yaml

### ISSUE THREAD

**Issue by FernandoMiguel** [docker/buildx#111]
Having an environment variable on a tty doesn't seem be passed to buildx, as it was on docker-compose

besides https://github.com/docker/buildx/pull/16 , I don't see an option to pass args 

```sh
export FOO=bar
/usr/libexec/docker/cli-plugins/docker-buildx bake --progress plain -f docker-compose.yml
```

```yml
  image:
    image: image/test:${FOO}
    build:
      context: .
      dockerfile: buildx
```

github.com/docker/buildx v0.2.2-6-g2b03339-tp-docker 2b03339235021a481300385977ca5a70a403b7c0

Client: Docker Engine - Community
 Version:           19.03.0-rc3
 API version:       1.40
 Go version:        go1.12.5
 Git commit:        27fcb77
 Built:             Thu Jun 20 02:02:44 2019
 OS/Arch:           linux/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          19.03.0-rc3
  API version:      1.40 (minimum version 1.12)
  Go version:       go1.12.5
  Git commit:       27fcb77
  Built:            Thu Jun 20 02:01:20 2019
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.2.6
  GitCommit:        894b81a4b802e4eb2a91d1ce216b8817763c29fb
 runc:
  Version:          1.0.0-rc8
  GitCommit:        425e105d5a03fabd737a126ad93d62a9eeede87f
 docker-init:
  Version:          0.18.0
  GitCommit:        fec3683

**Comment by tonistiigi** [comment]
Not sure if we want to support this. Looks quite dangerous to trust random things in current env. For hcl I think we need something better. Is this supported by `docker stack deploy`? Currently, you can set values in the file and override with `--set` if you need to.

@tiborvass

**Comment by FernandoMiguel** [comment]
Yes!! :boom:
