### ISSUE TITLE
failed to copy: httpReadSeeker: failed open: could not fetch content descriptor sha256:xxx from remote: not found

### ISSUE THREAD

**Issue by fengyinqiao** [docker/buildx#1110]
## docker version 
<img width="489" alt="image" src="https://user-images.githubusercontent.com/58540165/167889380-10b48722-60cc-448b-b4ba-101effa321a7.png">

## Dockerfile
<img width="701" alt="image" src="https://user-images.githubusercontent.com/58540165/167891687-2b3b211a-f6ff-4840-afff-7ce1a633f8de.png">

## docker build
<img width="1414" alt="image" src="https://user-images.githubusercontent.com/58540165/167894116-88c40d3b-1774-413d-b2c0-de1d95ead24d.png">

----------------------------------------------------------------------------------
PS: if I remove the --pull option from the docker build instruction or disable DOCKER_BUILDKIT, problem solved
<img width="1416" alt="image" src="https://user-images.githubusercontent.com/58540165/167895064-ad4853cd-976e-4bfe-89ab-74fc03b2a5f4.png">

<img width="1363" alt="image" src="https://user-images.githubusercontent.com/58540165/167895450-18d22ec7-a969-4a2f-b57a-105f8918e2b6.png">

**Comment by fengyinqiao** [comment]
when I changed another image ,problem also solved...
I was confused , what is the key problem, my image or it is a bug for docker's buildkit but occasionally occured?

<img width="1416" alt="image" src="https://user-images.githubusercontent.com/58540165/167897107-ea62451f-e595-426e-acbf-f69a949945c4.png">

**Comment by crazy-max** [comment]
Looks like an issue with the registry `cd.artifactory....`. Can you repro with an image from Docker Hub like `golang:1.16-alpine`?

**Comment by fengyinqiao** [comment]
> Looks like an issue with the registry `cd.artifactory....`. Can you repro with an image from Docker Hub like `golang:1.16-alpine`?

@crazy-max I was working in a private network env and do not have a public internet. The image is maked by `docker save/load`.I can provide the image info by `docker image inspect` or `docker manifest inspect`, do you need?

**Comment by crazy-max** [comment]
> The image is maked by `docker save/load`.

Ok so `cd.artifactory...` is not a registry endpoint, therefore `--pull` should not be used because [with this flag it "always attempt to pull all referenced images"](https://github.com/docker/buildx/blob/master/docs/reference/buildx_build.md#options).

**Comment by fengyinqiao** [comment]
> > The image is maked by `docker save/load`.
> 
> Ok so `cd.artifactory...` is not a registry endpoint, therefore `--pull` should not be used because [with this flag it "always attempt to pull all referenced images"](https://github.com/docker/buildx/blob/master/docs/reference/buildx_build.md#options).
`cd.artifactory...`is a private docker registry endpoint, I save the docker image from public internet and load it in private network and then push it to the private registry.

**Comment by crazy-max** [comment]
> `cd.artifactory...`is a private docker registry endpoint, I save the docker image from public internet and load it in private network and then push it to the private registry.

Ok then I would say it's an issue with your registry. Is there a reverse proxy behind it?

What is the output of `docker buildx imagetools inspect cd.artifactory.../yourimage:tag --format "{{json .}}"`?

> The image is maked by `docker save/load`

If you're using this command to save and load a multi-platform image it will not work as intended because Docker store does not support multi-platform.

**Comment by fengyinqiao** [comment]
> If you're using this command to save and load a multi-platform image it will not work as intended because Docker store does not support multi-platform.
>
I saved both amd64 and arm64 image and load them in private network ,then use `docker manifest create/push` to make and push the multi-platform image to the registry.

**Comment by fengyinqiao** [comment]
> Ok then I would say it's an issue with your registry. Is there a reverse proxy behind it?

 I don't know ,how to check it?

> What is the output of `docker buildx imagetools inspect cd.artifactory.../yourimage:tag --format "{{json .}}"`?

Sorry, no buildx in the private network for creating a buildx-builder need to pull some dependencies from public internet.

**Comment by crazy-max** [comment]
> I don't know ,how to check it?

If this is Artifactory (assumed by the fqdn being used here), then you should ask to your sysadmin.

> Sorry, no buildx in the private network for creating a buildx-builder need to pull some dependencies from public internet.

?

This command doesn't not create a builder but show details of an image from a registry.

**Comment by fengyinqiao** [comment]
> > Sorry, no buildx in the private network for creating a buildx-builder need to pull some dependencies from public internet.
> 
> ?
> 
> This command doesn't not create a builder but show details of an image from a registry.

sorry ,I mistook it with `docker buildx build`, here is the output:
<img width="1426" alt="image" src="https://user-images.githubusercontent.com/58540165/168328248-35129453-d191-477f-b51a-6e5389d70de1.png">
