### ISSUE TITLE
Proposal: weak bake dependencies

### ISSUE THREAD

**Issue by jedevc** [docker/buildx#1112]
Currently, dependencies between targets can be expressed as follows:

```hcl
group "default" {
  targets = ["a", "b"]
}
target "a" {
  dockerfile = "a.Dockerfile"
}
target "b" {
  dockerfile = "b.Dockerfile"
  contexts = {
    ubuntu = "target:a"
  }
}
```

If the user runs `docker buildx bake`, then `a` is built first, then `b` is built using `a` instead of `ubuntu` as it's base image.

However, assume that the user runs `docker buildx bake b` to only build `b` - because `b` depends on `a`, `a` is also built.
If the user has also set `--push`, then *both* `a` and `b` will be built, but only `b` will be pushed.

If `a` is not a perfectly reproducible build (e.g. it installs some packages which don't have fixed version numbers), then when `b` is pushed, it will have an entirely different set of layers than an `a` that was already pushed - sometimes this might not be desirable.

To resolve this, I propose weak references, i.e. references that will only be built if they would otherwise already be built.

e.g. target `b` could become (syntax tbd):

```hcl
target "b" {
  dockerfile = "b.Dockerfile"
  contexts = {
    ubuntu = "weaktarget:a"
  }
}
```

If `docker buildx bake b` is run, then the ubuntu context should not be overwritten because `a` is not being built; conversely if `docker buildx bake a b` is run, then the context should be overwritten.

This proposal would ensure that for scenarios where not all targets are built at the same time, layer sharing can still be used and unnecessary builds don't need to be run.

**Comment by tonistiigi** [comment]
I'm not sure if a special syntax is worth it. The way I show this case in https://www.docker.com/blog/dockerfiles-now-support-multiple-build-contexts/ is a bake file written with:

```
target "a" {
  dockerfile = "a.Dockerfile"
}
target "b" {
  dockerfile = "b.Dockerfile"
}
target "b-stage" {
  inherits = ["b"]
  contexts = {
    ubuntu = "target:a"
  }
}
```

Now `buildx bake b` would build using the release dependencies and `buildx bake b-stage` with local dependencies(same as weak target with multiple input names in your case).

**Comment by thompson-shaun** [comment]
@jedevc - Did we want to re-start discussion on this one or close it out?
