### ISSUE TITLE
docker buildx build --build-context throws a Unknown desc error

### ISSUE THREAD

**Issue by skei0** [docker/buildx#1124]
I want to use a additional context via ```--build-context``` to add some file. But i get this Error:

```
error: failed to solve: rpc error: code = Unknown desc = 
failed to solve with frontend dockerfile.v0: unsupported frontend capability moby.buildkit.frontend.contexts

```
Minimal Example:

I have too folders ```A``` and ```B```. ```À``` has a dockerfile, with needs some file located in ```B``` (```COPY --from=b /some_file_i_need_i_A.txt /```) . 
```.
├── A
│   ├── Dockerfile
│   └── just_some_file.txt
└── B
    └── some_file_i_need_i_A.txt
```

Dockerfile:
```docker
From redis
COPY /just_some_file.txt /
RUN ls -la
COPY --from=b /some_file_i_need_i_A.txt /
RUN ls -la
```

Command to build image:
```bash
user:~/A$ docker buildx build --build-context b=../B .
```

buildx version: 
```
github.com/docker/buildx v0.8.2-docker 6224def4dd2c3d347eee19db595348c50d7cb491
```

What am I doing wrong? Has same one a hint for me? 
By the way thx for buildx and your work!

**Comment by crazy-max** [comment]
@skei0 You need at least Dockerfile 1.4 using the syntax comment or Buildkit 0.10:

```dockerfile
# syntax=docker/dockerfile:1

FROM redis
COPY /just_some_file.txt /
RUN ls -la
COPY --from=b /some_file_i_need_i_A.txt /
RUN ls -la
```

**Comment by skei0** [comment]
@crazy-max Thank you. it works.
