### ISSUE TITLE
Wrong Accept header set when doing a multi-arch build

### ISSUE THREAD

**Issue by caervs** [docker/buildx#114]
## Steps to Reproduce

1. Clone the [Docker doodle](https://github.com/docker/doodle) and `cd` into a doodle dir (e.g. `birthday2019`)

2. Do a multi-arch build and push to a registry
```
docker buildx build -f Dockerfile.cross --platform linux/amd64,linux/arm64,linux/arm/v8,linux/s390x,linux/ppc64le,windows/amd64 -t rabrams-dev.dtr.caas.docker.io/admin/alpine:latest --push .
```

3. Observe that buildx will try to push up individual image manifests before trying to unify into a manifest list. You will get a PUT request to `/v2/admin/alpine/manifests/latest` with the payload

```
{
   "mediaType": "application/vnd.docker.distribution.manifest.v2+json",
   "schemaVersion": 2,
   "config": {
      "mediaType": "application/vnd.docker.container.image.v1+json",
      "digest": "sha256:517227285745b426e5eb4d9d63dedc1b6759c6ac640fd432c0c5f011b709aa74",
      "size": 801
   },
   "layers": [
      {
         "mediaType": "application/vnd.docker.image.rootfs.diff.tar.gzip",
         "digest": "sha256:58fd16eaae0bf5c343b8f43832206c1e7f3ff712bee5257a90cf2b51703b58e9",
         "size": 100457713
      },
      {
         "mediaType": "application/vnd.docker.image.rootfs.diff.tar.gzip",
         "digest": "sha256:3ac6604e4ee640afc57931337dc8691e323d4f52280b2986b4e54b83b179e932",
         "size": 1403916
      }
   ]
}
```

4. Buildx will do a HEAD request for the manifest it just created but set a manifest list header

```
Accept:         application/vnd.docker.distribution.manifest.list.v2+json, *
```

and as a consequence the manifest is considered invalid and the client will get a 400

**Comment by tonistiigi** [comment]
What request goes out with that header? Do you have a trace of all the requests/headers you are seeing?

**Comment by dmcgowan** [comment]
A few questions. Why is it putting the non-index manifests with the tag? What is that HEAD request doing in that case, is it checking for whether those other manifests were already pushed? What does the registry consider invalid about the request as it still accepts `*`? It seems like a descriptor is wrong somewhere though if it is specifying an Accept type and a digest, but that digest is an object of a different type.
