### ISSUE TITLE
add reference of how to initiate a buildkitd for remote driver

### ISSUE THREAD

**Issue by developer-guy** [docker/buildx#1162]
There are various ways to run buildkitd on macOS[^1] or Linux environments. However, I just thought that according to the new feature called `remote` driver that allows us to use self-provisioned buildkitd instance as a builder, it'd be nice to have command examples to show people how they can create a buildkitd on their environments.

WDYT @jedevc? 

[^1]: https://github.com/developer-guy/buildkit-machine

**Comment by jedevc** [comment]
So far, we have https://github.com/docker/buildx/blob/master/docs/guides/remote-builder.md as a guide to how to configure the `remote` driver, is that roughly what you're thinking of?

I think instructions on the different configurations of `buildkitd` are probably more suited to [moby/buildkit](https://github.com/moby/buildkit), where there are some more guides on how to configure buildkitd precisely.

**Comment by developer-guy** [comment]
Ah great, yes, I missed that, thank you
