### ISSUE TITLE
Proposal: annotations helpers

### ISSUE THREAD

**Issue by jedevc** [docker/buildx#1171]
With https://github.com/moby/buildkit/pull/2879 close to merging, I thought I'd propose some new syntax here :tada:

When merged, it'll be possible to use annotations as follows (with no changes to buildx):
```
docker buildx build . --output type=image,name=example/foo,push=true,annotation.x=1 --platform=linux/arm64,linux/amd64
```

However, this isn't ideal, and it would be nice to provide a shorthand, similar to how `--push` appends `push=true`.

## Buildx

For buildx, we can provide the `--annotation` flag:

```
docker buildx build . --output type=image,name=example/foo,push=true --annotation x=1 --platform=linux/arm64,linux/amd64
```

For platform-specific annotations, we can allow prefixing with the platform name:

```
docker buildx build . --output type=image,name=example/foo,push=true --annotation linux/amd64:x=1 --platform=linux/arm64,linux/amd64
```

Not super sure about the exact syntax, but something along those lines should work.

I think we should explicitly avoid allowing using anything other than the `manifest` annotation type, directing users to manually add the output attribute if they want more advanced behavior.

## Bake

For bake, we can add an `annotations` key:

```hcl
target "x" {
    ...
    annotations = {
        "linux/amd64:x" = "1"
    }
    ...
}
```

Comments appreciated :tada:

**Comment by johnsonshi** [comment]
This is nice work @jedevc! I think the experience of allowing multiple `--annotation` flags (like the example below) would allow image builders to support [OCI Annotations](https://github.com/opencontainers/image-spec/blob/main/annotations.md#pre-defined-annotation-keys).

```bash
docker buildx build \
  --annotation 'org.opencontainers.image.authors=authorName' \
  --annotation 'org.opencontainers.image.licenses=Apache' \
  -f Dockerfile -t myimage:latest .
```

I suppose the annotations should be added at the `manifest` type.

---

For multi-arch builds, would the annotations be only in the `manifestList`, or should they also be in each `manifest` within the multi-arch `manifestList`?


```bash
docker buildx build \
  --annotation 'org.opencontainers.image.authors=authorName' \
  --annotation 'org.opencontainers.image.licenses=Apache' \
  --platform=linux/arm64,linux/amd64 \
  -f Dockerfile -t myimage:latest .
```

**Comment by johnsonshi** [comment]
> I think we should explicitly avoid allowing using anything other than the manifest annotation type, directing users to manually add the output attribute if they want more advanced behavior.

Scenario: image build users may want to add annotations to `manifest configs` and `layers`.
The problem is that there is no tool out there today that supports annotating a `manifest config` or a `layer` if a user wants to.

I think we need to explore the experience around specifying annotations for any OCI spec (manifest, manifestList, config, layer, etc) during image build.

**Comment by jedevc** [comment]
So chatting with @tonistiigi and @crazy-max - I think we want to hold off on adding any buildx-specific syntax just for the time being, at least until we can gather some more concrete use cases of how we expect users to interact with this feature.

The buildkit is still accessible by attaching annotations using the exporter options, e.g. `type=image,name=example/foo,push=true,annotation.x=1`.

@developer-guy @chrisdostert since you were both active on the original buildkit issue https://github.com/moby/buildkit/issues/1220, did you have any concrete use cases you were wanting to use annotations for?

**Comment by crazy-max** [comment]
This would be useful for the [metadata-action](https://github.com/docker/metadata-action) where we use labels atm to provide [OCI Image Format Specification](https://github.com/opencontainers/image-spec/blob/master/annotations.md): https://github.com/docker/metadata-action/blob/97c170d70b5f8bfc77e6b23e68381f217cb64ded/src/meta.ts#L440-L453

**Comment by nightah** [comment]
If this was added am I correct in understanding that we can annotate architecture-specific annotations/labels?

I've just been exploring how to set different labels per architecture on a multi-architecture build. I have not had any luck without creating each architecture separately and modifying the final manifest.

If the proposed annotation structure was introduced which is prefixed with the platform e.g: `linux/amd64:org.opencontainers.image.base.digest=xyz` we potentially could at build time?

**Comment by tonistiigi** [comment]
@nightah https://github.com/moby/buildkit/blob/master/docs/annotations.md

**Comment by tonistiigi** [comment]
> but I'm not seeing any of the annotations that I'm attempting to include in a build.

Are you using master buildkit? This feature is not in any release yet. @jedevc Maybe we can make it more clear in the docs.

`docker buildx create --driver-opt image=moby/buildkit:master --use`

> especially those that are specified with annotation-index) be visible in a docker inspect

No (at least not with the current version). You would need to use `docker buildx imagetools inspect`, `ctr` or any other tool that can show you the blobs in the registry storage.

**Comment by nightah** [comment]
> Are you using master buildkit? This feature is not in any release yet. @jedevc Maybe we can make it more clear in the docs.

Looks like this was the key, specifying the master version of buildkit now has annotations on the respective blob.

> No (at least not with the current version).

Does this imply that at some point this is going to change, or already is being considered to change?

**Comment by jedevc** [comment]
> Are you using master buildkit? This feature is not in any release yet. @jedevc Maybe we can make it more clear in the docs.

CC @crazy-max, we've discussed making versioning more clear across all of our docs, not sure if we came up with any solutions?

**Comment by favonia** [comment]
My 2 cents for a concrete proposal. I think this is far from being perfect, but it mimics the `--output` design, and I would love to see progress in this discussion.

| Helper                                    | Output                                |
| ----------------------------------------- | ------------------------------------- |
| `--annotation "key=value"`                | `annotation.key=value`                |
| `--annotation "type:key=value"`           | `annotation-type.key=value`           |
| `--annotation "[platform]:key=value"`     | `annotation[platform].key=value`      |
| `--annotation "type[platform]:key=value"` | `annotation-type[platform].key=value` |

**Comment by jedevc** [comment]
@favonia sorry for the delay in getting back to you - I think the design you suggest is good - I'd be happy with that.

I currently don't have the time to work on this, but I'll mark this issue as `help wanted` - if anyone wants to help by putting together a PR, I'm happy to help out where I can :heart:
