### ISSUE TITLE
Unable to use multiple build definition files with `bake`

### ISSUE THREAD

**Issue by Apakottur** [docker/buildx#1172]
I am unable to use `docker buildx bake` to build a docker image based on two docker-compose files.

To reproduce, create three files, all in the same directory:
```dockerfile
# Dockerfile
FROM ubuntu:latest
```
```yml
# docker-compose.yml
services:
  test:
    build:
      context: .
    entrypoint: echo 1
```
```yml
# docker-compose.prod.yml
services:
  test:
    entrypoint: echo 2
```

The idea is to have the core configuration of an image in the base yml file, and then have another one with overrides (for a prod environment, for example).
I can then build and run the base/prod images like so:
```shell
$ docker-compose build
$ COMPOSE_FILE=docker-compose.yml docker-compose run --rm test
1
$ COMPOSE_FILE=docker-compose.yml:docker-compose.prod.yml docker-compose run --rm test
2
```

The [buildx docs](https://github.com/docker/buildx/blob/master/docs/reference/buildx_bake.md#-specify-a-build-definition-file--f---file) say that `If multiple files are specified they are all read and configurations are combined`.

However, when I try to use both files with buildx:
```shell
docker buildx bake -f docker-compose.yml -f docker-compose.prod.yml test
```
I am getting:
```shell
error: service "test" has neither an image nor a build context specified: invalid compose project
```

Am I missing something, or is this a bug?

**Comment by crazy-max** [comment]
As I can see, consistency check added in https://github.com/docker/buildx/pull/87 is already handled by the library: https://github.com/compose-spec/compose-go/blob/c45b40b31e66dbc3966642803d133bba33680b21/loader/validate.go#L31-L33

Now with compose v2, I think we can skip the consistency check and remove the dup check in bake as well and just use the default values. In this case it would produce:

```yaml
# docker-compose.yml
services:
  test:
    build:
      context: .
      tags:
        - docker.io/username/webapp:latest
    entrypoint: echo 1
```


```yaml
# docker-compose.prod.yml
services:
  test:
    entrypoint: echo 2
```

```console
$ docker buildx bake -f docker-compose.yml test --print
{
  "group": {
    "default": {
      "targets": [
        "test"
      ]
    }
  },
  "target": {
    "test": {
      "context": ".",
      "dockerfile": "Dockerfile",
      "tags": [
        "docker.io/username/webapp:latest"
      ]
    }
  }
}
```

```console
$ docker buildx bake -f docker-compose.prod.yml test --print
{
  "group": {
    "default": {
      "targets": [
        "test"
      ]
    }
  },
  "target": {
    "test": {
      "context": ".",
      "dockerfile": "Dockerfile"
    }
  }
}
```

```console
$ docker buildx bake -f docker-compose.yml -f docker-compose.prod.yml test --print
{
  "group": {
    "default": {
      "targets": [
        "test"
      ]
    }
  },
  "target": {
    "test": {
      "context": ".",
      "dockerfile": "Dockerfile",
      "tags": [
        "docker.io/username/webapp:latest"
      ]
    }
  }
}
```

WDYT @tonistiigi?

**Comment by Apakottur** [comment]
@crazy-max @tonistiigi Thanks a lot for the fix!

I am using `buildx` via the [GitHub Action](https://github.com/docker/setup-buildx-action), but it seems that pointing the buuldx version in the action to `master` triggers a very lengthy build, presumably buildx is compiled from scratch?

Is there a testing release I can point the action to, so that I can use this fix?
