### ISSUE TITLE
"dial tcp: lookup" "no such host" for kubernetes node, when combining with docker-driver node (TLS DOCKER_HOST)

### ISSUE THREAD

**Issue by jobcespedes** [docker/buildx#1186]
## Summary
Error about "dial tcp: lookup" "no such host" for kubernetes node, when combining with docker-driver node (TLS DOCKER_HOST):
`kubernetes:///multiarch-builder?deployment=&kubeconfig= error during connect: Get "http://%2Fmultiarch-builder%3Fdeployment=&kubeconfig=/v1.24/info": dial tcp: lookup /multiarch-builder?deployment=&kubeconfig=: no such host`

## Reproduce
```
# docker context create --docker host=tcp://public_dns:2376,ca="/tmp/ca.pem",cert="/tmp/cert.pem",key="/tmp/key.pem" arm64
docker buildx create --append --name=multiarch-builder --platform=linux/amd64 --driver=kubernetes amd64
## At this point, there is no error with amd64 node
docker buildx create --append --name multiarch-builder --driver docker-container --platform linux/arm64 arm64
## At this point, there is an error with amd64 node, no error with arm64 node
```
## Info
Buildx version: `github.com/docker/buildx v0.8.2 6224def4dd2c3d347eee19db595348c50d7cb491`
Docker info:
```
Client:
 Context:    default
 Debug Mode: false
 Plugins:
  buildx: Docker Buildx (Docker Inc., v0.8.2)
  pushrm: Push Readme to container registry (Christian Korneck, 1.7.0)

Server:
 Containers: 3
  Running: 3
  Paused: 0
  Stopped: 0
 Images: 2315
 Server Version: 20.10.16
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Native Overlay Diff: true
  userxattr: false
 Logging Driver: journald
 Cgroup Driver: systemd
 Cgroup Version: 1
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: runc io.containerd.runc.v2 io.containerd.runtime.v1.linux
 Default Runtime: runc
 Init Binary: /usr/libexec/docker/docker-init
 containerd version: 
 runc version: eae618f-dirty
 init version: 
 Security Options:
  seccomp
   Profile: default
  selinux
 Kernel Version: 5.17.12-100.fc34.x86_64
 Operating System: Fedora 34.20220605.0 (Silverblue)
 OSType: linux
 Architecture: x86_64
 CPUs: 4
 Total Memory: 11.62GiB
 Name: silverblue
 ID: FD2Q:A7PL:6S4O:GQTH:MMFT:QYHM:M2DD:Q6ZM:DEME:VHLZ:LWSY:HCRT
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 Username: jobcespedes
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: true
```

**Comment by jedevc** [comment]
Heya @jobcespedes, I'm not able to reproduce with the steps you've given, so wanted to check a couple things:

1. Does the driver ever work? After creating it, are you ever able to start a build?
    Could you try running your `buildx create` command with `--bootstrap`, to see if the buildkit container starts up?
2. Is your kubernetes environment accessible using `kubectl`?
3. Is there a reason you're mixing-and-matching drivers on a single builder? A single builder can only have a single driver, so using `docker-container` and `kubernetes` together shouldn't work.

**Comment by crazy-max** [comment]
> ```
> # docker context create --docker host=tcp://public_dns:2376,ca="/tmp/ca.pem",cert="/tmp/cert.pem",key="/tmp/key.pem" arm64
> docker buildx create --append --name=multiarch-builder --platform=linux/amd64 --driver=kubernetes amd64
> ## At this point, there is no error with amd64 node
> docker buildx create --append --name multiarch-builder --driver docker-container --platform linux/arm64 arm64
> ## At this point, there is an error with amd64 node, no error with arm64 node
> ```

Can't repro myself. Some commands are missing like the creation of the initial builder `multiarch-builder` you want to append to.

> `docker buildx create --append --name=multiarch-builder --platform=linux/amd64 --driver=kubernetes amd64`

What is `amd64`? Is this your intent to specify the context/endpoint you want to connect to? If so I don't think the `kubernetes` driver takes into account the endpoint addr as it's generated based on its driver opts:

```console
$ docker buildx create --name k3s --driver kubernetes --driver-opt=qemu.install=true --bootstrap k3s1.home.foo.com:6443
k3s

$ docker buildx ls
NAME/NODE              DRIVER/ENDPOINT                        STATUS  BUILDKIT PLATFORMS
k3s                    kubernetes
  k3s0-9cd56555d-kfrph                                        running          linux/amd64, linux/arm64, linux/riscv64, linux/ppc64le, linux/s390x, linux/386, linux/mips64le, linux/mips64, linux/arm/v7, linux/arm/v6
default *              docker
  default              default                                running 20.10.16 linux/amd64, linux/arm64, linux/riscv64, linux/ppc64le, linux/s390x, linux/386, linux/arm/v7, linux/arm/v6

$ cat ~/.docker/buildx/instances/k3s | jq
{
  "Name": "k3s",
  "Driver": "kubernetes",
  "Nodes": [
    {
      "Name": "k3s0",
      "Endpoint": "kubernetes:///k3s?deployment=&kubeconfig=%2Fhome%2Fcrazy%2Fk3s.yaml",
      "Platforms": null,
      "Flags": null,
      "DriverOpts": {
        "qemu.install": "true"
      },
      "Files": null
    }
  ],
  "Dynamic": false
}
```

> `docker buildx create --append --name multiarch-builder --driver docker-container --platform linux/arm64 arm64`

Same for this one, what is `arm64`? Also mixing drivers does not look good. I checked on my side to create a kubernetes builder and append a `docker-container` builder and it seems the kubernetes node is broken after that:

```console
$ docker buildx create --name k3s --driver kubernetes --driver-opt=qemu.install=true --bootstrap k3s1.home.foo.com:6443
k3s

$ docker buildx ls
NAME/NODE              DRIVER/ENDPOINT                        STATUS  BUILDKIT PLATFORMS
k3s                    kubernetes
  k3s0-9cd56555d-kfrph                                        running          linux/amd64, linux/arm64, linux/riscv64, linux/ppc64le, linux/s390x, linux/386, linux/mips64le, linux/mips64, linux/arm/v7, linux/arm/v6
default *              docker
  default              default                                running 20.10.16 linux/amd64, linux/arm64, linux/riscv64, linux/ppc64le, linux/s390x, linux/386, linux/arm/v7, linux/arm/v6

$ docker buildx create --append --name k3s --driver docker-container --bootstrap
#1 [internal] booting buildkit
#1 pulling image moby/buildkit:buildx-stable-1
#1 pulling image moby/buildkit:buildx-stable-1 1.3s done
#1 creating container buildx_buildkit_k3s1
#1 creating container buildx_buildkit_k3s1 0.7s done
#1 DONE 2.0s
k3s

$ docker buildx ls
NAME/NODE     DRIVER/ENDPOINT                                                     STATUS  BUILDKIT PLATFORMS
k3s           docker-container
  k3s0        kubernetes:///k3s?deployment=&kubeconfig=%2Fhome%2Fcrazy%2Fk3s.yaml error
  k3s1        unix:///var/run/docker.sock                                         running v0.10.3  linux/amd64, linux/amd64/v2, linux/amd64/v3, linux/arm64, linux/riscv64, linux/ppc64le, linux/s390x, linux/386, linux/mips64le, linux/mips64, linux/arm/v7, linux/arm/v6
default *     docker
  default     default                                                             running 20.10.16 linux/amd64, linux/arm64, linux/riscv64, linux/ppc64le, linux/s390x, linux/386, linux/arm/v7, linux/arm/v6

Failed to get status for k3s (k3s0): error during connect: Get "http://%2Fk3s%3Fdeployment=&kubeconfig=%252Fhome%252Fcrazy%252Fk3s.yaml/v1.24/info": dial tcp: lookup /k3s?deployment=&kubeconfig=%2Fhome%2Fcrazy%2Fk3s.yaml: no such host  

$ cat ~/.docker/buildx/instances/k3s | jq
{
  "Name": "k3s",
  "Driver": "docker-container",
  "Nodes": [
    {
      "Name": "k3s0",
      "Endpoint": "kubernetes:///k3s?deployment=&kubeconfig=%2Fhome%2Fcrazy%2Fk3s.yaml",
      "Platforms": [],
      "Flags": null,
      "DriverOpts": {
        "qemu.install": "true"
      },
      "Files": null
    },
    {
      "Name": "k3s1",
      "Endpoint": "unix:///var/run/docker.sock",
      "Platforms": null,
      "Flags": null,
      "DriverOpts": {},
      "Files": null
    }
  ],
  "Dynamic": false
}
```

@tonistiigi @jedevc Looks like when appending a node using a different driver, it replaces the original builder driver. I think we should not take into account `--driver` when using `--append` or at least error if mismatch with original one. WDYT?

**Comment by jobcespedes** [comment]
Hi, thanks for taking a lool at this.
@jedevc quastions:
> Does the driver ever work? After creating it, are you ever able to start a build?

Yes. The driver and builds work, as long as I do not mix drivers for the same instance.
> Could you try running your buildx create command with --bootstrap, to see if the buildkit container starts up?

Yes, Buildkit container starts up. Error appears after adding a new node with a different driver
> Is your kubernetes environment accessible using kubectl?

Yes
> Is there a reason you're mixing-and-matching drivers on a single builder? A single builder can only have a single driver, so using docker-container and kubernetes together shouldn't work.

Yes, mixing drivers reduces costs for us. Let me expand a little bit more about this. We are running buildx client in pipelines for CI, on premise k8s clusters. There is native (faster) amd64 (x86_64) infra avaiable with k8s clusters but no native arm64 (aarch64) So, a remote builder for native arm64 is launched on demand in AWS provider with [multiarch-builder terraform module](https://registry.terraform.io/modules/krestomatio/multiarch-builder/aws) during each pipeline (it is terminated once pipeline is run).

**Comment by jobcespedes** [comment]
Hi @crazy-max:
> Some commands are missing like the creation of the initial builder multiarch-builder you want to append to.

The initial builder is created with the first --append command if not found, at least in my case.

> What is amd64? Is this your intent to specify the context/endpoint you want to connect to?

Yes. The intention to name the context/endpoint based on the native architecture the node is. In the case ot amd64 node (running in k8s cluster), the inCluster config applies. For arm64 node (running in a remote EC2 vm), the connection is configured when the respective context is created (command included above).
