### ISSUE TITLE
Rpmdb checksum is invalid: dCDPT(pkg checksums): wget.aarch64 0:1.14-18.el7_6.1 - u

### ISSUE THREAD

**Issue by zzxwill** [docker/buildx#119]
When trying to install `wget` in Dockerfile, I hit the issue as below:
```
Rpmdb checksum is invalid: dCDPT(pkg checksums): wget.aarch64 0:1.14-18.el7_6.1 - u
```
The command is as below:
```
docker buildx build --platform linux/arm64 -t xxx:0.1 .
```
The Dockerfile is as below:
```
FROM xxx/centos7-aarch64-xxx:xxx
RUN yum install -y wget
```

I have specified in the command with `--platform linux/arm64`, the issue of rebuilding Rpmdb should not occur. Thanks.

**Comment by crazy-max** [comment]
See https://github.com/docker/buildx#building-multi-platform-images:

```console
$ docker run --privileged --rm tonistiigi/binfmt --install all
```

If it's still happening can you post a complete repro so we can test on our side please?
