### ISSUE TITLE
Docs - bake and secrets

### ISSUE THREAD

**Issue by ciaranmcnulty** [docker/buildx#1192]
The only reference in the docs is that `secrets` is an option, but that's not correct it's `secret`

There are no concrete examples so you'll have to guess the syntax :/

**Comment by jedevc** [comment]
Do you mean the references here? https://github.com/docker/buildx/blob/master/docs/guides/bake/configuring-build.md?plain=1#L156. So the override options here are correct, you override using `secrets` at the command line, but you do have to specify `secret` in the HCL.

But yup, we should definitely have some better documentation of the `secret` option - the format of the option is the same as described here though, https://github.com/docker/buildx/blob/master/docs/reference/buildx_build.md#secret.

**Comment by ciaranmcnulty** [comment]
Ah I see; yep at least one concrete example would really help. I was searching for something like #1193 really :)
