### ISSUE TITLE
cache-from still fails if cache does not already exist

### ISSUE THREAD

**Issue by leolivier** [docker/buildx#1194]
Hi
I'm using 
```
$ docker buildx version
github.com/docker/buildx v0.8.2-docker 6224def4dd2c3d347eee19db595348c50d7cb491
```
and I still get the same issue as #206...
```
target "front" {
  inherits = ["defaults"]
  context="."
  tags = tag("nginx")
  cache-from = [
    "user/app:cache",
    "type=local,src=/tmp/buildx-cache"
  ]
  cache-to = ["type=local,dest=/tmp/buildx-cache"]
}
```
and when I build, I get:
```
$ docker buildx bake -f ./build.hcl --progress plain --push
[...]
 > importing cache manifest from user/app:cache:
------
------
 > exporting to image:
------
WARNING: local cache import at /tmp/buildx-cache not found due to err: could not read /tmp/buildx-cache/index.json: open /tmp/buildx-cache/index.json: no such file or directory

```

_Originally posted by @leolivier in https://github.com/docker/buildx/issues/206#issuecomment-1166334858_

Creating a new issue as it is probably a different reason...
@nonameolsson commented also he had the same problem in https://github.com/docker/buildx/issues/206#issuecomment-1169235174

**Comment by leolivier** [comment]
weird, tried again today and now, it's working the second time (it wasn't previously)
Closing...

**Comment by orhun** [comment]
I still get this error from time to time.
