### ISSUE TITLE
Sharing a build stage between architectures

### ISSUE THREAD

**Issue by ohnotnow** [docker/buildx#120]
Hi,

We have a lot of images which have an npm stage purely to build/compile JS/CSS assets.  Doing a multi-arch build runs the stage for each - which can get very time-consuming even though the output is the same.  For instance the project I have open just now took 7 minutes to run the npm scripts for the linux/arm/v7 stage compared to about 1 for linux/amd64.  

I suspect that kind of asset step is quite common so I was just wanting to raise a feature request of some way of marking a stage as 'shared' during multi-arch builds.

And just wanted to also say - buildx is _really_ nice - thank you! :-)

**Comment by FernandoMiguel** [comment]
build an image with the common assets, and then pull that as the layer for the source of the other archs?

**Comment by ohnotnow** [comment]
Yeah - I realise there are ways of doing it - but it would be really nice not to have to fiddle around as much.  Being able to do something like `FROM node:12 as frontend SHARE linux/amd64,linux/arm/v7` or something would be very clean.

**Comment by tonistiigi** [comment]
@ohnotnow Use `FROM --platform=$BUILDPLATFORM` on the stage that is already cross-platform, then copy the files to a platform specific stage.

**Comment by ohnotnow** [comment]
@tonistiigi ohhhh! I'd never come across the `--platform` flag - I'll investigate that - thanks! :-)

**Comment by tonistiigi** [comment]
@ohnotnow look at the cross-compile section of https://github.com/docker/buildx#building-multi-platform-images

**Comment by ohnotnow** [comment]
@tonistiigi thanks for that - cheers :-)  I'll close this issue now as that will work fine.
