### ISSUE TITLE
error: failed to find driver "remote"

### ISSUE THREAD

**Issue by dev-samples** [docker/buildx#1213]
Running:

```
$ docker buildx version
github.com/docker/buildx v0.8.2-docker 6224def4dd2c3d347eee19db595348c50d7cb491

```
I am trying to connect to an existing buildkitd instance using the **remote** driver::
https://github.com/docker/buildx/blob/master/docs/reference/buildx_create.md#remote-driver

`docker buildx create --use --name remote-builder --driver remote tcp://buildkitd:1234
`
But get this error:

`error: failed to find driver "remote"
`
Any ideas/suggestions?

**Comment by jedevc** [comment]
The remote driver isn't shipped in buildx v0.8.2 - it *will* be released in 0.9 when that's done :tada: Until it's released, you can try a build from the master branch on [Docker Hub](https://hub.docker.com/r/docker/buildx-bin/tags) if you want to use it before that :smile:

There's definitely some confusion in the docs around which features are released/unreleased etc. CC @crazy-max, I remember a conversation we had around adding version info around features in our docs/guides?

**Comment by dev-samples** [comment]
Ok so until 9.0 I guess there is no way to connect to an existing/running buildkitd through buildx and I instead need to do that through vanilla buildctrl?

**Comment by dev-samples** [comment]
Thanks for the info, do you have a link to an issue/pr regarding the remote driver feature I can subscribe to?

**Comment by jedevc** [comment]
https://github.com/docker/buildx/pull/1078 was the PR that introduced the feature, but it's unlikely to have any updates on it now that the feature is released.
