### ISSUE TITLE
Reopen #59

### ISSUE THREAD

**Issue by larsqa** [docker/buildx#1220]
Reopen issue #59 since:
- In 2019, [it's been mentioned that `--load` can't be used temporarily for multi-platform builds.](https://github.com/docker/buildx/issues/59#issuecomment-488902807)
- 2022 and the issue still exists, [as well the docs are misleading mentioning that it works](https://docs.docker.com/engine/reference/commandline/buildx_build/#output )
- It's been asked in the discussions to re-open the issue but it seems like they are ignored.

**Comment by thaJeztah** [comment]
The docs mentions;

> Will automatically load the single-platform build result to docker images.

The detail is in "single-platform" here (as the docker daemon storage does not allow for multiple architectures for the same image to be stored).

Wondering if that section would be clearer if we added a not that it cannot be used if multiple platforms are specified

**Comment by larsqa** [comment]
@jedevc Thanks for the quick reply! Glad to hear things are moving forward 😃

@thaJeztah Would agree - I had to read through many Error message descriptions and what they actually meant, before I figured out that there's an issue with the default `--load` flag.

**Comment by thaJeztah** [comment]
@larsqa if you're interested in contributing; the source for those docs are in this repository; https://github.com/docker/buildx/blob/master/docs/reference/buildx_build.md#load

(happy to give it a go myself as well if you want)

**Comment by larsqa** [comment]
@thaJeztah I might not have enough knowledge to understand the full scope of the issue - but I provided my go, from a higher abstract level, from my understanding. Not sure if the majority of readers have a better understanding and are interested in deeper details?

PR: https://github.com/docker/buildx/pull/1221
