### ISSUE TITLE
environment variable error under arm64 platform

### ISSUE THREAD

**Issue by dnomd343** [docker/buildx#1234]
I got some errors while using docker's buildx command, here is how to reproduce:

The following is the system information:

```
shell> uname -a
Linux scutrobot-us 4.19.0-20-amd64 #1 SMP Debian 4.19.235-1 (2022-03-17) x86_64 GNU/Linux

shell> docker -v
Docker version 20.10.14, build a224086

shell> docker buildx inspect
Name:   buildkit
Driver: docker-container

Nodes:
Name:      buildkit0
Endpoint:  unix:///var/run/docker.sock
Status:    running
Platforms: linux/amd64*, linux/386*, linux/arm64*, linux/arm/v7*, linux/amd64/v2, linux/amd64/v3
```

Under normal conditions, the following `Dockerfile` will build without any errors. (the command doesn't make sense, just for test)

```
FROM golang:1.18
RUN env CGO_ENABLED=0 go version
```

First, we build under amd64 architecture:

```
shell> docker buildx build -t test --platform=linux/amd64 .
```

Without a doubt, the build was successful. However, when we switch the architecture to arm64:

```
shell> docker buildx build -t test --platform=linux/arm64 .
···
 => ERROR [2/2] RUN env CGO_ENABLED=0 go version                                                                                                                              0.4s
------
 > [2/2] RUN env CGO_ENABLED=0 go version:
#0 0.311 Error while loading /go/bin/go: No such file or directory
------
Dockerfile:2
--------------------
   1 |     FROM golang:1.18
   2 | >>> RUN env CGO_ENABLED=0 go version
   3 |
--------------------
error: failed to solve: process "/dev/.buildkit_qemu_emulator /bin/sh -c env CGO_ENABLED=0 go version" did not complete successfully: exit code: 1
```

The `PATH` in the environment variable of the image is `/go/bin:/usr/local/go/bin:/usr/local/sbin:...`. In other tests, I observed that for instructions executed after `env`, only the first path is used, such as `/go/bin` here, when in fact it should be in `/usr/local/go/bin`.

This problem not only occurs here, no matter *Debian*, *Ubuntu* or *Centos*, no matter what the linux kernel version is, no matter the go version number, or switch other image, such as `golang:1.18-alpine3.16`, it get the same error. But the **strangest thing** is that when I move to *Windows* (Docker Desktop, base on WSL2), this problem disappears, it builds fine under both `amd64` and `arm64` architecture.

If I use `CGO_ENABLED=0 go version` directly (remove the env command), this problem can be circumvented, but for some established compile scripts (not only golang, but also other make-based projects will crash because of this problem), I can't use buildx for them in cross-platform build occasions, so I can only temporarily switch to windows to execute the build.

What is the reason for this, how should I solve this problem, thank you for your early reply.

**Comment by crazy-max** [comment]
https://github.com/docker/buildx/issues/900#issuecomment-1004170814

**Comment by dnomd343** [comment]
> [#900 (comment)](https://github.com/docker/buildx/issues/900#issuecomment-1004170814)

### Thank you very much, the problem is solved perfectly!

---

 **TIPS**: Execute the following command to fix this problem:

```
shell> docker run --privileged --rm tonistiigi/binfmt --install all
```

By the way, can this feature be automatically enabled at installation? Just like Docker Desktop on Windows.
