### ISSUE TITLE
Fixes for `--invoke` for v0.9

### ISSUE THREAD

**Issue by tonistiigi** [docker/buildx#1258]
I think it is worth doing some small updates to `--invoke` so we can get better feedback when we release this as experimental in v0.9.

- On initial launch of the debug container, a message should be printed "Launching interactive container. Press Ctrl-a-c to switch to monitor console".
- There should be "help" command that lists the currently available commands. Typing unknown command should also show help or show "Run help to see all supported commands".

Nice to have:
- Output warnings should be suppressed then running `--invoke`. "WARNING: No output specified " is not relevant.
- After issuing "rollback" command would be nice to show message "Interactive container was restarted. Press Ctrl-a-c to switch to the new container".
- On monitor mode, if there is no active container and Ctrl-a-c is pressed, a message could show "No running interactive containers. You can start one by issuing rollback command".

@ktock (or others) LMK if you would like to take some of these; otherwise, I can look into them myself as well.

**Comment by ktock** [comment]
Thanks for the suggestion. I'll take it.
