### ISSUE TITLE
Migrate buildx to the public Jenkins

### ISSUE THREAD

**Issue by zelahi** [docker/buildx#130]
**Description:** We recently created a new Jenkins at ci.docker.com/public.  It may be worth it to migrate buildx from travis to Jenkins by creating a new Jenkinsfile using the declarative syntax.

**Comment by zelahi** [comment]
I'm more than happy to work on this, but was wondering what your thoughts were before committing to it

**Comment by crazy-max** [comment]
We use github actions on this repository.
