### ISSUE TITLE
error: failed to solve: failed to compute cache key: failed to get state for index 0 on

### ISSUE THREAD

**Issue by Antiarchitect** [docker/buildx#1308]
We're moving to `docker buildx bake` in our CI and I beleive we're using custom Docker 20.10.17 + Buildkit 0.9.3 docker image in order to mitigate https://github.com/moby/moby/issues/42422

Only using `buildx bake` we faced:

```
#65 [bundled] pushing xxx/cloud/web:av-buildx--bundled with docker
#65 pushing layer ab717947b04e 3.1s done
#65 pushing layer 4abf2dec39bb 3.1s done
#65 pushing layer 5f70bf18a086 3.8s done
#65 pushing layer 6e778c7c02b5 3.1s done
#65 pushing layer 53e78cc72074 3.1s done
#65 pushing layer 58953a7a73dc 3.1s done
#65 pushing layer 80a98d5ba1d4 3.1s done
#65 pushing layer 20a6a1100fe3 3.1s done
#65 pushing layer d8275311d71b 3.1s done
#65 pushing layer 5ce143433645 3.1s done
#65 pushing layer 1c5f426f5e73 3.1s done
#65 pushing layer a812115138fb 3.1s done
#65 pushing layer 6485bed63627 3.1s done
#65 CANCELED
------
 > [ruby] importing cache manifest from xxx/cloud/web:master--ruby:
------
------
 > [bundled] importing cache manifest from xxx/cloud/web:master--bundled:
------
------
 > [assets] importing cache manifest from xxx/cloud/web:master--assets:
------
error: failed to solve: failed to compute cache key: failed to get state for index 0 on [assets 8/9] WORKDIR /app/apps/cloud/web
```

```
#110 DONE 3.0s
------
 > [ruby] importing cache manifest from xxx/cloud/erp:master--ruby:
------
------
 > [gemfiles] importing cache manifest from xxx/cloud/erp:master--gemfiles:
------
------
 > [bundled] importing cache manifest from xxx/cloud/erp:master--bundled:
------
------
 > [assets] importing cache manifest from xxx/cloud/erp:master--assets:
------
error: failed to solve: failed to compute cache key: failed to get state for index 0 on [bundled 5/5] RUN set -x     && /gemfiles/bundle_install /gemfiles/apps/erp     && apt-get remove --purge -y build-essential libpq-dev     && apt-get -y autoremove     && apt-get clean     && rm -rf /var/lib/apt/lists/*
```

The common part is `error: failed to solve: failed to compute cache key: failed to get state for index` and the error appears sporadically

**Comment by Antiarchitect** [comment]
Just faced this on docker 23.0.1

**Comment by jedevc** [comment]
Is there a reason you're using Buildkit 0.9.3? We've just finished releasing the v0.11 release series, the 0.9 one is quite old, and not really actively maintained.

Could you try and the most recent v0.11 release of BuildKit? Is the issue fixed there - if so, it's likely there's already a fix in master somewhere.

**Comment by multun** [comment]
I can confirm it's still an issue with the latest buildx (v0.12.0) and buildkit (v0.12.3) release: https://github.com/osrd-project/osrd/actions/runs/6980472616/job/18996283211?pr=5847#step:13:1412

**Comment by jedevc** [comment]
Thanks @multun - I've also recently started to see this in https://github.com/dagger/dagger on some builds, see https://github.com/dagger/dagger/pull/5315.

Since this is definitely an upstream buildkit issue, I'm going to close in preference of https://github.com/moby/buildkit/pull/3654, which is a better place to track this.

**Comment by jedevc** [comment]
Thanks @multun - I've also recently started to see this in https://github.com/dagger/dagger on some builds, see https://github.com/dagger/dagger/pull/5315.

Since this is definitely an upstream buildkit issue, I'm going to close in preference of https://github.com/moby/buildkit/issues/3635, which is a better place to track this.
