### ISSUE TITLE
Docker enterprise 

### ISSUE THREAD

**Issue by FernandoMiguel** [docker/buildx#135]
Currently, buildx comes bundled as a plugin with the latest community edition.
Are there plans for it to be bundled with the Enterprise edition too?

**Comment by andrewhsu** [comment]
@FernandoMiguel Yes, `buildx` plugin comes with docker-ee 19.03, just need to [enable experimental from cli config](https://docs.docker.com/engine/reference/commandline/cli/#configuration-files).

**Comment by FernandoMiguel** [comment]
@andrewhsu thanks.
Just need github actions CI to update docker version.
They have a one year old 🙄
