### ISSUE TITLE
Using multiple builders for same architectures not working

### ISSUE THREAD

**Issue by frederikhs** [docker/buildx#1365]
I have the following builder registered with 2 amd64 nodes and 2 arm64 nodes.

```sh
NAME/NODE  DRIVER/ENDPOINT                          STATUS  BUILDKIT PLATFORMS
amazon *  docker-container
  amazon0 ssh://ubuntu@amd64-builder-01.example.com   running v0.10.5  linux/amd64, linux/amd64/v2, linux/amd64/v3, linux/amd64/v4, linux/386
  amazon1 ssh://ubuntu@amd64-builder-02.example.com   running v0.10.5  linux/amd64*, linux/amd64/v2, linux/amd64/v3, linux/amd64/v4, linux/386
  amazon2 ssh://ubuntu@arm64-builder-01.example.com   running v0.10.5  linux/arm64, linux/arm/v7, linux/arm/v6
  amazon3 ssh://ubuntu@arm64-builder-02.example.com   running v0.10.5  linux/arm64*, linux/arm/v7, linux/arm/v6
```

I notice that the 02-builder for each architecture has the `*` to the platform. From my understanding this defines the default.

The problem is that when building more than 1 image docker buildx does not utilize the fact that there is more nodes per architecture than 1.

This results in half the registered builders being idle and their cache being empty since nothing is scheduled on them

### Problem

Is my understanding of registering additional builders wrong? Is it not possible to add addtional builders with the same architecture to speed up builds when building multiple targets? e.g using bake

**Comment by tonistiigi** [comment]
Multiple builders is currently only for selecting a builder for an architecture. The first builder node that matches the architecture constraints for the specific build is used.
