### ISSUE TITLE
COPY from works, subsequent Copy does not 🤔 

### ISSUE THREAD

**Issue by ShahOdin** [docker/buildx#1395]
In my `docker-bake.hcl` I have:

```dockerfile
target "foo" {
  dockerfile = "path/to/docker/file"
  contexts = {
    src = "./path/to/context"
  }
}
```

in the above docker file, I have:

```dockerfile
COPY --from=src . /src2
RUN ls /src2 # all good
RUN ls /src2/file.json # all good
# COPY /src2/file.json foo.json
# COPY /src2 /src3
```

I get an error if I uncomment the last lines:

>  failed to compute cache key: "/src2/file.json" not found: not found

and the similar for the other line.

 I don't understand why! This is driving me crazy! why? am I making a very silly mistake

**Comment by jedevc** [comment]
Ahh, the `COPY` command doesn't perform a COPY within the build itself - instead it copies files from *outside* the build to *inside* the build.

For example, if you create a file `x.json` in your main context (the value of the `context` key in your `docker-bake.hcl` file and then `COPY /x.json /y.json`, that file will be copied into your build.

Hope that answers your question :heart:

**Comment by ShahOdin** [comment]
Thanks @jedevc This took me forever to realise! :D
