### ISSUE TITLE
have master artifacts build automatic

### ISSUE THREAD

**Issue by FernandoMiguel** [docker/buildx#142]
Would it be possible to have automatically built on PRs and merge to master?
the current release https://github.com/docker/buildx/releases/tag/v0.3.0 is a month old and it has some fixes I would benefit in my CI, without having to build from master

**Comment by tonistiigi** [comment]
Where is a good place to put the master artifacts as we can't just push them to github releases like for other builds.

@tiborvass Do we have some s3 location/code that can be used for this.

**Comment by FernandoMiguel** [comment]
@tonistiigi @tiborvass

I've made a quick github workflow that builds for Linux architecture and publishes the artifact 
https://github.com/FernandoMiguel/buildx/blob/master/.github/workflows/build.yml

I can probably add a matrix and build it for Darwin, Windows, and arm(a) 
Would this be of interest?

**Comment by crazy-max** [comment]
Fixed through https://github.com/docker/buildx/pull/468
