### ISSUE TITLE
 401 Unauthorized when pushing to Azure Container Registry (ACR) with kubernetes driver

### ISSUE THREAD

**Issue by rhollins** [docker/buildx#1428]
I have Azure Kubernetes Cluster with Managed Identity which has access to push and pull from ACR, when tried to push I get 401 error. There is no anonymous access enabled on ACR.

Just wondering if there is a way to utilize MI to authenticate like it can be done with Kaniko with using credHelpers https://github.com/GoogleContainerTools/kaniko#pushing-to-azure-container-registry

```
docker buildx create \
  --bootstrap \
  --name=builder-1 \
  --driver=kubernetes \
  --driver-opt replicas=1,namespace=default
```

```
docker buildx build --push --tag somereponame.azurecr.io/myrepository:mytag . -f - <<EOF
FROM alpine
RUN echo "hello world"
EOF
```

Error:

level=error msg="/moby.buildkit.v1.Control/Solve returned error: rpc error: code = Unknown desc = failed to fetch anonymous token: unexpected status: 401 Unauthorized\n"

**Comment by crazy-max** [comment]
Have you configured the Azure credential helper in your Docker client config?

**Comment by crazy-max** [comment]
No I mean the client where `docker buildx build` runs.
