### ISSUE TITLE
Docker build paths not persistent across RUNs

### ISSUE THREAD

**Issue by Firedrops** [docker/buildx#147]
Noticed this behaviour. For a Program A that, during install, checks for the existence of Program B through a bash script, it will fail unless `PATH` is re-exported in the same `RUN` line.

For example, if program B was installed and had its `PATH` exported in line 30, the build step of the next `RUN` in, say, line 50, will not see it.

Implementation like this is required as a workaround:
```
RUN export PATH:$PATH:/programB/ && \
    pip3 install programA 
```
i.e. Program B's path get re-exported in the same `RUN` line as Program A's install

Would be good to have PATHs be persistent across build steps/caches to avoid this mismatch between standard CLI behaviour and docker builds.

**Comment by tonistiigi** [comment]
`export` can't be used in `RUN` commands to set environment variables for the image as `export` only runs in the context of the current shell instance. Use `ENV` command in Dockerfile to update the `PATH`

**Comment by Firedrops** [comment]
TIL. So will replacing all `RUN export PATH=$PATH:/ProgramA` with `ENV PATH=$PATH:/ProgramA` be the way to do what I want?

**Comment by tonistiigi** [comment]
@Firedrops yes
