### ISSUE TITLE
Variable with COPY --from?

### ISSUE THREAD

**Issue by DzianisMatveyeu** [docker/buildx#1506]
Can i pass variable in dockerfile with COPY --from?
```
ARG IMAGE=some_image
COPY --from=$IMAGE  .  .
```
In this case, don't working

**Comment by tonistiigi** [comment]
https://medium.com/@tonistiigi/faster-multi-platform-builds-dockerfile-cross-compilation-guide-part-1-ec087c719eaf Find the section "Using build arguments in ` --from`"

**Comment by DzianisMatveyeu** [comment]
If I understand correctly
```
ARG IMAGE=some_image
FROM $IMAGE as variable

FROM ubuntu:22.04 as build
COPY --from=variable .  .
```

will work?

**Comment by tonistiigi** [comment]
Correct
