### ISSUE TITLE
Environment variable OTEL_EXPORTER_OTLP_ENDPOINT causes segmentation violation

### ISSUE THREAD

**Issue by svrnm** [docker/buildx#1521]
Probably related but not a duplicate to https://github.com/docker/buildx/pull/1383:

When I try to build with docker compose and buildx and in my `.env` file I set the environment variables for opentelemetry (OTEL_EXPORTER_OTLP_ENDPOINT) I get a SIGSEGV

```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x2 addr=0x18 pc=0x1032bde18]

goroutine 53 [running]:
github.com/moby/buildkit/client.(*withTracerDelegate).SetSpanExporter(0x1045142c0?, {0x1045142c0?, 0x14000128880?}, {0x1044fffe8?, 0x140000603c0?})
	<autogenerated>:1 +0x38
github.com/moby/buildkit/client.(*Client).setupDelegatedTracing(0x1045142c0?, {0x1045142c0, 0x14000128880}, {0x1044f92c0, 0x1400080c8f0})
	github.com/moby/buildkit@v0.10.4/client/client.go:168 +0x158
github.com/moby/buildkit/client.New({0x1045142c0, 0x14000128880}, {0x0, 0x0}, {0x140008a3d88, 0x2, 0x14000100000?})
	github.com/moby/buildkit@v0.10.4/client/client.go:156 +0x11a8
github.com/docker/buildx/driver/docker-container.(*Driver).Client(0x140007a8400?, {0x1045142c0, 0x14000128880})
	github.com/docker/buildx@v0.9.1/driver/docker-container/driver.go:362 +0x1ec
github.com/docker/buildx/driver.(*cachedDriver).Client.func1()
	github.com/docker/buildx@v0.9.1/driver/manager.go:157 +0x38
sync.(*Once).doSlow(0x140004fae78?, 0x1034a4164?)
	sync/once.go:74 +0x104
sync.(*Once).Do(...)
	sync/once.go:65
github.com/docker/buildx/driver.(*cachedDriver).Client(0x140007a8380?, {0x1045142c0?, 0x14000128880?})
	github.com/docker/buildx@v0.9.1/driver/manager.go:156 +0x64
github.com/docker/buildx/driver.Boot({0x1045142c0, 0x140007a8400}, {0x1045142c0, 0x14000128880}, {0x10451e208?, 0x140007a8380}, {0x104505770?, 0x14000061c20})
	github.com/docker/buildx@v0.9.1/driver/driver.go:82 +0x124
github.com/docker/buildx/build.ensureBooted.func1.1()
	github.com/docker/buildx@v0.9.1/build/build.go:181 +0x74
golang.org/x/sync/errgroup.(*Group).Go.func1()
	golang.org/x/sync@v0.1.0/errgroup/errgroup.go:75 +0x5c
created by golang.org/x/sync/errgroup.(*Group).Go
	golang.org/x/sync@v0.1.0/errgroup/errgroup.go:72 +0xa4
```

I can reproduce this on ARM64 and AMD64 platform and with buildx version 0.10 as well as a fresh build from this github repo. 

Here's the setup to reproduce:

```
/// docker-compose.yml
version: '3'
services:
  service1:
    build:
      context: .
```

```
# .env file
OTEL_EXPORTER_OTLP_ENDPOINT=http://localhost:4317
```

By simple running `docker compose` I get the error above. It goes away if I remove the .env file entry

**Comment by danielamar101** [comment]
Is there any update to this? Did you end up finding a solution @svrnm ?

**Comment by svrnm** [comment]
> Is there any update to this? Did you end up finding a solution @svrnm ?

No, the solution I have so far is running it with MY_OTEL_... and then map them back to OTEL_ in my yml file

**Comment by danielamar101** [comment]
Can you explain a bit more how you did this? I am running into this problem now.

**Comment by crazy-max** [comment]
So you have this issue when running `docker compose build`? Looking at the stack

```
github.com/docker/buildx@v0.9.1
github.com/moby/buildkit@v0.10.4
```

Compose seems to vendor a pretty old version of buildx. Latest compose vendors a more recent version: https://github.com/docker/compose/blob/24ff0982524eee52780eb264d62a5741be095781/go.mod#L13. Can you try with latest compose?

Also do you repro with bake using `docker buildx bake`?

**Comment by svrnm** [comment]
> So you have this issue when running `docker compose build`? Looking at the stack
> 
> ```
> github.com/docker/buildx@v0.9.1
> github.com/moby/buildkit@v0.10.4
> ```
> 
> Compose seems to vendor a pretty old version of buildx. Latest compose vendors a more recent version: https://github.com/docker/compose/blob/24ff0982524eee52780eb264d62a5741be095781/go.mod#L13. Can you try with latest compose?
> 
> Also do you repro with bake using `docker buildx bake`?

Good catch, I thought I forced compose to use local installations of buildx, but apparently that didn't work. Let me see if I can update to a more recent version of compose and see the results.

**Comment by svrnm** [comment]
I build compose from the latest commit of the git repo and I don't get the same error 👍

**Comment by goodspark** [comment]
Happening on 0.11.5 as well.

**Comment by goodspark** [comment]
Here are some simple steps to recreate the segfault:

```
export OTEL_EXPORTER_OTLP_ENDPOINT=http://localhost:4317
docker buildx create --name mybuilder --driver docker-container --bootstrap
[+] Building 1.2s (0/1)                                                                            
 => [internal] booting buildkit                                                               1.2s
 => => pulling image moby/buildkit:buildx-stable-1                                            0.7s
 => => creating container buildx_buildkit_mybuilder0                                          0.5s
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x18 pc=0xe66bd8]

goroutine 41 [running]:
github.com/moby/buildkit/client.(*withTracerDelegate).SetSpanExporter(0x21ebf88?, {0x21ebf88?, 0xc0006bff40?}, {0x21d7a20?, 0xc0009665a0?})
        <autogenerated>:1 +0x38
github.com/moby/buildkit/client.(*Client).setupDelegatedTracing(0x21ebff8?, {0x21ebff8, 0xc000452ba0}, {0x21d06e0, 0xc000865b80})
...
```

OS: Ubuntu 18.04, amd64
Docker version: 20.10.22, build 3a2c30b
Buildkit image tag: v0.11.5

**Comment by goodspark** [comment]
Oh, sorry. On Docker 23.0.2, this is no longer an issue.
