### ISSUE TITLE
Default image output from buildx v0.10 cannot run on Google Cloud Run or AWS Lambda

### ISSUE THREAD

**Issue by jedevc** [docker/buildx#1533]
As of Buildx 0.10, images are built with provenance -- this behavior is opt-out, and can be disabled with `--provenance=false` if using the buildx build cli, or `provenance: false` if using docker/build-push-action.

Images built with these default attestations that use the [attestation storage](https://github.com/moby/buildkit/blob/master/docs/attestations/attestation-storage.md) from buildkit cannot be run on Google Cloud Run or AWS Lambda. While both Cloud Run and Lambda support the OCI format, they do not support multi-platform images.

From [Google Cloud Run docs](https://cloud.google.com/run/docs/container-contract#languages) (emphasis mine):

> Cloud Run accepts container images in the Docker Image Manifest V2, [Schema 1](https://docs.docker.com/registry/spec/manifest-v2-1/), [Schema 2](https://docs.docker.com/registry/spec/manifest-v2-2/), and [OCI](https://github.com/opencontainers/image-spec) image formats.
>
> **[Manifest lists](https://docs.docker.com/registry/spec/manifest-v2-2/#manifest-list) used for [Multi-Architecture Images](https://www.docker.com/blog/multi-arch-build-and-images-the-simple-way/) are not supported.**

> **Note**
>
> Cloud Run has now added support for processing image indexes: https://github.com/docker/buildx/issues/1533#issuecomment-1416814739.

From [Lambda docs](https://docs.aws.amazon.com/lambda/latest/dg/images-create.html#images-reqs) (emphasis mine):

> Lambda provides multi-architecture base images. However, the image you build for your function must target only one of the architectures. **Lambda does not support functions that use multi-architecture container images.**

Ideally, GCR and Lambda should support multi-platform images, and detect the current platform from the Docker manifest list / OCI index.

As a temporary workaround (in order of preference):
- Users should set `--provenance=false` on buildx build, or set `provenance: false` on docker/build-push-action
- Users can force an explicit buildx version to v0.9.1
- Users can force an explicit buildkit version to v0.10

**Comment by steren** [comment]
Cloud Run PM here, we received many reports about this. At the moment, Cloud Run [doesn't support ](https://cloud.google.com/run/docs/container-contract#languages) multi architecture images.

We were tracking this work item, but we do not have an delivery date to communicate yet.

**Comment by piotrekkr** [comment]
@steren If you are Cloud Run PM then I have a request that can help save few hours of debugging for everyone. Would be nice to return proper error message when we try to use multi-platform images with cloud run instead of returning 
```
Image 'europe-docker.pkg.dev/xxx/xxxx' not found
```

It clearly exist in artifact registry since I choose it from select list when creating cloud run service. 

Message like:

```
Image 'europe-docker.pkg.dev/xxx/xxxx'  is a multi-platform image and is not supported
```

Would probably reduce debug time to 15 min instead of 6h.

Thanks

**Comment by davideme** [comment]
@steren and buildx team, Cloud Run supports SLSA Build level 3 through provenance, see https://cloud.google.com/software-supply-chain-security/docs/sds/deploy-run-view-security-insights#build
Is there a way to support provenance in buildx without multi architecture images?
Or the way provenance is added by Cloud Build and buildx is not the same?

**Comment by billinghamj** [comment]
Cloud Run _was_ supporting the old Docker "fat manifest" manifest lists `application/vnd.docker.distribution.manifest.list.v2+json` - we've been using them for over a year

It just doesn't support the new OCI format

**Comment by tonistiigi** [comment]
@billinghamj OCI images are documented in https://github.com/opencontainers/image-spec

**Comment by billinghamj** [comment]
@tonistiigi understand the Docker site isn't the place where the spec lives any more, but nevertheless this situation is incredibly confusing and there's nowhere on the Docker site to find out about this. We burned about 8 hours of eng time before finally finding this issue, I imagine an awful lot of teams are affected by this. Could do well by making the change easy to find

**Comment by steren** [comment]
> Would be nice to return proper error message

I agree, Cloud Run is prioritizing this. And we hope to be able to deploy these images soon after.

Because this change was [known ahead of time to break Cloud Run and Lambda](https://github.com/docker/build-push-action/releases/tag/v3.3.0), it would have been in the best interest of users to give a heads up to these impacted runtimes ahead of time.

**Comment by jedevc** [comment]
> Because this release was [known to break Cloud Run and Lambda](https://github.com/docker/build-push-action/releases/tag/v3.3.0), it would have been in the best interest of users to give a heads up to these impacted runtimes ahead of time.

Agreed. We actually unfortunately *didn't know* that this would break Cloud Run and Lambda at the time of release - we only realized late last week when GitHub updated buildx on GitHub actions. We later then amended the release notes to reflect this, to try and point users towards this issue, to make it easier to debug and track.

**Comment by pantelis-karamolegkos** [comment]
a) It does not only affect GCP CloudRun + AWS Lambda, but [GCR](https://stackoverflow.com/questions/75219715/docker-push-in-github-actions-to-gcr-creates-multiple-images) as well
b) Downgrading the action (I am facing the issue in the GHA step) does not help; is there a way to set manually the BuiltKit version in the action?

**Comment by WesleyKlop** [comment]
I have not tested this but setting the buildx version through the docker/setup-buildx-action with the previous version might work? Something like:

```yaml
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
        with:
            version: v0.9.1
```

But again, I have not tested this. (we fixed it by setting `provenance: false`)

On our side we had pinned actions on their commit sha so it was a big surprise that this happened without our knowledge

**Comment by pantelis-karamolegkos** [comment]
For some weird reason, setting `provenance: false` does not help...I have wasted valuable time for this...

**Comment by pantelis-karamolegkos** [comment]
Here is my step setup

```yaml
      - name: build and push to local registry
        uses: docker/build-push-action@v3.3.0
        with:
          context: ${{ inputs.context }}
          file: ${{ inputs.context }}/${{ inputs.dockerfile }}
          no-cache: ${{ inputs.no_cache }}
          build-args: ${{ inputs.build_args }}
          push: true
          tags: ${{ env.LOCAL_IMAGE }}
          builder: ${{ steps.setup-buildx.outputs.name }}
          provenance: false
```

and here is how the command is executed (from GHA logs)

```sh
/usr/bin/docker buildx build --file ./test_image_creation/Dockerfile --iidfile /tmp/docker-build-push-df1hXH/iidfile --provenance false --tag localhost:5000/name/app:latest --builder builder-12345676-8306-133f-be30-6535318b1528 --metadata-file /tmp/docker-build-push-df1hXH/metadata-file --no-cache --push ./test_image_creation
```

Here is what I see in GCR

<img width="1337" alt="Screenshot 2023-01-24 at 5 17 58 PM" src="https://user-images.githubusercontent.com/50835081/214333262-c77f6021-b7d2-4de3-a042-ed95cd8fd26d.png">

Clicking on one image (the one with the `1.1.1` tag and 0 virtual size)

<img width="607" alt="Screenshot 2023-01-24 at 5 18 49 PM" src="https://user-images.githubusercontent.com/50835081/214333490-a4a1fe09-b98a-4ee2-a92d-2bb19b8bc060.png">

While the other one:

<img width="614" alt="Screenshot 2023-01-24 at 5 19 25 PM" src="https://user-images.githubusercontent.com/50835081/214333659-bb43a871-4596-4ba7-93e7-847b91e567d4.png">

**Comment by jedevc** [comment]
@pantelis-karamolegkos can you open a separate issue - this issue is about images built with buildx being run on Google Cloud Run or AWS Lambda.

It sounds like you're having an issue with the build-push-action and the Google Container Registry - if you can open an issue or discussion on that repository, or even message us in the #buildkit channel on the [Docker Community Slack](https://dockr.ly/comm-slack), we can try and discuss in more detail there.

**Comment by pantelis-karamolegkos** [comment]
@jedevc I like the slack option but I tried and I don't seem to have permissions to join (it did not let me with my `gmail` account). [Me](https://github.com/docker/build-push-action/issues/771) and [someone](https://github.com/docker/build-push-action/issues/774) else opened issues on the build-push action repo but they were promptly closed

**Comment by pantelis-karamolegkos** [comment]
Would it be an option to get an invication for slack?

**Comment by neotrow** [comment]
@pantelis-karamolegkos 

That's odd. I've tried both options. The one with pinning the buildx version to v0.9.1 and setting provenance to false.
Both options worked for me. Although I didn't try it with the `build-push-action` for the provenance option but instead using manual commands. But from your previous comments, it looks like the command gets generated correctly... 

Did you double check the `setup-buildx-action` step's output to confirm it uses `v0.9.1`?

**Comment by pantelis-karamolegkos** [comment]
@neotrow are you pushing to GCR? My problem is actually another issue, discussed [here](https://github.com/docker/build-push-action/issues/771)

**Comment by pantelis-karamolegkos** [comment]
and yes, the buildx version is correct

![Screenshot 2023-01-24 at 6 42 58 PM](https://user-images.githubusercontent.com/50835081/214354301-f5a4f816-55c3-44a2-9ed4-4c824c5f3aeb.png)

**Comment by christallire** [comment]
I'm leaving this for anyone who google searching: This also broke image pull on EKS.

```
Failed to pull image "account-id.dkr.ecr.region.amazonaws.com/image:tag": rpc error: code = NotFound desc = failed to pull and unpack image "account-id.dkr.ecr.region.amazonaws.com/image:tag": no match for platform in manifest: not found
```

`provenance: false` works as an workaround.

**Comment by mueschm** [comment]
> I'm leaving this for anyone who google searching: This also broke image pull on EKS and ECR.
> 
> ```
> Failed to pull image "account-id.dkr.ecr.region.amazonaws.com/image:tag": rpc error: code = NotFound desc = failed to pull and unpack image "account-id.dkr.ecr.region.amazonaws.com/image:tag": no match for platform in manifest: not found
> ```
> 
> `provenance: false` works as an workaround.

We did some testing and found that we only had this issue on clusters running on version 1.21. All other versions (1.22, 1.23 and 1.24) all seemed to work fine for us.

**Comment by christallire** [comment]
> 



> > I'm leaving this for anyone who google searching: This also broke image pull on EKS and ECR.
> > ```
> > Failed to pull image "account-id.dkr.ecr.region.amazonaws.com/image:tag": rpc error: code = NotFound desc = failed to pull and unpack image "account-id.dkr.ecr.region.amazonaws.com/image:tag": no match for platform in manifest: not found
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > `provenance: false` works as an workaround.
> 
> We did some testing and found that we only had this issue on clusters running on version 1.21. All other versions (1.22, 1.23 and 1.24) all seemed to work fine for us.

I'm not sure, but I'm on `v1.24.7-eks-fb459a0`

**Comment by steren** [comment]
Thanks for your patience

Cloud Run now [supports](https://cloud.google.com/run/docs/container-contract#languages) multi-architecture images as long as the manifest list includes `amd64/linux`.

We now expect buildx images built with default settings to deploy to Cloud Run, please let us know here if you still experience issues.

**Comment by hadim** [comment]
I tested building an image with `provenance: true` and using `docker/build-push-action@v4`. The built image is then pushed to GCS, but I still see the reported weird 3 images being shown on the GCS dashboard with outdated date and image size of 0 bytes.

Doing the same while reverting to `provenance: false`, works as it was before.

**Comment by steren** [comment]
Try pushing to [Artifact Registry](https://cloud.google.com/artifact-registry) instead of Container Registry

**Comment by hadim** [comment]
Indeed it seems to work. Thanks.

**Comment by majidakbaridh** [comment]
Is there any way to use newer version of setup-buildx-action but changing mediaType to "mediaType": "application/vnd.docker.distribution.manifest.list.v2+json" ?

**Comment by tonistiigi** [comment]
@majidakbaridh you can use `-o oci-mediatypes=false` but if you want to avoid attestations then disable attestations directly with `--provenance=false`. You can't have the attestations without the OCI mediatypes as well.
