### ISSUE TITLE
Getting error after upgrading to v0.10.0 - manifest for moby/buildkit:buildx-stable-1 not found

### ISSUE THREAD

**Issue by alexyap1205** [docker/buildx#1537]
Hi,

Currently having issue after upgrading our buildx from 0.9.1 to 0.10.0.

The gist of the command it runs on our build system are:
docker buildx create --name builder --use
docker buildx build --push ...

Upon checking the buildx version:
      github.com/docker/buildx v0.10.0-docker 876462897612d36679153c3414f7689626251501

The error says:
      ERROR: Error response from daemon: manifest for moby/buildkit:buildx-stable-1 not found

Any body has encountered this before?

**Comment by tonistiigi** [comment]
What version of docker? Buildx requires Docker at least 19.03.

**Comment by alexyap1205** [comment]
Thanks you for that tip. let me look into the version.

**Comment by alexyap1205** [comment]
Thank you, that resolves it. We're using docker in docker, which was pinned to an old version.
