### ISSUE TITLE
Buildx creating multiple images on google cloud registry (gcr)

### ISSUE THREAD

**Issue by pyrat** [docker/buildx#1554]
We needed to pin buildkit version to 0.10.6 to solve this problem.

eg. 
```
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
        with:
          driver-opts: |
            image=moby/buildkit:v0.10.6
```

Below is what it looks like on google cloud registry:

<img width="938" alt="Screenshot 2023-01-25 at 15 21 39" src="https://user-images.githubusercontent.com/892/214588089-5e99b2c7-45fb-44db-9f43-207f42026748.png">

This looks weird and also doesnt work with google cloud run (gcr). `docker pull` works fine tho.

**Comment by kespinola** [comment]
Issue occurs for dockhub as well. The manifest has a platform of `unknown` which causes it to request linux/arm64/v8 even though running Rosseta which is capable of running amd64 this the platform built from gihub actions ubuntu runner. For the time being I have pinned buildx to v0.9.1.

**Comment by crazy-max** [comment]
> which causes it to request linux/arm64/v8 even though running Rosseta which is capable of running amd64 this the platform built from gihub actions ubuntu runner.

Do you have a repro for this please? Using the `docker pull`?

**Comment by crazy-max** [comment]
https://github.com/docker/buildx/issues/1533#issuecomment-1416814739
