### ISSUE TITLE
docker buildx create  failed to read metadata: unexpected end of JSON input

### ISSUE THREAD

**Issue by crackfan** [docker/buildx#1578]
Ref  *<https://github.com/docker/for-win/issues/13180>*

  ```shell
  docker context create wsl-default
  docker context list
  ```

failed to read metadata: unexpected end of JSON input
![image](https://user-images.githubusercontent.com/2922399/215798962-f03d4def-0b66-48df-906b-62d02ca8ad51.png)

**Comment by crazy-max** [comment]
Hum I'm not able to repro with `0.10.2`:

```
$ docker buildx create --driver-opt env.BUILDKIT_STEP_LOG_MAX_SIZE=1000000,env.BUILDKIT_STEP_LOG_MAX_SPEED=100000000 --use
tender_galileo
```

> ```
> failed to read metadata: unexpected end of JSON input
> ```

And this error doesn't look to be from Buildx or BuildKit :thinking:

Can you post a full repro please?

**Comment by thaJeztah** [comment]
Possibly related to / similar to https://github.com/docker/for-win/issues/13180

**Comment by crackfan** [comment]
> Possibly related to / similar to [docker/for-win#13180](https://github.com/docker/for-win/issues/13180)

Thank you so much！
