### ISSUE TITLE
buildx failed with: ERROR: failed to solve: missing provenance for 8m1im5wrkc0w9eragpyl66gap

### ISSUE THREAD

**Issue by Legion112** [docker/buildx#1583]
The job [here](https://github.com/SoftFineWare/discriminator-default-normalizer/actions/runs/4063433803/jobs/6995772583) failed for some reason.
Can't find any similar issue anywhere. 
```
ERROR: failed to solve: missing provenance for 8m1im5wrkc0w9eragpyl66gap
Error: buildx failed with: ERROR: failed to solve: missing provenance for 8m1im5wrkc0w9eragpyl66gap
```

This repo also don't have an error message which start with `missing provenance for`
<img width="1322" alt="image" src="https://user-images.githubusercontent.com/20613430/216025242-ec971dff-159a-4a07-ab66-6fe6c53b7900.png">

**Comment by jedevc** [comment]
Could you enable debug in your build? https://docs.docker.com/build/ci/github-actions/configure-builder/#buildkit-container-logs

This seems vaguely familiar to me, it looks like an issue in https://github.com/moby/buildkit.

**Comment by Legion112** [comment]
I found only this line in github search. By this [query](https://github.com/search?q=%22missing+provenance+for%22&type=code)
https://github.com/nydusaccelerator/buildkit/blob/db0108f49100bcaa3cf60cd59ee314000477b74c/solver/llbsolver/solver.go#L406

**Comment by jedevc** [comment]
Yeah, there's two possible lines that can produce this error in buildkit: https://github.com/jedevc/buildkit/blob/25c190d9e913180d41e865da4c9ffcfaeb3dda6a/solver/llbsolver/solver.go#L738-L750

With debug logs it should be able to work out which one it is. We can keep the discussion in this repo for now - most of the maintainers between buildx and buildkit are the same, so we'll see it regardless.

**Comment by Legion112** [comment]
I have enable the debug [here](https://github.com/SoftFineWare/discriminator-default-normalizer/actions/runs/4063716549) the running job

**Comment by Legion112** [comment]
> Could you enable debug in your build? https://docs.docker.com/build/ci/github-actions/configure-builder/#buildkit-container-logs
> 
> This seems vaguely familiar to me, it looks like an issue in https://github.com/moby/buildkit.

Done.
Here the job https://github.com/SoftFineWare/discriminator-default-normalizer/actions/runs/4063730164

**Comment by Legion112** [comment]
@jedevc do you see any additional logs?
Look same output to me 😄 .

**Comment by jedevc** [comment]
@Legion112, yup we get a nice stack trace now - just investigating it :)

https://github.com/SoftFineWare/discriminator-default-normalizer/actions/runs/4063730164/jobs/6996308316#step:12:165

**Comment by jedevc** [comment]
Woop, thanks @Legion112 - it looks like you're using duplicate platforms in your workflow file :tada:

`linux/arm64` and `linux/arm64/v8` are actually the same platform - they're aliases of each other. The error you're getting is definitely an upstream issue, have reported it there, and we'll work on a fix.

The workaround is pretty simple - there's no need to build for duplicate platforms, so you should be able to remove one of those platforms, and it should work again :tada: 

Thanks for the report1
