### ISSUE TITLE
Any advice to increase speed?

### ISSUE THREAD

**Issue by killua99** [docker/buildx#161]
Hi,

I've been trying build images for the architecture arm, and it seems to take longer for arm images to be completed.

This is an example of what's going on https://travis-ci.com/killua99/mastodon-alpine

You could check a lot of information and what's happening with those two images, the amd64 finish in no time but the arm builds take way too much.

Looking for advices to increase those builds. The major problem seems to be in the last part where I guess a lot of disk usage is been involve.

**Comment by Johannestegner** [comment]
When you build multi-arch images you use Qemu, qemu is a type of virtualization and sadly, it does have the ability to utilize as much power as your host does. So all none host architectures will take a lot more time.

Personally I have spun up extra ARM64 VPS'es to handle the heavy building, while it have its own problems, it does at the least shorten the build time! :)

**Comment by tonistiigi** [comment]
If qemu is not performant for you, you can also use buildx with native nodes and cross-compilation https://github.com/docker/buildx#building-multi-platform-images

**Comment by killua99** [comment]
Alright, that last part I did miss, perhaps I'll take a look into that and work with the `--append` instead. Thanks for point me out. For me you can close this question.  🙇🏽‍♂️

**Comment by Aisuko** [comment]
Wait, even though I used docker-container, the build speed of arm64 still takes longer than amd64. I copy the code into the container and run `go build`.
