### ISSUE TITLE
Undefined Handler in struct k8s.io/api/core/v1

### ISSUE THREAD

**Issue by TheMMSH** [docker/buildx#1615]
I have error below while using v0.10.2 or previous versions, due to a change made by k8s.io/api/core/v1/types.go which is not handled in this repo.

> github.com/docker/buildx@v0.10.2/driver/kubernetes/manifest/manifest.go:92:9: unknown field 'Handler' in struct literal of type "k8s.io/api/core/v1".Probe
> github.com/docker/buildx@v0.10.2/driver/kubernetes/manifest/manifest.go:92:25: undefined: v1.Handler

[This is](https://github.com/kubernetes/api/commit/cca52a076791d31b1796453ece4b2f4df97406a2) the breaking change that causes this error

As you can see, They've changed `Handler` type to `ProbeHandler`

**Comment by jedevc** [comment]
cc @AkihiroSuda

**Comment by AkihiroSuda** [comment]
Fixed in #1677
