### ISSUE TITLE
[BUG] Bake build fails when using BAKE_CMD_CONTEXT locally

### ISSUE THREAD

**Issue by nVlast** [docker/buildx#1627]
I noticed that when I use the `BAKE_CMD_CONTEXT` built-in variable in a local HCL bake file, the build fails.

**Steps to reproduce:**
1. Create a Dockerfile (named "Dockerfile"):
  ```Dockerfile
  FROM alpine
  CMD ["sleep", "infinity"]
  ```
2. Create a bake file (named "docker-bake.hcl"):
  ```HCL
  target "default" {
    dockerfile = "Dockerfile"
    context = BAKE_CMD_CONTEXT
    tags = ["myimage:myversion"]
  }
  ```
3. Run `docker buildx bake`

**Expected outcome:**
The docker image specified should be built

**Actual outcome:**
```
ERROR: could not find cwd:: stat cwd:: no such file or directory
```

---

I looked into it a bit further, and it seems that when the aforementioned built-in variable was introduced, while the context [was arranged to be "cleaned"](https://github.com/docker/buildx/pull/671/files#diff-fbe2fa23203f2ff05f06b6c0731ea90529f90906807483db76a79f6018781465R581-R585) from the [cwd protocol](https://github.com/docker/buildx/pull/671/files#r668896194), the dockerfilePath is left with a cwd reference in it. Perhaps something as simple as adding a `!strings.HasPrefix(contextPath, "cwd://")` check [here](https://github.com/docker/buildx/pull/671/files#diff-fbe2fa23203f2ff05f06b6c0731ea90529f90906807483db76a79f6018781465R560) would be sufficient but take that with a pinch of salt as I'm not all that familiar with the codebase.

Also, if this variable was never meant to work in a local setting, please close this issue.

**Comment by crazy-max** [comment]
@nVlast Yes `BAKE_CMD_CONTEXT` has to be used with a remote definition as shown here: https://docs.docker.com/build/bake/file-definition/#remote-definition but it should not fail for local builds.

I'm able to repro locally but `--print` gives the expected value for `context`:

```
$ docker buildx bake --print
{
  "target": {
    "default": {
      "context": ".",
      "dockerfile": "Dockerfile",
      "tags": [
        "myimage:myversion"
      ]
    }
  }
}
```

Will take a look, thanks for your feedback.

**Comment by jedevc** [comment]
@nVlast @c-ameron sorry this missed getting added to the v0.11.0 release, but I'll try and get it cherry-picked into v0.11.1, since it's a pretty small change.

@socheatsok78 your `Rel: can't make . relative to /path-to-project` looks like https://github.com/docker/buildx/pull/1840, which was in the v0.11.0 release.

**Comment by c-ameron** [comment]
I think `cwd://` would be better than `BAKE_CMD_DOCKERFILE`, that way you could have multiple Dockerfiles in the same remote reference
