### ISSUE TITLE
http: server gave HTTP response to HTTPS client

### ISSUE THREAD

**Issue by zhipengzuo** [docker/buildx#163]
**when:**
I ran :docker buildx build -t registry.com:8000/xxx/buildx-test . --push 
i have docker login successfully and add registry to "insecure registries"
**errors:**
http: server gave HTTP response to HTTPS client

**more to try :**
i tried something from https://github.com/docker/buildx/issues/94:
docker buildx create  --driver-opt network=host 
docker buildx use quirky_hofstadter
docker buildx build -t registry.com:8000/xxx/buildx-test . --push 

same errors occurs. : http: server gave HTTP response to HTTPS client

**env:**
macos
docker buildx version  :github.com/docker/buildx v0.3.0-5-g5b97415-tp-docker 5b974158f94f67d2bc072a8853fb280cbc600841
docker version :Version:           19.03.2 

**more to say:**
i can use docker push to this registry successfully
i can use "docker buildx build -t registry.com:8000/xxx/buildx-test . " successfully

**Comment by FernandoMiguel** [comment]
Can you please try with the latest buildx?
https://github.com/docker/buildx/releases

**Comment by FernandoMiguel** [comment]
Cc @tiborvass

**Comment by tonistiigi** [comment]
@zhipengzuo use `docker buildx create --config=<filename>` to point to a buildkit configuration file https://github.com/moby/buildkit/blob/master/docs/buildkitd.toml.md where you can set your registry as `http = true` to skip tls.

**Comment by zhipengzuo** [comment]
> @zhipengzuo use `docker buildx create --config=<filename>` to point to a buildkit configuration file https://github.com/moby/buildkit/blob/master/docs/buildkitd.toml.md where you can set your registry as `http = true` to skip tls.

it works.Thanks you very much.
