### ISSUE TITLE
--output type=tar,dest=/tmp/buildx-arrch-echo.tar  The image cannot be exported as a tar file

### ISSUE THREAD

**Issue by JokerDevops** [docker/buildx#1648]
My buildx driver is kubernetes, as shown below:

```
docker [root@kvm-xingxia-179 ~]# docker buildx ls
NAME/NODE                DRIVER/ENDPOINT STATUS  BUILDKIT PLATFORMS
kube *                   kubernetes
  kube0-5bc7fb99b5-wsvjs                 running          linux/amd64, linux/arm64, linux/riscv64, linux/ppc64le, linux/s390x, linux/386, linux/mips64le, linux/mips64, linux/arm/v7, linux/arm/v6
default                  docker
  default                default         running 19.03.8  linux/amd64, linux/386
```
When I build images of different platforms of AMD64 and ARM64 and push them to the registry, it is normal.

But when I use -- output type as tar, I output the image of different platforms to a tar file, and then import it through Docker import. It is found that it is not available.

The error message is as follows:
```
docker: Error response from daemon: No command specified.
```

**Comment by crazy-max** [comment]
Can you post a repro please with a Dockerfile, build command and output of `docker buildx version`? Also what version of BuildKit in your cluster?
