### ISSUE TITLE
Output path - remove existing files?

### ISSUE THREAD

**Issue by ciaranmcnulty** [docker/buildx#1649]
If I `docker buildx build . --output=/path` I sometimes want to remove existing files, is there a way to do this?

A specific example is documentation generation where pages may have been removed

I can cleanup beforehand of course, but I think having the output dir in a consistent state after the operation even if it was 'messy' would be a good idea

**Comment by crazy-max** [comment]
https://github.com/moby/buildkit/issues/2805
