### ISSUE TITLE
Unauthenticated S3 caching

### ISSUE THREAD

**Issue by yrashk** [docker/buildx#1666]
### Description

I am using S3 caching in my GitHub Actions to cache layers between builds. However, this doesn't work for PRs from forks because I can't supply AWS secrets to them; they come as empty strings.

I've enabled public access to the bucket I am using but I need an equivalent of `--no-sign-request` for the S3 backend to be able to download these files.

**Comment by jedevc** [comment]
Closing this as the fix upstream in buildkit has been merged.
