### ISSUE TITLE
Azure/GCP/Openstack plugins removed in latest release of client-go

### ISSUE THREAD

**Issue by jedevc** [docker/buildx#1704]
See https://github.com/kubernetes/client-go/tree/master/plugin/pkg/client/auth - until we resolve this, we can't bump the versions of `client-go` (which it tries to do if revendoring buildkit, as in https://github.com/docker/buildx/pull/1703).

Both the Azure and GCP plugins have been deprecated, while the Openstack plugin has been completely removed, and all moved into client credential plugins: https://kubernetes.io/docs/reference/access-authn-authz/authentication/#client-go-credential-plugins.

I think we need to update the buildx code to use the [k8s.io/client-go/plugin/pkg/client/auth/exec](https://github.com/kubernetes/client-go/tree/master/plugin/pkg/client/auth/exec) package? @AkihiroSuda do you know what the right thing to do here is?

**Comment by AkihiroSuda** [comment]
I guess we can just drop these lines?
https://github.com/docker/buildx/blob/f360088ae73988ef478ecddb2cbc0c882bedf392/cmd/buildx/main.go#L19-L22

**Comment by jedevc** [comment]
I would guess so? I'm not 100% sure, I don't know what we used them for in the first place :eyes:
