### ISSUE TITLE
imagetools create should propagate the original error

### ISSUE THREAD

**Issue by crazy-max** [docker/buildx#1726]
If I'm unauthenticated and try to use `imagetools create`, it fails without showing me the original error that would help to find out the issue:

```
$ docker buildx imagetools create --tag foo.com/user/repo:latest --tag foo.com/user/repo:v1.0 foo.com/user/repo:v1.0.0
#1 [internal] pushing foo.com/user/repo:v1.0
#1 0.000 pushing sha256:1bf960763a14552b30e1e91967966b659f595ea854cf2c2c445f1c529853bcc4 to foo.com/user/repo:v1.0
#1 ...

#2 [internal] pushing foo.com/user/repo:latest
#0 0.000 pushing sha256:1bf960763a14552b30e1e91967966b659f595ea854cf2c2c445f1c529853bcc4 to foo.com/user/repo:latest
#2 ERROR: failed to copy after 5 retries

#1 [internal] pushing foo.com/user/repo:v1.0
#1 ERROR: failed to copy after 5 retries
------
 > [internal] pushing foo.com/user/repo:v1.0:
#1 0.000 pushing sha256:1bf960763a14552b30e1e91967966b659f595ea854cf2c2c445f1c529853bcc4 to foo.com/user/repo:v1.0
------
------
 > [internal] pushing foo.com/user/repo:latest:
#0 0.000 pushing sha256:1bf960763a14552b30e1e91967966b659f595ea854cf2c2c445f1c529853bcc4 to foo.com/user/repo:latest
------
ERROR: failed to copy after 5 retries
ERROR: failed to copy after 5 retries
ERROR: failed to copy after 5 retries
```

It does not seem to be in buildx but containerd: https://github.com/containerd/containerd/blob/5885db62c856e703f11f2195c54efbec5d00a788/content/helpers.go#L206

Bisecting indicates https://github.com/containerd/containerd/pull/6995 is the PR introducing this issue that has been fixed by @jedevc in https://github.com/containerd/containerd/pull/7985 for `pushWriter` but we also need to propagate the original error for the `Copy` helper: https://github.com/containerd/containerd/blob/5885db62c856e703f11f2195c54efbec5d00a788/content/helpers.go#L143-L207

@akhilerm Let me know if you want another issue on containerd repo.

**Comment by akhilerm** [comment]
@crazy-max Can this issue be reproduced by just using the `ctr` tool.  Then we can raise an issue in containerd with steps to minimally reproduce the issue.

**Comment by akhilerm** [comment]
@crazy-max How can I reproduce this issue. ? Should `foo.com/user/repo` be a public repository or a private one. Should i be logged into the registry but without the sufficient permissions to the repo?

**Comment by crazy-max** [comment]
Ok I'm not able to repro anymore :disappointed:, I guess my issue was not related to auth but something flaky with the registry I guess.

```
ERROR: server message: insufficient_scope: authorization failed
```

This error is from BuildKit, not containerd so it fails early before even going through the `Copy` helper. Looking at this test: https://github.com/containerd/containerd/blob/5885db62c856e703f11f2195c54efbec5d00a788/content/helpers_test.go#L132-L142 it does not propagate the write failure as it should imo.

**Comment by jedevc** [comment]
There are some locations in BuildKit where we also use `content.Copy`, see https://github.com/moby/buildkit/blob/333ee9158128dbb821118f0b19a4c140d49c7657/exporter/containerimage/writer.go#L280-L282: `WriteBlob` calls `Copy` (we should probably be using `WriteBlob` in buildx imagetools tbf).

I'm not sure why we don't also have this issue in BuildKit though - we use the same pusher, so I don't know why we don't see a bunch of `ErrReset` everywhere.
