### ISSUE TITLE
Bake with remote `docker-bake.hcl` does not resolve custom target contexts

### ISSUE THREAD

**Issue by milas** [docker/buildx#1738]
### Contributing guidelines

- [X] I've read the [contributing guidelines](https://github.com/docker/buildx/blob/master/.github/CONTRIBUTING.md) and wholeheartedly agree

### I've found a bug and checked that ...

- [X] ... the documentation does not mention anything about my problem
- [X] ... there are no open or closed issues that are related to my problem

### Description

If you've got a target with a `context` defined, when baking the target remotely, the context does not have the Git context prepended.

Interestingly it actually is resolved correctly to find the `Dockerfile` (from the remote), so it'll actually fail on the first `COPY`.

### Expected behaviour

* `COPY` commands reference files from the context in the Git remote

Possibly output like this:
```
$ docker buildx bake 'https://example.com/myrepo.git' foo --print
{
  "target": {
    "foo": {
      "context": "https://example.com/myrepo.git:bar",
      "dockerfile": "Dockerfile"
    }
  }
}
```

### Actual behaviour

* `COPY` tries to copy from local path

```
$ docker buildx bake 'https://example.com/myrepo.git' foo --print
{
  "target": {
    "foo": {
      "context": "bar",
      "dockerfile": "Dockerfile"
    }
  }
}
```

### Buildx version

github.com/docker/buildx 0.10.4 c513d34049e499c53468deac6c4267ee72948f02

### Docker info

```text
Client:
 Context:    pinkypie
 Debug Mode: false
 Plugins:
  buildx: Docker Buildx (Docker Inc.)
    Version:  0.10.4
    Path:     /usr/lib/docker/cli-plugins/docker-buildx
  compose: Docker Compose (Docker Inc.)
    Version:  v2.17.2
    Path:     /home/milas/.docker/cli-plugins/docker-compose

Server:
 Containers: 2
  Running: 0
  Paused: 0
  Stopped: 2
 Images: 24
 Server Version: 23.0.3
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Using metacopy: true
  Native Overlay Diff: false
  userxattr: false
 Logging Driver: json-file
 Cgroup Driver: systemd
 Cgroup Version: 2
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: io.containerd.runc.v2 runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 1fbd70374134b891f97ce19c70b6e50c7b9f4e0d.m
 runc version: 
 init version: de40ad0
 Security Options:
  seccomp
   Profile: builtin
  cgroupns
 Kernel Version: 6.1.24-1-MANJARO
 Operating System: Manjaro Linux
 OSType: linux
 Architecture: x86_64
 CPUs: 24
 Total Memory: 62.72GiB
 Name: pinkypie
 ID: LMGH:VDPN:Y2ZA:WRZA:ZQXA:U66B:KX3K:KY7C:SPFT:RX6Q:YV7M:DUN2
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 Username: milas
 Registry: https://index.docker.io/v1/
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false
```

### Builders list

```text
NAME/NODE                   DRIVER/ENDPOINT                            STATUS   BUILDKIT    PLATFORMS
default                     docker
default                   default                                    running  23.0.3      linux/amd64, linux/amd64/v2, linux/amd64/v3, linux/386
pinkypie *                  docker
pinkypie                  pinkypie                                   running  23.0.3      linux/amd64, linux/amd64/v2, linux/amd64/v3, linux/386
```

### Configuration

Here's a hypothetical example to make it easy to follow:

#### `https://example.com/myrepo.git`
```text
myrepo/
├── docker-bake.hcl
└── bar/
    ├── Dockerfile
    └── super-cool.txt
```

#### `docker-bake.hcl`
```hcl
target foo {
  context = "./bar"
}
```

#### `./bar/Dockerfile`
```dockerfile
FROM scratch

COPY super-cool.txt /
```

#### Attempt to build... 💥 
```shell
docker buildx bake \
  'https://example.com/myrepo.git' \
  foo
```

This will end up with an error such as
```
ERROR: failed to solve: failed to compute cache key: failed to calculate checksum of ref moby::zhw5urpf8sto3shv0hjhbnpcj: "/super-cool.txt": not found
```

### Additional info

Here's my real-world case that's a bit messier 🙃 :
```shell
docker buildx bake --print \
  'https://github.com/milas/rock5-toolchain.git#rknn' \
  yolov8-model-rknn
```
Notice that the `context` is `rknn` on the target!

This actually works if you override the context:
```shell
docker buildx bake --print \
  --set='*.context=https://github.com/milas/rock5-toolchain.git#rknn:rknn' \
  'https://github.com/milas/rock5-toolchain.git#rknn' \
  yolov8-model-rknn
```
(fyi that target takes a bit and has some big layers so wouldn't necessarily bother building it)

**Comment by jedevc** [comment]
Aha, another case of not handling remote contexts correctly :cry:

This is very odd, and I'm confused by the code that handles this: https://github.com/docker/buildx/blob/b716e48926298a5be3f2381a6fb09d6cd442272f/bake/bake.go#L936

This will only copy the directory to the top-level, instead of copying the contents of the directory to the top-level. So, "super-cool.txt" doesn't exist, but "bar/super-cool.txt" does. This definitely seems incorrect to me, I'd expect that `CopyDirContentsOnly` would be set here, so that `super-cool.txt` would exist at the top-level.

cc @crazy-max @tonistiigi, do either of you have more context here? I think this is just an edge case that maybe has regressed over time?

**Comment by tonistiigi** [comment]
> I think this is just an edge case that maybe has regressed over time?

Seems so. Note that another way would be to add a subdir to the Git URL and avoid the copy. Early BuildKit versions did not support Git subdirs so I think that is why it always does copy.
