### ISSUE TITLE
Bake doesn't work without BuildKit

### ISSUE THREAD

**Issue by dm17** [docker/buildx#1761]
### Contributing guidelines

- [X] I've read the [contributing guidelines](https://github.com/docker/buildx/blob/master/.github/CONTRIBUTING.md) and wholeheartedly agree

### I've found a bug and checked that ...

- [X] ... the documentation does not mention anything about my problem
- [X] ... there are no open or closed issues that are related to my problem

### Description

This work around is required to be able to have networking during build time (except for `none` and `host` networking modes) - https://github.com/docker/buildx/issues/175#issuecomment-952269412

However, creating a builder instance with `buildx create --driver-opt network=custom` and selecting it with "--use," then the error is the same as when using compose with buildkit and custom networks:
```ERROR: network mode "custom" not supported by buildkit - you can define a custom network for your builder using the network driver-opt in buildx create```

Going around in circles with this is basically like deprecating custom networks during build time, but plenty of us have valid reasons to continue to use them from the days of the classic builder. Is there another work around I'm not seeing? Could we get `bake` to read a compose file that has custom networks defined under `build:` like they did before buildkit was default?

### Expected behaviour

`bake` to read the compose file correctly and use the builder instance it is set to.

### Actual behaviour

`ERROR: network mode "custom" not supported by buildkit`

### Buildx version

0.10.4 and 0.10.3

### Builders list

```text
/NODE DRIVER/ENDPOINT             STATUS  BUILDKIT PLATFORMS
app-custom *  docker-container
  app-dm0 unix:///var/run/docker.sock running v0.11.5  linux/amd64, linux/amd64/v2, linux/amd64/v3, linux/386
default   docker
  default default                     running 23.0.1   linux/amd64, linux/amd64/v2, linux/amd64/v3, linux/386
```

### Configuration

```services:
  app:
    restart: "always"
    build:
      context: .
      network: "${NETWORK}"
```

**Comment by TBBle** [comment]
Since you created your driver with the custom network, take `network` out of your bake config. Bake doesn't need to know about the network, the builder context already does.

**Comment by dm17** [comment]
In order to test this I've begun moving all of the inherent logic in the previous compose environments to bash scripts with buildx commands. This is due to the fact that ${project} variables in Dockerfiles doesn't seem to work with bake - not to mention bake refuses to find local images build in previous layers, but perhaps it is because they were built with compose and not buildx (despite the fact that they're supposed to be analogous tools with overlapping functionality).

In order to test this properly I need to get a bit further so that `buildx bake service` doesn't try to download the previous layer from dockerhub (where it doesn't exist) and finds it locally (since it exists in `docker images`).

Frusterating building so many things with compose and then have to migrate away because buildkit doesn't support custom networks during build time, whereas the classic builder did.

**Comment by jedevc** [comment]
I'm going to close this in preference of https://github.com/docker/buildx/issues/175 - I think it's the same issue? It's easier to keep the conversation in one place, since it all seems to be around custom network support for buildkit.
