### ISSUE TITLE
host-gateway no longer supported in docker build

### ISSUE THREAD

**Issue by zamlz** [docker/buildx#1832]
### Description

Hi all, I've noticed that once I upgraded my docker to the new version I'm unable to use `host-gateway` during the build process.

I get the following error when using the `--add-host=host.docker.internal:host-gateway` argument for `docker build`.

```
[+] Building 0.0s (0/0)
 ERROR: failed to solve: failed to parse additional hosts: failed to parse IP host-gateway
```

This used to work before the upgrade and what's interesting is that the `docker run` command and even `docker comnpose` still support the argument.

### Reproduce

1. Run a docker build command with the `--add-host=host.docker.internal:host-gateway`

For example

```
docker build --add-host=host.docker.internal:host-gateway .
```

### Expected behavior

`docker build` is able to use the `host-gateway` special string to bridge the host network with the containers network.

### docker version

```bash
Client: Docker Engine - Community
  Version:           23.0.0
  API version:       1.42
  Go version:        go1.19.5
  Git commit:        e92dd87
  Built:             Wed Feb  1 17:49:08 2023
  OS/Arch:           linux/amd64
  Context:           default
 
 Server: Docker Engine - Community
  Engine:
   Version:          23.0.0
   API version:      1.42 (minimum version 1.12)
   Go version:       go1.19.5
   Git commit:       d7573ab
   Built:            Wed Feb  1 17:49:08 2023
   OS/Arch:          linux/amd64
   Experimental:     false
  containerd:
   Version:          1.6.16
   GitCommit:        31aa4358a36870b21a992d3ad2bef29e1d693bec
  runc:
   Version:          1.1.4
   GitCommit:        v1.1.4-0-g5fd4c4d
  docker-init:
   Version:          0.19.0
   GitCommit:        de40ad0
```

### docker info

```bash
Client:
  Context:    default
  Debug Mode: false
  Plugins:
   buildx: Docker Buildx (Docker Inc.)
     Version:  v0.10.2
     Path:     /usr/libexec/docker/cli-plugins/docker-buildx
   compose: Docker Compose (Docker Inc.)
     Version:  v2.15.1
     Path:     /usr/libexec/docker/cli-plugins/docker-compose
   scan: Docker Scan (Docker Inc.)
     Version:  v0.23.0
     Path:     /usr/libexec/docker/cli-plugins/docker-scan
 
 Server:
  Containers: 9
   Running: 7
   Paused: 0
   Stopped: 2
  Images: 115
  Server Version: 23.0.0
  Storage Driver: overlay2
   Backing Filesystem: extfs
   Supports d_type: true
   Using metacopy: false
   Native Overlay Diff: true
   userxattr: false
  Logging Driver: json-file
  Cgroup Driver: cgroupfs
  Cgroup Version: 1
  Plugins:
   Volume: local
   Network: bridge host ipvlan macvlan null overlay
   Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
  Swarm: inactive
  Runtimes: io.containerd.runc.v2 runc
  Default Runtime: runc
  Init Binary: docker-init
  containerd version: 31aa4358a36870b21a992d3ad2bef29e1d693bec
  runc version: v1.1.4-0-g5fd4c4d
  init version: de40ad0
  Security Options:
   apparmor
   seccomp
    Profile: builtin
  Kernel Version: 5.4.0-121-generic
  Operating System: Ubuntu 20.04.5 LTS
  OSType: linux
  Architecture: x86_64
  CPUs: 4
  Total Memory: 3.666GiB
  Name: dev-testing-amlesh
  ID: HYQS:EF3Y:2IJR:XJHT:IPNI:2M3H:SPSX:3UBG:7OFQ:SE77:7U7J:WHYU
  Docker Root Dir: /var/lib/docker
  Debug Mode: false
  Registry: https://index.docker.io/v1/
  Experimental: false
  Insecure Registries:
   127.0.0.0/8
  Live Restore Enabled: false
 
 WARNING: No swap limit support
```

**Comment by thaJeztah** [comment]
Thanks for trying! So from a quick glance,  I think https://github.com/moby/moby/pull/44537 would've fixed the situation where the CLI would use the JSON / REST API to perform builds, but buildx uses the BuildKit gRPC API, so probably some fix elsewhere is still needed now that the default is to use the gRPC API for BuildKit builds 🤔

**Comment by dvictori** [comment]
I'm facing this same issue, using docker 24.0.1 on Ubuntu. I noticed it when I tried to build a docker-compose with `extra_hosts` on the build section. I need to access a postgres sever that is running on the host machine. So I'm using extra_hosts "host.docker.internal:host-gateway" to make the connection.

**Comment by tschallacka** [comment]
For linux i've suddenly run into this as well as my xdebug stopped connecting after an update.

Luckely we use an internal stitching for docker compose files, and it's easy to add to a shell script.

This command can be added to a bashrc or bash  profile or any other 'autoexec' file that starts on a terminal session, adapt as needed. This supports mac and linux.

```bash
case "$(uname -sr)" in

   Darwin*)
     IPADDRESS=$(ifconfig | grep "inet " | grep -Fv 127.0.0.1 | awk '{print $2}')
     ;;

   Linux*Microsoft*)
     IPADDRESS=$(hostname -I | awk '{print $1}')
     ;;

   Linux*)
     IPADDRESS=$(hostname -I | awk '{print $1}')
     ;;

   CYGWIN*|MINGW*|MINGW32*|MSYS*)
     ;;

   # Add here more strings to compare
   # See correspondence table at the bottom of this answer

   *)
     echo "Unknown platform, aborting";exit
     ;;
esac
export IPADDRESS
```

**Comment by zamlz** [comment]
> I'm facing this same issue, using docker 24.0.1 on Ubuntu. I noticed it when I tried to build a docker-compose with `extra_hosts` on the build section. I need to access a postgres sever that is running on the host machine. So I'm using extra_hosts "host.docker.internal:host-gateway" to make the connection.
> 
> --- Addendum
> 
> I'm running on Linux. So I changed extra_hosts to point to the docker-host IP and things worked. Here is what I placed on my docker-compose:
> 
> ```
> extra_hosts:
>             - "host.docker.internal:172.17.0.1"
> ```
> 
> source: https://forums.docker.com/t/how-to-reach-localhost-on-host-from-docker-container/113321/4

Decent solution, but I can't guarantee all the containers I'm running are on the same docker network bridge. They'd have different IPs. We do not wish to hardcode these.

**Comment by dvictori** [comment]
> 
> Decent solution, but I can't guarantee all the containers I'm running are on the same docker network bridge. They'd have different IPs. We do not wish to hardcode these.

I agree. It was just a quick fix that I used. But by no means a definitive solution.

**Comment by zamlz** [comment]
I finally got around to testing this on my end. The issue is closed for some reason, but I can't seem to get it to work still.

```
$ docker --version
Docker version 24.0.2, build cb74dfcd85
```

Unfortunately, this particular version of `docker` does not appear to be fixed. Am I using an older version still?

```
ERROR: failed to solve: failed to parse additional hosts: failed to parse IP host-gateway
```

**Comment by neersighted** [comment]
The fix requires buildx v0.11.1, and daemon v24.0.3 (which were released together). The version you have provided is the CLI, which does not need to be updated to get this fix; however I find it unlikely that you have the correct daemon and buildx version given that CLI version.

**Comment by thaJeztah** [comment]
Looks like fixes went into 24.0.3 https://github.com/moby/moby/pull/45790

And buildx v0.11.1 through https://github.com/docker/buildx/pull/1926

You need both updated to at least those versions to get the fix

**Comment by thaJeztah** [comment]
Ah @neersighted beat me to it 😅

**Comment by zamlz** [comment]
Ahhh I see, cool okay that's what I figured happened, but wanted to make sure. I saw that issue link before but I didn't see a version number so I had no clue if the version I currently updated to had it or not.

However, looking at the page again, I see that there is a milestones on the right side that indicated the version. Cool, will look at that next time! Thanks for your help!

**Comment by neersighted** [comment]
You can also review https://docs.docker.com/engine/release-notes when you update, and look for the fix there 😉

**Comment by zamlz** [comment]
Awesome! Thanks for sharing! I forgot about the release notes document. I'll definitely refer to that doc next time!

**Comment by elichai** [comment]
This issue still persists, you can easily re-create it with in github action: https://github.com/elichai/docker-bug/actions/runs/12456873279/job/34770817326

**Comment by CHN-beta** [comment]
> This issue still persists, you can easily re-create it with in github action: https://github.com/elichai/docker-bug/actions/runs/12456873279/job/34770817326

Same issue.
