### ISSUE TITLE
Import multi-arch tarball for tag and push

### ISSUE THREAD

**Issue by Johannestegner** [docker/buildx#186]
In my workflow I usually have a step between build and push, in which I run some tests on the image (often in the form of a tarball or local image), when I use 'standard docker' I just load the image locally and test it that way, but when doing multi platform builds, that is a bit more of an issue, seeing I cant import multi-arch images(?).

What I figured would be the best way to do this is to export the image to tar or OCI-tar and then run the tests on that, and when tests are done, import the tarball and push it to docker. Here comes my issue: I can't for the life of me figure out how to load the tarball and then tag and push it to my registries...

Is there any documentation on this? Is it even possible?  
I know that the `docker image load` and `docker image import` commands exist, but neither of those seem to support multi-arch images as of right now.

**Comment by tonistiigi** [comment]
Yes, in 19.03 `docker load` does not support loading multi-arch images. You either need to use a local registry or build a single-arch image for your local steps that you can later merge to multi-arch in registry with `buildx imagetools create`

**Comment by Johannestegner** [comment]
Ahh I see, that's annoying... Are there any plans to add ta feature like this? Cause it would be quite useful! :)

**Comment by tonistiigi** [comment]
Yes, https://github.com/moby/moby/pull/38738 https://gist.github.com/tonistiigi/5c86c720d196ce74d989ea37b325a621

**Comment by Johannestegner** [comment]
Ahh that's great!
Guess we could close this issue then if you guys don't feel that it have some purpose :)

Thanks for info!
