### ISSUE TITLE
Update SLSA provenance to v1.0

### ISSUE THREAD

**Issue by lucacome** [docker/buildx#1875]
### Description

SLSA went v1 and updated the provenance schema https://slsa.dev/provenance/v1#schema

Would it be possible to update buildx generation to use v1? 

Thanks 🙏

**Comment by jedevc** [comment]
Thanks for the report 🎉

This is tracked upstream in buildkit https://github.com/moby/buildkit/issues/3684 - we need to fix it there instead of in buildx.

**Comment by lucacome** [comment]
Thanks! I checked that repo too and missed that issue apparently 😅
