### ISSUE TITLE
Tag v0.11.0 exists but no releases, breaks devcontainer docker-in-docker feature

### ISSUE THREAD

**Issue by hpe-ykoehler** [docker/buildx#1878]
### Contributing guidelines

- [X] I've read the [contributing guidelines](https://github.com/docker/buildx/blob/master/.github/CONTRIBUTING.md) and wholeheartedly agree

### I've found a bug and checked that ...

- [X] ... the documentation does not mention anything about my problem
- [X] ... there are no open or closed issues that are related to my problem

### Description

devconatiner docker-in-docker  feature polls github for tags, find the latest then try to download the release tarball, yet fails now because latest if v0.11.0 but the release tarball for it doesn't exists:

```#0 105.5 buildx_version=0.11.0
#0 105.5 (*) Installing buildx 0.11.0...
#0 105.5 --2023-06-13 14:18:56--  https://github.com/docker/buildx/releases/download/v0.11.0/buildx-v0.11.0.linux-amd64
#0 105.5 Resolving github.com (github.com)... 192.30.255.113
#0 105.5 Connecting to github.com (github.com)|192.30.255.113|:443... connected.
#0 105.6 HTTP request sent, awaiting response... 404 Not Found
#0 105.7 2023-06-13 14:18:56 ERROR 404: Not Found.
#0 105.7
#0 105.7 ERROR: Feature "Docker (Docker-in-Docker)" (ghcr.io/devcontainers/features/docker-in-docker) failed to install! Look at the documentation at https://github.com/devcontainers/features/tree/main/src/docker-in-docker for help troubleshooting this error.
------
Dockerfile-with-features:95
--------------------
  94 |     ENV DOCKER_BUILDKIT=1
  95 | >>> RUN --mount=type=bind,from=dev_containers_feature_content_source,source=docker-in-docker_3,target=/tmp/build-features-src/docker-in-docker_3 \
  96 | >>>     cp -ar /tmp/build-features-src/docker-in-docker_3 /tmp/dev-container-features \
  97 | >>>  && chmod -R 0755 /tmp/dev-container-features/docker-in-docker_3 \
  98 | >>>  && cd /tmp/dev-container-features/docker-in-docker_3 \
  99 | >>>  && chmod +x ./devcontainer-features-install.sh \
 100 | >>>  && ./devcontainer-features-install.sh \
 101 | >>>  && rm -rf /tmp/dev-container-features/docker-in-docker_3
 102 |
--------------------
```

### Expected behaviour

Please publish the v0.11.0 tarball to unblock devcontainer users.

### Actual behaviour

devcontainer image build are failing.

### Buildx version

v0.11.0

### Builders list

```text
n/a
```

### Configuration

n/a

**Comment by jedevc** [comment]
https://github.com/docker/buildx/releases/tag/v0.11.0 has now been released.

Looks like this access to the release happened right in-between steps.

**Comment by hpe-ykoehler** [comment]
will pass that along to the devcontainer feature author, thanks.

**Comment by benjamin-commentor** [comment]
@jedevc It has been released on github, but not in the docker repo
Example: https://download.docker.com/linux/centos/8/x86_64/stable/Packages/

**Comment by thaJeztah** [comment]
@benjamin-commentor packages on download.docker.com are currently built as part of the release pipeline for docker engine; updated packages for buildx will be released together with the next patch release of the engine (24.0.3); I don't have a date for that yet (we have a couple of fixes to backport, after that we probably can do a patch release)
