### ISSUE TITLE
bake-hcl: Unable to use matrix variables in some target attributes 

### ISSUE THREAD

**Issue by jeliebig** [docker/buildx#1887]
### Contributing guidelines

- [X] I've read the [contributing guidelines](https://github.com/docker/buildx/blob/master/.github/CONTRIBUTING.md) and wholeheartedly agree

### I've found a bug and checked that ...

- [X] ... the documentation does not mention anything about my problem
- [X] ... there are no open or closed issues that are related to my problem

### Description

I just learned about bake and HCL and have created the bake definition and Dockerfiles below as a small test.
To verify my bake definition is correct, I ran `docker buildx bake -f docker-bake-test.hcl --print php` which returned a few confusing errors. Since there are multiple error messages, but only 2 different ones I'll describe only them below. 

The file structure for this test:
- root/
  - php-7.4/
    - Dockerfile 
  - php-8.0/
    - Dockerfile
  - docker-bake-test.hcl

### Expected behaviour

The command should have printed the following bake definition:
```json                                                                                                                                                                              
{
  "group": {
    "php": {
      "targets": [
        "php-7-4",
        "php-8-0"
      ]
    }
    "default": {
      "targets": [
        "php"
      ]
    }
  },
  "target": {
    "php-7-4": {
      "context": "php-7.4",
      "dockerfile": "php-7.4/Dockerfile",
      "tags":  [
        "php:7.4"
      ]
    },
    "php-8-0": {
      "context": "php-8.0",
      "dockerfile": "php-8.0/Dockerfile",
      "tags":  [
        "php:8.0"
      ]
    }
  }
}
```

Note that I'm new to bake, so I'm not 100% sure if this would be the exact result, but this should hopefully suffice. 

### Actual behaviour

First error after running `docker buildx bake -f docker-bake-test.ym --print php`:
```
[+] Building 0.0s (0/0)                                                                                                                                                                              
docker-bake-test.hcl:12
--------------------
  10 |         dockerfile = "php-${version}/Dockerfile"
  11 |         context = "php-${version}"
  12 | >>>     tags = ["php:${version}"]
  13 |     }
  14 |     
--------------------
ERROR: docker-bake-test.hcl:12,12-30: Invalid expression; variable cycle not allowed for version
```

Second error after commenting the attributes `dockerfile` and `context`:
```
[+] Building 0.0s (0/0)                                                                                                                                                                              
docker-bake-test.hcl:12
--------------------
  10 |         // dockerfile = "php-${version}/Dockerfile"
  11 |         // context = "php-${version}"
  12 | >>>     tags = ["php:${version}"]
  13 |     }
  14 |     
--------------------
ERROR: docker-bake-test.hcl:12,20-27: Unknown variable; There is no variable named "version"., and 1 other diagnostic(s)
```

### Buildx version

github.com/docker/buildx 0.10.5 86bdced7766639d56baa4c7c449a4f6468490f87

### Docker info

```text
Client:
 Version:    24.0.2
 Context:    default
 Debug Mode: false
 Plugins:
  buildx: Docker Buildx (Docker Inc.)
    Version:  0.10.5
    Path:     /usr/lib/docker/cli-plugins/docker-buildx
  compose: Docker Compose (Docker Inc.)
    Version:  2.18.1
    Path:     /usr/lib/docker/cli-plugins/docker-compose
  scan: Docker Scan (Docker Inc.)
    Version:  v0.1.0-280-gc7fa31d4c4
    Path:     /usr/lib/docker/cli-plugins/docker-scan

Server:
 Containers: 0
  Running: 0
  Paused: 0
  Stopped: 0
 Images: 4
 Server Version: 24.0.2
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Using metacopy: true
  Native Overlay Diff: false
  userxattr: false
 Logging Driver: json-file
 Cgroup Driver: systemd
 Cgroup Version: 2
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: io.containerd.runc.v2 runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 0cae528dd6cb557f7201036e9f43420650207b58.m
 runc version: 
 init version: de40ad0
 Security Options:
  seccomp
   Profile: builtin
  cgroupns
 Kernel Version: 6.1.33-1-lts
 Operating System: Arch Linux
 OSType: linux
 Architecture: x86_64
 CPUs: 12
 Total Memory: 23.2GiB
 Name: REDACTED
 ID: 3e036ffc-36e6-45e5-b357-ccce91c04fcd
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false
```

### Builders list

```text
NAME/NODE DRIVER/ENDPOINT STATUS  BUILDKIT                              PLATFORMS
default * docker                                                        
  default default         running v0.11.7-0.20230525183624-798ad6b0ce9f linux/amd64, linux/amd64/v2, linux/amd64/v3, linux/386
```

### Configuration

In this file structure each version has its own Dockerfile. This example Dockerfile would be present at `php-7.2/Dockerfile`:
```Dockerfile
FROM php:7.2

RUN echo hello
```

In the root directory of this file structure I created the following bake definition as `docker-bake-test.hcl`:
```hcl
variable "PHP_VERSIONS" {
    default = ["7.4", "8.0"]
}

target "php" {
    name = "php-${replace(version, ".", "-")}"
    matrix = {
        version = PHP_VERSIONS
    }   
    dockerfile = "php-${version}/Dockerfile"
    context = "php-${version}"
    tags = ["php:${version}"]
}
```

An earlier version of this file looked like this and produced the same issue:
```hcl
target "php" {
    name = "php-${replace(version, ".", "-")}"
    matrix = {
        version = ["7.4", "8.0"]
    }   
    dockerfile = "php-${version}/Dockerfile"
    context = "php-${version}"
    tags = ["php:${version}"]
}
```

### Additional info

The documentation for [target.matrix](https://docs.docker.com/build/bake/reference/#targetmatrix) doesn't specify that matrix variables don't work with some attributes in case the errors are expected behavior.

I have not yet tried to use matrix variables with other `target` attributes, so I'm not sure if this only affects `dockerfile`, `context` and `tags`.

I hope I didn't miss any relevant information here, but if I did please tell me and I'll try to add the missing bits.

---

Not relevant to this issue, but I just saw that the [group](https://docs.docker.com/build/bake/reference/#group) documentation also doesn't specify that you can reference other groups in the `targets` attribute as well.

**Comment by jedevc** [comment]
Your buildx version is shown as v0.10.5 - the matrix field is only introduced in v0.11.0, it looks like you're still on the older version?

**Comment by jeliebig** [comment]
Thanks for the quick reply! I had no idea it was introduced with `v0.11.0`. I just updated and ran the same command again and it worked just as expected!

Should this be clarified in the documentation maybe?
