### ISSUE TITLE
--build-arg fails with private key

### ISSUE THREAD

**Issue by jamesyli** [docker/buildx#1898]
### Contributing guidelines

- [X] I've read the [contributing guidelines](https://github.com/docker/buildx/blob/master/.github/CONTRIBUTING.md) and wholeheartedly agree

### I've found a bug and checked that ...

- [X] ... the documentation does not mention anything about my problem
- [X] ... there are no open or closed issues that are related to my problem

### Description

docker buildx build fails with the following build args:

```
--build-arg SSH_PRV_KEY=-----BEGIN OPENSSH PRIVATE KEY-----
xxx
END OPENSSH PRIVATE KEY----- --build-arg ANOTHER=foo
```

### Expected behaviour

build succeeds

### Actual behaviour

build failed

### Buildx version

github.com/docker/buildx v0.10.0 876462897612d36679153c3414f7689626251501

### Builders list

```text
NAME/NODE       DRIVER/ENDPOINT STATUS  BUILDKIT PLATFORMS
default *       docker
  default       default         running 20.10.22 linux/arm64, linux/amd64, linux/riscv64, linux/ppc64le, linux/s390x, linux/386, linux/arm/v7, linux/arm/v6
desktop-linux   docker
  desktop-linux desktop-linux   running 20.10.22 linux/arm64, linux/amd64, linux/riscv64, linux/ppc64le, linux/s390x, linux/386, linux/arm/v7, linux/arm/v6
```

### Configuration

fails with any Dockerfile

**Comment by jedevc** [comment]
Can you provide the exact error you're getting?

:warning: That said! It's *really* not a good idea to add secrets as build-args - there's a chance that they'll end up in the build result, or they could get stored in the build cache, if you're using `--cache-to` (or just on the system).

You should instead prefer to use `--secret` for sensitive data. You can access these using secret mounts in `RUN`: https://docs.docker.com/engine/reference/builder/#run---mount.
