### ISSUE TITLE
feature request: a --push flag for docker buildx bake

### ISSUE THREAD

**Issue by patrickattnt** [docker/buildx#190]
After creating a buildx builder with a number of enabled platforms (eg. amd64, arm64), I was able to successfully using a command like: 

docker buildx build --push --platform linux/amd64,linux/arm64 -t registry-url/project/project:latest -f Dockerfile .

It appears that the following command works as well: 
docker buildx bake -f  docker-compose.yml

The use of the docker-compose.yml file for bake is definitely advantageous - there are multiple build targets defined in the Dockerfile and docker-compose.yml file using https://docs.docker.com/compose/compose-file/#target 

Requesting a flag for buildx bake that would be roughly equiv to 'docker-compose push' - it would build the necessary images for all defined platforms, and then push the images for all defined services to the registry.

**Comment by andrwwbstr** [comment]
It seems that a push can be done with `--set target.output=type=registry`.  See #164 for a patch that makes `--push` an alias.

**Comment by tonistiigi** [comment]
#164
