### ISSUE TITLE
`--push` fails with `unexpected status: 404 Not Found`

### ISSUE THREAD

**Issue by SeMeKh** [docker/buildx#196]
Running `docker build -t myregistry.jfrog.io/backend/test --push --progress=plain .` ends with:
```
#6 exporting to image
#6 exporting layers done
#6 exporting manifest sha256:5c7409b399a82c9db2ec67cdbd6751bbb3a3744690493d34ba7c533877d25098 0.0s done
#6 exporting config sha256:bed2be5d8b85a79ec121dc603170315afc6582b877e66d8c0053bea8ba6ccce0 done
#6 pushing layers
#6 pushing layers 0.9s done
#6 ERROR: failed commit on ref "config-sha256:bed2be5d8b85a79ec121dc603170315afc6582b877e66d8c0053bea8ba6ccce0": unexpected status: 404 Not Found
------
 > exporting to image:
------
failed to solve: rpc error: code = Unknown desc = failed commit on ref "config-sha256:bed2be5d8b85a79ec121dc603170315afc6582b877e66d8c0053bea8ba6ccce0": unexpected status: 404 Not Found
```

You can `--push` the image to DockerHub successfully, but not Artifactory's Docker registry, although `docker push` is successful on both registries. So, I tried to capture the network requests, and realized that there's a small difference between the way `docker push` and `docker buildx build --push` push the image layers.

Apparently, `docker push` does a sequence of `POST`, `PATCH`, and `PUT` (with no body), while `docker buildx build --push` does a `POST` followed by a `PUT` (with body). The latter `PUT` results in a 404 BLOB_UNKNOWN on Artifactory.

So, is it possible to change the behavior of `docker buildx build --push` to match that of `docker build` so that other registries work as expected? Please note that the same issue happens for `--cache-to`.

**Comment by tonistiigi** [comment]
cc @dmcgowan

**Comment by SeMeKh** [comment]
Any updates on this? Should this be followed up from the Artifactory team instead?

**Comment by franckOL** [comment]
Same issue. need it.
is there any kind workaround for that ?

**Comment by keiyasssss** [comment]
Same issue using latest version of builx and artifactory version 6.16.0

**Comment by Legogris** [comment]
Same issue here, with a locally hosted repository that has worked previously.

**Comment by dpipemazo** [comment]
Perhaps this issue I filed is related: #271

**Comment by opsnull** [comment]
Same issue here, with a locally hosted harbor repository.

**Comment by dathdev** [comment]
I'm running into the same issue in 2021 with Artifactory

**Comment by wichert** [comment]
@dathdev I suspect that this is related to https://www.jfrog.com/jira/browse/RTFACT-19344, and I'm not sure if that has made it into a release yet.

**Comment by kaka-ruto** [comment]
My issue was that I was pushing to an inexistent repository (I had put the wrong url), thus my error. It worked after using the right URL

**Comment by wichert** [comment]
FYI I can confirm is that upgrading to a current version of Artifactory makes this problem go away.

**Comment by franckOL** [comment]
Since which Artifactory version it works ?

**Comment by dathdev** [comment]
I can confirm this was fixed when I upgraded Artifactory past 6.20.0.

**Comment by soapergem** [comment]
I think this same issue is happening with Amazon ECR.

**Comment by wyaopeng** [comment]
same issue
