### ISSUE TITLE
arm aarch64 detects as platform when  --platform linux/arm/v7 passed to buildx on aarch64 hardware

### ISSUE THREAD

**Issue by iav** [docker/buildx#198]
I run `docker buildx build --platform linux/arm/v7 ...` on arm64 SBC
```
$ uname -a
Linux droid 4.9.190-odroidn2 #1 SMP PREEMPT Mon Sep 2 07:23:40 CEST 2019 aarch64 aarch64 aarch64 GNU/Linux
```
but generally inside docker builder I see not a armv7l, but aarch64 platform
```
#8 [stage-1 3/19] RUN echo "Hello, my CPU architecture is $(uname -m)"
#8 0.338 Hello, my CPU architecture is aarch64
#8 DONE 0.4s
```
then all platform-depended `configure `scripts works wrong.
Is it bug or feature? How can I get a platform currently builded inside dockerfile shell scripts?
```
Client: Docker Engine - Community
 Version:           19.03.5
 API version:       1.40
 Go version:        go1.12.12
 Git commit:        633a0ea
 Built:             Wed Nov 13 07:27:46 2019
 OS/Arch:           linux/arm64
 Experimental:      true

Server: Docker Engine - Community
 Engine:
  Version:          19.03.5
  API version:      1.40 (minimum version 1.12)
  Go version:       go1.12.12
  Git commit:       633a0ea
  Built:            Wed Nov 13 07:26:16 2019
  OS/Arch:          linux/arm64
  Experimental:     false
 containerd:
  Version:          1.2.10
  GitCommit:        b34a5c8af56e510852c35414db4c1f4fa6172339
 runc:
  Version:          1.0.0-rc8+dev
  GitCommit:        3e425f80a8c931f88e6d94a8c831b9d5aa481657
 docker-init:
  Version:          0.18.0
  GitCommit:        fec3683

$ cat /etc/os-release
NAME="Ubuntu"
VERSION="18.04.3 LTS (Bionic Beaver)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 18.04.3 LTS"
VERSION_ID="18.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=bionic
UBUNTU_CODENAME=bionic

$ docker buildx ls
NAME/NODE  DRIVER/ENDPOINT             STATUS  PLATFORMS
builder *  docker-container
  builder0 unix:///var/run/docker.sock running linux/arm64, linux/arm/v7, linux/arm/v6
default    docker
  default  default                     running linux/arm64, linux/arm/v7, linux/arm/v6

```

**Comment by FernandoMiguel** [comment]
What does `docker buildx ls` show?

**Comment by iav** [comment]
@FernandoMiguel see at the end of issue.

**Comment by tonistiigi** [comment]
I assume this is without qemu and just native arm64 backward compatibility. In that case armv7 `uname` binary will execute against your current system, so if you create new binaries/install packages they would be for armv7 but the actual output for invoking `uname` would come based on your `arm64` system. You can either try to install qemu-user for arm so all armv7 binaries get executed through emulator (haven't really ever tried it for arm64) and then the emulator will provide a fake result to `uname` output. Another way is to define `ARG TARGETPLATFORM` (or `TARGETARCH`) and then you can use `$TARGETPLATFORM` to see the value that you would need.

**Comment by iav** [comment]
Yes, it was without qemu.
Thank you, will try TARGETPLATFORM

**Comment by iav** [comment]
Now I set qemu-user-static binfmt-support.
Nothing changes.
How can I tell buildx "now use qemu for  buildx build --platform linux/arm/v7"?

**Comment by tonistiigi** [comment]
if you have installed the support in the kernel you need to restart the builder instance or recreate with `buildx create use`. You can add support for arch that isn't natively supported like `amd64` in your case so you can see if buildx will detect it.

**Comment by iav** [comment]
So, I did.
I remove existed builder, check for qemu platform support:
```
$ docker run --rm mplatform/mquery mplatform/mquery
Image: mplatform/mquery
 * Manifest List: Yes
 * Supported platforms:
   - linux/amd64
   - linux/arm
   - linux/arm64
   - linux/ppc64le
   - linux/s390x
   - windows/amd64:10.0.14393.1593
```
then recreate builder:
```
$ docker buildx create --use
agitated_murdock
```
see for platforms
```
$ docker buildx ls
NAME/NODE           DRIVER/ENDPOINT             STATUS  PLATFORMS
agitated_murdock *  docker-container
  agitated_murdock0 unix:///var/run/docker.sock running linux/arm64, linux/arm/v7, linux/arm/v6
default             docker
  default           default                     running linux/arm64, linux/arm/v7, linux/arm/v6
```
hm? Why I see no ppc, no amd64?

then run build armv7 again
```
$ docker buildx build --platform linux/arm/v7 -f test --progress plain . 
...
#1 [internal] booting buildkit
#1 pulling image moby/buildkit:buildx-stable-1
#1 pulling image moby/buildkit:buildx-stable-1 2.4s done
#1 creating container buildx_buildkit_agitated_murdock0
#1 creating container buildx_buildkit_agitated_murdock0 1.7s done
#1 DONE 4.1s
...
#6 [2/3] RUN echo "Hello, my CPU architecture is $(uname -m)"
#6 0.295 Hello, my CPU architecture is aarch64
```
Seems something goes wrong,  arm64 still used instead armv7.

**Comment by tonistiigi** [comment]
`mplatform/mquery mplatform/mquery` does not show you the qemu support. It just shows the platdorms mquery image was built for. `buildx ls` or `buildx inspect` shows the supported platforms.

**Comment by iav** [comment]
Thank you for clarification. However we see `docker-container` and `linux/arm64, linux/arm/v7` in `buildx ls` output. How to enforce `armv7` emulation?

**Comment by tonistiigi** [comment]
If you want to use emulation for `arm/v7` under `arm64` instead of using the native fallback execution mode you need to set up qemu-user emulation for arm binaries in the kernel. Same as when you use emulation to build for x86 from arm64 for example. https://github.com/docker/buildx#building-multi-platform-images . Can't say I recommend it though, as should be a big performance hit.
