### ISSUE TITLE
Cache of RUN command depends on the --network option value

### ISSUE THREAD

**Issue by vuadensl** [docker/buildx#1989]
### Contributing guidelines

- [X] I've read the [contributing guidelines](https://github.com/docker/buildx/blob/master/.github/CONTRIBUTING.md) and wholeheartedly agree

### I've found a bug and checked that ...

- [X] ... the documentation does not mention anything about my problem
- [X] ... there are no open or closed issues that are related to my problem

### Description

The cache for the RUN commands is not shared across builds with different `--network` option value (same dockerfile).

To say it otherwise, when building an image with the network allowed then building it without the network allowed (using the docker build option: --network), the cache for the RUN commands is not shared.

For a glimpse of our use case: we want to build a layer without the network allowed and so we need the steps of the previous layers (because some use the network) to hit the cache.

### Expected behaviour

The --network option value is not used to determine if the cache can be used or not.

### Actual behaviour

The --network option value is used to determine the cache key.

### Buildx version

github.com/docker/buildx v0.11.0 687feca9e8dcd1534ac4c026bc4db5a49de0dd6e

### Docker info

```text
Client: Docker Engine - Community
 Version:    24.0.2
 Context:    default
 Debug Mode: false
 Plugins:
  buildx: Docker Buildx (Docker Inc.)
    Version:  v0.11.0
    Path:     /usr/local/lib/docker/cli-plugins/docker-buildx
  compose: Docker Compose (Docker Inc.)
    Version:  v2.19.1
    Path:     /usr/local/lib/docker/cli-plugins/docker-compose
  dev: Docker Dev Environments (Docker Inc.)
    Version:  v0.1.0
    Path:     /usr/local/lib/docker/cli-plugins/docker-dev
  extension: Manages Docker extensions (Docker Inc.)
    Version:  v0.2.20
    Path:     /usr/local/lib/docker/cli-plugins/docker-extension
  init: Creates Docker-related starter files for your project (Docker Inc.)
    Version:  v0.1.0-beta.6
    Path:     /usr/local/lib/docker/cli-plugins/docker-init
  sbom: View the packaged-based Software Bill Of Materials (SBOM) for an image (Anchore Inc.)
    Version:  0.6.0
    Path:     /usr/local/lib/docker/cli-plugins/docker-sbom
  scan: Docker Scan (Docker Inc.)
    Version:  v0.26.0
    Path:     /usr/local/lib/docker/cli-plugins/docker-scan
  scout: Command line tool for Docker Scout (Docker Inc.)
    Version:  0.16.1
    Path:     /usr/local/lib/docker/cli-plugins/docker-scout

Server:
 Containers: 20
  Running: 20
  Paused: 0
  Stopped: 0
 Images: 30
 Server Version: 24.0.2
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Using metacopy: false
  Native Overlay Diff: true
  userxattr: false
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Cgroup Version: 2
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: io.containerd.runc.v2 runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 3dce8eb055cbb6872793272b4f20ed16117344f8
 runc version: v1.1.7-0-g860f061
 init version: de40ad0
 Security Options:
  seccomp
   Profile: builtin
  cgroupns
 Kernel Version: 5.15.90.1-microsoft-standard-WSL2
 Operating System: Docker Desktop
 OSType: linux
 Architecture: x86_64
 CPUs: 5
 Total Memory: 15.62GiB
 Name: docker-desktop
 ID: d84e83ab-15cd-4bd4-88da-99cff7d7d014
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 HTTP Proxy: http.docker.internal:3128
 HTTPS Proxy: http.docker.internal:3128
 No Proxy: hubproxy.docker.internal
 Experimental: false
 Insecure Registries:
  hubproxy.docker.internal:5555
  127.0.0.0/8
 Live Restore Enabled: false
```

### Builders list

```text
NAME/NODE       DRIVER/ENDPOINT STATUS  BUILDKIT                              PLATFORMS
default *       docker
  default       default         running v0.11.7-0.20230525183624-798ad6b0ce9f linux/amd64, linux/amd64/v2, linux/amd64/v3, linux/amd64/v4, linux/arm64, linux/riscv64, linux/ppc64le, linux/s390x, linux/386, linux/mips64le, linux/mips64, linux/arm/v7, linux/arm/v6
desktop-linux   docker
  desktop-linux desktop-linux   running v0.11.7-0.20230525183624-798ad6b0ce9f linux/amd64, linux/amd64/v2, linux/amd64/v3, linux/amd64/v4, linux/arm64, linux/riscv64, linux/ppc64le, linux/s390x, linux/386, linux/mips64le, linux/mips64, linux/arm/v7, linux/arm/v6
```

### Configuration

Given a simple Dockerfile:
```Dockerfile
FROM alpine
RUN echo "Hello World!"
```

Both commands used are:
```console
$  docker build -f Dockerfile --progress=plain .
$  docker build -f Dockerfile --progress=plain --network=none .
```

See next section for the output of the commands.

### Build logs

I ran a first time without much option so allowing the network:
```console
$  docker build -f Dockerfile --progress=plain .
#0 building with "default" instance using docker driver

#1 [internal] load build definition from Dockerfile
#1 transferring dockerfile: 72B done
#1 DONE 0.0s

#2 [internal] load .dockerignore
#2 transferring context: 2B done
#2 DONE 0.0s

#3 [internal] load metadata for docker.io/library/alpine:latest
#3 DONE 0.4s

#4 [1/2] FROM docker.io/library/alpine@sha256:82d1e9d7ed48a7523bdebc18cf6290bdb97b82302a8a9c27d4fe885949ea94d1
#4 CACHED

#5 [2/2] RUN echo "Hello World!"
#5 0.202 Hello World!
#5 DONE 0.2s

#6 exporting to image
#6 exporting layers 0.0s done
#6 writing image sha256:583a69a0622748720d7f390803255800bbe3672c7743d2395dc1425a778f3cde done
#6 DONE 0.0s

What's Next?
  View summary of image vulnerabilities and recommendations → docker scout quickview
```

Everything is built & cached but let's confirm it by running the command again (look at the RUN):
```console
$ docker build -f Dockerfile --progress=plain .
#0 building with "default" instance using docker driver

#1 [internal] load .dockerignore
#1 transferring context: 2B done
#1 DONE 0.0s

#2 [internal] load build definition from Dockerfile
#2 transferring dockerfile: 72B 0.0s done
#2 DONE 0.0s

#3 [internal] load metadata for docker.io/library/alpine:latest
#3 DONE 0.4s

#4 [1/2] FROM docker.io/library/alpine@sha256:82d1e9d7ed48a7523bdebc18cf6290bdb97b82302a8a9c27d4fe885949ea94d1
#4 DONE 0.0s

#5 [2/2] RUN echo "Hello World!"
#5 CACHED

#6 exporting to image
#6 exporting layers done
#6 writing image sha256:583a69a0622748720d7f390803255800bbe3672c7743d2395dc1425a778f3cde done
#6 DONE 0.0s

What's Next?
  View summary of image vulnerabilities and recommendations → docker scout quickview
```

It is using the cache, now lets turn of the network:
```console
$ docker build -f Dockerfile --progress=plain --network=none .
#0 building with "default" instance using docker driver

#1 [internal] load .dockerignore
#1 transferring context: 2B done
#1 DONE 0.0s

#2 [internal] load build definition from Dockerfile
#2 transferring dockerfile: 72B done
#2 DONE 0.0s

#3 [internal] load metadata for docker.io/library/alpine:latest
#3 DONE 1.1s

#4 [1/2] FROM docker.io/library/alpine@sha256:82d1e9d7ed48a7523bdebc18cf6290bdb97b82302a8a9c27d4fe885949ea94d1
#4 CACHED

#5 [2/2] RUN echo "Hello World!"
#5 0.072 Hello World!
#5 DONE 0.1s

#6 exporting to image
#6 exporting layers 0.0s done
#6 writing image sha256:2bdb020bfbad3d983eee77345ccf32cf0e0febdc9a283c9a3c5c473cfed13edb done
#6 DONE 0.0s

What's Next?
  View summary of image vulnerabilities and recommendations → docker scout quickview
```
So here everything is rebuild and if we ran the command again then this time it hits the cache:
```console
$ docker build -f Dockerfile --progress=plain --network=none .
#0 building with "default" instance using docker driver

#1 [internal] load build definition from Dockerfile
#1 transferring dockerfile: 72B done
#1 DONE 0.0s

#2 [internal] load .dockerignore
#2 transferring context: 2B done
#2 DONE 0.0s

#3 [internal] load metadata for docker.io/library/alpine:latest
#3 DONE 0.4s

#4 [1/2] FROM docker.io/library/alpine@sha256:82d1e9d7ed48a7523bdebc18cf6290bdb97b82302a8a9c27d4fe885949ea94d1
#4 DONE 0.0s

#5 [2/2] RUN echo "Hello World!"
#5 CACHED

#6 exporting to image
#6 exporting layers done
#6 writing image sha256:2bdb020bfbad3d983eee77345ccf32cf0e0febdc9a283c9a3c5c473cfed13edb done
#6 DONE 0.0s

What's Next?
  View summary of image vulnerabilities and recommendations → docker scout quickview
```

### Additional info

I submit it as an issue because it worked 1 month ago on GitHub runners but not anymore. I don't know what was the version :/

**Comment by crazy-max** [comment]
> I submit it as an issue because it worked 1 month ago on GitHub runners but not anymore. I don't know what was the version :/

In GitHub Actions are you using the setup-buildx-action to setup Buildx and BuildKit? If you don't set any custom BuildKit image then it's using BuildKit v0.12 by default.

Looking at your repro:

> ```
> #0 building with "default" instance using docker driver
> ```

You're using the docker driver which has BuildKit v0.11 embedded in Docker 24.0.2 so don't think this is a regression with BuildKit v0.11 if there is one.

**Comment by tonistiigi** [comment]
Different network is a different execution context for the process and can make it behave differently. If that is not the case for your dockerfile you should mark the command's network mode there:

```
FROM alpine
RUN --network=none echo "Hello World!"
```

Now the `echo` will always run without network access and does not depend on `build --network` flags.

**Comment by vuadensl** [comment]
Sorry, I was off for the past 2 weeks. Thanks for your time.

@crazy-max we use the 'docker build' command (in direct). Unfortunately, I don't know what was the docker version on GH 3 weeks ago (the version where the network flag was not part of the cache).
I'm talking about a regression because the behavior changed after at least 2 years and I couldn't find an explanation in the documentation or the patch notes (but Docker is big so I might have miss it).

@tonistiigi 
It's in fact not possible for our real case since the RUN command is an apt-update :)
To explain more, we have 2 stages in our image that we build this way:
1. we build a first stage with the network (globally all third parties and updates)
2. we build the second stage reusing the cache from the stage 1 build where we inject our code.
Here we want to ensure that the step 2 is reusing the cache of the stage 1 so we are able to reinject our code in a no internet zone. So we end up using the network none flag that fits perfectly our need (and was working well for the last 2 years).
Locally we didn't run manually this check in a while because we have this CI check running in GH.

**Comment by tonistiigi** [comment]
`--network=none` is not meant for detecting cache matches and causing runtime errors in non-matches. You are running a different command (with different properties), and therefore the cache is different. If you want to use the result from stage1 in the stage2 build directly you can just point to it in your stage2 build (with image or named context for example).

**Comment by vuadensl** [comment]
OK, so I understand from your response that from a "recent" release, all the docker build command options are included in the cache state computation.

For example adding the `--quiet` option will also not use the cache of the same command without it.
So I tried and this option does not change the cache state: the same cache is used with & without the option.

Maybe a note should be added to https://docs.docker.com/build/cache/ to explain more about what information are used to determine if a cache can be reused or not ?

**Comment by vuadensl** [comment]
To share with the community, we found an alternative:
```
unshare --net --ipc -r docker build -f Dockerfile --progress=plain .
```

**Comment by jsternberg** [comment]
@vuadensl we're doing some research into making the build cache more understandable and debuggable. I'm going to close this issue but include it in some existing research we've been doing for how to expose things.

> OK, so I understand from your response that from a "recent" release, all the docker build command options are included in the cache state computation.
>
> For example adding the --quiet option will also not use the cache of the same command without it.
So I tried and this option does not change the cache state: the same cache is used with & without the option.

I think there might be some miscommunication regarding what's used for the cache and not. If you have a `RUN` command in your dockerfile, you're essentially writing this:

```
RUN --network=default ...
```

It's not explicit because that's the default, but it's essentially part of the cache. When you specify `--network=host`, you're changing that to `RUN --network=host` which changes how the command is being run. If you want `default` to always be used regardless of the `--network` flag to the build, you can use `RUN --network=default` and I believe that will prevent it from being modified. In general, that's not really needed.

`--quiet` is an option for the docker cli and doesn't influence the build. It modifies the output rather than how a command runs. The build cache isn't saving the command line options for build itself but the options for the `RUN` command. So you likely won't see `--quiet` affecting what does and does not match cache.
