### ISSUE TITLE
when handling FROM, buildx should check local image store first?

### ISSUE THREAD

**Issue by jingxiaolu** [docker/buildx#199]
**Env**: 

docker 19.03.5 + buildx, **no connection to dockerhub**

buildx version: `github.com/docker/buildx v0.3.1-13-g8bce430.m 8bce430f4d74c9a9ca72a46139804e88502d4b78.m`

**What I'm trying to do**

Build a simple image with Dockerfile:

```
FROM xxx_gcc:aarch64
RUN gcc "-DARCH=\"`uname -a`\"" hello.c -o hello
ENTRYPOINT ["/hello"]
```

**Problem I met**

I have loaded the image `xxx_gcc:aarch64` to dockerd, so this Dockerfile works fine with `docker build .`

But when I try `docker buildx build .`, it fails with:

```
# docker buildx build --pull  .
WARN[0000] No output specified for docker-container driver. Build result will only remain in the build cache. To push result image into registry use --push or to load image into docker use --load
[+] Building 40.1s (4/5)
 => [internal] load build definition from Dockerfile                                                                                                                                                         0.1s
 => => transferring dockerfile: 92B                                                                                                                                                                          0.0s
 => [internal] load .dockerignore                                                                                                                                                                            0.1s
 => => transferring context: 2B                                                                                                                                                                              0.0s
 => ERROR [internal] load metadata for xxx_gcc:aarch64                                                                                                            20.0s
 => ERROR [1/2] FROM xxx_gcc:aarch64                                                                                                                              20.0s
 => => resolve xxx_gcc:aarch64                                                                                                                                    20.0s
------
 > [internal] load metadata for xxx_gcc:aarch64:
------
------
 > [1/2] FROM xxx_gcc:aarch64:
------
failed to solve: rpc error: code = Unknown desc = failed to solve with frontend dockerfile.v0: failed to build LLB: failed to load cache key: failed to do request: Head [REDACTED]/xxx_gcc/manifests/aarch64: dial tcp: lookup [REDACTED]: read udp [REDACTED]: i/o timeout

```

**What I expect**

When `docker build`, it will first check whether the image in `FROM` exists in local store, but `docker buildx build` always trying to pull it from remote registry.

For this case, from my POV, buildx should only pull the image from remote registry when `--pull` is specified:

```
--pull                     Always attempt to pull a newer version of the image
```

Please help to check, thanks!

**Comment by tonistiigi** [comment]
To use images from docker image store you need to use the `docker` driver. From the logs, you are using the container driver that does not have access to your docker images.

**Comment by jingxiaolu** [comment]
thanks @tonistiigi , after switched to `docker` driver, it's OK now~

One similar question on `docker buildx inspect mybuilder --bootstrap`, `mybuild` is `docker-container` driver.
When inspecting with `--bootstrap`, it will pull & run image `moby/buildkit:buildx-stable-1`. 
It will pull image first, but not check local docker image store whether this image exists, so it always fail in my env:
```
# docker buildx inspect mybuilder --bootstrap
[+] Building 0.0s (1/1) FINISHED
 => ERROR [internal] booting buildkit                                                                                                                                                                        0.0s
 => => pulling image moby/buildkit:buildx-stable-1                                                                                                                                                           0.0s
------
 > [internal] booting buildkit:
------
Name:   mybuilder
Driver: docker-container

Nodes:
Name:      mybuilder0
Endpoint:  unix:///var/run/docker.sock
Status:    inactive
Platforms:
```

The related code is https://github.com/docker/buildx/blob/8bce430f4d74c9a9ca72a46139804e88502d4b78/driver/docker-container/driver.go#L62
I think before `ImageCreate()`, we can call `ImageInspectWithRaw()` to check docker image store?

**Comment by tonistiigi** [comment]
@jingxiaolu Sure, we should probably still try to pull first, but if it fails we could check if image with that name already exists and not error if it does.

**Comment by jingxiaolu** [comment]
@tonistiigi thanks for your clarification!
So I can make a PR with `ImageInspectWithRaw()` when `ImageCreate()` returns error for `docker buildx inspect mybuilder --bootstrap`?

**Comment by tonistiigi** [comment]
@jingxiaolu yes
