### ISSUE TITLE
for gitlab registry buildx --push makes error insufficient_scope: authorization failed, docker push same image works

### ISSUE THREAD

**Issue by iav** [docker/buildx#202]
One of my dockerfile can't be pushed to registry.gitlab.com as part of `docker buildx build -f test -t registry.gitlab.com/xxxxx --platform amd64 --push .` with error
```
#26 pushing layers
#26 pushing layers 2.5s done
#26 ERROR: server message: insufficient_scope: authorization failed
------
 > exporting to image:
------
failed to solve: rpc error: code = Unknown desc = server message: insufficient_scope: authorization failed

```
but same image can be pushed if builded to local registry then pushed by docker:
`docker push registry.gitlab.com/xxxxxx`

same time same computer other (tiny test image) can be successfuly build and pushed to gitlab directly as it should, `docker buildx build -f test -t registry.gitlab.com/iav1/musl-builder --platform linux/arm/v7,linux/arm64,amd64 --push .`

How to fix that?
```
$ docker version
Client: Docker Engine - Community
 Version:           19.03.3
 API version:       1.40
 Go version:        go1.12.10
 Git commit:        a872fc2f86
 Built:             Tue Oct  8 01:00:44 2019
 OS/Arch:           linux/amd64
 Experimental:      true

Server: Docker Engine - Community
 Engine:
  Version:          19.03.3
  API version:      1.40 (minimum version 1.12)
  Go version:       go1.12.10
  Git commit:       a872fc2f86
  Built:            Tue Oct  8 00:59:17 2019
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.2.10
  GitCommit:        b34a5c8af56e510852c35414db4c1f4fa6172339
 runc:
  Version:          1.0.0-rc8+dev
  GitCommit:        3e425f80a8c931f88e6d94a8c831b9d5aa481657
 docker-init:
  Version:          0.18.0
  GitCommit:        fec3683
```

**Comment by tonistiigi** [comment]
cc @dmcgowan

**Comment by mingzhaochina** [comment]
I have the same problem..

**Comment by viceice** [comment]
same here, see https://github.com/viceice/docker-buildx-tests

**Comment by miigotu** [comment]
I just got this working, with github actions:

```yml
    - name: Prepare
      if: success()
      id: prepare
      run: |
        echo ::set-output name=docker_platforms::linux/amd64
        echo ::set-output name=docker_username::miigotu
        echo ::set-output name=docker_image::docker.io/miigotu/sickchill
        echo ::set-output name=version::${GITHUB_REF#refs/*/}
    - name: Docker Login
      if: success()
      env:
        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      run: |
        echo "${DOCKER_PASSWORD}" | docker login --username "${{ steps.prepare.outputs.docker_username }}" --password-stdin docker.io
    - name: Run Buildx (master)
      if: success() && contains(steps.prepare.outputs.version, 'master')
      run: |
        docker buildx build \
          --output type=image,name=${{ steps.prepare.outputs.docker_image }},push=true \
          --platform ${{ steps.prepare.outputs.docker_platforms }} \
          --tag "${{ steps.prepare.outputs.docker_image }}:${{ steps.prepare.outputs.version }}" \
          --tag "${{ steps.prepare.outputs.docker_image }}:latest" \
          --file Dockerfile .
    - name: Run Buildx (non-master)
      if: success() && !contains(steps.prepare.outputs.version, 'master')
      run: |
        docker buildx build \
          --output type=image,name=${{ steps.prepare.outputs.docker_image }},push=true \
          --platform ${{ steps.prepare.outputs.docker_platforms }} \
          --tag "${{ steps.prepare.outputs.docker_image }}:${{ steps.prepare.outputs.version }}" \
          --file Dockerfile .
```

**Comment by miigotu** [comment]
@iav You mind adding `github` and `insufficient_scope: authorization failed` to the title of this issue so it can be found via google search for `github insufficient_scope: authorization failed` and `gitlab insufficient_scope: authorization failed` ?

**Comment by alessiocol** [comment]
The missing step for me was that I forgot to login to the Docker hub.
Running `docker login --username <myusername>` before `docker buildx build [..]` solved the problem.

**Comment by erulabs** [comment]
Hello! 

I ran into this issue using buildx on a system with Ubuntu's `snap` docker installed. `docker login` puts credentials in a directory like `/home/$USER/snap/docker/471/.docker/config.json` - which `buildx` does not appear to read. Copying that file to the normal `/home/$USER/.docker/config.json` location allows `buildx` to authenticate.

**Comment by matwey** [comment]
Where did `/home/$USER/snap/docker/471/.docker/` come from?

**Comment by crazy-max** [comment]
Seems to be a host misconfiguration issue. Let us know if it still happens.

**Comment by itkach** [comment]
I have this exact issue 
```
❯ docker version
Client:
 Cloud integration: v1.0.24
 Version:           20.10.14
 API version:       1.41
 Go version:        go1.16.15
 Git commit:        a224086
 Built:             Thu Mar 24 01:49:20 2022
 OS/Arch:           darwin/arm64
 Context:           default
 Experimental:      true

Server: Docker Desktop 4.8.1 (78998)
 Engine:
  Version:          20.10.14
  API version:      1.41 (minimum version 1.12)
  Go version:       go1.16.15
  Git commit:       87a90dc
  Built:            Thu Mar 24 01:45:44 2022
  OS/Arch:          linux/arm64
  Experimental:     false
 containerd:
  Version:          1.5.11
  GitCommit:        3df54a852345ae127d1fa3092b95168e4a88e2f8
 runc:
  Version:          1.0.3
  GitCommit:        v1.0.3-0-gf46b6ba
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0
```

**Comment by cforce** [comment]
@miigotu Your working solution is nice, but can you explain what are /was the exact turn points which make it work and before didn't for the docker buildx command . Thanks once again for clarifying
@itkach Of course repository urls for project repos which are below a group will also include the group in the repo path.  Your comment is misleading as someone might think all gitlab docker repos in gitlab are at the main domain path, but it depends.

**Comment by miigotu** [comment]
> @miigotu Your working solution is nice, but can you explain what are /was the exact turn points which make it work and before didn't for the docker buildx command . Thanks once again for clarifying
> @itkach Of course repository urls for project repos which are below a group will also include the group in the repo path.  Your comment is misleading as someone might think all gitlab docker repos in gitlab are at the main domain path, but it depends.
> 

All of them are in a "group", which is your username or organization that the repo is under. You can't push to gitlab's root domain. Aside from that idk what your question means?

**Comment by cforce** [comment]
For me it was just an simple issue with the ~/.docker/config.json . Delete it and  run
"docker login registry.gitlab.com" - then use your gitlab user name and token (with read/write registry) rights and it works and auth is stored, so next time will reuse. Maybe "docker logout  registry.gitlab.com" would have achieved the same - cleanup some token/auth state mess
