### ISSUE TITLE
Add https:// schema

### ISSUE THREAD

**Issue by lictw** [docker/buildx#2047]
### Description

I want to connect my buildx clients (local, CI/CD) to kubernetes buildkit via just a https URL. Even if I have ingress for buildkit with valid domain I should connect buildx via `tcp://..:443` with `servername` and certificates, can we simplify this to just a `docker buildx create --driver remote https://buildkit..`?

**Comment by jsternberg** [comment]
I'm going to close this due to inactivity. I'll reopen this if there's any response to the above comment or any activity.
