### ISSUE TITLE
kubernetes driver: support resources requests and limits

### ISSUE THREAD

**Issue by thomas-riccardi** [docker/buildx#210]
#167 adds kubernetes as a new driver, creating Deployments with buildkit images.

(reserving) and limiting CPU and Memory on buildkit kubernetes Deployments would be useful.

There doesn't seem to be any in https://github.com/docker/buildx/blob/709ef36b4f10a9389fd9a806657c48a969909d85/driver/kubernetes/manifest/manifest.go

**Comment by crazy-max** [comment]
Fixed through https://github.com/docker/buildx/pull/618
