### ISSUE TITLE
Driver docker-container: add support --debug for buildkitd

### ISSUE THREAD

**Issue by jingxiaolu** [docker/buildx#211]
Sometimes we want to debug with docker-container, so `buildkitd --debug` is important. 
It seems we don't have such option when creating driver docker-container.

My proposal:
- Option 1. add supporting to `--driver-opt debug=true` when `docker buildx create`
- Option 2. add `--debug` for `docker buildx create`, and it passes `--debug` to buildx with `driver.InitConfig.BuildkitFlags` -> `container.Config.Cmd` -> buildkitd in container

I can work on it if you agree 😄 

Please share your comments~

**Comment by tonistiigi** [comment]
`create --buildkitd-flags '--debug'` should work. You can also set the full buildkitd config with `--config`

**Comment by jingxiaolu** [comment]
Thanks @tonistiigi ! I'll log them in my develop guide~
