### ISSUE TITLE
DOCKER_CONTENT_TRUST doesn't work when building with BuildKit. If we disable BuildKit, it functions, but we receive a deprecated warning related to the Docker legacy builder

### ISSUE THREAD

**Issue by Padmavathi126** [docker/buildx#2133]
### Description

Hi, it appears that the problem is still unresolved. When using DOCKER_CONTENT_TRUST=1 and DOCKER_BUILDKIT=0, Content Trust is functioning, but we're encountering a 'DEPRECATED' warning. Going forward, the use of the legacy builder is not recommended. How can I ensure the seamless integration of Docker Content Trust in my GitHub workflow without encountering any issues in the future?

![image](https://github.com/docker/buildx/assets/75683126/17ef6837-6798-4244-9259-436e3cb65022)

This issue seems similar to #987. When can we expect a resolution for this issue? Any updates?

**Comment by LMantovan** [comment]
Hi, any updates? It seems that now we cannot use DOCKER_BUILDKIT=0 anymore

**Comment by thompson-shaun** [comment]
@Padmavathi126 At present this is not planned for buildx.

`DOCKER_BUILDKIT=0` is still available but you will not be able to leverage any buildx-specific features in this mode as this uses the legacy builder.
