### ISSUE TITLE
darwin executable checksums missing from v0.12 checksums file

### ISSUE THREAD

**Issue by andrewrothstein** [docker/buildx#2141]
### Contributing guidelines

- [X] I've read the [contributing guidelines](https://github.com/docker/buildx/blob/master/.github/CONTRIBUTING.md) and wholeheartedly agree

### I've found a bug and checked that ...

- [ ] ... the documentation does not mention anything about my problem
- [X] ... there are no open or closed issues that are related to my problem

### Description

Looking at the [checksums.txt](https://github.com/docker/buildx/releases/download/v0.12.0/checksums.txt) published with v0.12.0, there are none for the darwin executables.

### Expected behaviour

expect checksums for all OS/arch combos

### Actual behaviour

Checksums present for linux and windows executables

### Buildx version

v0.12.0

### Builders list

```text
trying to install it
```

### Configuration

can't get this far

**Comment by tonistiigi** [comment]
We don't generate checksums for darwin binaries as they are signed outside the pipeline. Instead, check that the binary is signed.
