### ISSUE TITLE
Unable to build for platform linux/amd64 on ARM

### ISSUE THREAD

**Issue by sptrakesh** [docker/buildx#2168]
### Contributing guidelines

- [X] I've read the [contributing guidelines](https://github.com/docker/buildx/blob/master/.github/CONTRIBUTING.md) and wholeheartedly agree

### I've found a bug and checked that ...

- [X] ... the documentation does not mention anything about my problem
- [X] ... there are no open or closed issues that are related to my problem

### Description

I periodically build a host of images that I use for various projects, for amd64 and arm64 platforms.  I am updating all my base images from Alpine 3.18 to 3.19, and ran into issues with building on ARM hardware for the AMD64 platform.  I encountered this on my M2 Mac, as well as an EC2 Gravitron instance. On ARM, the arm64 platform build works fine, but generally the amd64 builds fail with gcc seg faulting.  I was able to resolve the issue by building all my images from an x86 EC2 instance, so   this seems to be very ARM specific issue.

### Expected behaviour

As I have done in the past (most recent perhaps 3 months ago), be able to build images for both arm64 and amd64 from ARM hardware.

### Actual behaviour

The amd64 builds fail with gcc seg fault.

### Buildx version

github.com/docker/buildx v0.11.2-desktop.5 f20ec1393426619870066baba9618cf999063886

### Docker info

```text
Client:
 Version:    24.0.6
 Context:    desktop-linux
 Debug Mode: false
 Plugins:
  buildx: Docker Buildx (Docker Inc.)
    Version:  v0.11.2-desktop.5
    Path:     /Users/rakesh/.docker/cli-plugins/docker-buildx
  compose: Docker Compose (Docker Inc.)
    Version:  v2.23.0-desktop.1
    Path:     /Users/rakesh/.docker/cli-plugins/docker-compose
  dev: Docker Dev Environments (Docker Inc.)
    Version:  v0.1.0
    Path:     /Users/rakesh/.docker/cli-plugins/docker-dev
  extension: Manages Docker extensions (Docker Inc.)
    Version:  v0.2.20
    Path:     /Users/rakesh/.docker/cli-plugins/docker-extension
  init: Creates Docker-related starter files for your project (Docker Inc.)
    Version:  v0.1.0-beta.9
    Path:     /Users/rakesh/.docker/cli-plugins/docker-init
  sbom: View the packaged-based Software Bill Of Materials (SBOM) for an image (Anchore Inc.)
    Version:  0.6.0
    Path:     /Users/rakesh/.docker/cli-plugins/docker-sbom
  scan: Docker Scan (Docker Inc.)
    Version:  v0.26.0
    Path:     /Users/rakesh/.docker/cli-plugins/docker-scan
  scout: Docker Scout (Docker Inc.)
    Version:  v1.0.9
    Path:     /Users/rakesh/.docker/cli-plugins/docker-scout

Server:
 Containers: 1
  Running: 1
  Paused: 0
  Stopped: 0
 Images: 28
 Server Version: 24.0.6
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Using metacopy: false
  Native Overlay Diff: true
  userxattr: false
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Cgroup Version: 2
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: io.containerd.runc.v2 runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 8165feabfdfe38c65b599c4993d227328c231fca
 runc version: v1.1.8-0-g82f18fe
 init version: de40ad0
 Security Options:
  seccomp
   Profile: unconfined
  cgroupns
 Kernel Version: 6.4.16-linuxkit
 Operating System: Docker Desktop
 OSType: linux
 Architecture: aarch64
 CPUs: 12
 Total Memory: 7.758GiB
 Name: linuxkit-f6f6881c0c0d
 ID: 34b6bd9a-7539-4226-9230-a41077a56b5a
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 HTTP Proxy: http.docker.internal:3128
 HTTPS Proxy: http.docker.internal:3128
 No Proxy: hubproxy.docker.internal
 Experimental: false
 Insecure Registries:
  hubproxy.docker.internal:5555
  127.0.0.0/8
 Live Restore Enabled: false

WARNING: daemon is not using the default seccomp profile
```

### Builders list

```text
NAME/NODE       DRIVER/ENDPOINT             STATUS  BUILDKIT             PLATFORMS
mybuilder       docker-container                                         
  mybuilder0    unix:///var/run/docker.sock running v0.12.4              linux/arm64, linux/riscv64, linux/ppc64le, linux/s390x, linux/386, linux/mips64, linux/arm/v7, linux/arm/v6
default         docker                                                   
  default       default                     running v0.11.6+616c3f613b54 linux/arm64, linux/riscv64, linux/ppc64le, linux/s390x, linux/386, linux/mips64, linux/arm/v7, linux/arm/v6
desktop-linux * docker                                                   
  desktop-linux desktop-linux               running v0.11.6+616c3f613b54 linux/arm64, linux/riscv64, linux/ppc64le, linux/s390x, linux/386, linux/mips64, linux/arm/v7, linux/arm/v6
```

### Configuration

```
FROM sptrakesh/cppbase
RUN apk add --no-cache curl curl-dev perl python3 snappy-dev

ENV API_VERSION=1.11.226

WORKDIR /opt
RUN git clone --recurse-submodules https://github.com/aws/aws-sdk-cpp.git --branch ${API_VERSION} --depth 1 \
  && cd aws-sdk-cpp \
  && mkdir build && cd build \
  && cmake \
    -DCMAKE_EXE_LINKER_FLAGS="-fuse-ld=mold" -DCMAKE_SHARED_LINKER_FLAGS="-fuse-ld=mold" \
    -DCMAKE_CXX_STANDARD=20 \
    -DCMAKE_CXX_STANDARD_REQUIRED=ON \
    -DCMAKE_BUILD_TYPE=Release \
    -DCMAKE_PREFIX_PATH=/opt/local \
    -DCMAKE_INSTALL_PREFIX=/opt/local \
    -DCMAKE_INSTALL_LIBDIR=lib \
    -DFORCE_SHARED_CRT=OFF \
    -DBUILD_SHARED_LIBS=OFF \
    -DENABLE_TESTING=OFF \
    -DCPP_STANDARD=20 \
    -DENABLE_UNITY_BUILD=ON \
    -DBUILD_ONLY="s3" \
    -DCMAKE_CXX_FLAGS="-Wno-deprecated-declarations" \
    .. \
  && make -j8 \
  && make install

FROM sptrakesh/cppbase
MAINTAINER Rakesh Vidyadharan <rakesh@sptci.com>

ENV API_VERSION=1.11.226

RUN apk --update --no-cache del perl python3 \
  && apk add --no-cache curl-dev

WORKDIR /opt
COPY --from=0 /opt/local local
```

```
docker buildx build --builder mybuilder --platform linux/arm64,linux/amd64 --compress --force-rm -f Dockerfile -m 8192m .
```

### Additional info

I ran into same issue trying to build flatbuffers, arrow, mongocxx, rocksdb etc.

**Comment by crazy-max** [comment]
> The amd64 builds fail with gcc seg fault.

Hard to tell without logs

> I periodically build a host of images that I use for various projects, for amd64 and arm64 platforms. I am updating all my base images from Alpine 3.18 to 3.19, and ran into issues with building on ARM hardware for the AMD64 platform. I encountered this on my M2 Mac, as well as an EC2 Gravitron instance. On ARM, the arm64 platform build works fine, but generally the amd64 builds fail with gcc seg faulting. I was able to resolve the issue by building all my images from an x86 EC2 instance, so this seems to be very ARM specific issue.

It doesn't seem an issue with buildx/buildkit but something wrong with musl/gcc happening since Alpine 3.19. This is also reported in other projects:
* https://github.com/osohq/oso/issues/1735
* https://github.com/alpinelinux/docker-alpine/issues/362
* https://github.com/scrm/scrm-r/issues/45

**Comment by EmTheSKills** [comment]
I encountered the same issue on my end. Last month, I successfully built my app image on the `linux/amd64` platform using my Mac M2. However, today when I attempted to rebuild the image locally, it stalls indefinitely at the last Docker step. I'm hoping this issue gains visibility, as it was working perfectly before.

Here's my **Dockerfile** of my app:

```dockerfile
FROM node:20-alpine as builder
WORKDIR /frontend
COPY package.json ./
RUN npm install
COPY . .
RUN npm run build


FROM nginx:alpine3.17
COPY --from=builder /frontend/build /srv/www
WORKDIR /frontend
COPY  /default.conf /etc/nginx/conf.d/default.conf
```

**Comment by sptrakesh** [comment]
This seems to have been a issue with the `4.25` series of Docker Mac.  I updated to `4.26.1` and am again able to build for both arm64 and amd64.

**Comment by eightnoneone** [comment]
Same. The telltale was the the builder platform details were missing `linux/amd64, linux/amd64/v2`
Updated from 4.25 and those are back.
