### ISSUE TITLE
--push to local registry connection refused with /etc/host redirect

### ISSUE THREAD

**Issue by howardjohn** [docker/buildx#218]
I am trying to get buildkit setup to push to a local registry. Here is what i have done so far:

Create local registry: `docker run -d --restart=always -p "5000:5000" --name registry registry:2`

Add `registry` alias to /etc/hosts: `127.0.0.1       registry` (this is because I want to use https://kind.sigs.k8s.io/docs/user/local-registry/ which will have a docker container with `registry` pointing to a different IP and its easier to keep things consistent instead of using localhost:5000 on my machine and registry:5000 on kubernetes)

Create runner: `docker buildx create --driver-opt network=host --use --config config.toml --name container-builder`
config is:
```toml
[registry."registry:5000"]
  http = true
```

Then run build: `docker buildx build --push -t registry:5000/image .`. Output shows:
```
 => ERROR exporting to image                                                                                                                                                                                  16.0s
 => => exporting layers                                                                                                                                                                                        0.0s
 => => exporting manifest sha256:e6708c8197f8205be8461c880dd61538db7459f3cef7aa754ee5b0115f4cacc1                                                                                                              0.0s
 => => exporting config sha256:26d67aae1a79e498959007b0a0961af346774ab3fe6198baefe4f2e03283870a                                                                                                                0.0s
 => => pushing layers                                                                                                                                                                                         15.9s
------
 > exporting to image:
------
failed to solve: rpc error: code = Unknown desc = failed to do request: Head http://registry:5000/v2/pilot/blobs/sha256:26d67aae1a79e498959007b0a0961af346774ab3fe6198baefe4f2e03283870a: dial tcp [2607:f8b0:4005:80b::200e]:5000: connect: connection timed out
```

If I instead run  `docker buildx build --push -t localhost:5000/image .`. output works:
```
 => exporting to image                                                                                                                                                                                         0.2s
 => => exporting layers                                                                                                                                                                                        0.0s
 => => exporting manifest sha256:e6708c8197f8205be8461c880dd61538db7459f3cef7aa754ee5b0115f4cacc1                                                                                                              0.0s
 => => exporting config sha256:26d67aae1a79e498959007b0a0961af346774ab3fe6198baefe4f2e03283870a                                                                                                                0.0s
 => => pushing layers                                                                                                                                                                                          0.1s
 => => pushing manifest for localhost:5000/image:tag
```

Interestingly, if I switch to 127.0.0.1 instead of localhost I get `http: server gave HTTP response to HTTPS client`, not sure if there is special logic to make `localhost` use http?

Everything above is from a Linux desktop, running Debian 5.2.17, but its a work desktop so it probably has some weird networking configurations set. 

**The same exact steps work on a linux laptop.**

Docker info:
```
Client:
 Debug Mode: false
 Plugins:
  app: Docker Application (Docker Inc., v0.8.0)
  buildx: Build with BuildKit (Docker Inc., v0.3.1-tp-docker)

Server:
 Containers: 3
  Running: 3
  Paused: 0
  Stopped: 0
 Images: 3
 Server Version: 19.03.5
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Native Overlay Diff: true
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: b34a5c8af56e510852c35414db4c1f4fa6172339
 runc version: 3e425f80a8c931f88e6d94a8c831b9d5aa481657
 init version: fec3683
 Security Options:
  apparmor
  seccomp
   Profile: default
 Kernel Version: 5.2.17-1rodete3-amd64
 Operating System: Debian GNU/Linux rodete
 OSType: linux
 Architecture: x86_64
 CPUs: 6
 Total Memory: 62.64GiB
 Name: howardjohn.svl.corp.google.com
 ID: A757:6JXI:57IH:OP4C:LWX7:R2OK:ZYYG:GIQK:ARZ4:Q34S:7FUG:A4O5
 Docker Root Dir: /usr/local/google/docker
 Debug Mode: true
  File Descriptors: 39
  Goroutines: 46
  System Time: 2020-01-02T10:28:10.803261195-08:00
  EventsListeners: 0
 Username: howardjohn
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Registry Mirrors:
  https://mirror.gcr.io/
 Live Restore Enabled: false
```

Any ideas what I may be missing?

**Comment by bug-author** [comment]
I have the save problem, I config buildx.com in /etc/hosts, but it's not work, and it always use https, but my docker warehouse do not have https.
![image](https://user-images.githubusercontent.com/4133268/71817116-cb8b1d00-30bf-11ea-9a4b-af5e523fb703.png)

**Comment by tonistiigi** [comment]
Buildkit runs inside a container with buildx container driver and therefore will never access `/etc/hosts` inside your host machine. You can use buildkitd config with `--config` to configure registry mirrors and http/https. I assume `mirrors = ["localhost:5000"]` should work for you although it is a weird usage.

**Comment by howardjohn** [comment]
> Buildkit runs inside a container with buildx container driver and therefore will never access /etc/hosts inside your host machine.

I have very minimal understand of docker networking, so maybe this makes no sense, but I thought --network=host would make this use the same /etc/hosts? I execed into the buildx container and it seemed to have my /etc/hosts?

For now I am just doing everything as localhost:5000 and no `registry` stuff so its not blocking me at all, just figured it might be an issue/bug others have. If not, feel free to close

**Comment by tonistiigi** [comment]
>  but I thought --network=host would make this use the same /etc/hosts?

Not quite. It makes it so that localhost means the same in both. But `/etc/hosts` comes from the filesystem and filesystems are different in your host and container.

There is also `docker run --add-host registry:localhost` but I don't think the container driver in buildx allows you to set this flag atm.

**Comment by bug-author** [comment]
> Buildkit runs inside a container with buildx container driver and therefore will never access `/etc/hosts` inside your host machine. You can use buildkitd config with `--config` to configure registry mirrors and http/https. I assume `mirrors = ["localhost:5000"]` should work for you although it is a weird usage.

Thanks for telling me why, And I reslove it by dnsmasq.

**Comment by crazy-max** [comment]
Looks like it's solved.
