### ISSUE TITLE
Docker 4.27 build broken

### ISSUE THREAD

**Issue by groogiam** [docker/buildx#2218]
### Contributing guidelines

- [X] I've read the [contributing guidelines](https://github.com/docker/buildx/blob/master/.github/CONTRIBUTING.md) and wholeheartedly agree

### I've found a bug and checked that ...

- [X] ... the documentation does not mention anything about my problem
- [X] ... there are no open or closed issues that are related to my problem

### Description

After upgrading to Docker 4.27 my project no longer builds.

#10 ERROR: failed to calculate checksum of ref 7e5e69fe-0a93-4e6f-94a2-6d69155a6ff7::ry4vsmtlgm8vymwaaeuecfhcn: failed to walk /var/lib/docker/tmp/buildkit-mount1368382612/MyProject/docker-build: lstat /var/lib/docker/tmp/buildkit-mount1368382612/MyProject/docker-build: no such file or directory

### Expected behaviour

Projects that built with 4.26.1 should build in 4.27

### Actual behaviour

Docker build fails copying local files in 4.27

### Buildx version

github.com/docker/buildx v0.12.1-desktop.4 6996841df2f61988c2794d84d33205368f96c317

### Docker info

```text
Client:
 Version:    25.0.1
 Context:    default
 Debug Mode: false
 Plugins:
  buildx: Docker Buildx (Docker Inc.)
    Version:  v0.12.1-desktop.4
    Path:     C:\Program Files\Docker\cli-plugins\docker-buildx.exe
  compose: Docker Compose (Docker Inc.)
    Version:  v2.24.3-desktop.1
    Path:     C:\Program Files\Docker\cli-plugins\docker-compose.exe
  debug: Get a shell into any image or container. (Docker Inc.)
    Version:  0.0.22
    Path:     C:\Program Files\Docker\cli-plugins\docker-debug.exe
  dev: Docker Dev Environments (Docker Inc.)
    Version:  v0.1.0
    Path:     C:\Program Files\Docker\cli-plugins\docker-dev.exe
  extension: Manages Docker extensions (Docker Inc.)
    Version:  v0.2.21
    Path:     C:\Program Files\Docker\cli-plugins\docker-extension.exe
  feedback: Provide feedback, right in your terminal! (Docker Inc.)
    Version:  v1.0.4
    Path:     C:\Program Files\Docker\cli-plugins\docker-feedback.exe
  init: Creates Docker-related starter files for your project (Docker Inc.)
    Version:  v1.0.0
    Path:     C:\Program Files\Docker\cli-plugins\docker-init.exe
  sbom: View the packaged-based Software Bill Of Materials (SBOM) for an image (Anchore Inc.)
    Version:  0.6.0
    Path:     C:\Program Files\Docker\cli-plugins\docker-sbom.exe
  scout: Docker Scout (Docker Inc.)
    Version:  v1.3.0
    Path:     C:\Program Files\Docker\cli-plugins\docker-scout.exe

Server:
 Containers: 1
  Running: 1
  Paused: 0
  Stopped: 0
 Images: 2
 Server Version: 25.0.1
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Using metacopy: false
  Native Overlay Diff: true
  userxattr: false
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Cgroup Version: 1
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local splunk syslog
 Swarm: inactive
 Runtimes: io.containerd.runc.v2 runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: a1496014c916f9e62104b33d1bb5bd03b0858e59
 runc version: v1.1.11-0-g4bccb38
 init version: de40ad0
 Security Options:
  seccomp
   Profile: unconfined
 Kernel Version: 5.15.133.1-microsoft-standard-WSL2
 Operating System: Docker Desktop
 OSType: linux
 Architecture: x86_64
 CPUs: 12
 Total Memory: 7.759GiB
 Name: docker-desktop
 ID: 7e5e69fe-0a93-4e6f-94a2-6d69155a6ff7
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 HTTP Proxy: http.docker.internal:3128
 HTTPS Proxy: http.docker.internal:3128
 No Proxy: hubproxy.docker.internal
 Experimental: false
 Insecure Registries:
  hubproxy.docker.internal:5555
  127.0.0.0/8
 Live Restore Enabled: false

WARNING: No blkio throttle.read_bps_device support
WARNING: No blkio throttle.write_bps_device support
WARNING: No blkio throttle.read_iops_device support
WARNING: No blkio throttle.write_iops_device support
WARNING: daemon is not using the default seccomp profile
```

### Builders list

```text
NAME/NODE       DRIVER/ENDPOINT STATUS  BUILDKIT             PLATFORMS
default *       docker
  default       default         running v0.12.4+3b6880d2a00f linux/amd64, linux/amd64/v2, linux/amd64/v3, linux/arm64, linux/riscv64, linux/ppc64le, linux/s390x, linux/386, linux/mips64le, linux/mips64, linux/arm/v7, linux/arm/v6
desktop-linux   docker
  desktop-linux desktop-linux   running v0.12.4+3b6880d2a00f linux/amd64, linux/amd64/v2, linux/amd64/v3, linux/arm64, linux/riscv64, linux/ppc64le, linux/s390x, linux/386, linux/mips64le, linux/mips64, linux/arm/v7, linux/arm/v6
```

### Configuration

Working on providing a simplified repro.

**Comment by crazy-max** [comment]
> Working on providing a simplified repro.

If you can provide a minimal repro with a Dockerfile that would help, thanks :pray:

**Comment by groogiam** [comment]
> > Working on providing a simplified repro.
> 
> If you can provide a minimal repro with a Dockerfile that would help, thanks 🙏

I had to rollback to 4.26.1 as this was preventing me from working. It looks like I'm going to have to build a new VM to reproduce.

> Also looks similar to [moby/moby#47231](https://github.com/moby/moby/issues/47231)

This looks very similar, I have yet to test the repro due to rolling back but 4.26.1 but the main place this manifested when I had 4.27 installed was inside a docker compose file that was launched by the Visual Studio docker tooling.

**Comment by crazy-max** [comment]
> This looks very similar, I have yet to test the repro due to rolling back but 4.26.1 but the main place this manifested when I had 4.27 installed was inside a docker compose file that was launched by the Visual Studio docker tooling. [microsoft/DockerTools#414](https://github.com/microsoft/DockerTools/issues/414)

Ah ok so this is with `docker compose` and not `docker buildx` or `docker build` right?

**Comment by groogiam** [comment]
> > This looks very similar, I have yet to test the repro due to rolling back but 4.26.1 but the main place this manifested when I had 4.27 installed was inside a docker compose file that was launched by the Visual Studio docker tooling. [microsoft/DockerTools#414](https://github.com/microsoft/DockerTools/issues/414)
> 
> Ah ok so this is with `docker compose` and not `docker buildx` or `docker build` right?

It seems to happen when the build is invoked via docker compose. I am not familiar with the underlying toolchain so I'm not sure what component the actual issue is in. Thanks.

**Comment by crazy-max** [comment]
Ok was able to repro on vscode and this is related to compose build invocation, let's continue the discussion in https://github.com/moby/moby/issues/47231.
