### ISSUE TITLE
Output cache hit / miss layer count on build

### ISSUE THREAD

**Issue by devonwarren** [docker/buildx#2223]
### Description

It would be very nice to be able to easily track how many layers were cached vs missed during a build. I would like to use this information to track cache performance in our CI system. Can this be added as an option for `buildx build`?

Something like `docker buildx build -f Dockerfile . --cache-report=cache-report.json`

cache-report.json:
```json
{
  "overall" : {
    "misses": 2,
    "hits": 1
  },
  "cached_layers": [
    {
      "layer_number": 1,
      "layer_id": 18fb1a987c75191231,
      "type": "FROM",
      "command":  "FROM ubuntu"
    }
  ],
  "missed_layers": [
    {
      "number": 2,
      "id": aabc7757571bca,
      "type": "COPY",
      "command": "COPY ./src ./src",
    },
    {
      "number": 3,
      "id": aabc3891a57571bca,
      "type": "RUN",
      "command": "RUN ./script.sh",
    }
  ]
}
```

**Comment by jedevc** [comment]
Linking to https://github.com/moby/buildkit/pull/4464, which added something very similar like this to `buildctl`.

**Comment by tonistiigi** [comment]
We have added the info about a number of build steps and cached build steps to the history API. This is saved for every build (all buildx builds) and can be inspected in Docker Desktop build views https://docs.docker.com/desktop/use-desktop/builds/ (raw data can also be pulled in `buildctl`).
