### ISSUE TITLE
buildx bake file doesn't support new ulimit directives

### ISSUE THREAD

**Issue by ViliusS** [docker/buildx#2241]
### Description

Not sure if this is a bug, or just feature oversight.

https://github.com/compose-spec/compose-spec/pull/433 implemented support for ulimit directives in Docker Compose file specification, however if I try to use new directives in BuildX Bake file it produces an error.

```
services:
  mydefaultbuild:
    build:
      ulimits:
        nofile:
          soft: 65536
          hard: 65536
```

```
[] docker buildx bake
[+] Building 0.0s (1/1) FINISHED                                                                         docker:default
 => [internal] load local bake definitions                                                                         0.0s
 => => reading docker-compose.yaml 139B / 139B                                                                     0.0s
ERROR: validating : services.mydefaultbuild.build Additional property ulimits is not allowed
```

**Comment by crazy-max** [comment]
This is not yet supported, we need to think of proper way to implement this with bake, see https://github.com/docker/buildx/pull/790#issuecomment-932642761. It might also make more sense to have this attr in the dockerfile.

**Comment by crazy-max** [comment]
> ERROR: validating : services.mydefaultbuild.build Additional property ulimits is not allowed

Oh actually this error comes from compose file validation in bake, that should be solved with https://github.com/docker/buildx/pull/2205 but still `ulimit` will not be handled in the current implementation.

**Comment by crazy-max** [comment]
Opened #2242 if you want to try it:

```
$ docker buildx bake --set *.output=. https://github.com/crazy-max/buildx.git#bake-ulimits-shmsize
$ ./buildx bake
```

**Comment by thaJeztah** [comment]
LOL, saw this ticket, and thought it was not yet supported by Buildkit, so went looking at my epic (https://github.com/moby/moby/issues/40379), but found that this was implemented at some point for BuildKit

- https://github.com/moby/buildkit/pull/2398
- https://github.com/docker/buildx/pull/800


> It might also make more sense to have this attr in the dockerfile.
>> I don't think ulimit belongs to Dockerfile.


Also on the fence if this would make sense in the Dockerfile itself 🤔 I guess the "upside" would be to allow defining that a specific stage requires specific limits, but OTOH that would imply that the Dockerfile would assume it could escalate / gain additional resources (likely not something desirable), besides likely not _possible_ if it tries to gain higher limits than available? (although in that case, if could potentially give a more specific error that the Dockerfile requires certain limits)

**Comment by crazy-max** [comment]
> One caveat though! It looks like nor passing `--ulimit` to the `docker build` command, nor using them in compose file works on Docker Engine >= 25.0 for me anymore. It only works on 24 version and lower. I didn't have time to fully verify this yet, but it could be do [these changes](https://github.com/moby/moby/pull/45534) in the engine.
> 
> EDIT: by "no longer works for me on 25.0" I have meant that I cannot verify if it works or not, because my use case specifically requires `infinity` or very large nofile numbers to fail the build. As I understood 25.0 now caps this limit to 524288 and no matter what I could not increase my test sample configuration pass that limit.

Interesting, can you try with a container builder?

```
$ docker buildx create --name test
$ docker buildx --builder test bake
```

**Comment by crazy-max** [comment]
I tried on Docker 25 with a simple Dockerfile and seems to work for me:

```dockerfile
FROM busybox
RUN ulimit -n
```

```
$ docker version
Client:
 Cloud integration: v1.0.35+desktop.10
 Version:           25.0.3
 API version:       1.44
 Go version:        go1.21.6
 Git commit:        4debf41
 Built:             Tue Feb  6 21:13:00 2024
 OS/Arch:           linux/amd64
 Context:           default

Server: Docker Desktop
 Engine:
  Version:          25.0.3
  API version:      1.44 (minimum version 1.24)
  Go version:       go1.21.6
  Git commit:       f417435
  Built:            Tue Feb  6 21:14:25 2024
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.6.28
  GitCommit:        ae07eda36dd25f8a1b98dfbf587313b99c0190bb
 runc:
  Version:          1.1.12
  GitCommit:        v1.1.12-0-g51d5e94
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0
```

```
$ docker buildx build --ulimit "nofile=1024:1024" .
#0 building with "default" instance using docker driver

#1 [internal] load build definition from Dockerfile
#1 transferring dockerfile: 64B done
#1 DONE 0.1s

#2 [internal] load metadata for docker.io/library/busybox:latest
#2 DONE 0.0s

#3 [internal] load .dockerignore
#3 transferring context: 2B done
#3 DONE 0.1s

#4 [1/2] FROM docker.io/library/busybox:latest
#4 DONE 0.0s

#5 [2/2] RUN ulimit -n
#5 0.307 1024
#5 DONE 0.3s

#6 exporting to image
#6 exporting layers 0.1s done
#6 writing image sha256:04088e084b1c323bae0eb07d74d3b6fb4114cae6ebbb17eceffb4070f9d98d33 done
#6 DONE 0.1s
```

**Comment by ViliusS** [comment]
OK, I've bean able to verify this on 25.0 too. It works 👍 I've set `LimitNOFILE=infinity` in `/usr/lib/systemd/system/docker.service` and this allowed to set ulimit through bake script past `524288`.

Given that ulimit parameter is now capped by default it looses some usage point (at least for our use case where we specifically want to cap it).

I think at least ulimit parameter documentation needs to be updated everywhere as now it silently allows very large values, but they do not work.

**Comment by polarathene** [comment]
> Given that ulimit parameter is now capped by default it looses some usage point (at least for our use case where we specifically want to cap it).

It isn't capped by Docker anymore, just inherits the default from the system which will typically be `1024:524288`. You can provide a drop-in unit override config like you discovered to raise the hard limit higher when that's necessary. That can be for the particular service like Docker or system-wide (_provided a service doesn't override it that, which was the case previously with Docker_).

---

> I think at least ulimit parameter documentation needs to be updated everywhere as now it silently allows very large values, but they do not work

Looks like that shouldn't silently happen anymore and you'd get a failure. Had a quick glance over the docs but doesn't appear to mention any caveats / advice to raise the hard limit beyond the system-wide default.

Out of curiosity, what were you building that needed more than 524288 file descriptors? Or was the issue with the soft limit being 1024? (_some software that requires a higher limit doesn't request it internally even though it should, so you need to raise it manually if 1024 is not enough for a process_)

**Comment by ViliusS** [comment]
> > Given that ulimit parameter is now capped by default it looses some usage point (at least for our use case where we specifically want to cap it).
> 
> It isn't capped by Docker anymore, just inherits the default from the system which will typically be `1024:524288`. You can provide a drop-in unit override config like you discovered to raise the hard limit higher when that's necessary. That can be for the particular service like Docker or system-wide (_provided a service doesn't override it that, which was the case previously with Docker_).
 
It's probably a matter of what system default was before Docker changes. At least for me, on RedHat Enterprise Linux, root user had `nofile` set to `Infinity`. And since Docker Engine runs as root by default, from my perspetive `nofile` is now capped.

> > I think at least ulimit parameter documentation needs to be updated everywhere as now it silently allows very large values, but they do not work
> 
> Looks like that shouldn't silently happen anymore and you'd get a failure. Had a quick glance over the docs but doesn't appear to mention any caveats / advice to raise the hard limit beyond the system-wide default.
> 
> Out of curiosity, what were you building that needed more than 524288 file descriptors? Or was the issue with the soft limit being 1024? (_some software that requires a higher limit doesn't request it internally even though it should, so you need to raise it manually if 1024 is not enough for a process_)

I'm building some an ancient database (SQL Anywhere from year 1999) Docker image. I'm not sure how their built their install and other cli utilities, but I found that they enumerate all possible file descriptors in the system every time execute these utilities in a Dockerfile. On my environment that's `Infinity` and takes ~2 minutes to complete. Capping `nofile` during build time in Docker Compose or HCL file solved this. As mentioned this is no longer needed for my use case as it is now capped in Docker Engine itself. Other cases may be still valid though.

Anyway, as you can see from my previous comment, if one needs to actually increase `nofile` past the engine limit that would just silently won't work.
