### ISSUE TITLE
introduce a `--progress` type to collect raw solver responses

### ISSUE THREAD

**Issue by ndeloof** [docker/buildx#2247]
### Description

To avoid vendoring buildx codebase into docker compose, I'd like I can trigger image builds as a `docker buildx` shell-out, but doing so (with multiple images in parallel) I can't let buildkit manage the terminal presentation. An option I have in mind is to get a special `--progress` value to dump solver response events as a newline delimited json stream

**Comment by jedevc** [comment]
It looks like this might be https://github.com/moby/buildkit/pull/4113?

**Comment by ndeloof** [comment]
indeed, sounds related. But also need to get this exposed by the CLI

**Comment by jedevc** [comment]
```
$ docker buildx build . --progress=rawjson
{
  "vertexes": [
    {
      "digest": "sha256:9d93b929c9e23e511e6571db7471435497319b725869382e88527de20161a6ba",
      "name": "[internal] load build definition from Dockerfile"
    }
  ]
}
{
  "vertexes": [
    {
      "digest": "sha256:9d93b929c9e23e511e6571db7471435497319b725869382e88527de20161a6ba",
      "name": "[internal] load build definition from Dockerfile",
      "started": "2024-02-05T18:37:58.113853435Z",
      "completed": "2024-02-05T18:37:58.113906372Z"
    }
  ]
}
...
```

Not newline separated, but `json.Decoder` should handle it I think.

**Comment by ndeloof** [comment]
that's actually a newline delimited json stream, awesome !
