### ISSUE TITLE
[v0.13] allow network.host daemon entitlement by default in container drivers

### ISSUE THREAD

**Issue by tonistiigi** [docker/buildx#2255]
### Description

Based on comments in https://github.com/moby/buildkit/pull/4524#issuecomment-1937917305 , there shouldn't be a need to set `--allowed-entitlemtns network.host` as buildkitd flags when builder runs in a container as the container network is already isolated. At least when `--driver-opt network` does not equal `host`.

**Comment by crazy-max** [comment]
I think it would also makes sense for `kubernetes` driver (cc @AkihiroSuda)

**Comment by crazy-max** [comment]
I was wondering one thing. Should we set this entitlement silently when creating the builder or set it in buildx store? I think silently makes sense.
