### ISSUE TITLE
Install 'buildx', but not a docker command

### ISSUE THREAD

**Issue by lja9702** [docker/buildx#226]
Hello.
I install 'buildx', but docker says `'buildx' is not a docker command.`
This is my installed docker info.
![buildx](https://user-images.githubusercontent.com/23358756/74426702-28d17580-4e99-11ea-846e-25f7fcc22d50.png)

Above info, you can see plugins `buildx: Build with BuildKit (Docker Inc., v0.3.1-tp-docker)`

but, when I command like `docker buildx`, you can look `'buildx' is not a docker command`
![buildx2](https://user-images.githubusercontent.com/23358756/74426223-5538c200-4e98-11ea-8709-887501939512.png)

I write `"experimental": "enabled"` in "~/.docker/config.json" and `{ "experimental": true }` in "/etc/docker/daemon.json", BUT NOT WORK.

Please help me.. Thanks.

**Comment by jameshowison** [comment]
Could one possibility be that path issues are causing you to call a different version of docker for each of these?

**Comment by dannykansas** [comment]
Same issue here. 

@Clement-Jean I believe that `--version` works because of the evaluation order for  of Docker's daemon (e.g. you can run `docker lolwut --version` and it outputs version info as well without errors. Kind of weird.)

**Comment by atreb** [comment]
Ran into same issue with amazon linux 2. I do not think buildx is packaged with the docker from amazon-linux-extras even though the docker --version says `Docker version 19.03.13-ce, build 4484c46` [tested using the below scratch Dockerfile]
```
FROM amazonlinux:2
RUN amazon-linux-extras install docker
RUN rpm -qla docker
RUN docker --version
```

**Comment by atreb** [comment]
Nevermind, I was able to get buildx working as below:
```
FROM amazonlinux:2
RUN amazon-linux-extras install docker
RUN curl --silent -L https://github.com/docker/buildx/releases/download/v0.5.1/buildx-v0.5.1.linux-amd64 -o buildx-v0.5.1.linux-amd64
RUN chmod a+x buildx-v0.5.1.linux-amd64
RUN mkdir -p ~/.docker/cli-plugins
RUN mv buildx-v0.5.1.linux-amd64 ~/.docker/cli-plugins/docker-buildx
RUN docker buildx
```

**Comment by crazy-max** [comment]
Linked to https://github.com/docker/buildx/pull/649. cc @chris-crone

**Comment by gaby** [comment]
Same error with Ubuntu 20.04, Docker installed via deb repos.

**Comment by romainx** [comment]
On my Amazon Linux distribution the `buildx` binary is available under `/usr/libexec/docker/cli-plugins/buildx` with the proper rights. 
I noticed that it does not have the correct name that should be `docker-buildx`.
So I've fixed it by creating a symlink. 

```bash
ln -s /usr/libexec/docker/cli-plugins/buildx /usr/libexec/docker/cli-plugins/docker-buildx
```
After that the plugin seems to be recognised and `docker buildx` is working as expected.

**Comment by crazy-max** [comment]
@romainx

> On my Amazon Linux distribution the `buildx` binary is available under `/usr/libexec/docker/cli-plugins/buildx` with the proper rights.

Is it manually installed there or through a package manager?

**Comment by romainx** [comment]
@crazy-max through the standard package.
```bash
rpm -q --whatprovides /usr/libexec/docker/cli-plugins/buildx
# docker-20.10.7-5.amzn2.x86_64
```

**Comment by samuelkarp** [comment]
Thanks for the ping @thaJeztah!  I've let my colleagues on the Amazon Linux team know about this bug report.  @romainx, you can reach the Amazon Linux team in the future through the [Amazon Linux forum](https://forums.aws.amazon.com/forum.jspa?forumID=228) or through AWS Support.

**Comment by romainx** [comment]
@samuelkarp thanks for the feedback. Good to know, however this time I did not think it was specifically related to Amazon Linux but more generally to `buildx`. Thanks.
