### ISSUE TITLE
Debugging failed builds

### ISSUE THREAD

**Issue by peterwaller-arm** [docker/buildx#227]
I have a build step which takes a long time to run (imagine, e.g. hours). Sometimes it fails.

It would be nice when that happens if the image continued to be around, so I could:

* Go and dig out logs which the build machinery saves into /tmp/...buildfailure...log. (This is unpredictable and unconfigurable, since there are quite a number of things going on in the build.)
* Quickly go in and run commands in the same failing context, without having to repeat ~hours worth of build to get to the point of failure.

I might have expected an option like `--keep-failed`, but I didn't yet find it.

**Comment by tonistiigi** [comment]
https://github.com/moby/buildkit/issues/1472
