### ISSUE TITLE
Is it possible to build an linux/amd64 docker image from a raspberry pi?

### ISSUE THREAD

**Issue by rykerrumsey** [docker/buildx#228]
I am developing on a raspberry pi and need to push linux/amd64 images to my repository. Buildx is giving me...

`failed to solve: rpc error: code = Unknown desc = failed to solve with frontend dockerfile.v0: failed to load LLB: runtime execution on platform linux/amd64 not supported`

**Comment by tonistiigi** [comment]
You can try installing qemu-user for x86 https://github.com/docker/buildx#building-multi-platform-images , then recreate the builder instance and check supported platforms with `buildx inspect` https://packages.debian.org/buster/qemu-user-binfmt
