### ISSUE TITLE
In s390x dockerx env, how could we build on local image or how to create buildx instance with Driver "docker"

### ISSUE THREAD

**Issue by caixiangibm** [docker/buildx#229]
We are working on build docker images on s390x (redhat8 zLinux) with buildx, but found that buildx not work with local image which need to be as base image.

Following list how docker and buildx in build env.
**Install docker ce on s390x (redhat8 zLinux)**
1. Download the static binary archive from https://download.docker.com/linux/static/stable/s390x/docker-18.06.3-ce.tgz (already latest version for s390x)
2. Extract the archive using the tar utility
3. Move the binaries to a directory on your executable path, such as /usr/bin/
4. Start the Docker daemon ($ dockerd &)

**Install dockerx on s390x (redhat8 zLinux)**
1. Download from https://github.com/docker/buildx/releases/download/v0.3.1/buildx-v0.3.1.linux-s390x
2. copy it to /usr/bin folder with name docker-buildx
3. chmod a+x /usr/bin/docker-buildx

```
# docker-buildx inspect
Name:   default
Driver: docker-container

Nodes:
Name:      default
Endpoint:  default
Status:    running
Platforms: linux/s390x
```

In our Dockerfile design, it will build on one local image as base image, but we found that docker-buildx only use base image from remote docker rgistry, it could not detect local docker image. From google search, buildx need to use Driver of "docker" to utilze local image, but I cannot find way to create buildx instance with Driver of "docker"
```
# docker-buildx create --use --name mybuild --platform linux/s390x --driver docker
Error: failed to find driver "docker"
```

As for the s390x dockerx env, how could we build on local image or how to create buildx instance with Driver "docker"?

**Comment by tonistiigi** [comment]
Docker driver requires Docker 19.03+

**Comment by deleisha** [comment]
Looks like this is happening for docker 19.03+ on s390x ubuntu
test@dev61:~/go/src/k8s.io/ingress-nginx$ sudo docker buildx create --use --platform linux/s390x --driver docker
failed to find driver "docker"
test@dev61:~/go/src/k8s.io/ingress-nginx$ sudo docker version
Client:
 Version:           19.03.6
 API version:       1.40
 Go version:        go1.12.17
 Git commit:        369ce74a3c
 Built:             Fri Feb 28 23:44:52 2020
 OS/Arch:           linux/s390x
 Experimental:      true

Server:
 Engine:
  Version:          19.03.6
  API version:      1.40 (minimum version 1.12)
  Go version:       go1.12.17
  Git commit:       369ce74a3c
  Built:            Wed Feb 19 01:06:16 2020
  OS/Arch:          linux/s390x
  Experimental:     true
 containerd:
  Version:          1.3.3-0ubuntu1~18.04.2
  GitCommit:
 runc:
  Version:          spec: 1.0.1-dev
  GitCommit:
 docker-init:
  Version:          0.18.0
  GitCommit:
test@dev61:~/go/src/k8s.io/ingress-nginx$ sudo docker buildx version
github.com/docker/buildx v0.4.1 bda4882a65349ca359216b135896bddc1d92461c

**Comment by Shaked** [comment]
@tonistiigi I'm experiencing the same issue as @deleisha 

```
docker version                                                                                                                    1 ↵  458  18:35:55
Client: Docker Engine - Community
 Version:           19.03.12
 API version:       1.40
 Go version:        go1.13.10
 Git commit:        48a66213fe
 Built:             Mon Jun 22 15:45:36 2020
 OS/Arch:           linux/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          19.03.12
  API version:      1.40 (minimum version 1.12)
  Go version:       go1.13.10
  Git commit:       48a66213fe
  Built:            Mon Jun 22 15:44:07 2020
  OS/Arch:          linux/amd64
  Experimental:     true
 containerd:
  Version:          1.2.13
  GitCommit:        7ad184331fa3e55e52b890ea95e65ba581ae3429
 runc:
  Version:          1.0.0-rc10
  GitCommit:        dc9208a3303feef5b3839f4323d9beb36df0a9dd
 docker-init:
  Version:          0.18.0
  GitCommit:        fec3683
```

**Comment by tonistiigi** [comment]
Docker driver instance comes with docker daemon. You can't make new instances of it as you already only have one docker daemon running. If you are running Docker 19.03 you can already see it in `docker buildx ls` without running `create`
