### ISSUE TITLE
While doing the docker build i am facing error saying DEPRECATED: The legacy builder is deprecated and will be removed in a future release. Install the buildx component to build images with BuildKit:

### ISSUE THREAD

**Issue by Satyadevoperations** [docker/buildx#2297]
### Contributing guidelines

- [X] I've read the [contributing guidelines](https://github.com/docker/buildx/blob/master/.github/CONTRIBUTING.md) and wholeheartedly agree

### I've found a bug and checked that ...

- [X] ... the documentation does not mention anything about my problem
- [X] ... there are no open or closed issues that are related to my problem

### Description

Hello Team,

While performing the build operation. I am facing error saying as

DEPRECATED: The legacy builder is deprecated and will be removed in a future release.
            Install the buildx component to build images with BuildKit:
Thanks
Sidharth

### Expected behaviour

Actually the build should run successfully but no luck it failed with the below error message.

DEPRECATED: The legacy builder is deprecated and will be removed in a future release.
            Install the buildx component to build images with BuildKit:

### Actual behaviour

Hello While performing the build operation for my Java code i have encountered an issue saying as mentioned below.

docker: 'buildx' is not a docker command.
See 'docker --help'

### Buildx version

docker: 'buildx' is not a docker command. See 'docker --help'

### Docker info

```text
ubuntu@ip-172-31-31-167:~/projects/buildx$ docker info
Client:
 Version:    24.0.5
 Context:    default
 Debug Mode: false

Server:
 Containers: 3
  Running: 0
  Paused: 0
  Stopped: 3
 Images: 6
 Server Version: 24.0.5
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Using metacopy: false
  Native Overlay Diff: true
  userxattr: false
 Logging Driver: json-file
 Cgroup Driver: systemd
 Cgroup Version: 2
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: io.containerd.runc.v2 runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 
 runc version: 
 init version: 
 Security Options:
  apparmor
  seccomp
   Profile: builtin
  cgroupns
 Kernel Version: 6.2.0-1012-aws
 Operating System: Ubuntu 22.04.3 LTS
 OSType: linux
 Architecture: x86_64
 CPUs: 1
 Total Memory: 949.7MiB
 Name: ip-172-31-31-167
 ID: f5eb916b-0ff9-40ba-b2a5-cd8a936ee43a
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false
```

### Builders list

```text
docker: 'buildx' is not a docker command.
See 'docker --help'
```

### Configuration

ubuntu@ip-172-31-31-167:~/projects/java-app$ cat Dockerfile
#Get a Base image with Jdk installed
FROM openjdk:8-jdk-alpine

#Create a working directory to compile, run java apps
WORKDIR /app

#copy code from local machine to docker container
COPY Hello.java .

# Compile the code
RUN javac Hello.java

# Run the java app
CMD["java","Hello"]

**Comment by crazy-max** [comment]
Doesn't seem you have the `buildx` cli plugin installed. Did you follow our docs to install Docker? https://docs.docker.com/engine/install/

**Comment by vedannt511** [comment]
I am also facing the same issue , i have installed docker but haven't installed docker desktop as i working on aws EC2 instance have you got the solution for it??

**Comment by crazy-max** [comment]
> i have installed docker

Same as https://github.com/docker/buildx/issues/2297#issuecomment-1971214610, did you follow the instructions to install Docker from https://docs.docker.com/engine/install/?

I'm closing this issue in the meantime but feel free to left a comment if you still have an issue.

**Comment by Batohack** [comment]
<img width="1987" height="590" alt="Image" src="https://github.com/user-attachments/assets/971adf74-26a7-424d-b9a5-0c18e0b321e5" />
moi je suis confronté à ce problème

**Comment by bschaatsbergen** [comment]
I ran into this as well. I’m using Colima with Docker and already had docker-buildx installed, but I was still seeing the issue.

It turned out that buildx also needed to be linked as a Docker CLI plugin, for those using Homebrew:
```
brew install docker-buildx

mkdir -p ~/.docker/cli-plugins 
ln -sfn $(brew --prefix docker-buildx)/bin/docker-buildx ~/.docker/cli-plugins/docker-buildx
```

**Comment by carsonsaldanha** [comment]
I also experienced this same issue using Homebrew. @bschaatsbergen's comment above works, but the recommended approach is to link via your Docker config file because this aligns with how Docker intends for third-party package managers to distribute CLI plugins.

The Hombrew formula for docker-buildx also mentions this step: https://formulae.brew.sh/formula/docker-buildx

Add the below to `~/.docker/config.json`:

```
"cliPluginsExtraDirs": [
  "$HOMEBREW_PREFIX/lib/docker/cli-plugins"
]
```

Replace `$HOMEBREW_PREFIX` with the output of `echo $HOMEBREW_PREFIX`, typically `/opt/homebrew` on Apple Silicon Macs.

**Source:** https://darren.oh.name/node/82
