### ISSUE TITLE
add "env" driver that connects to $BUILDKIT_HOST

### ISSUE THREAD

**Issue by AkihiroSuda** [docker/buildx#23]
This driver allows creating a buildx instance directly pointing to the existing buildkit endpoint.

`docker buildx create --driver=env unix:///var/lib/buildkitd.sock`
`docker buildx create --driver=env` uses `BUILDKIT_HOST` env value with UNIX sock default.

I guess TLS info is just passed with a custom driver-opt:

```
docker buildx create --driver=env --driver-opt ca=mycafile.pem https://foobar
```

`rm/stop` commands are no-op in this driver.

A better name could be "remote".

**Comment by tonistiigi** [comment]
It's possible this could be combined with #21 as #21 doesn't really have an endpoint.

**Comment by tonistiigi** [comment]
Otoh, combining may add complexity as #21 is linux only and requires credentials while this could work from anywhere. It would be easier to do this split by using different drivers.

**Comment by pchico83** [comment]
+1 This would be awesome!

**Comment by Shaked** [comment]
Any updates regarding this issue? Is it there another way  to run buildx with a remote buildkitd?

**Comment by developer-guy** [comment]
Hello folks, kindly ping 🙋🏻‍♂️✌️ Are there any updates? We (w/@dentrax) thought that, if it happens, we can be able to use the buildkitd running in lima-vm for this. So, we are so excited about this.

**Comment by tonistiigi** [comment]
Nobody is working on it afaik. It should quite easy to add it If somebody wants to take it on. Most of the work would probably be to make sure that CI would test this driver.

**Comment by remidebette** [comment]
@jedevc thanks for the feature, what do you think about: https://github.com/docker/for-mac/issues/6149 ?

**Comment by remidebette** [comment]
Hi @tonistiigi @jedevc ,
I wanted to work with this, but it seems there is no release containing #1078 ?

Same for https://hub.docker.com/r/docker/buildx-bin/tags

**Comment by jedevc** [comment]
The [buildx-bin](https://hub.docker.com/r/docker/buildx-bin/tags) image has the `:master` tag which tracks the state of the `master` branch here on git - that should allow you to use the feature.

You're right, the remote driver is still not in a release of buildkit yet, but it will be in the next release of buildkit with v0.9. We've got a milestone of issues/prs that are targeted towards that release as well: https://github.com/docker/buildx/milestones/v0.9.0 - it's in progress.
