### ISSUE TITLE
Bake: using secrets?

### ISSUE THREAD

**Issue by bendavies** [docker/buildx#230]
Hey there,

Is there a way to use secrets with `bake`?
I'm looking at this: https://github.com/docker/buildx/blob/891d3556797cc33a63f76529824a99cc03dcf826/bake/bake.go#L164
but I can't really work out how that is used or what file it is parsing.

Many thanks.

**Comment by bendavies** [comment]
It's always the way. worked it out just after posting this.
```sh
docker buildx bake --progress plain -f docker-compose.yaml --set target.secrets=id=....
```

Can they be specified in a yaml/hcl file, rather than using `--set?`

**Comment by kuloed** [comment]
I've tried this, and worked. You can also set secret in hcl file
```
target "php" {
    secret = ["id=auth.json,src=auth.json"]
}
```
