### ISSUE TITLE
Avoid interpolation of variables in dockerfile-inline

### ISSUE THREAD

**Issue by dmarkhas** [docker/buildx#2305]
### Contributing guidelines

- [X] I've read the [contributing guidelines](https://github.com/docker/buildx/blob/master/.github/CONTRIBUTING.md) and wholeheartedly agree

### I've found a bug and checked that ...

- [X] ... the documentation does not mention anything about my problem
- [X] ... there are no open or closed issues that are related to my problem

### Description

I am trying to use `buildx bake` for multi-platform builds, however I'm unable to properly leverage the --platform flag inside the Dockerfile, since it is being interpolated as a variable by bake.

First, I tried to use the following syntax:

```
 dockerfile-inline: |
            FROM --platform=${TARGETPLATFORM:-linux/amd64} base
            CMD ./server serve
```

However, that failed since bake attempted to interpolate the variable and failed since it did not find a matching closing bracket.

Then, I tried:

```
 dockerfile-inline: |
            FROM --platform=${TARGETPLATFORM} base
            CMD ./server serve
```

Which also failed, as it expected me to declare TARGETPLATFORM as a variable in the bake configuration file.
However, after adding it - with a default value of "linux/amd64"-  bake seems to build only that flavor, and ignores the `platforms` that I am passing to it explicitly.

It should be noted that if I don't use dockerfile-inline, but instead take its contents and place them into a separate Dockerfile, everything works as expected.

Am I missing something or is this the expected behavior?

### Expected behaviour

Bake should not interpolate the TARGETPLATFORM variable

### Actual behaviour

Bake is interpolating the variable and either failing or setting the default value

### Buildx version

github.com/docker/buildx v0.12.1-desktop.4 6996841df2f61988c2794d84d33205368f96c317

### Builders list

```text
NAME/NODE       DRIVER/ENDPOINT STATUS  BUILDKIT PLATFORMS
default *       docker
  default       default         running v0.12.5  linux/amd64, linux/amd64/v2, linux/amd64/v3, linux/arm64, linux/riscv64, linux/ppc64le, linux/s390x, linux/mips64le, linux/mips64
desktop-linux   docker
  desktop-linux desktop-linux   running v0.12.5  linux/amd64, linux/amd64/v2, linux/amd64/v3, linux/arm64, linux/riscv64, linux/ppc64le, linux/s390x, linux/mips64le, linux/mips64
```

### Configuration

```{
  "group": {
    "build-group": {
      "targets": [
        "default"
      ]
    }
  },
  "target": {
    "base": {
      "dockerfile": "Dockerfile",
      "platforms": [
        "linux/amd64",
        "linux/arm64"
      ]
    },
    "default": {
      "dockerfile-inline": "FROM --platform=${TARGETPLATFORM:-linux/amd64}\nbase\nCMD ./server serve",
      "tags": [
        "v0.0.0"
      ],
      "platforms": [
        "linux/amd64",
        "linux/arm64"
      ],
      "contexts": {
        "base": "target:base"
      }
    }
  }
}
```

**Comment by tonistiigi** [comment]
Looks like `$$` seems to work for compose file (cc @ndeloof to correct if wrong). That is also the syntax for HCL.

**Comment by ndeloof** [comment]
`dockerfile-inline` in a compose file was introduced with the explicit limitation it should only be used for simplest Dockerfiles, as interpolation would have impact on content. As any other place in compose file, `$$` can be used to bypass interpolation

**Comment by dmarkhas** [comment]
Thanks, seems like $$ does work 👍🏾
