### ISSUE TITLE
Name resolution in custom network doesn't work during build

### ISSUE THREAD

**Issue by juansebastianl** [docker/buildx#2306]
### Contributing guidelines

- [X] I've read the [contributing guidelines](https://github.com/docker/buildx/blob/master/.github/CONTRIBUTING.md) and wholeheartedly agree

### I've found a bug and checked that ...

- [X] ... the documentation does not mention anything about my problem
- [X] ... there are no open or closed issues that are related to my problem

### Description

I've got a builder with a custom network with other docker containers attached, during build I have a `RUN curl http://my-other-container` and I get a `Not Found` error. The curl works after the container is built and run, as well as in the builder container, but not during the build. 

### Expected behaviour

I start with a custom network `my-network` which has `my-other-container` attached to it. 

I create a custom builder

```
docker buildx create --use \
        --name custom_network_builder \
        --driver docker-container \
        --driver-opt "network=my-network"
```

and then build my Dockerfile 

```
docker build --builder=custom_network_builder --load -f ./Dockerfile
```

where my dockerfile is 

```
FROM ubuntu:focal
RUN curl http://my-other-container
```

then my docker container should build successfully.

### Actual behaviour

I get a `Could not resolve: my-other-container` error from `curl` and the build fails. I have done `docker excec -it buildx_build_container bash` and tried the curl and it works as expected. I have also done the curl from the docker container once it is built (after taking the RUN step out) and it works fine as well. 

### Buildx version

github.com/docker/buildx v0.11.2 9872040

### Builders list

```text
NAME/NODE DRIVER/ENDPOINT STATUS  BUILDKIT             PLATFORMS
default * docker
  default default         running v0.11.7+d3e6c1360f6e linux/amd64, linux/amd64/v2, linux/amd64/v3, linux/386
```

### Configuration

```
FROM ubuntu:focal
RUN curl http://my-other-container
```
```
docker build --builder=custom_network_builder --load -f ./Dockerfile
```

**Comment by tonistiigi** [comment]
I believe this has been fixed in buildkit v0.13.0 but you need to use `--network=host` (that effectively means network of your builder container) so that the `RUN` commands don't use their own (potentially) isolated network.

https://github.com/moby/buildkit/pull/4524
