### ISSUE TITLE
[question] How to limit platform support?

### ISSUE THREAD

**Issue by iav** [docker/buildx#231]
I want to use one of x86_64 host with enabled qemu in some multibuilder as x64-only.
I have 
```
multibuilder *  docker-container
  multibuilder1 aws-arm                     running linux/arm64, linux/arm/v7, linux/arm/v6
  multibuilder0 unix:///var/run/docker.sock running linux/amd64, linux/amd64, linux/arm64, linux/riscv64, linux/ppc64le, linux/s390x, linux/386, linux/arm/v7, linux/arm/v6
```
I try to do `docker buildx create --name multibuilder --platform linux/amd64 --node multibuilder0`

`docker buildx create --name multibuilder --platform linux/amd64 --node multibuilder0 --append`

nothing changed, and run arm builds on this host instead of a special arm builder.

**Comment by tonistiigi** [comment]
If you want to force arm builds to run on `aws-arm` you need to set `--platform linux/arm64` manually when creating that node/builder. Manual platforms take precedence over the detected ones.

**Comment by iav** [comment]
I add worker with --platform. 
Sometime it adds with all platforms. Sometime it adds with platform I note, but again shows all available platforms after start `docker build buildx ...`

**Comment by tonistiigi** [comment]
Yes, output shows both manual and automatically detected platforms. But again, when making choices about what node to prefer, nodes with manual platform are used before.

**Comment by iav** [comment]
Then how can I check what platforms will be used, and separate it from detected platforms?

**Comment by tonistiigi** [comment]
They are not separated in the inspect output.

**Comment by iav** [comment]
Thank you.
