### ISSUE TITLE
Building buildx v0.3.1 fails on Go 1.13

### ISSUE THREAD

**Issue by thaJeztah** [docker/buildx#232]
Noticed in the "nightly" build pipeline after https://github.com/docker/docker-ce-packaging/pull/436 and https://github.com/docker/cli/pull/2360 were merged;

```
github.com/docker/buildx/version.Package=github.com/docker/buildx -X main.experimental=1' ./cmd/buildx
go: github.com/containerd/containerd@v1.3.0-0.20190507210959-7c1e88399ec0: invalid pseudo-version: version before v1.3.0 would have negative patch number
```

@tiborvass @tonistiigi @glours

**Comment by tonistiigi** [comment]
Buildx currently requires go1.12 and has not been updated to go1.13/14

**Comment by thaJeztah** [comment]
@tonistiigi would it only be related to updating `go.mod`, or do you anticipate other changes being required?

**Comment by tonistiigi** [comment]
Similar to https://github.com/moby/buildkit/pull/1376

**Comment by tonistiigi** [comment]
https://github.com/docker/buildx/pull/233
