### ISSUE TITLE
ERROR: failed to find instance "instance-name" for append

### ISSUE THREAD

**Issue by kmohan778** [docker/buildx#2346]
### Contributing guidelines

- [X] I've read the [contributing guidelines](https://github.com/docker/buildx/blob/master/.github/CONTRIBUTING.md) and wholeheartedly agree

### I've found a bug and checked that ...

- [ ] ... the documentation does not mention anything about my problem
- [ ] ... there are no open or closed issues that are related to my problem

### Description

Facing issues while using the below command after the buildx upgrade.

Command: docker buildx create --use --append --name test-builder --platform linux/amd64,linux/arm64,linux/arm/v7 default

Previously we havent had any issues with this command and it was executing without any issues in our Azure pipeline. Pasting the output in Azure pipeline.

Pipeline output:
>> docker buildx create --use --append --name test-builder --platform linux/amd64,linux/arm64,linux/arm/v7 default
WARNING: failed to find "test-builder" for append, creating a new instance instead
test-builder

>> docker buildx inspect --bootstrap
#1 [internal] booting buildkit
#1 pulling image moby/buildkit:buildx-stable-1
#1 pulling image moby/buildkit:buildx-stable-1 0.7s done
#1 creating container buildx_buildkit_test-builder0
#1 creating container buildx_buildkit_test-builder0 5.0s done
#1 DONE 5.8s
Name:          test-builder
Driver:        docker-container
Last Activity: 2024-03-11 23:12:18 +0000 UTC

Nodes:
Name:      test-builder0
Endpoint:  unix:///var/run/docker.sock
Status:    running
Buildkit:  v0.12.5
Platforms: linux/amd64*, linux/arm64*, linux/arm/v7*, linux/amd64/v2, linux/amd64/v3, linux/riscv64, linux/ppc64, linux/ppc64le, linux/s390x, linux/386, linux/mips64le, linux/mips64, linux/arm/v6
Labels:

But we started to face issues since after March 13 2024 with below details.

Pipeline Output:
>> docker buildx create --use --append --name test-builder --driver docker-container --platform linux/amd64,linux/arm64,linux/arm/v7
ERROR: failed to find instance "test-builder" for append

>> docker buildx inspect --bootstrap
Name:   default
Driver: docker

Nodes:
Name:             default
Endpoint:         default
Status:           running
BuildKit version: v0.11.7+435cb77e369c
Platforms:        linux/amd64, linux/amd64/v2, linux/amd64/v3, linux/amd64/v4, linux/386, linux/arm64, linux/riscv64, linux/ppc64, linux/ppc64le, linux/s390x, linux/mips64le, linux/mips64, linux/arm/v7, linux/arm/v6
Labels:

### Expected behaviour

WARNING: failed to find "test-builder" for append, creating a new instance instead

### Actual behaviour

WARNING: failed to find "test-builder" for append, creating a new instance instead

### Buildx version

N/A

### Builders list

```text
N/A
```

### Configuration

N/A

**Comment by tonistiigi** [comment]
dupe https://github.com/docker/buildx/issues/2347
