### ISSUE TITLE
Intermittent `failed commit on ref`

### ISSUE THREAD

**Issue by EduardSergeev** [docker/buildx#235]
We are using `buildx` to build multi-arch images and it was working fine for us until we've decided to upgrade the base image we are using (it is .NET Core app and we trying to upgrade from 3.0 to 3.1). Once we've upgraded the base image our build started to fail *intermittently* (we have several apps and every build one of the app fails with a similar but different error):
```
#9 [linux/arm64 3/3] COPY bin/Release/netcoreapp3.1/publish/ .
#9 DONE 0.2s

#13 exporting to image
#13 exporting layers
#13 exporting layers 2.2s done
#13 exporting manifest sha256:35aebe8a07f8cb8f3fce06b8fb83d2c3d87b1e7e2d9ffa2a9950eb871a38f3d6 0.0s done
#13 exporting config sha256:5353fb9c6116c9a93fe710fc81f0b0b901177f928eba13bf1e50b02f01725e1f 0.0s done
#13 exporting manifest sha256:27ba7bca72a72cc5f625196c4f80e39bfa65c8967e65b0cd2086f06d3d81133e 0.0s done
#13 exporting config sha256:11757b857faebad435048acfc8f155289688f63983ef8d2514ec531348dcfd1d 0.0s done
#13 exporting manifest list sha256:bd2c1f02707b6156caaf008337e70ac41a9ea109303feed445c488a7387e5682 0.0s done
#13 pushing layers
#13 pushing layers 1.7s done
#13 ERROR: failed commit on ref "layer-sha256:0a73308879211d22735c99aefffd97d8c3c9cdc02912853671ab73d6ddeaa96c": unxpected size 18845227, expected 19893803
```
this (sic!) `unxpected size 18845227, expected 19893803` is different for every build (even if the same project fails)
We are using locally deployed `registry:2` to store the images
```
/# docker --version
Docker version 19.03.4, build 9013bf583a
```
```
/# docker buildx version
github.com/docker/buildx v0.3.1-tp-docker 6db68d029599c6710a32aa7adcba8e5a344795a7
```

The builds based on older 3.0 version of base images run without error

**Comment by tonistiigi** [comment]
https://github.com/containerd/containerd/issues/2706 cc @dmcgowan

**Comment by tonistiigi** [comment]
Not 100% sure it is the same issue as sizes are different. If you have a repro we can double-check.

**Comment by EduardSergeev** [comment]
> Not 100% sure it is the same issue as sizes are different

It is definitely related: I just run a build and it failed with this:
```
failed to solve: rpc error: code = Unknown desc = failed commit on ref "layer-sha256:de83a2304fa1f7c4a13708a0d15b9704f5945c2be5cbb2b3ed9b2ccb718d0b3d": unxpected size 70730, expected 35365
```
We don't do anything docker-related in parallel but apparently
> Also possible to hit it by just pushing multiple images that share some layers to the same repo

which is probably exactly our case since we have multiple projects which share the same two base images.
Strange that it never happened with .NET 3.0 but always happens with .NET 3.1 - different structure of the base images?
Is there any work around for this issue?

**Comment by tonistiigi** [comment]
> docker-related in parallel but apparently

When you build multi-arch, separate architectures are built/pushed in-parallel.

**Comment by EduardSergeev** [comment]
> When you build multi-arch, separate architectures are built/pushed in parallel.

OK, make sense. But why it never happened with 3.0?
 - `mcr.microsoft.com/dotnet/core/runtime:3.0` - always works
 - `mcr.microsoft.com/dotnet/core/runtime:3.1` - fails intermittently (but reliably)
This base container is the only difference from our point of view. Both versions build multi-arch images.

**Comment by tonistiigi** [comment]
Somehow the new images causes identical layers to be created and the old one didn't. These may be the layers you create with the base image or ones in the base image. Not sure what platforms you are building.

**Comment by EduardSergeev** [comment]
OK, we have figured this one out.
The difference was due to our mistake: we are using intermediate "base" image (built from `mcr.microsoft.com/dotnet/core/runtime`) and that image was not made multi-arch for 3.1. As a result subsequent `docker buildx build` was building multi-arch image from single-arch which apparently caused the above error (layers were duplicated because both platforms were effectively the same image?).
Closing it since it isn't buildx issue

**Comment by jonstelly** [comment]
> > docker-related in parallel but apparently
> 
> When you build multi-arch, separate architectures are built/pushed in parallel.

@tonistiigi do you know if this issue is being tracked or worked on anywhere else?

I'm getting these errors frequently during my CI builds for arm64 and amd64 and pushing to a private registry.  I've got my builds set up to retry 2 times on this error but my builds still fail (all 3 attempts) about 1/4 of the time.

Any suggestions for a workaround?  I'm currently considering building and pushing each platform separately to platform-specific tags (none of my builds are very complex or time consuming, so not parallelizing them shouldn't be too bad), then using a `docker manifest create ...` and `docker manifest push ...` to create the common tag.

FWIW, the command I'm running is:
`docker buildx build . --platform=linux/arm64,linux/amd64 -t my.hub/my-app:0.1.0 --pull --push --no-cache`

and the error I'm getting is:
```
#12 pushing layers
#12 pushing layers 7.2s done
#12 ERROR: failed commit on ref "layer-sha256:629a5dd1f6de2cb28d8b5b6da6ba831bc34a5e3d8c169a6c1483d6380ef0e692": unexpected size 136543610, expected 137592186
```

**Comment by tonistiigi** [comment]
containerd/containerd#2706 is the tracking issue. you can also use `buildx imagetools create`

**Comment by mdfard** [comment]
> We are using `buildx` to build multi-arch images and it was working fine for us until we've decided to upgrade the base image we are using (it is .NET Core app and we trying to upgrade from 3.0 to 3.1). Once we've upgraded the base image our build started to fail _intermittently_ (we have several apps and every build one of the app fails with a similar but different error):
> 
> ```
> #9 [linux/arm64 3/3] COPY bin/Release/netcoreapp3.1/publish/ .
> #9 DONE 0.2s
> 
> #13 exporting to image
> #13 exporting layers
> #13 exporting layers 2.2s done
> #13 exporting manifest sha256:35aebe8a07f8cb8f3fce06b8fb83d2c3d87b1e7e2d9ffa2a9950eb871a38f3d6 0.0s done
> #13 exporting config sha256:5353fb9c6116c9a93fe710fc81f0b0b901177f928eba13bf1e50b02f01725e1f 0.0s done
> #13 exporting manifest sha256:27ba7bca72a72cc5f625196c4f80e39bfa65c8967e65b0cd2086f06d3d81133e 0.0s done
> #13 exporting config sha256:11757b857faebad435048acfc8f155289688f63983ef8d2514ec531348dcfd1d 0.0s done
> #13 exporting manifest list sha256:bd2c1f02707b6156caaf008337e70ac41a9ea109303feed445c488a7387e5682 0.0s done
> #13 pushing layers
> #13 pushing layers 1.7s done
> #13 ERROR: failed commit on ref "layer-sha256:0a73308879211d22735c99aefffd97d8c3c9cdc02912853671ab73d6ddeaa96c": unxpected size 18845227, expected 19893803
> ```
> 
> this (sic!) `unxpected size 18845227, expected 19893803` is different for every build (even if the same project fails)
> We are using locally deployed `registry:2` to store the images
> 
> ```
> /# docker --version
> Docker version 19.03.4, build 9013bf583a
> ```
> 
> ```
> /# docker buildx version
> github.com/docker/buildx v0.3.1-tp-docker 6db68d029599c6710a32aa7adcba8e5a344795a7
> ```
> 
> The builds based on older 3.0 version of base images run without error

hi sir 
I have the same error in docker building(failed commit on ref "layer-sha256)
so how did you solve this error ? could you help me ?
