### ISSUE TITLE
Auth support for remote bake definitions

### ISSUE THREAD

**Issue by crazy-max** [docker/buildx#2360]
related to https://github.com/docker/actions-toolkit/pull/288

We don't support building a remote bake definition from a private repository using a git auth token. Only SSH auth with default agent is currently supported for this case: https://github.com/docker/buildx/blob/8abef5908705e49f7ba88ef8c957e1127b597a2a/bake/remote.go#L30-L33

Loading a remote bake definition is done by a dedicated solve request before build occurs: https://github.com/docker/buildx/blob/8abef5908705e49f7ba88ef8c957e1127b597a2a/bake/remote.go#L62

So we would need to pass the secret in a proper manner through `bake` command and attach it to the session.

@tonistiigi suggests that we could have a builtin name as override that would look like this:

```
docker buildx bake \
  --set "<builtin_name>.secrets=id=GIT_AUTH_TOKEN,env=GIT_AUTH_TOKEN"
  https://github.com/docker/test-docker-action.git#remote-private
```

Where `<builtin_name>` would be unique and could not be used as target name in the bake definition. As we already restrict target name with specific chars: https://github.com/docker/buildx/blob/8abef5908705e49f7ba88ef8c957e1127b597a2a/bake/bake.go#L35

We could use one not part of it to avoid collision such as `bake@remote`:

```
docker buildx bake \
  --set "bake@remote.secrets=id=GIT_AUTH_TOKEN,env=GIT_AUTH_TOKEN"
  https://github.com/docker/test-docker-action.git#remote-private
```

Open to suggestions.

**Comment by dvdksn** [comment]
could environment variable be an option? `DOCKER_BAKE_GIT_TOKEN=foo docker buildx bake`
