### ISSUE TITLE
Stdin builds hang if `BUILDX_EXPERIMENTAL=1` is set

### ISSUE THREAD

**Issue by tonistiigi** [docker/buildx#2368]
### Description

```
BUILDX_EXPERIMENTAL=1 docker buildx build - <<eot                                                                    !1518
from alpine
eot
```

Hangs after

```
 => [internal] connecting to local controller
```

output.

Without the experimental opt-in all seems to work.

Probably related to the controller switch or the debugging features opt-in (cc @ktock @jedevc )

@crazy-max We should probably add `BUILDX_EXPERIMENTAL` also to the CI test matrix.

### Buildx version

v0.13 (likely v0.12 as well)

**Comment by crazy-max** [comment]
I was looking at this issue and it hangs at https://github.com/docker/buildx/blob/5c29e6e26eab79b47220af609ab36be4beb327fe/build/opt.go#L384 where no data are being produced so it blocks indefinitely. I wonder if this is linked to https://github.com/docker/buildx/blob/5c29e6e26eab79b47220af609ab36be4beb327fe/commands/build.go#L421-L428 where one end of the pipe is waiting for the other end to consume or produce data.
