### ISSUE TITLE
Error printed during "CPU Architecture" detection

### ISSUE THREAD

**Issue by robbieknuth** [docker/buildx#238]
Background:
Looking to build images on my amd64 system for my aarch64 raspberry pi systems.

Info:
OS: Kubuntu 19.10
Docker version 19.03.2, build 6a30dfca03
Installed buildx by downloading linux-amd64 release and plopping at ~/.docker/cli-plugins/buildx.
Set "experimental": "enabled" in ~/.docker/config.json

Example repro command: 
`~$ docker buildx ls`

> ERRO[0000] failure getting variant                       error="getCPUInfo for pattern: Cpu architecture: not found"
NAME/NODE DRIVER/ENDPOINT STATUS  PLATFORMS
default * docker                  
  default default         running linux/amd64, linux/386

In a preliminary check, it looks like buildx is looking for a label "Cpu architecture" in /proc/cpuinfo? This label does not in /proc/cpuinfo on my system, which is effectively stock.
`cat /proc/cpuinfo | grep -i "architecture" | wc -l` => `0`

It seems as this is only a cosmetic error, commands seem to execute just fine. Seeing as how it later detects "linux/amd64", somewhere else it is clearly able to get amd64.

**Comment by tonistiigi** [comment]
This error comes from https://github.com/containerd/containerd/blob/master/platforms/cpuinfo.go#L93 . Can you open an issue in containerd with your system information and possibly suggestions how this should be improved there.

**Comment by robbieknuth** [comment]
Code navigation works too well. Wound up in a different repo without realizing it. Closing.
