### ISSUE TITLE
Support `RUN --gpus ...` or equivalent.

### ISSUE THREAD

**Issue by gabrieldemarmiesse** [docker/buildx#239]
Hi and thanks for this awesome tool!

We make heavy use of buildkit (soon buildx) in [Tensorflow Addons](https://github.com/tensorflow/addons) to run our tests. It's awesome to be able to run all those tests in parralel in isolated environements, even on remote servers. With the docker cache it's awesome, no need to pull the dependencies again... etc.

Something that we're stuck with though is that we can't run our gpu tests in a dockerfile (like we do for all the other tests).

Would it be possible to support gpus for an entire stage? Or even better for a single `RUN` instruction?

Thanks a lot!

**Comment by tonistiigi** [comment]
cc @tiborvass , I think you had some early plans for this in buildkit when https://github.com/docker/cli/pull/1714 was added.

Support for this needs to happen in BuildKit first so probably better to track it there. Meanwhile, we did add `RUN --security=insecure` that I think can be used to access GPUs if you are willing to run some setup code that creates the devices inside your build.

**Comment by gabrieldemarmiesse** [comment]
I'm not at all familiar with the internals of buildkit or even how to create devices. So I won't be able to help you there, sorry about that. I just wanted to open the issue to show that there was an interest and so that other people who have the same need have a place to look at the status of this feature.

**Comment by tonistiigi** [comment]
Closing. Reopen in BuildKit for tracking.
