### ISSUE TITLE
Buildx gets stuck cross-compiling for ARM because of QEMU `getdents64`

### ISSUE THREAD

**Issue by Silex** [docker/buildx#241]
Just creating this issue so others can be aware of it, possibly contributing solutions. 

https://bugs.launchpad.net/qemu/+bug/1861161
https://bugs.launchpad.net/qemu/+bug/1805913
https://sourceware.org/bugzilla/show_bug.cgi?id=23960
https://bugzilla.kernel.org/show_bug.cgi?id=205957

**Comment by tonistiigi** [comment]
If there are patches for this please add them to https://github.com/moby/qemu

**Comment by Silex** [comment]
Thanks, continuing in https://github.com/moby/qemu/issues/9
