### ISSUE TITLE
Funcionou perfeitamente para quem tá usando WSL

### ISSUE THREAD

**Issue by ClaudioMarzo** [docker/buildx#2466]
```
failed to fetch metadata: fork/exec /usr/local/lib/docker/cli-plugins/docker-buildx: no such file or directory

DEPRECATED: The legacy builder is deprecated and will be removed in a future release.
            Install the buildx component to build images with BuildKit:
            https://docs.docker.com/go/buildx/
```

In fact `/usr/local/lib/docker/` contained only invalid symlinks.
So, running this command fixed it: `sudo rm -fr /usr/local/lib/docker/`

_Originally posted by @nmoreaud in https://github.com/docker/buildx/issues/262#issuecomment-1744354626_

**Comment by tonistiigi** [comment]
Not sure what is actionable here
