### ISSUE TITLE
How to specify builder instance driver in a HCL file

### ISSUE THREAD

**Issue by xUnholy** [docker/buildx#247]
Given the below example, how can I specify in my HCL file which builder instance driver I wish to use for the `docker buildx bake` command. Ideally, I don't want to preconfigure using the CLI and specify the instance to use here because I'll be building many images on the same host potentially and don't want to need to switch frequently.

```
{
   "target": {
      "example": {
         "context": "$.",
         "dockerfile": "Dockerfile",
         "args": {
            "BASE_VERSION": "${BASE_VERSION}",
         },
         "tags": [
            "${tag}"
         ],
         "platforms": [
            "linux/arm/v6",
            "linux/arm/v7"
         ]
      }
   }
}
```

**Comment by xUnholy** [comment]
Based on the source code I don't think it's currently possible https://github.com/docker/buildx/blob/52b0ea328fee203354fb6fadf3bf5ac8fc22060f/bake/bake.go#L246

Happy to be shown what might be the best way to approach this.

**Comment by tonistiigi** [comment]
Yes, you can't define builder instance in HCl files. These files are meant to work independently from the current builder instance/configuration.

**Comment by xUnholy** [comment]
@tonistiigi thanks for confirming.

This would definitely be a nice feature for people who use multiple builder instances and what to be able to define which one is used to build the image rather than script the builder instance to be used prior - makes sense that the definition also would include the builder required to build it.

**Comment by tonistiigi** [comment]
hcl file is something you commit to git with your project. If I pull your project I don't have the same builders/infra configuration that you had. There might be some useful features that would allow to detect active builder/context based on current project director/filesystemy instead of requiring to use `use`. But if your use case is to build one target with one builder and another with another builder with a single command then I think that seems very rare and we shouldn't optimize for it. Easier to just run 2 commands.

**Comment by xUnholy** [comment]
True, although my assumption is that a HCl file can be used to build on any machine and should result in the same artefact. At this point if I were to use a HCl file from an open source tool it would build that image depending on the builder instance I've setup which I guess is fine. It can be misleading initially cause it uses the default instance and people who may be unfamiliar with creating the instance with the right platform architectures might not get it right the first time. Thanks for the clarification! I might just setup a script to setup the builder instance and bootstrap the HCl file build command.

**Comment by errordeveloper** [comment]
@xUnholy maybe you could explain your use-case more specifically? It sounds like you want to have a new builder auto-configured or something like that for novice users?
I think the scope of bake config files is pretty clear, it's meant to be usable in different environment, specifying builder name would spoil that.

**Comment by xUnholy** [comment]
Forgot I still had this issue open, happy to close it now, thanks for all the responses.

**Comment by errordeveloper** [comment]
How did you solve it?
