### ISSUE TITLE
build --output=type=none

### ISSUE THREAD

**Issue by nicks** [docker/buildx#2483]
### Description

**Repro steps:**

1. Create a docker-container builder
2. Run `docker buildx build .`

**Current behavior:**

I get a warning:

```
WARNING: No output specified with docker-container driver. Build result will only remain in the build cache. To push result image into registry use --push or to load image into docker use --load
```

**Desired behavior:**

It'd be nice if we had a flag that explicitly requested this behavior, e.g.  `--output=type=none`, and did not emit any warning

**Additional info**

Most of my CI pipelines have a `dry-run` flag where i want `--output=type=none` on pull-request, but `--output=type=image,push=true` on push.

This also would make my bakefile a bit more explicit, because sometimes i want to override a `--output=type=image` with no output, and right now the syntax is kind of inscrutable.

**Comment by tonistiigi** [comment]
It's called `type=cacheonly` https://docs.docker.com/build/exporters/#cache-only-export

**Comment by thompson-shaun** [comment]
Ok to close @nicks?

**Comment by nicks** [comment]
thanks! i must have missed that.
