### ISSUE TITLE
cgroup property is not allowed when using bake command with docker compose as input

### ISSUE THREAD

**Issue by noorul** [docker/buildx#2548]
### Description

I am using `cgroup: private` property in docker-compose. This support was added in the spec via https://github.com/compose-spec/compose-spec/pull/292. But bake command fails to parse it. I get the following error

`Additional property cgroup is not allowed`

Versions:

Host OS: Ubuntu 22.04
Docker CE: 26.1.4-1~ubuntu.22.04~jammy
Docker Compose Plugin: 2.27.1-1~ubuntu.22.04~jammy
Docker Buildx Plugin: 0.14.1-1~ubuntu.22.04~jammy

**Comment by tonistiigi** [comment]
@crazy-max @ndeloof How is this possible? Looks like a relatively old PR and we are using compose v2.1.2

**Comment by crazy-max** [comment]
Seems to work fine with this new test: https://github.com/docker/buildx/pull/2555

@noorul Can you share your compose file and also the output of `docker buildx version` please?

**Comment by noorul** [comment]
My bad! Even though I was installing the latest from the docker apt repo, I had old installation instructions in the Dockerfile.  Sorry for the noise. I appreciate the help!
