### ISSUE TITLE
See contents of mount cache?

### ISSUE THREAD

**Issue by jameshowison** [docker/buildx#255]
Is it possible to see the contents of a mount cache?

I see from #244 that one can generate a tar inside a Dockerfile

```
run --mount=type=cache,target=/cache tar xvf https://mycache.tar -C /cache
```

That's helpful, but makes me wonder how these mount cache's are implemented, are they docker volumes or are they filesystems 'inside' the buildx docker-container builder?

Apologies if that question is not well formed!

(Also thanks to #156 for really helping me grasp the dual meaning of cache (instruction/mount) in buildx).

**Comment by tonistiigi** [comment]
With docker you can see them with `docker system df -v`. With other drivers you need the `du` command from https://github.com/docker/buildx/pull/249

**Comment by jameshowison** [comment]
Thanks.  This is the result I get with `docker system df -v` (after switching to the docker builder).

```
zgxi3eeyumrx*       exec.cachemount     0B                  2 days ago           About a minute ago   10                  false
```

So now I have a name for the exec.cachemount, which is something. However I'd like to see the file system contents (I'm debugging a cache issue).  I realize the one above has no contents (`0B`).  The only commands I can find for exporting files seem to work on containers or images, but they won't take the ID above for the `exec.cachemount` object. Any idea how to see the actual files in the `exec.cachemount`?  

For more context I'm trying to get `renv` working with buildx: https://github.com/howisonlab/test_repo_buildx_renv

I tried using the `buildx -o` command from  but that hangs, running for hours (the size of the export counts up for about 30s then stays at that, below I only ran it for 50s, but I've let it run for hours with no better result.

My hoped for result is to see the files from the cachemount `/buildx_caches/renv_cache` in the output directories.

```
SOI-A14570-Howison:test_repo_buildx_renv howison$ docker buildx build -o . .
[+] Building 50.5s (11/12)                                                                                                                                       
 => [internal] load build definition from Dockerfile                                                                                                        0.0s 
 => => transferring dockerfile: 32B                                                                                                                         0.0s
 => [internal] load .dockerignore                                                                                                                           0.1s
 => => transferring context: 2B                                                                                                                             0.0s
 => resolve image config for docker.io/docker/dockerfile:1.0-experimental                                                                                   0.3s
 => CACHED docker-image://docker.io/docker/dockerfile:1.0-experimental@sha256:cbd6491240cc8894d25e366ba83da19df1187f975dc3a5c2f88ce888ca696174              0.0s
 => [internal] load build definition from Dockerfile                                                                                                        0.0s
 => => transferring dockerfile: 32B                                                                                                                         0.0s
 => [internal] load .dockerignore                                                                                                                           0.0s
 => [internal] load metadata for docker.io/rocker/r-base:latest                                                                                             0.3s
 => [1/4] FROM docker.io/rocker/r-base@sha256:855c74722904f70e80f22df76defcedcb20899df850a4c8957135e0dc4999861                                              0.0s
 => CACHED [2/4] RUN --mount=type=cache,target=/buildx_caches/renv_cache R -e "install.packages('remotes', repos = c(CRAN = 'https://cloud.r-project.org')  0.0s
 => CACHED [3/4] RUN --mount=type=cache,target=/buildx_caches/renv_cache R -e "remotes::install_github('rstudio/renv@0.9.3-80')"                            0.0s
 => CACHED [4/4] RUN --mount=type=cache,target=/buildx_caches/renv_cache R -e "Sys.setenv(RENV_PATHS_ROOT = '/buildx_caches/renv_cache'); renv::consent(TR  0.0s
 => exporting to client                                                                                                                                    49.6s
 => => copying files 74.49MB                                                                                                                               49.6s
```

**Comment by jameshowison** [comment]
Still hopeful here.  I can see the contents of containers using `docker export` and volumes using the [volume backup commands](https://docs.docker.com/storage/volumes/) but I can't find a way to get a `tar` of an `exec.cachemount`.

I was referred to the `-o` argument of `buildx` but I couldn't figure it out.  Or perhaps things got stuck trying to do a complete tar of the build container? https://github.com/docker/buildx#-o---outputpath-typetypekeyvalue

Is there any way to see just the contents of an exec.cachemount?  Or could someone help by showing how to use `buildx -o` to get a tar archive of just a portion of the build container?

**Comment by tonistiigi** [comment]
`buildx du` was added. There isn't necessarily a path where the files exist. There could be multiple directories that are mounted together. To copy out during the build just use `RUN --mount=... cp`

**Comment by agirault** [comment]
For anyone stumbling here looking for an easy way to identify the cache mounts associated with their label (human id, vs ID), filesystem location and size, I whipped this up: 

https://gist.github.com/agirault/1ccccfb17acbf23afff628d18210ac5c

Example usage and outputs at the bottom.
