### ISSUE TITLE
ppc64le question

### ISSUE THREAD

**Issue by cegeyer78** [docker/buildx#258]
I'm having an issue with running ppc64le CentOS 7 and am not sure if I don't have the buildx setup correct or an issue with the repositories. Here is my Dockerfile and steps on how I build.

**Dockerfile**
`FROM centos:7`
`RUN uname -m`

**Test Steps**
`export DOCKER_CLI_EXPERIMENTAL=enabled`
`docker run --rm --privileged docker/binfmt:820fdd95a9972a5308930a2bdfb8573dd4447ad3`
`docker buildx create --name testbuilder`
`docker buildx use testbuilder`
`docker buildx inspect --bootstrap`
`docker buildx build --platform linux/ppc64le --load -t test-ppc64le .`
`docker run -it --rm test-ppc64le bash`
`yum makecache`

**Yum Output**
`# yum makecache`
`Loaded plugins: fastestmirror, ovl`
`Determining fastest mirrors`
` * base: mirror.siena.edu`
` * extras: mirror.genesisadaptive.com`
` * updates: mirror.genesisadaptive.com`
`base                                                                                               | 3.6 kB  00:00:00     `
`extras                                                                                             | 2.9 kB  00:00:00     `
`updates                                                                                            | 2.9 kB  00:00:00     `
`base/7/ppc64le/group_gz        FAILED                                                   ]  0.0 B/s |    0 B  --:--:-- ETA `
`http://mirror.siena.edu/centos-altarch/7.7.1908/os/ppc64le/repodata/4af1fba0c1d6175b7e3c862b4bddfef93fffb84c37f7d5f18cfbff08abc47f8a-c7-x86_64-comps.xml.gz: [Errno -1] Metadata file does not match checksum`
`Trying other mirror.`
`extras/7/ppc64le/filelists_db  FAILED                                                   ]  0.0 B/s | 672 kB  --:--:-- ETA `
`http://mirror.genesisadaptive.com/centos-altarch/7.7.1908/extras/ppc64le/repodata/5945031ac4ddad7c50e16941b63ececfa92a648281de468355b904b9045e92d8-filelists.sqlite.bz2: [Errno -1] Metadata file does not match checksum`
`Trying other mirror.`
`...`

**Comment by chenghlee** [comment]
I ran into the same problem on my Ubuntu 18.04 systems, and this commands seems to have fixed the issue for me:
```
docker run --rm --privileged multiarch/qemu-user-static:latest --reset -p yes
```

However, I'm not 100% sure what the underlying cause is, nor am I sure this won't interfere with any QEMU applications you already have installed on the host.

**Comment by crazy-max** [comment]
You can test with QEMU from https://github.com/tonistiigi/binfmt that is made for running containers:

```
$ docker run -it --rm tonistiigi/binfmt:latest --version
binfmt/8703596 qemu/v6.0.0 go/1.16.5
```
