### ISSUE TITLE
Can cachemounts be copied to images at same path?

### ISSUE THREAD

**Issue by jameshowison** [docker/buildx#260]
I'm working to get renv or R packages working with buildx cachemounts.  Unlike pip etc, R builds packages "in place" so even if I can set up a buildx cachemount what is built is not available to containers after the building.  Is there a way to "instantiate" the cachemount in the built container (without changing the path)?

ie if I have a cachemount at:

```
RUN --mount=type=cache,target=/buildx_caches/renv_cache 
```

Can I get the contents of `/buildx_caches/renv_cache` to show up under that path on the image being built?

Otherwise I have to set a path for the renv cache at build time, to use the buildx cachemount. Then copy the contents of the cachemount to the image but at a different path, then when the image is run, the renv symlinks still point to the cachemount path, so I would have to update all the symlinks.

**Comment by FernandoMiguel** [comment]
I'm very confused here.
The mount point in the new build will be exactly like the original one, and its contents the same left by the previous build

**Comment by jameshowison** [comment]
Apologies for the confusion. I was asking about having a copy of the
contents of the mount cache available on a container, at image runtime.

I hope that’s clearer.

Although it Turns out that’s not needed with renv as the renv::isolate
method does what I need.

**Comment by tonistiigi** [comment]
There isn't a built-in method for this. You would need to copy files from cache to your image as part of your build (with a possible temporary symlink like you explain if your app only takes hardcoded path).

**Comment by FernandoMiguel** [comment]
@jameshowison sounds like host cache is the wrong approach here.
In the past when working with heavy maven projects, i did a "cache docker".
it would keep all the build cache in it, and then be the FROM for future images.
when the "cache" needed to be invalidated, i would just rebuild that container

**Comment by warrenc5** [comment]
Sophisticated node/jmod/apt CI builds require dependencies downloaded at build time to be reused across builds and available at runtime also. 

Without polluting the build context, git etc. Or depending on the docker build host filesystem mounts directly. 
 
I would like to see this as a feature.

Options could be:
Introduce a new Dockerfile syntax

# syntax=docker.io/docker/dockerfile-upstream:cache-export

overload the ADD or COPY --from cache  

COPY --from cache --mount=type=cache,src=/site/cache --mount=type=cache,src=/root/.cache/pnpm  --link

The syntax should support cache directory relocations and  --link 

The workaround I currently have is  

```
RUN --mount=type=cache,target=/root/.cache \
    --mount=type=cache,target=/root/.local \
    --mount=type=cache,target=/site/cache \
    --mount=type=cache,target=/var/cache/apt \
    --mount=type=cache,target=/tmp \
    tar uf /tmp/cache.tar /root/.local /root/.cache /site/cache /var/cache/apt 

RUN --mount=type=cache,target=/tmp tar xf /tmp/cache.tar -C / --skip-old-files
```

The output is below and you can see that any performance improvement obtained by using the cache is lost in manually exporting the files into the image. 

I don't know why cache interactions are so slow.

```
#17 [stage-0  9/11] RUN --mount=type=cache,target=/root/.cache     --mount=type=cache,target=/root/.local     --mount=type=cache,target=/site/cache     --mount=type=cache,target=/var/cache/apt     --mount=type=cache,target=/tmp     tar uf /tmp/cache.tar /root/.local /root/.cache /site/cache /var/cache/apt
#17 17.17 tar: Removing leading `/' from member names
#17 17.17 tar: Removing leading `/' from hard link targets
#17 DONE 54.4s

#18 [stage-0 10/11] RUN --mount=type=cache,target=/tmp tar xf /tmp/cache.tar -C / --skip-old-files
#18 DONE 49.2s
```
