### ISSUE TITLE
Exporting cache crashes with a content not found error 

### ISSUE THREAD

**Issue by SunnyMagadan** [docker/buildx#261]
Hello! 👋 
I have a suspicious behavior of `bulidx` cache during the cache export. The build starts with `cache-from` and `cache-to` options configured to a local directory.

```
docker buildx build \
  --tag project/app:latest \
  --target builder \
  --progress=plain \
  --cache-from=type=local,src=/home/appuser/docker-cache \
  --cache-to=type=local,dest=/home/appuser/docker-cache,mode=max \
  --output type=docker,dest=image.tar .
```
 
The build process seems fine and the log shows how a builder uses cache layers from a previous run without rebuilding them again. 
```
....
#23 [node_modules 5/5] RUN yarn install --frozen-lockfile
#23 CACHED

#18 [builder  7/11] COPY --from=ruby_bundle /usr/local/bundle /usr/local/bun...
#18 CACHED

#17 [ruby_bundle 3/3] RUN bundle config --global frozen 1     && bundle inst...
#17 CACHED

#20 [node_modules 2/5] COPY package.json yarn.lock ./
#20 CACHED

#10 [builder  2/11] COPY config/application.yml.example config/application.y...
#10 CACHED
...
```

The export of an image completed without any issues:
```
#29 exporting to oci image format
#29 exporting layers
#29 exporting layers 51.6s done
#29 exporting manifest sha256:19948f3a7107602b862bc4abfad30511005e8a61256a70028f3870cbb0f91576 0.0s done
#29 exporting config sha256:a10a089dc0df2d86e0609147f0212de47a3137edb4628aa314e47c431f1d6bbe done
#29 sending tarball
#29 sending tarball 10.2s done
#29 DONE 61.9s
```

But writing of new cache files crashes:
```
#30 exporting cache
#30 preparing build cache for export
#30 preparing build cache for export 0.2s done
#30 writing layer sha256:00ccf2324a0b8894378909f8cb0c8f264a2e8a1581ed46500787dd8dacf68432 done
#30 ERROR: error writing layer blob: content sha256:00ccf2324a0b8894378909f8cb0c8f264a2e8a1581ed46500787dd8dacf68432: not found
------
 > exporting cache:
------
failed to solve: rpc error: code = Unknown desc = error writing layer blob: content sha256:00ccf2324a0b8894378909f8cb0c8f264a2e8a1581ed46500787dd8dacf68432: not found

Exited with code exit status 1
```

The issue started to appear when I manually removed several blobs from a cache directory. I took those files that were not accessed for a long time (atime) and removed them before the build run. Several first builds were successful and I started doing such a clean up regularly, but at some point, the aforementioned problem started to appear. I would not be surprised by such behavior if the build crashed at the beginning or it failed to read some cache layers during the image build, but it looks surprising when it builds the image successfully uses the cache but fails during the export of a cache.

**Comment by tonistiigi** [comment]
We don't support partial cache imports where some data has been manually removed atm. The reason it fails on export is that the export doesn't only export cache that was pulled to the local system during the build but also all the dependant cache that was importable for the build.

**Comment by SunnyMagadan** [comment]
Thank you for the explanation. Now it's clear. I hope this will become possible in later releases.
