### ISSUE TITLE
Unable to install buildx plugin from the binary release

### ISSUE THREAD

**Issue by SunnyMagadan** [docker/buildx#262]
I followed the instructions from a readme file https://github.com/docker/buildx/#binary-release and placed a downloaded `docker-buildx` binary at the `~/.docker/cli-plugins/docker-buildx` path, but `docker buildx` command doesn't seem to work and displays the docker help information with the details about invalid `buildx` plugin.
```
Invalid Plugins:
  buildx      failed to fetch metadata: fork/exec /home/appuser/.docker/cli-plugins/docker-buildx: exec format error
```
I am using Ubuntu 16.04 and docker 19.03.08 installed from a binary release. I downloaded `buildx-v0.3.1.linux-amd64` file.

**Comment by tonistiigi** [comment]
you can't pulled the binary for the correct architecture. Run `file /home/appuser/.docker/cli-plugins/docker-buildx` to check.

**Comment by SunnyMagadan** [comment]
Thank you for the quick resolution. Indeed, it was an issue with a file. In my case, it was corrupted for some reason.

**Comment by 201Factory** [comment]
I have get the same error and i just remove this one `file /home/appuser/.docker/cli-plugins/docker-buildx` and all it's gona be okay

**Comment by sirno-baka** [comment]
I had the same problem, I just made it executable
`chmod -x /home/user/.docker/cli-plugins/docker-buildx`

**Comment by htmgarcia** [comment]
`rm /home/appuser/.docker/cli-plugins/docker-buildx` fixed the issue in my end

**Comment by jdnichollsc** [comment]
This is the right solution to this issue from Mac:
```sh
brew install docker-buildx
ln -sfn /opt/homebrew/opt/docker-buildx/bin/docker-buildx ~/.docker/cli-plugins/docker-buildx
chmod +x ~/.docker/cli-plugins/docker-buildx
```
Homebrew is beautiful! <3

**Comment by Intevel** [comment]
> `rm /home/appuser/.docker/cli-plugins/docker-buildx` fixed the issue in my end

Same for me

**Comment by nmoreaud** [comment]
```
failed to fetch metadata: fork/exec /usr/local/lib/docker/cli-plugins/docker-buildx: no such file or directory

DEPRECATED: The legacy builder is deprecated and will be removed in a future release.
            Install the buildx component to build images with BuildKit:
            https://docs.docker.com/go/buildx/
```

In fact `/usr/local/lib/docker/` contained only invalid symlinks.
So, running this command fixed it: `sudo rm -fr /usr/local/lib/docker/`

**Comment by feyounger** [comment]
> This is the right solution to this issue from Mac:
> 
> ```shell
> brew install docker-buildx
> ln -sfn /opt/homebrew/opt/docker-buildx/bin/docker-buildx ~/.docker/cli-plugins/docker-buildx
> chmod +x ~/.docker/cli-plugins/docker-buildx
> ```
> 
> Homebrew is beautiful! <3

yes sir,i want to why
