### ISSUE TITLE
ERROR: bad file descriptor running docker build commands

### ISSUE THREAD

**Issue by MattpMatt** [docker/buildx#2623]
### Contributing guidelines

- [X] I've read the [contributing guidelines](https://github.com/docker/buildx/blob/master/.github/CONTRIBUTING.md) and wholeheartedly agree

### I've found a bug and checked that ...

- [X] ... the documentation does not mention anything about my problem
- [X] ... there are no open or closed issues that are related to my problem

### Description

The commands: 
`docker build .`
`docker build ls`
 throw ERROR: bad file descriptor
 
 I suspect that there might be issues with some config or file that is inaccessible to buildx 

### Expected behaviour

The docker image should be built.

### Actual behaviour

Caching fails and throws a bad file descriptor error:
`ERROR: bad file descriptor`

### Buildx version

github.com/docker/buildx v0.16.1 34c1952

### Docker info

```text
Client: Docker Engine - Community
 Version:    27.1.0
 Context:    default
 Debug Mode: false
 Plugins:
  buildx: Docker Buildx (Docker Inc.)
    Version:  v0.16.1
    Path:     /usr/libexec/docker/cli-plugins/docker-buildx
  compose: Docker Compose (Docker Inc.)
    Version:  v2.29.0
    Path:     /usr/libexec/docker/cli-plugins/docker-compose

Server:
 Containers: 0
  Running: 0
  Paused: 0
  Stopped: 0
 Images: 0
 Server Version: 27.1.0
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Using metacopy: false
  Native Overlay Diff: true
  userxattr: false
 Logging Driver: json-file
 Cgroup Driver: systemd
 Cgroup Version: 2
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local splunk syslog
 Swarm: inactive
 Runtimes: io.containerd.runc.v2 runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 2bf793ef6dc9a18e00cb12efb64355c2c9d5eb41
 runc version: v1.1.13-0-g58aa920
 init version: de40ad0
 Security Options:
  apparmor
  seccomp
   Profile: builtin
  cgroupns
 Kernel Version: 5.15.0-91-generic
 Operating System: Linux Mint 21.1
 OSType: linux
 Architecture: x86_64
 CPUs: 16
 Total Memory: 31.12GiB
 Name: cs22002iu
 ID: 89fb2c0b-baa7-4dd6-94f0-4241fb1f9f15
 Docker Root Dir: /var/lib/docker
 Debug Mode: true
  File Descriptors: 30
  Goroutines: 41
  System Time: 2024-07-23T16:17:47.590832661+12:00
  EventsListeners: 0
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false
```

### Builders list

```text
ERROR: bad file descriptor
```

### Configuration

NA

### Build logs

```text
NA
```

### Additional info

The following fixes the issue although not ideal:

- Installing version 0.15.1-1~ubuntu.22.04~jammy
- Running the commands with sudo
- Setting DOCKER_BUILDKIT=0

**Comment by crazy-max** [comment]
duplicates of https://github.com/docker/buildx/issues/2593
