### ISSUE TITLE
Is it possible to Push to Docker HUB inside a GitHub Action?

### ISSUE THREAD

**Issue by WaterKnight1998** [docker/buildx#264]
Is it possible to Push to Docker HUB inside a GitHub Action?

**Comment by AkihiroSuda** [comment]
https://github.com/marketplace/actions/docker-buildx

**Comment by iav** [comment]
The same: how to provide repository auth credentials to mage push to container repo?

**Comment by iav** [comment]
@WaterKnight1998 I found. Look to example https://github.com/HaschekSolutions/PictShare-Docker/blob/28d6b93c3123e2e7807e5d00fda2ed470d5167ec/.github/workflows/buildx_dockerhub.yml

**Comment by WaterKnight1998** [comment]
> 
> 
> @WaterKnight1998 I found. Look to example https://github.com/HaschekSolutions/PictShare-Docker/blob/28d6b93c3123e2e7807e5d00fda2ed470d5167ec/.github/workflows/buildx_dockerhub.yml

Yeah, I was testing it right now. I have an example here:

https://github.com/WaterKnight1998/terraria-docker/blob/master/.github/workflows/publish-ARM-container.yml

**Comment by crazy-max** [comment]
See https://github.com/docker/build-push-action/#usage to use buildx with GitHub Actions.
