### ISSUE TITLE
Feature Request: ability to disable recursive clone

### ISSUE THREAD

**Issue by TilGP** [docker/buildx#2644]
### Description

I am using JetBrains-IDEs and want to set up a DevContainer environment.
When I build the DevContainer it executes `docker build --ssh default=$SSH_AUTH_SOCK -f .devcontainer/Dockerfile git@user/repo.git#branch`.
Docker build seems to try to recursively clone the repository, which is bad, because I don't have access to one of the submodules.

So the feature request is a new docker build option that disables automatic recursive cloning.

**Comment by tonistiigi** [comment]
Add your use case to https://github.com/moby/buildkit/issues/4905
