### ISSUE TITLE
ERROR: failed to solve: process "/bin/sh -c npm install" did not complete successfully: exit code: 1

### ISSUE THREAD

**Issue by aaditya-crypto** [docker/buildx#2648]
FROM node:22.6.0-alpine3.19 AS production

ENV NODE_ENV=production

WORKDIR /app

COPY package.json .

COPY package-lock.json .

RUN npm install 

COPY . .

RUN npm run build

CMD ["sh", "-c", "npm run start: production"]

EXPOSE 3001

**Comment by tonistiigi** [comment]
This is an error from the application you are running inside container.
