### ISSUE TITLE
[v0.4.0] build fail with --pull arg

### ISSUE THREAD

**Issue by opopops** [docker/buildx#265]
Hi,

with the last version (v0.4.0) there is a problem with the build command when I use it whith --pull arg, I guess that there is command parsing problem:

```shell
docker buildx build   --target dev   --tag my_tag --pull --load .
invalid argument "--load" for "--pull" flag: strconv.ParseBool: parsing "--load": invalid syntax
```

If I had ```true``` just after ```--pull``` arg it works:

```shell
docker buildx build   --target dev   --tag my_tag --pull true --load .
```

**Comment by tamalsaha** [comment]
I am seeing the same issue on GitHub Actions. https://github.com/kubepack/kubepack/pull/97/checks?check_run_id=633987589

```
DOCKER_CLI_EXPERIMENTAL=enabled docker buildx build --platform linux/amd64 --load --pull -t appscodeci/kubepack-operator:e7770b6_linux_amd64 -f bin/.dockerfile-PROD-linux_amd64 .
invalid argument "-t" for "--pull" flag: strconv.ParseBool: parsing "-t": invalid syntax
```

**Comment by thaJeztah** [comment]
Does it work if you use `--pull=true` ?

**Comment by tamalsaha** [comment]
checking

**Comment by thaJeztah** [comment]
Looks like this was introduced in https://github.com/docker/buildx/pull/165

**Comment by tiborvass** [comment]
Yes I'm on a fix

**Comment by tamalsaha** [comment]
`--pull=true` works.

https://github.com/kubepack/kubepack/runs/634064651?check_suite_focus=true#step:8:19

Should we expect a patch release soon with the fix?

**Comment by tiborvass** [comment]
@tamalsaha yes, apologies for the bug.

**Comment by thaJeztah** [comment]
> `--pull=true` works.

👍 great! At least that can be used as a temporary workaround (I think that continues working even after the bug fix, so if needed, you can apply that workaround)

**Comment by tamalsaha** [comment]
Thanks for the quick fix, folks!
