### ISSUE TITLE
bake: HCL does not support pathexpand() function

### ISSUE THREAD

**Issue by Cryowatt** [docker/buildx#269]
My use case is that I want to do something like this:
```hcl
target "builder" {
  secret = [
    "id=mysecret,src=~/.secrets/mysecret"
  ]
}
```

Docker doesn't resolve `~` in paths, so I tried `"id=mysecret,src=${pathexpand("~/.secrets/mysecret"}"` in hope that the common HCL [functions from Terraform](https://www.terraform.io/docs/configuration/functions/pathexpand.html) also were available here. It failed to parse.

Next I tried just basic interpolation `"id=mysecret,src=${"/users/myuser"}/.secrets/mysecret"}` and it also failed to resolve the path correctly.

So two questions:

1. Is it supposed to work and if not can it be added?
2. Is there a workaround for this? Best option currently seems to be to skip using `docker-bake.hcl` and just script the build commands explicitly in a shell script.

**Comment by k911** [comment]
In your case you could use `$HOME` environment variable that should be available, e.g.:

```hcl
variable "HOME" {
  # value will be overridden by $HOME env variable
  default = "/home/default_user"
}

target "builder" {
  secret = [
    "id=mysecret,src=${HOME}/.secrets/mysecret"
  ]
}
```

As per [docs](https://github.com/docker/buildx#hcl-variables-and-functions), you can find available functions [here](https://github.com/docker/buildx/blob/master/bake/hcl.go#L19-L65)

**Comment by tiborvass** [comment]
It's unclear to me how important pathexpand is. For your particular case, I would agree with @k911's suggestion. If that solves your issue feel free to close, otherwise I'm keeping this open for now for discussion around pathexpand().

**Comment by tonistiigi** [comment]
You should get the function definitions to go-cty first. Then we can include them.
