### ISSUE TITLE
Tweak 'BUILDX_GIT_LABELS' to get the git tag if it exists

### ISSUE THREAD

**Issue by a-watts-fnc** [docker/buildx#2735]
### Description

Hi, I think it might make sense to edit the behaviour of `BUILDX_GIT_LABELS=1` to also add a label `org.opencontainers.image.tag=<git_tagged_version>`? 

If it exists, a tag is more semantically useful than the commit hash IMO - I'd even make the argument that it should attempt to use the tag first, and then fall back to using the commit hash if it isn't present. It looks that there is already the [`Git.Tag`](https://github.com/docker/buildx/blob/1de332530f6c21e69ddf8577fbc7adcf0ae7c723/util/gitutil/gitutil.go#L111) function for retrieving the tag, so hopefully it wouldn't be too big a change.

**Comment by tonistiigi** [comment]
What's the behavior if there are more than one tags for a commit?

**Comment by a-watts-fnc** [comment]
Ah, I didn't know you could have multiple tags, in that case I see why the hash make sense
