### ISSUE TITLE
Provide a way to use the image cache for moby/buildkti:buildx-stable-1

### ISSUE THREAD

**Issue by arthurzenika** [docker/buildx#2819]
### Description

Hi, 

we're running buildx with the docker-container driver through a docker-in-docker setup with services in gitlab-ci and we are witnessing a great number of image pulls for the image `moby/buildkit:buildx-stable-1` and we were surprised since the 3 virtual machines running the gitlab-runners have that image in their `docker images` list, so we were expecting the cached version to be used. 

Here is a sample of the log : 

```
[info]  running multi-arch Docker build ...
#1 [internal] booting buildkit
#1 pulling image moby/buildkit:buildx-stable-1
#1 pulling image moby/buildkit:buildx-stable-1 6.3s done
#1 creating container buildx_buildkit_vigorous_galileo0
```

Reading the documentation there seems to be a number of ways to manipulate cache but it seems to be directed at the layers of the built image, not the builder image... Did we miss something ? Is that "pulling image" using the docker engine or is it something different ?

**Comment by arthurzenika** [comment]
Thanks for looking at this... I understand the logic, but I'm seeing something different for 3 VMs (and their docker-in-docker containers) which have the image I would not expect the number of pulls for that image to be (daily) in the hundreds : 

![Image](https://github.com/user-attachments/assets/af6c7267-935f-498c-960b-2a99742288cc)

And we can see these are actual pulls not version checks : 

![Image](https://github.com/user-attachments/assets/a218bfe7-2513-4c40-bec3-353b4e191db4)

Could it be that running buildx with the docker-container driver it cannot cache that image ? I would expect it to use the image on the host machine, but is it using it ?

**Comment by Selaron** [comment]
Something like this might work:

> script:
>   - docker pull gitlab.company.tld:5000/user/project/buildkit:buildx-stable-1 && docker tag gitlab.company.tld:5000/user/project/buildkit:buildx-stable-1 moby/buildkit:buildx-stable-1 || docker pull moby/buildkit:buildx-stable-1 && docker tag moby/buildkit:buildx-stable-1 gitlab.company.tld:5000/user/project/buildkit:buildx-stable-1 && docker push gitlab.company.tld:5000/user/project/buildkit:buildx-stable-1

**Comment by crazy-max** [comment]
> Could it be that running buildx with the docker-container driver it cannot cache that image ? I would expect it to use the image on the host machine, but is it using it ?

It always tries to pull or use local image if pull fails: https://github.com/docker/buildx/blob/567361d4948b06c559b41797c58e683f9a587583/driver/docker-container/driver.go#L93-L114

This suggestion would work https://github.com/docker/buildx/issues/2819#issuecomment-2517259357
