### ISSUE TITLE
Add "bake: additional test for empty variable" from v0.19 branch

### ISSUE THREAD

**Issue by thompson-shaun** [docker/buildx#2825]
Additional tests were added in https://github.com/docker/buildx/pull/2824 at https://github.com/docker/buildx/pull/2824/commits/8b029626f3d25f3ceb8a5689ba1201d55ccca0d4, these should be added to `master` as well.

**Comment by crazy-max** [comment]
Handled in https://github.com/docker/buildx/pull/2814
