### ISSUE TITLE
--cache-from user/image:cache does not work when builder spans multiple host

### ISSUE THREAD

**Issue by Silex** [docker/buildx#284]
Hello,

I have the following config:

``` shell
rm -rf ~/.docker/cli-plugins
mkdir -p ~/.docker/cli-plugins
DOCKER_BUILDKIT=1 docker build --platform=local -o . git://github.com/docker/buildx
mv buildx ~/.docker/cli-plugins/docker-buildx
chmod a+x ~/.docker/cli-plugins/docker-buildx
docker buildx create --name emacs-$CI_JOB_NAME --driver docker-container --driver-opt image=moby/buildkit:master,network=host
docker buildx create --append --name emacs-$CI_JOB_NAME --driver docker-container --driver-opt image=moby/buildkit:master,network=host ssh://root@$DOCKER_ARM_HOST
```

But only the images that are built on that host get cached in the cache. The ones that runs on DOCKER_ARM_HOST are not.

**Comment by tonistiigi** [comment]
How are you exporting cache? At least inline cache should work even with this method.

**Comment by Silex** [comment]
Sorry I forgot to show you the buildx line, I think it's simpler if I show you the whole build process

```
# Latest buildx
rm -rf ~/.docker/cli-plugins
mkdir -p ~/.docker/cli-plugins
DOCKER_BUILDKIT=1 docker build --platform=local -o . git://github.com/docker/buildx
mv buildx ~/.docker/cli-plugins/docker-buildx
chmod a+x ~/.docker/cli-plugins/docker-buildx

# Recreate builder
docker buildx rm emacs-26.3 || true
docker buildx create --name emacs-26.3 --driver docker-container --driver-opt image=moby/buildkit:master,network=host
docker buildx create --append --name emacs-26.3 --driver docker-container --driver-opt image=moby/buildkit:master,network=host ssh://root@$DOCKER_ARM_HOST

# Build image
export  DOCKER_PLATFORMS: linux/amd64,linux/386,linux/arm/v7,linux/arm64/v8
docker buildx build --platform $DOCKER_PLATFORMS --pull --push --cache-from silex/emacs:26.3-cache --cache-to silex/emacs:26.3-cache -t silex/emacs:26.3-test .
```

As you see I delete the builder between each run. If I use a permanent worker where I don't delete the worker then of course it works but my goal is to move the image building process to some automated CI where a new VM spawns every time.

I can also try to export to a local cache if you think it works better.

**Comment by Silex** [comment]
Here is a Dockerfile if you want to test: https://gitlab.com/Silex777/docker-emacs/-/blob/master/26.3/ubuntu/18.04/Dockerfile

But actually it's weird. I ran the same 3 times: the first time everything got built. The 2nd time the i386/amd64 images were cached, arm32v7&arm64v8 got rebuilt. The 3rd time the opposite! i386/amd64 being rebuilt and arm images cached.

**Comment by Silex** [comment]
Same results with a simpelr image:

**Comment by Silex** [comment]
@tonistiigi: friendly ping. What can I do to debug this issue? maybe run with some DOCKER_DEBUG flags? Then maybe try to understand what happens in buildx? I'm a developper so maybe I can help, but I'm very new to buildx/go in general.

**Comment by tonistiigi** [comment]
Yes, registry mode does not work in this case as both nodes will push to the same name, overwriting the cache from other. This could be fixed if they push by digest and the client performs a merge later. But as I said, the inline cache should work atm as well `--cache-to type=inline`

**Comment by Silex** [comment]
@tonistiigi: ah, thanks for the explanation & suggestion I'll try and report :+1:

**Comment by Silex** [comment]
It worked! :tada:

It needs both `--cache-to type=inline` and `--cache-from namespace/image:tag` (logical but expliciting it for future readers).

Thanks a lot!
