### ISSUE TITLE
ERROR exporting to oci image format during docker buildx build

### ISSUE THREAD

**Issue by MarkCarbonell98** [docker/buildx#290]
While running the command: 

```bash
docker buildx build --platform linux/arm/v7,linux/amd64 . -f _docker/base.raspberry.Dockerfile  --load
```

With the following Dockerfile:
```dockerfile
FROM arm32v7/docker:19.03.8

RUN apk add openssh \
            ca-certificates

RUN apk update \
    && apk add py-pip \
            python-dev \
            libffi-dev \
            openssl-dev \
            gcc \
            libc-dev \
            make

RUN pip install docker-compose

RUN pip install awscli

RUN apk add bash \
            vim \
            git \
            jq \
            sed \
            curl \
            gzip \
            bind-tools

CMD ["/bin/bash"]
```

I get the error: ***ERROR exporting to oci image format***

![Screenshot from 2020-05-13 11-38-53](https://user-images.githubusercontent.com/32847477/81798811-bd875600-9510-11ea-9bba-e1029e8a632c.png)

Apparently the docker exporter does not support exporting manifests lists. That's odd. Wasn't this issue fixed in a previous release ?

***Notice***: This does not happen when running it without the `--platform` flag. But that's useless in my case because it ***must*** be build for both linux/amd64 and linux/armv7 architectures. 

Has anyone seen this issue before ? Or has an idea on how to fix it ?

Docker version: ***19.03.8, build afacb8b***
Linux Kernel version:  ***4.19.97-v7l+***
OS: 
```env
PRETTY_NAME="Raspbian GNU/Linux 10 (buster)"
NAME="Raspbian GNU/Linux"
VERSION_ID="10"
VERSION="10 (buster)"
VERSION_CODENAME=buster
ID=raspbian
ID_LIKE=debian
HOME_URL="http://www.raspbian.org/"
SUPPORT_URL="http://www.raspbian.org/RaspbianForums"
BUG_REPORT_URL="http://www.raspbian.org/RaspbianBugs"
```

**Comment by tonistiigi** [comment]
`docker load` does not currently support loading manifest lists and images in `docker images` can only be for a single platform. This is documented in https://github.com/docker/buildx#docker
