### ISSUE TITLE
buildx platfrom is arm64, but actually the images is amd64.

### ISSUE THREAD

**Issue by bestbugwriter** [docker/buildx#295]
I was use buildx to build a arm64 image in a amd64 server. my command like this, but it actually is amd64 arch. This is an event with probability. about 20%.
docker buildx build --platform arm64 -t hub.dtwarebase.tech/studio/workflow:1.7.0.21 . --push

my buildx version
![image](https://user-images.githubusercontent.com/4133268/82123707-5d710800-97cd-11ea-909a-f5da744f8a92.png)

the problem
![image](https://user-images.githubusercontent.com/4133268/82123542-8d6bdb80-97cc-11ea-9e94-d4ce0a78d232.png)

**Comment by tonistiigi** [comment]
`--platform` is a hint to the `FROM` commands on what platform to use when pulling an image if `FROM` doesn't specify `--platform` itself. If the `FROM` image is not multi-arch and only for `amd64` or `FROM` overrides the value with `--platform` then this is expected.
