### ISSUE TITLE
Add a new progress mode "--progress=plain-in-order"

### ISSUE THREAD

**Issue by gabrieldemarmiesse** [docker/buildx#299]
Hi, maybe this issue would be a better fit for the buildkit repo. Let me know and I can transfer it over there.

Docker buildx has this awesome feature of being able to build many dockerfiles/stages in parralel. This is very nice when following the progression in a TTY terminal, but when running in plain mode, it's harder to understand what is going on because the output is printed on the fly. I understand a best-effort is made here since everything is asynchronous. 

Some example of log in a CI that is hard to read, I've put some xxx for the information we can't disclose:

```
#10 9.817 Building wheels for collected packages: xxxxxxxxx
#10 9.817   Building wheel for xxxxxxx (setup.py): started
#10 ...

#22 [tests-celery-worker-minio-server create_data_directory 7/7] RUN --mount...
#22 11.63 Done
#22 16.03 Stopping the minio server.
#22 16.03 Exiting on signal: TERMINATED
#22 16.55 Minio server exited cleanly.
#22 ...

#10 [tests-celery-worker stage-0 2/4] RUN --mount=src=tests/requirements.txt...
#10 17.58   Building wheel for xxxxx (setup.py): finished with status 'done'
#10 17.58   Created wheel for xxxxxx: filename=xxxxxxx-2.8.5-cp37-cp37m-linux_x86_64.whl size=467626 sha256=a40a26dd53961fc3e820dce4219f808fc1c643f160437eb869f4031d1d070716
#10 17.58   Stored in directory: /root/.cache/pip/wheels/fb/85/a8/57f24b92b9554880384d00a84881c0ea80cbcee02d6dcede54
#10 17.62   Building wheel for xxxxx (setup.py): started
#10 ...

#22 [tests-celery-worker-minio-server create_data_directory 7/7] RUN --mount...
#22 DONE 17.9s

#10 [tests-celery-worker stage-0 2/4] RUN --mount=src=tests/requirements.txt...
#10 18.08   Building wheel for xxxxxx (setup.py): finished with status 'done'
#10 18.09   Created wheel for xxxxxxx: filename=xxxxxx-6.0.4-cp37-cp37m-linux_x86_64.whl size=428923 sha256=902ff8186359c0a6225831240e8ae38c4bc419809c65f86b16420c3634cd4042
#10 18.09   Stored in directory: /root/.cache/pip/wheels/93/84/2f/409c7b2bb3afc3aa727f7ee8787975e0793f74d1165f4d0104
#10 18.12   Building wheel for xxxxxxx (setup.py): started
#10 18.35   Building wheel for xxxxxx (setup.py): finished with status 'done'
#10 18.35   Created wheel for xxxxxx: filename=xxxxxx-0.5.1-cp37-none-any.whl size=17901 sha256=5b30d1ce5137b6b5146eb5f5c1f140199b5a885d964767d1ce01cef0eaa764cb
#10 18.35   Stored in directory: /root/.cache/pip/wheels/69/86/6c/f8b8593bc273ec4b0c653d3827f7482bb2001a2781a73b7f44
#10 18.36   Building wheel for xxxxxxxxx (setup.py): started
#10 18.61   Building wheel for xxxxxxxx (setup.py): finished with status 'done'
#10 18.61   Created wheel for xxxxxxx: filename=xxxxxxxx-1.51.0-cp37-none-any.whl size=77593 sha256=5e2ac2fd5cef0ac972a1f9437b6bba9b8884622e91488e0b87297b0316c78982
#10 18.61   Stored in directory: /root/.cache/pip/wheels/2c/f9/7f/6eb87e636072bf467e25348bbeb96849333e6a080dca78f706
#10 18.63 Successfully built xxxxx xxxxxx xxxxxx  xxxxx
#10 18.92 Installing collected packages: xxxxx, xxxxxx, xxxxx, xxxxxxx, xxxxx, xxxxx, xxxx
#10 22.66 Successfully installed xxxxxxx, xxxxx, xxxxx, xxxxx, xxxx, xxxx, xxxxx, xxxxx, xxxx, xxxx
#10 22.92 WARNING: You are using pip version 19.2.1, however version 20.1.1 is available.
#10 22.92 You should consider upgrading via the 'pip install --upgrade pip' command.
#10 ...

#23 [tests-celery-worker-minio-server test_image 1/1] COPY --from=create_dat...
#23 DONE 2.3s

#10 [tests-celery-worker stage-0 2/4] RUN --mount=src=tests/requirements.txt...
#10 DONE 23.1s

#24 [tests-celery-worker-minio-server] exporting to image
#24 exporting layers
#24 ...

#11 [tests-celery-worker stage-0 3/4] COPY ./ ./
#11 DONE 0.1s
```

I see that the step number is available, next to the logs there is `#11` or `#24` for example. So there is an "order" available when running the graph, right?

Something like `--progress=order` would be very nice to have, especially for CI logs. It would behave like `--progress=plain` but would hold on to stdout and stderr until all previous steps have displayed their logs.  Some users might expect this to be in the TODO list of features parity with the old builder.

I understand that it would be challenging for existing builds, since logs can be huge and we don't want to hold on to logs that are too big. So maybe this should be opt-in. --progress=auto cannot choose the `order` mode when no tty is found for example.

Thanks for reading, and thanks again for this awesome piece of software!

**Comment by tonistiigi** [comment]
> Hi, maybe this issue would be a better fit for the buildkit repo.

I agree 

> I understand a best-effort is made here since everything is asynchronous.

That is the case. For example in your output, with no switches none of this would be shown as it would just be showing you the progress of `#10` while actually many other processes were started and finished at the same time.

The printing logic is already somewhat controllable with https://github.com/moby/buildkit/blob/7f4214f5b4b314ff3e4bfb3117556369974f75ad/util/progress/progressui/printer.go#L16-L19 . I don't think we have ever changed these constants. It is possible it is not ideal but we need better data (and possibly examples directly against the package, not just builds so that it is deterministic) to make changes. I also wouldn't mind to make these constants configurable with environment variables so it can be tweaked in runtime.

**Comment by gabrieldemarmiesse** [comment]
Closing in favor of https://github.com/moby/buildkit/issues/1507
