### ISSUE TITLE
Buildx vs Jenkins - no sync ntp

### ISSUE THREAD

**Issue by AlanTuring1988** [docker/buildx#303]
I am working on Jenkins to build the docker image for multi-platform, using the buildx module version **v0.4.1 bda4882a65349ca359216b135896bddc1d92461c**
 
Builds are unsuccessful. There is a disconnection of Jenkins client during the process of _unpacking_ of a large docker image (about 8GB). The dates between VM and Jenkins are correctly aligned but I suspect there are time synchronization issues with the buildx process.

I ask you if you have any suggestions, if there is the possibility of synchronizing the time...
 
The details of the VM used are shown below:

- Linux builder-jenkins-centos8 5.0.0-1036-azure # 38-Ubuntu SMP Sun 22 Mar 21:27:21 UTC 2020 x86_64 x86_64 x86_64 GNU / Linux

**Comment by AlanTuring1988** [comment]
a temporary solution adopted is to set a cron to synchronize the time from ntp every 5 minutes

**Comment by tonistiigi** [comment]
I don't understand this report. Buildx does not manage time on your system and if it deploys buildkit in a container it will not put it under a separate time namespace. Or are you saying you have a remote machine that builds is communicating with that has different time and this is causing you some issues?

**Comment by crazy-max** [comment]
Closing for housekeeping. Let us know if it still happens.
