### ISSUE TITLE
docker buildx within docker container

### ISSUE THREAD

**Issue by ryan-WORK** [docker/buildx#305]
Is it possible to run get docker buildx to run within a docker container?

I am running Jenkins from within a docker container and I would like to get docker buildx to run from the docker container that is also running Jenkins to build multi-arch images. 

I accomplished this outside of a docker container on a Raspberry Pi, but from within the docker container with shared volumes there is no `.docker`.

Do you possibly have any ideas about how I can do this from within a docker container?

**Comment by jer-k** [comment]
Not sure what base image you're using, but I'll explain what I did and hopefully that can help you. I'm using alpine linux base image and installing docker from there. That package doesn't currently have buildx available so I had to install the binary the the config to enable it.

```
FROM alpine
ARG USER=app_user
ENV HOME /home/$USER

RUN addgroup -S appgroup && adduser -S $USER -G appgroup

RUN apk --no-cache --update upgrade && apk add --no-cache --update docker

# Create the .docker directory under /home/app_user/.docker
RUN mkdir -p $HOME/.docker/cli-plugins
COPY buildx/buildx-v0.4.0.linux-amd64 $HOME/.docker/cli-plugins/docker-buildx
COPY buildx/config.json $HOME/.docker/
RUN chown -R $USER:appgroup $HOME/.docker
RUN chmod -R 755 $HOME/.docker
```

This is set up with a `docker-compose` and using the `dind` image (I can post that too if need be).

Hopefully that leads you in the right direction.

**Comment by Xplouder** [comment]
I was wondering the same "why the oficial docker container does not have buildx?" and I couldn't find documentation for it.

Nonetheless here is my version:
```
# syntax=docker/dockerfile:experimental

FROM docker:19.03.13

# ensure all builds runs with Buildkit
ENV DOCKER_BUILDKIT=1
# enable full log of Buildkit builds
ENV BUILDKIT_PROGRESS=plain
# enable Buildx integration with docker
ENV DOCKER_CLI_EXPERIMENTAL=enabled

ARG BUILDX_URL=https://github.com/docker/buildx/releases/download/v0.4.2/buildx-v0.4.2.linux-amd64

RUN mkdir -p $HOME/.docker/cli-plugins && \
    wget -O $HOME/.docker/cli-plugins/docker-buildx $BUILDX_URL && \
    chmod a+x $HOME/.docker/cli-plugins/docker-buildx
```

**Comment by FernandoMiguel** [comment]
that's correct Docker in Docker (DinD) does not come bundled with plugins.
you need to install it

**Comment by Xplouder** [comment]
@FernandoMiguel Neither the image with just Docker.

**Comment by viceice** [comment]
Which path's do i need to mount into build container?

I've tried only my workspace and the docker socket, but it can't connect to the buildkit daemon.

**Comment by crazy-max** [comment]
See https://github.com/docker-library/docker/issues/243. You can use [this image](https://github.com/crazy-max/docker-docker) which contains buildx and buildkit if you want.

**Comment by oneslideicywater** [comment]
run this command to use docker buildx
```bash
$ docker run --name test --rm -it  -v /var/run/docker.sock:/var/run/docker.sock -v /usr/bin/docker:/usr/bin/docker -v /usr/libexec/docker:/usr/libexec/docker  -v /root:/root centos:7  /bin/bash
$ docker buildx ls
```

**Comment by benmoss** [comment]
@oneslideicywater the reason that works is you're mounting in your docker binaries from your host. People are looking for an image where buildx is already installed

**Comment by a-a-k** [comment]
is there any appeared here in 2023?

**Comment by viceice** [comment]
> is there any appeared here in 2023?

works for me as expected

**Comment by Nasller** [comment]
In WSL2
`-v /mnt/wsl/docker-desktop/cli-tools/usr/local/lib/docker:/usr/local/lib/docker`
add this to your docker run, `/mnt/wsl/docker-desktop/cli-tools/usr/local/lib/docker` this path can find in your wsl linux system, such as unbuntu20.04, `cd /usr/local/lib/docker` in this path then `ll` your can find the path
![Image](https://github.com/user-attachments/assets/de336e2c-50dc-44d8-8ae2-c6b6624e8a93)

**Comment by viceice** [comment]
> In WSL2 `-v /mnt/wsl/docker-desktop/cli-tools/usr/local/lib/docker:/usr/local/lib/docker` add this to your docker run, `/mnt/wsl/docker-desktop/cli-tools/usr/local/lib/docker` this path can find in your wsl linux system, such as unbuntu20.04, `cd /usr/local/lib/docker` in this path then `ll` your can find the path ![Image](https://github.com/user-attachments/assets/de336e2c-50dc-44d8-8ae2-c6b6624e8a93) then docker buildx version is success in docker container ![Image](https://github.com/user-attachments/assets/66649425-f3b7-447d-8c4c-2c1a283af8af)

I don't need this, it works by design
```sh
> docker buildx version
github.com/docker/buildx v0.18.0-desktop.2 44b68677dee147502ef0be4cbead34310e44d1f6
```

**Comment by Nasller** [comment]
> > In WSL2 `-v /mnt/wsl/docker-desktop/cli-tools/usr/local/lib/docker:/usr/local/lib/docker` add this to your docker run, `/mnt/wsl/docker-desktop/cli-tools/usr/local/lib/docker` this path can find in your wsl linux system, such as unbuntu20.04, `cd /usr/local/lib/docker` in this path then `ll` your can find the path ![Image](https://github.com/user-attachments/assets/de336e2c-50dc-44d8-8ae2-c6b6624e8a93) then docker buildx version is success in docker container ![Image](https://private-user-images.githubusercontent.com/26132153/392672984-66649425-f3b7-447d-8c4c-2c1a283af8af.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzMzOTAxNjMsIm5iZiI6MTczMzM4OTg2MywicGF0aCI6Ii8yNjEzMjE1My8zOTI2NzI5ODQtNjY2NDk0MjUtZjNiNy00NDdkLThjNGMtMmMxYTI4M2FmOGFmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMDUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjA1VDA5MTEwM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTE2OTlkMGZhN2I5MDIyYWEzMmE1YzdiMmQzY2FlYTg4NTU5YTAxM2ZhYzRjYjQ1ZGQ4MzQ1OWM4YjUxZmM3OWEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.NP-mlX0OfZXl8rsThp8b2d6aLYCazQZFQdzJC9DdMAI)
> 
> I don't need this, it works by design
> 
> > docker buildx version
> github.com/docker/buildx v0.18.0-desktop.2 44b68677dee147502ef0be4cbead34310e44d1f6

Yes sir, this is just one case I've encountered in docker desktop and doesn't work for everyone
