### ISSUE TITLE
how to create builder using custom buildkit image?

### ISSUE THREAD

**Issue by errordeveloper** [docker/buildx#307]
I am trying to troubleshoot #300, and have built buildkit locally with some custom debug logs. I cannot see a way of passing my custom image to `buildx create`, it would be nice if this could be documented.

**Comment by tonistiigi** [comment]
`--driver-opt image=name`

**Comment by errordeveloper** [comment]
Are these options documented somewhere?

**Comment by tonistiigi** [comment]
https://github.com/docker/buildx#--driver-opt-options

**Comment by errordeveloper** [comment]
Thanks a lot!
