### ISSUE TITLE
Building docker images for Raspberry Pi 3b and 4b

### ISSUE THREAD

**Issue by DhruvM1994** [docker/buildx#309]
I am trying to build docker images for the Raspberry Pi 3b and 4b on a Windows machine (x64) using the buildx tool. I have installed Ubuntu 18.04 (64bit) on both devices.
For building the images I am using the following command:
```docker buildx build --platform linux/arm64 -t <tag> <location_dockerfile>```

The application consists of nodejs images and a Python image.
Whereas the Python image runs, the nodejs images are crashing.

To verify the components in general, I built the same images directly on the Raspberry Pi.
In that case the nodejs and the Python images are running.

Are there certain configurations that I need to make, in order to build all images for the Raspberry Pi on the Windows machine?

Base images:
 - node:lts-alpine3.9
 - python:3.7.7-alpine3.11

**Comment by benchonaut** [comment]
* install buildx command 
* command example ( add `--push --output type=registry`  and` -t yourdockerhubuser/yourdocekerrepo:yourdockertags` to push do dockerhub) : 
`time docker buildx build --progress plain --network=host --memory-swap -1 --memory 1024 --platform=linux/amd64 --network=host --memory-swap -1 --memory 1024 -f Dockerfile .`

**Comment by technimad** [comment]
I'm experiencing a similar issue (also see https://github.com/rust-lang/cargo/issues/7451). 

I try to build a for linux/arm/v7 on macOS using buildx. This image contains rust code and the rust build fails for arm/v7. If I build the same Dockerfiles on the raspberry, the build always succeeds, so there is no issue with the architecture in the base images.

**Comment by R4V3NN0** [comment]
Have you tried to use a non alpine image? I had some problem with them, while cross-compiling or do you have a more specific error log?

**Comment by DhruvM1994** [comment]
After initially building directly on the Raspberry Pi, subsequent builds were possibile using buildx so far.

**Comment by crazy-max** [comment]
You can test with QEMU from https://github.com/tonistiigi/binfmt that is made for running containers:

```
$ docker run -it --rm tonistiigi/binfmt:latest --version
binfmt/8703596 qemu/v6.0.0 go/1.16.5
```
