### ISSUE TITLE
bake with multiple outputs

### ISSUE THREAD

**Issue by errordeveloper** [docker/buildx#316]
The manifest currently has `Outputs` as a a slice:

https://github.com/docker/buildx/blob/f3111bcbef8ce7e3933711358419fa18294b3daf/bake/bake.go#L350

However, trying to set multiple outputs results in an error:

```
multiple outputs currently unsupported
```

https://github.com/docker/buildx/blob/6db68d029599c6710a32aa7adcba8e5a344795a7/build/build.go#L356

The message suggests that this may be implemented in the future, but I couldn't find an existing issue so opening one.

My use-case would be to use something like this:

```
      "output": [
        "type=image,push=true",
        "type=docker,dest=image.oci"
      ]
```

I'd like to push to a registry and store a tarball as CI artefact as well.

**Comment by tonistiigi** [comment]
moved to https://github.com/moby/buildkit/issues/1555

**Comment by errordeveloper** [comment]
@tonistiigi thanks!
