### ISSUE TITLE
Build failed when using a previous built image which built by buildx

### ISSUE THREAD

**Issue by Jingzhao123** [docker/buildx#318]
Hi, I am trying to build multi-arch images with buildx tool. But I encounter some issues about it. Could you help me with it?

### Problems:
The building process can not refer to a previous build image which was built by buildx.
I write some scripts for the whole building process. 

- Firstly, it will create a build instance:
```
docker run --rm --privileged multiarch/qemu-user-static --reset -p yes
docker buildx rm  multi-builder | true
docker buildx create --use --name multi-builder --platform linux/arm64,linux/amd64
```

- Secondly, it will build base images and export them:
```
docker buildx build -o type=docker --platform linux/amd64 -f Dockerfile.base -t ubuntuwithvim:latest .
docker buildx build -o type=docker --platform linux/arm64 -f Dockerfile.base -t ubuntuwithvim:latest-arm64 .
```
The Dockerfile has been attached in the final issue. Please check it.

- Thirdly, build the final image based on previous export image:

```
echo "Start to build derived images==============================================="
docker buildx build -f Dockerfile.make -t ubuntuwithmake .
```
The ubuntuwithmake image based on the previous ubuntuwithvim:latest image. But it builds failed. There are some error information just like that:
```
Start to build derived images===============================================
WARN[0000] No output specified for docker-container driver. Build result will only remain in the build cache. To push result image into registry use --push or to load image into docker use --load
[+] Building 0.4s (4/5)
 => [internal] load build definition from Dockerfile.make                                                                                                                                             0.0s
 => => transferring dockerfile: 86B                                                                                                                                                                   0.0s
 => [internal] load .dockerignore                                                                                                                                                                     0.0s
 => => transferring context: 2B                                                                                                                                                                       0.0s
 => ERROR [internal] load metadata for docker.io/library/ubuntuwithvim:latest                                                                                                                         0.2s
 => ERROR [1/2] FROM docker.io/library/ubuntuwithvim:latest                                                                                                                                           0.2s
 => => resolve docker.io/library/ubuntuwithvim:latest                                                                                                                                                 0.2s
------
 > [internal] load metadata for docker.io/library/ubuntuwithvim:latest:
------
------
 > [1/2] FROM docker.io/library/ubuntuwithvim:latest:
------
failed to solve: rpc error: code = Unknown desc = failed to load cache key: pull access denied, repository does not exist or may require authorization: server message: insufficient_scope: authorization failed
```

**Is there some wrong with my steps?**

Dockerfile.base:
```
FROM ubuntu:18.04
RUN apt update
RUN apt install -y vim
```

Dockerfile.make:
```
FROM ubuntuwithvim
RUN apt install -y make
```

**Comment by tonistiigi** [comment]
The container driver can't access the images only in the `docker images` of a local docker daemon. Need to use docker driver, a registry or join the dockerfiles together so you can access another stage instead of external image.

**Comment by jusjusjus** [comment]
> The container driver can't access the images only in the `docker images` of a local docker daemon. Need to use docker driver, a registry or join the dockerfiles together so you can access another stage instead of external image.

Sorry, i found this answer a bit cryptic.  In the first sentence, is it _can't_ or _can_?  My preferred solution would be to _use docker driver_, and build stuff locally.   However, this is already done in the original question, and I'm not sure how else I'd approach this:
```
docker buildx create --use --name multi-builder --platform linux/arm64,linux/amd64
```

**Comment by larsqa** [comment]
This might be related to #59.

`--load`, the default flag in `docker buildx build ...`, stores images locally. However, multi-platform builds are only supported using remote repositories.
Using `--push` instead, the images are automatically pushed to a remote repository.
