### ISSUE TITLE
Cannot create armv6l image

### ISSUE THREAD

**Issue by andpc** [docker/buildx#329]
Dear all, 

I'm having problems working with armv6l images.

I'm being able to create them, however, when I access and try to check its arch it always returns armv7l, never the sixth version, as expected.

I'm building the simplest image as possible 

```
FROM debian:buster AS builder 
RUN apt update
WORKDIR /home
CMD ["/bin/bash"]
```

The command used to build the images is:

```
docker buildx build --platform linux/arm/v6,linux/arm/v7,linux/arm64 -t my/tag . --push 
```

The return of the command **docker buildx ls** shows me that I have the target arch in my system.

![image](https://user-images.githubusercontent.com/68664326/88230029-1299c380-cc48-11ea-879f-c88b93b0e134.png)

Also, when I check on my Docker Hub, different images are created for armv6l and armv7l

![image](https://user-images.githubusercontent.com/68664326/88230150-3c52ea80-cc48-11ea-9f95-c61b0c266efc.png)

Am I missing anything here? Is it possible to create the armv6l image?

Thank you all in advance.

**Comment by tonistiigi** [comment]
> I'm being able to create them, however, when I access and try to check its arch it always returns armv7l, never the sixth version, as expected.

How do you check the arch? Note that for emulation there is only one arm emulator in qemu so calling `uname -a` under arm emulation always shows the same value.

**Comment by andpc** [comment]
> > I'm being able to create them, however, when I access and try to check its arch it always returns armv7l, never the sixth version, as expected.
> 
> How do you check the arch? Note that for emulation there is only one arm emulator in qemu so calling `uname -a` under arm emulation always shows the same value.

I check it by `uname -a` and also trying to run the generated binary in the Raspberry Pi Zero W, which is armv6l. 

Even when I create the image only with armv6l, it always returns the armv7l

**Comment by tonistiigi** [comment]
`uname -a` does not show the platform of your image/binary but of your system. And as I said under emulation, arm always shows `v7`. Same as with arm64, this will show `aarch` while you can also run/build v7/v6 binaries. If you want to check the format of a binary, use `file`.
