### ISSUE TITLE
[internal] booting buildkit: exit code 1 with no error message

### ISSUE THREAD

**Issue by howardjohn** [docker/buildx#331]
Occasionally (~1% of the time), we are seeing failures in buildkit with not useful error message.

```
DOCKER_CLI_EXPERIMENTAL=enabled docker buildx bake -f /home/prow/go/src/istio.io/istio/out/linux_amd64/dockerx_build/docker-bake.hcl default
#1 [internal] booting buildkit
#1 pulling image moby/buildkit:buildx-stable-1
#1 pulling image moby/buildkit:buildx-stable-1 30.2s done
#1 creating container buildx_buildkit_container-builder0
#1 creating container buildx_buildkit_container-builder0 5.3s done
#1 ERROR: exit code 1
------
 > [internal] booting buildkit:
------
exit code 1
```

My expectation would be that there is either a useful error message, or things don't fail.

Docker version: 19.03.8

Two examples from our CI logs (above is copied from there):
https://prow.istio.io/view/gs/istio-prow/logs/integ-k8s-117_istio_postsubmit/1524
https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/25778/integ-ipv6-k8s-tests_istio/2978

**Comment by tonistiigi** [comment]
`docker logs buildx_buildkit_container-builder0` should have the logs for the failure.

**Comment by howardjohn** [comment]
Thanks for that command! If the timeout is only 2.2s seems pretty plausible the root cause, we often get massive throttling in our CI for short periods of time, so the timeout increase will be helpful. Thanks!

**Comment by pkpfr** [comment]
https://github.com/docker/buildx/pull/332 increases the timeout to 14.4 seconds, but it is still inadequate.  Running build inside a container inside dockerized Jenkins this timeout frequently gets hit.
