### ISSUE TITLE
Impact of docker CLI plugin depreciation?

### ISSUE THREAD

**Issue by AkihiroSuda** [docker/buildx#334]
I saw the docker CLI plugin is being deprecated :cry: https://github.com/docker/cli/commit/459c6082f87750d45c84cd9454f3fa4b6c5580d9

What's the future of buildx? Will it be a part of docker CLI? Or will it be a standalone tool?

**Comment by tonistiigi** [comment]
Nothing will change for buildx afaik

**Comment by AkihiroSuda** [comment]
So it will continue to work as `buildx` binary, but `docker buildx` command will be unavailable eventually?

**Comment by tonistiigi** [comment]
Both will work, or at least no plans to break either atm.
