### ISSUE TITLE
Problems to resolve addresses

### ISSUE THREAD

**Issue by d-lareg** [docker/buildx#335]
I try to build an arm64 container on my x86 linux machine which is part of our company network. I already set up the systemwide proxy and DNS settings and also the docker settings. Building the test container without buildx works fine. 

I Get the following messages...

```
...
Err:1 http://ports.ubuntu.com/ubuntu-ports bionic InRelease
Could not resolve 'ports.ubuntu.com'
Err:2 http://ports.ubuntu.com/ubuntu-ports bionic-updates InRelease
 Could not resolve 'ports.ubuntu.com'
Err:3 http://ports.ubuntu.com/ubuntu-ports bionic-backports InRelease
Could not resolve 'ports.ubuntu.com'
Err:4 http://ports.ubuntu.com/ubuntu-ports bionic-security InRelease
Could not resolve 'ports.ubuntu.com'
...
```

Since the DNS doesn't work properly with buildx, I guess there are some network settings still to make. But I am not sure.

**Dockerfile**
```
FROM ubuntu:18.04
RUN cat /etc/resolv.conf
RUN apt update
``` 

The settings of resolv.conf are identical no matter if I use buildx or not. 

**Configuration**
Docker: 19.03.12, build 48a66213fe
Buildx: github.com/docker/buildx v0.4.1 bda4882a65349ca359216b135896bddc1d92461c

**How I set up the builder**
`docker buildx create --driver-opt env.http_proxy=$http_proxy --driver-opt env.https_proxy=$https_proxy --buildkitd-flags '--allow-insecure-entitlement network.host' --name armbuilder`

That made it at least possible to fetch the base base image.

**Build command**
```
 docker buildx build --no-cache --progress plain --platform linux/arm64 -t vision_build_arm:latest .
```

**Can I build the container for x86 without buildx?**
Yes.

How do I have to configure the buildx plugin to run properly?

**Comment by tonistiigi** [comment]
I guess you are missing `--driver-opt network=host`. `allow-insecure-entitlement` is only needed if you want to use `RUN --network=host` in Dockerfiles. If you just want to switch the whole builder to only host mode then this is not needed.

**Comment by d-lareg** [comment]
I don't really need the flag. I was only wondering if it makes any difference if I use the default or the host network adapter. Unfortunately, it doesn't.

`RUN cat /etc/resolv.conf` shows the same output for buildx and the default build. I don't understand the different behavior.

How do both build types differ in terms of using the network adapter?

**Comment by Alien2150** [comment]
@tonistiigi That flag helped me in my case. Thanks ❤️
