### ISSUE TITLE
Push cache to insecure registry

### ISSUE THREAD

**Issue by extraleo** [docker/buildx#339]
How to push cache to an insecure registry? I have already added it to my docker config and can log in successfully by `docker login`.
This is my docker command:
```
docker buildx build --cache-to=type=registry,ref=my-insecure-repo/lib/test:0730 \
    --output=type=image,push=true \
    -t test:0730 -f ut.dockerfile .
```
and get error msg:
```
#12 ERROR: server message: insufficient_scope: authorization failed
------
 > exporting to image:
------
failed to solve: rpc error: code = Unknown desc = server message: insufficient_scope: authorization failed
```
I tried to add ` --output=type=image,push=true,registry.insecure=true` but same error. Also tried add ` --allow security.insecure` but get: `failed to solve: rpc error: code = Unknown desc = granting entitlement security.insecure is not allowed by build daemon configuration`

Docker version: Docker version 19.03.8, build afacb8b

Thank you all in advance.

**Comment by tonistiigi** [comment]
this regression has been fixed with https://github.com/moby/buildkit/pull/1601 (buildkit master). Meanwhile use `buildx create --config` to pass buildkit config https://github.com/moby/buildkit/blob/master/docs/buildkitd.toml.md for your insecure registries.

**Comment by sergeykad** [comment]
I am getting the same error running `docker build . --allow security.insecure` with buildx installed. I am trying to pull an image from an insecure registry.

Docker version 20.10.7, build f0df350

**Comment by crazy-max** [comment]
@sergeykad https://github.com/docker/buildx/issues/559#issuecomment-796430825
