### ISSUE TITLE
create new builder error -  mybuilder20 unix:///var/run/docker.sock inactive

### ISSUE THREAD

**Issue by hm400** [docker/buildx#346]
`docker buildx create --name mybuilder2` produces inactive socket error.
Docker daemon is active and able to run images without issue.
```
user@laptop:~$ docker buildx ls
NAME/NODE    DRIVER/ENDPOINT       STATUS PLATFORMS
mybuilder2    docker-container                     
mybuilder20 unix:///var/run/docker.sock inactive
```

`docker buildx create --name mybuilder node-amd64` produces a connection/dns error.
My network connection is up and able to resolve domain names via DNS.
```
user@laptop:~$ docker buildx ls
NAME/NODE    DRIVER/ENDPOINT       STATUS PLATFORMS
mybuilder    docker-container             
mybuilder0 tcp://node-amd64:2375 error during connect: Get http://node-amd64:2375/v1.24/containers
/buildx_buildkit_mybuilder0/json: dial tcp: lookup node-amd64 on 127.0.0.53:53: server misbehaving
```
```
Client: Docker Engine - Community
 Version:           19.03.12
 API version:       1.40
 Go version:        go1.13.10
 Git commit:        48a66213fe
 Built:             Mon Jun 22 15:45:36 2020
 OS/Arch:           linux/amd64
 Experimental:      true
```
Thank you in advance for any help.

**Comment by tonistiigi** [comment]
What is `node-amd64` in your case? Do you actually have a insecure tcp endpoint configured under that name in `http://node-amd64:2375` . From the error your dns server at `127.0.0.53:53` does not seem to think so.

**Comment by hm400** [comment]
Thank you, I deleted the node-amd64 builder, ran this command and it worked.
`docker buildx build -t user/repo --platform=linux/arm,linux/arm64,linux/amd64 . --push`
