### ISSUE TITLE
"Dockerfile parse error line 18: Unknown flag: mount" with platform=linux/s390x and Docker 19.03 on Ubuntu

### ISSUE THREAD

**Issue by skriesch** [docker/buildx#348]
I wanted to install BuildX on my Ubuntu to emulate s390x. I am using Docker 19.03. Therefore, I followed your guidelines:

```

 export DOCKER_BUILDKIT=1
 docker build --platform=local -o . git://github.com/docker/buildx

```

I have used ` --platform=linux/s390x` instead of ` --platform=local`. That had the following error result:
```
Sending build context to Docker daemon  47.98MB
Error response from daemon: Dockerfile parse error line 18: Unknown flag: mount
```

The other installation workflow with cloning the whole repository and the installation from there is a nice workaround.

**Comment by tonistiigi** [comment]
output of `docker version`?

**Comment by skriesch** [comment]
```
 #docker version
Client:
 Version:           19.03.6
 API version:       1.40
 Go version:        go1.12.17
 Git commit:        369ce74a3c
 Built:             Fri Feb 28 23:45:43 2020
 OS/Arch:           linux/amd64
 Experimental:      false

Server:
 Engine:
  Version:          19.03.6
  API version:      1.40 (minimum version 1.12)
  Go version:       go1.12.17
  Git commit:       369ce74a3c
  Built:            Wed Feb 19 01:06:16 2020
  OS/Arch:          linux/amd64
  Experimental:     true
 containerd:
  Version:          1.3.3-0ubuntu1~18.04.2
  GitCommit:        
 runc:
  Version:          spec: 1.0.1-dev
  GitCommit:        
 docker-init:
  Version:          0.18.0
  GitCommit:        

```

**Comment by tonistiigi** [comment]
You're not building with BuildKit (nor buildx). I don't know where the `DOCKER_BUILDKIT=1` gets lost in your system.

**Comment by skorokithakis** [comment]
Looks like this happens anyway, though: https://github.com/docker/distribution/issues/3272

**Comment by skorokithakis** [comment]
Turns out you need to add `# syntax = docker/dockerfile:experimental` to the top of your Dockerfile.

**Comment by crazy-max** [comment]
https://github.com/moby/buildkit/blob/master/frontend/dockerfile/docs/syntax.md

**Comment by tzachs** [comment]
Adding `# syntax=docker/dockerfile:1.2` in the Dockerfile and `DOCKER_BUILDKIT=1 docker build` worked for me.
