### ISSUE TITLE
How to enable buildx when using DinD?

### ISSUE THREAD

**Issue by rolandjitsu** [docker/buildx#349]
I'm trying to implement a CI pipeline using [Docker in Docker](https://docs.gitlab.com/ee/ci/docker/using_docker_build.html) on Gitlab. And so far it seem to work, but I was wondering if there's a way to enable the buildx command for the child docker containers.

I can run `docker buildx` on the host, but the child docker containers don't seem to have this.

Do I need to manually download the buildx binary? If I do, where should it actually go as there's no home dir to move it to? 

NOTE: I'm using the official [docker](https://hub.docker.com/_/docker) image.

**Comment by tonistiigi** [comment]
> If I do, where should it actually go as there's no home dir to move it to?

wdym? if you run the docker image as root then home dir is `/root`

**Comment by rolandjitsu** [comment]
@tonistiigi I'm not sure how Gitlab runs the image. But I'm going to try to download and install buildx into root and see if that works.

**Comment by maniator** [comment]
This is one of the reasons I created a fork of the official docker image with one that has buildx built in https://hub.docker.com/r/maniator/dind-buildx

**Comment by rafagsiqueira** [comment]
If someone took the Dockerfile path, this should suffice:
COPY --from=docker/buildx-bin:latest /buildx /usr/libexec/docker/cli-plugins/docker-buildx
