### ISSUE TITLE
Different base images for different platforms

### ISSUE THREAD

**Issue by githubsaturn** [docker/buildx#362]
More broadly, is it possible to use different Dockerfiles for different platforms? Something like:

* Use `armv7.Dockerfile` for armv7
* Use `amd64.Dockerfile` for amd64

This is needed as not all base images have proper multiarch manifest.

**Comment by tonistiigi** [comment]
You can combine your dockerfiles with:

**Comment by tonistiigi** [comment]
You can combine your dockerfiles with:

```
from a as target-amd64
...

from b as target-armv7
...

from target-$TARGETOS$TARGETARCH
```
