### ISSUE TITLE
A few multi-node builder questions

### ISSUE THREAD

**Issue by boredazfcuk** [docker/buildx#366]
Hi,

I was just wondering if someone could answer a some questions for me regarding a multi-node, multi-arch builder I've created.

So my builder looks like this:
```
NAME/NODE    DRIVER/ENDPOINT             STATUS  PLATFORMS
mybuilder *  docker-container
  mybuilder0 unix:///var/run/docker.sock running linux/amd64, linux/arm64, linux/riscv64, linux/ppc64le, linux/s390x, linux/386, linux/arm/v7, linux/arm/v6
  mybuilder1 tcp://remotenode:2375           running linux/amd64, linux/arm64, linux/riscv64, linux/ppc64le, linux/s390x, linux/386, linux/arm/v7, linux/arm/v6
default      docker
  default    default                     running linux/amd64, linux/arm64, linux/riscv64, linux/ppc64le, linux/s390x, linux/386, linux/arm/v7, linux/arm/v6
```
I kicked off a build of a container with:
```
docker buildx build . --platform linux/amd64,linux/arm64,linux/arm/v7,linux/ppc64le,linux/386,linux/arm/v6 --tag "boredazfcuk/${image_name}"
```
...so far, I'm 12 hours into the build and it looks like it might just be coming to a close. However, I've been monitoring the remote node and nothing is happening on it. My local node has been showing 100% CPU utilisation from the start, but the remote node is pretty much 0%.

I was hoping that when I kicked off the build, it would see that it has 6 platforms to build for, 2 nodes that can accomplish that, and then split the jobs accordingly, effectively halving the build time. Is that not how it works? Must a multi-platform build be run on a single host?

To split the jobs, would I have to manually limit my 1st node to just amd64/386 and limit my 2nd node to the arm/ppc jobs?

Also, when I first added my remote node to the builder, I had TLS enabled on the remote host. The local host threw an error about sending HTTP requests to an HTTPS port. Is it not possible for buildx to use TLS, or do I need to copy the certificates locally and add them to the config somewhere?

Edit: Oh and other quick one, if I add a native ARM64 builder, would I have to remove support for ARM on my local machine, or could I set some sort of priority to say use node-arm64 if it's available, otherwise, local machine? Or a schedule to use it overnight (so when it's not in use).

**Comment by tonistiigi** [comment]
>  it would see that it has 6 platforms to build for, 2 nodes that can accomplish that, and then split the jobs accordingly,

Current multi-node support only works for splitting different platforms between nodes. If your first node is preferred for all the platforms you are building only it will be used. (Exception is kubernetes driver that does deterministic round robin but still same logic for splitting the build).

> To split the jobs, would I have to manually limit my 1st node to just amd64/386 and limit my 2nd node to the arm/ppc jobs?

yes (more later)

> Is it not possible for buildx to use TLS, or do I need to copy the certificates locally and add them to the config somewhere?

You should set up a context with `docker context` command. That allows many configurations options for endpoints. Then create builder instance/node with that context as an endpoint.

> Oh and other quick one, if I add a native ARM64 builder, would I have to remove support for ARM on my local machine, or could I set some sort of priority to say use node-arm64 if it's available

When adding a node with `buildx create` you can set manual platforms with `--platform` for that node. Manually set platforms are preferred over the automatically detected ones.

**Comment by boredazfcuk** [comment]
Perfect. Thanks for taking the time to explain this for me.
