### ISSUE TITLE
WORKDIR command fails on Windows images

### ISSUE THREAD

**Issue by claudiubelu** [docker/buildx#378]
Sample ``Dockerfile``:

    ARG BASEIMAGE
    FROM $BASEIMAGE

    WORKDIR "C:\Users"

    ENTRYPOINT ["cmd.exe", "/s", "/c"]

Command: ``docker buildx build --no-cache --pull --output=type=registry --platform windows/amd64 --build-arg BASEIMAGE=mcr.microsoft.com/windows/nanoserver:1809 -t claudiubelu/workdir-sample:1.0  .``

Fails with the following message:

    [+] Building 0.3s (5/5) FINISHED
     => [internal] load .dockerignore                                                                             0.1s
     => => transferring context: 2B                                                                               0.0s
     => [internal] load build definition from Dockerfile_windows                                                  0.1s
     => => transferring dockerfile: 721B                                                                          0.0s
     => [internal] load metadata for mcr.microsoft.com/windows/nanoserver:1809                                    0.1s
     => CACHED [1/2] FROM mcr.microsoft.com/windows/nanoserver:1809@sha256:4e2935a71de933e3576f7053d75eb3fadc3a9  0.0s
     => => resolve mcr.microsoft.com/windows/nanoserver:1809@sha256:4e2935a71de933e3576f7053d75eb3fadc3a929a1e7a  0.0s
     => ERROR [2/2] WORKDIR C:\Users                                                                              0.1s
    ------
     > [2/2] WORKDIR C:\Users:
    ------
    failed to solve: rpc error: code = Unknown desc = open /tmp/buildkit-mount549039607/etc/passwd: no such file or directory

docker buildx version: github.com/docker/buildx v0.4.1-25-ge24e04b e24e04be572034efbcc9e20fcf720d6b10646487

**Comment by tonistiigi** [comment]
Workdir requires capability to run container (mkdir needs to be run for windows containers) that does not look to be supported on your platform.

**Comment by claudiubelu** [comment]
If all is needed is to run mkdir to create that folder, it shouldn't be necessary to run a command to create that folder.

For creating a folder, there are different solutions:

- create a folder locally, and add an ``ADD`` for that folder in the Dockerfile.
- multistage Dockerfile: in the 1st Linux stage you create the empty folder, and in the 2nd Windows stage, you just copy it from the 1st stage.

**Comment by tonistiigi** [comment]
You're right. The run case was actually fixed a long time ago (buildkit v0.5). So I guess this is somehow related to the windows path formatting.

**Comment by olsh** [comment]
I can confirm that the issue still exists in the 0.5.1 version
```
github.com/docker/buildx v0.5.1-docker 11057da37336192bfc57d81e02359ba7ba848e4a
```

Dockerfile
```
# syntax=docker/dockerfile:1
FROM mcr.microsoft.com/dotnet/aspnet:5.0
COPY / app/
WORKDIR app/
ENTRYPOINT ["dotnet", "CurlToCSharp.dll"]
```

Command
```
docker buildx build . --platform linux/amd64,windows/amd64
```

Output
```
------
 > [windows/amd64 3/3] WORKDIR app/:
------
Dockerfile:4
--------------------
   2 |     FROM mcr.microsoft.com/dotnet/aspnet:5.0
   3 |     COPY / app/
   4 | >>> WORKDIR app/
   5 |     ENTRYPOINT ["dotnet", "CurlToCSharp.dll"]
   6 |
--------------------
error: failed to solve: rpc error: code = Unknown desc = open /tmp/buildkit-mount073956988/etc/passwd: no such file or directory
```

**Comment by claudiubelu** [comment]
I've been investigating this a bit. Basically, ``WORKDIR`` is going to create a new directory, and it is going to chown that directory under the image's current ``USER``, which in the Windows' case, it might be ``ContainerUser`` or ``ContainerAdministrator``. However, to do that chown, it's trying to read the file ``/etc/passwd`` under the image to get the proper UID, but there's no such file for Windows, which results in that ``error: failed to solve: rpc error: code = Unknown desc = open /tmp/buildkit-mount073956988/etc/passwd: no such file or directory`` error. The error probably occurs here: [1]

There are a couple of workarounds for this though. For example, even if we just provide a blank ``/etc/passwd`` file, it works:

```
ARG BASEIMAGE

FROM --platform=linux/amd64 busybox as prep

RUN mkdir /folder &&\
    touch /etc-passwd

FROM $BASEIMAGE

COPY --from=prep /folder /workspace
COPY --from=prep /etc-passwd /etc/passwd

WORKDIR "/workspace"

ENTRYPOINT ["cmd.exe", "/s", "/c"]
```

Alternatively, we can simply run a ``USER`` command before ``WORKDIR``, which will also bypass the problem, even if that user is the same as what it's already set:

```
ARG BASEIMAGE
FROM $BASEIMAGE

USER ContainerUser
WORKDIR "/workspace"

ENTRYPOINT ["cmd.exe", "/s", "/c"]
```

I'm wondering if the existence of the ``/etc/passwd`` file is mandatory after all. From what I can see in [1], if a given user is not found in that file, it will be assumed that ``root`` is going to be the owner of that directory. So, if the ``/etc/passwd`` file is not found, I think we can make the same assumptions. This way, we can avoid the workarounds above. Plus, I don't think the file / folder ownership is not properly set in the Windows container images anyways:

```
# From a ``mcr.microsoft.com/windows/servercore:ltsc2019`` container:
C:\>busybox.exe stat Users\ContainerUser
  File: Users\ContainerUser
  Size: 0               Blocks: 0          IO Block: 4096   directory
Device: 0h/0d   Inode: 0           Links: 1
Access: (0775/drwxrwxr-x)  Uid: ( 1000/ContainerAdministrator)   Gid: ( 1000/ContainerAdministrator)
Access: 2021-06-06 04:31:22.000000000
Modify: 2021-06-06 04:31:22.000000000
Change: 2021-06-06 04:31:21.000000000
```

[1] https://github.com/moby/buildkit/blob/master/solver/llbsolver/file/user_linux.go#L47

**Comment by tonistiigi** [comment]
I agree that if `/etc/passwd` file is not found the behavior should be the same as if no user was found in that file.

**Comment by claudiubelu** [comment]
I've sent a fix for it here: https://github.com/moby/buildkit/pull/2249
