### ISSUE TITLE
Exporting the image: failed to solve: rpc error:: unexpected status: 401 Unauthorized

### ISSUE THREAD

**Issue by jchen706** [docker/buildx#386]
![image](https://user-images.githubusercontent.com/32785168/92525847-8f7dfe00-f1f2-11ea-9262-04c3b8d9308c.png)

I've been attempting to export the image and I am logged in. Always get into this error. Need some help.

the command line i ran is 

sudo docker buildx build --platform linux/arm/v7 -t jchen777/odm_t . --push and i also ran into this warning: 
WARN[0000] invalid non-bool value for BUILDX_NO_DEFAULT_LOAD: docker

**Comment by tonistiigi** [comment]
Default config for containerd pusher did not work properly for long pushes where token expired. This has been fixed in https://github.com/moby/buildkit/pull/1636 . Switch your buildx to moby/buildkit:master image and try again.

**Comment by noahmatisoff** [comment]
I'm also seeing this issue, after doing a `docker buildx create --use --name multi-arch --driver-opt image=moby/buildkit:master`. Any ideas @tonistiigi?

**Comment by codebling** [comment]
This error went away when I added the `--tag` option

**Comment by crazy-max** [comment]
Should be fixed with latest buildkit
