### ISSUE TITLE
buildx painfully slow compared to normal build

### ISSUE THREAD

**Issue by bfrog** [docker/buildx#387]
docker build ~ 10min
docker buildx build --platform linux/amd64  ~1hr

Is there a way to check if its using qemu for linux/amd64 as well? Is this a known issue? I'm running on a x86_64 machine so I wouldn't expect --platform linux/amd64 to take any longer than docker build would

**Comment by AkihiroSuda** [comment]
Please provide a full reproducer?

**Comment by peitalin** [comment]
![image](https://user-images.githubusercontent.com/4037878/142729327-b254a0a0-ffe2-4faf-824a-50c5dd219b6e.png)

2500 seconds and counting on a image that usually takes ~400 seconds FYI

**Comment by akhtarusafzai** [comment]
hi @teburd, @peitalin do you got succeeeded in tuning the time consumption issues. 
I am building a .net 6 based application with openapigenerator tool using buildx for amd64 on arm architecture. The buidl take more then 1.5 hour.

**Comment by protoblade** [comment]
I am having the reverse version of the problem buildx on github runner (eg ubuntu with amd64 building for arm arch) and time jumps from about 1 min for building to 10 on buildx
