### ISSUE TITLE
[Question] Which sources does `--cache-to` and `--cache-from` cache for?

### ISSUE THREAD

**Issue by morlay** [docker/buildx#399]
**dockerx version**: 0.4.2

I expect to cache `/go/pkg/mod` in github workflow cross multi builds.

some dockerfile like above:
```Dockerfile
# syntax = docker/dockerfile:experimental

FROM golang:1.15 as builder

WORKDIR /go/src

# for trigger rebuild
ENV COMMIT_SHA=xxx 

RUN --mount=type=cache,sharing=locked,id=gomod,target=/go/pkg/mod go build

FROM busybox

COPY --from=builder /go/bin/app /go/bin/app
```

Then run script to build 
```shell
# create builder every time like in ci.
docker buildx create --use

docker buildx build \
    --load \
    --planform linux/arm64,linux/amd64 \
    --cache-to type=local,dest=/tmp/.buildx-cache \
    --cache-from type=local,src=/tmp/.buildx-cache \
    --tag gobuild \
    --file Dockerfile .
```

The `--mount=cache` not work. `/go/pkg/mod` always empty (go mod will re download).

![image](https://user-images.githubusercontent.com/1667873/94118940-c9046980-fe80-11ea-9d4a-2fad9992967a.png)

is `--cache-from` and `--cache-to` only cache the build layers? 

`--mount=type=cache` works well if builder not re-create until gc cleanup.

if i want to cache the `/go/pkg/mod`, could i have to copy `/var/lib/buildkit` from buildkit container? 

real-world demo https://github.com/querycap/istio/runs/1159405706

**Comment by FernandoMiguel** [comment]
`--cache-from` and `--cache-to` push all build layers to registry image/label of you choice, local or remote

**Comment by morlay** [comment]
so `--mount=type,cache` not be included？

**Comment by FernandoMiguel** [comment]
> so `--mount=type=cache` not be included？

Only you know your setup, so you use the best cache mechanism for you.
You can use either or both

**Comment by morlay** [comment]
@FernandoMiguel 

but how to? any suggestion in this case.
i need cache `/go/pkg/mod` for multi workflows in build stage.

but the `--cache-to` couldn't expose the cached files (`/var/lib/buildkit`) to host. 
and buildkit recreated when each workflow starts, all cached files in `/var/lib/buildkit` losts

**Comment by morlay** [comment]
mv to https://github.com/moby/buildkit/issues/1673 for further discussion

**Comment by 2063113624** [comment]
@morlay，我有几个js写的前端项目，想要用buildKit构建以减少npm install的时间。但是通过jenkins CI构建的时候总是报/app/node_moudles/目录下面找不到安装的依赖，你能帮忙给点建议吗？Dockerfile如下（文件中的一些变量可以忽略）：
# syntax = docker/dockerfile:experimental
FROM $COMPILE_IMAGE as builder
WORKDIR /app
COPY package.json package-lock.json /app
RUN --mount=type=cache,target=/app/node_modules,id=$image_name,sharing=private \
    $install
COPY . /app
RUN --mount=type=cache,target=/app/node_modules,id=$image_name,sharing=private \
    $compile
FROM nginx:1.20.2
COPY --from=builder /app/dist /usr/share/nginx/html
WORKDIR /usr/share/nginx/html
EXPOSE 80
CMD nginx -g "daemon off;"
镜像构建命令：```
export "DOCKER_BUILDKIT=1" && docker build  -t $SERVICE_IMAGE:${image_tag}  .
```
