### ISSUE TITLE
--filter "until=24h" not working

### ISSUE THREAD

**Issue by richard-kramer** [docker/buildx#400]
I'm using buildkit in my GitLab CI pipelines to build my images with build caches. To accelerate subsequent runs, I export and save the build cache from buildx after each job and import it before another. This works fine but leads to ever growing cache sizes. To clean things up, I tried running `docker buildx prune --filter "until=24h"` as suggested [here](https://docs.docker.com/engine/reference/commandline/builder_prune/) and judging from the [source code](https://github.com/docker/buildx/blob/master/commands/prune.go#L153) I assumed this would work with buildx too. But when using this filter, nothing gets removed. Using no filter leads to all caches being removed, even those, I just created with the latest build (and I need those to build the next image from cache).

**Comment by mrmachine** [comment]
Confirmed this is still a problem. I want to remove old layers from the build cache to avoid filling up my disk, but without removing recent layers that will be needed again and immediately repopulated on the the next build. I tried `docker builder prune --filter 'until=FOO'` with many values. 24h, 12h, 4h, 1h, 5m, 1m. Nothing was ever removed from the build cache.

**Comment by dshakey** [comment]
i am having this issue as well, any update on it?
