### ISSUE TITLE
--quiet should not return an error but a warning

### ISSUE THREAD

**Issue by jygastaud** [docker/buildx#401]
As discussed in [Docker Community Slack](https://dockercommunity.slack.com/archives/C7S7A40MP/p1601030935005400) `--quiet` in `docker buildx build` command return an error (from a code point of view), a message telling that quiet is not implemented that stop the build process.

That implementation cause some script to failed when used in combination of [`docker build` aliasing](https://github.com/jygastaud/buildx#setting-buildx-as-default-builder-in-docker-1903).

## Reproducing

* Install buildx
* Set buildx as default builder
* Run `docker build -q .` and you will get the message `quiet currently not implemented` and no build

## Expecting result

From my opinion, `--quiet` flag absence should not be a blocker.
When running `docker build -q .` we should have a warning, then the build still continue.

**Comment by wimax-grapl** [comment]
Is `--quiet` at all on the roadmap for `buildx` or is it strictly left around for `docker build` compatibility?

**Comment by tonistiigi** [comment]
I think `--quiet` can still be supported

**Comment by wimax-grapl** [comment]
Would love to get that on the roadmap if possible - we currently have no way to quiet some Buildx builds that happen during our  deployments (too much preexisting infrastructure in the middle to blackhole stderr)  😿
