### ISSUE TITLE
running buildx with `--cache-from` rebuilds all layers even when it shouldn't

### ISSUE THREAD

**Issue by peterholak** [docker/buildx#402]
I ran into this problem when using github actions with the action https://github.com/marketplace/actions/build-and-push-docker-images, which uses buildx.

The problem is that layer caching (set up using instructions from the link above) with exported/imported cache doesn't seem to work when any `COPY`d file is changed - it rebuilds all layers, even the ones before the `COPY` (which is different behavior from regular docker build).

I managed to reproduce the issue on my local machine (docker 19.03.8 in ubuntu, buildx 0.4.2 downloaded and placed in `~/.docker/cli-plugins/docker-buildx`, builder with `docker-container` driver, same setup that the github action uses).

I have the following Dockerfile https://github.com/peterholak/testcase-buildx-cache/blob/master/deploy/Dockerfile, which simulates the typical use case of "cache dependencies, unless the files which specify them have changed".

With regular `docker build`, it works as expected. When a file unrelated to the dependencies (e.g. `main.rs` from the same repo as the linked Dockerfile) is changed, subsequent `docker build` runs use the cache all the way [until `COPY . /src/testcase2/`](https://github.com/peterholak/testcase-buildx-cache/blob/master/deploy/Dockerfile#L15).

It works the same with `docker buildx`, but only if I keep the "regular" (non-exported) build cache on my machine. However, github actions uses a fresh environment on every run, so the cache needs to be exported/imported using --cache-from, --cache-to. To simulate this, I run `docker buildx prune --all` before the rebuild.

That still uses the cache correctly when no files are changed, but if I change any file at all (e.g. the already mentioned `main.rs`), the entire build starts from scratch (only [the step in the second stage](https://github.com/peterholak/testcase-buildx-cache/blob/master/deploy/Dockerfile#L22) is cached for some reason).

Steps to reproduce:

1. clone the repo https://github.com/peterholak/testcase-buildx-cache and cd into its directory
2. `docker buildx create --name builder-main-2 --driver docker-container --use`
3. `docker buildx inspect --bootstrap`
4. `docker buildx build --cache-from type=local,src=../testcase-buildx-cache-cached --cache-to type=local,dest=../testcase-buildx-cache-cached -f deploy/Dockerfile .`
5. `docker buildx prune --all`, confirm
6. run the build command from step 4 again, see that everything is used from cache as it should
7. run the prune command from step 5 again
8. edit file `src/main.rs` in any way
9. run the build command from step 4 again
10. all layers from the first stage (called `build`) are rebuilt, none are used from cache

**Comment by tonistiigi** [comment]
If you want to export cache for all stages you need to use `mode=max` cache option. Currently, only cache layers for the last stage are exported.

**Comment by peterholak** [comment]
Thanks, with `mode=max` on `--cache-to`, it works as expected.
