### ISSUE TITLE
add --load and --cache-to --cache-from to bake

### ISSUE THREAD

**Issue by xenoterracide** [docker/buildx#405]
I want bake to support these because I need to support caching in github builds and I want to run docker-compose up after building, and then doing a push, which I suspect doesn't currently support buildx images.

**Comment by tonistiigi** [comment]
`--load` and `--push` have been added to bake. `--cache-to/from` take a image name that should be target specific in most cases. If you really want same value for all targets you can do `--set=*.cache-from=...`
