### ISSUE TITLE
question: where is cache-from cache-to stored by default

### ISSUE THREAD

**Issue by xenoterracide** [docker/buildx#407]
I'm trying to save the cache with github `docker/build-push-action@v2` but I'm also trying to use it with docker-compose which doesn't support a cache option. I figure maybe if I store the default cache... or maybe there's another option?

**Comment by tonistiigi** [comment]
There is no default location. You need to set image or a path https://github.com/docker/buildx#--cache-fromnametypetypekeyvalue
