### ISSUE TITLE
Docker Desktop BuildKit --ssh fails with Windows 10 ssh-agent

### ISSUE THREAD

**Issue by lmoze** [docker/buildx#409]
- [x] I have tried with the latest version of my channel (Stable or Edge)
  - [x] I have uploaded Diagnostics
  - Diagnostics ID: 30374125-7A7A-46B1-9CFC-1BF283B9C885/20201007171900

### Expected behavior
Docker Desktop's `docker.exe build --ssh default` should detect and forward the system SSH agent to the Docker build.

### Actual behavior
The build fails with an error:

```

could not parse ssh: [default]: failed to open \\.\\pipe\\openssh-ssh-agent: open \\.\\pipe\\openssh-ssh-agent: All pipe instances are busy.

```

### Information

  - Windows Version: Windows 10 Pro 2004, build 19041.508
  - Docker Desktop Version: 2.4.0.0 (48506)
  - Are you running inside a virtualized Windows e.g. on a cloud server or on a mac VM: yes, Windows 10 in KVM with nested virtualization

The issue appears any time the `--ssh` option is used with a Docker BuildKit build on Windows when the official Microsoft OpenSSH agent is enabled. The Microsoft SSH agent listens on a Windows named pipe, and Docker Desktop is not configured to use this named pipe. If I set SSH_AUTH_SOCK to the location of the SSH-agent named pipe, it appears that Docker Desktop tries to use the SSH agent, but fails with this error:

```

could not parse ssh: [default]: failed to open \\.\\pipe\\openssh-ssh-agent: open \\.\\pipe\\openssh-ssh-agent: All pipe instances are busy.

```
This issue is a blocker on the use of any Docker build that leverages BuildKit `--ssh` in Windows.

### Steps to reproduce the behavior

I have created a full example Docker build using Buildkit + SSH agent forwarding to demonstrate the bug. Full setup instructions and links to the official Microsoft OpenSSH ssh-agent setup guides are in the README.md - https://github.com/lmoze/buildkit-ssh-sample

**Comment by lmoze** [comment]
Please ignore the spurious close/reopens - misclicked in the Github mobile app.

**Comment by tonistiigi** [comment]
@nicks ideas? (via moby/buildkit#1695)

**Comment by nicks** [comment]
I think what's going on is that most of the SSH implementations on windows use a file socket (someplace like `C:/Users/username/AppData/Local/Temp/ssh-l0E48ifEnCIz/agent.8496` as in https://github.com/moby/buildkit/issues/914). 

But Microsoft's OpenSSH issue uses a named pipe (\\.\\pipe), which have different semantics? So we'd need to use something like https://github.com/microsoft/go-winio and DialPipe instead of Dial("unix")

**Comment by crazy-max** [comment]
Fixed by https://github.com/moby/buildkit/pull/2127
