### ISSUE TITLE
Docker buildx - could not create a builder instance with TLS data loaded from environment

### ISSUE THREAD

**Issue by KamranAzeem** [docker/buildx#413]
Hello,

I am trying to build multiarch image through a gitlab-ci pipeline, using my own gitlab-runner , running on a docker-host.

First, I could not get basic TLS to work with docker "19.03.13". However, after two days of banging my head with the internet I finally got past the dreaded "is docker daemon running on tcp://docker:2376" family of errors.  I now have "buildx" complaining about some context not being created. Here is the error message:

> $ docker buildx create --name multiarch-builder --driver docker-container --use
> could not create a builder instance with TLS data loaded from environment. Please use `docker context create <context-name>` to create a context for current environment and then create a builder instance with `docker buildx create <context-name>`

![Screenshot from 2020-10-14 23-36-23](https://user-images.githubusercontent.com/4216369/96047918-2125fe80-0e76-11eb-81da-42a01621f099.png)

To understand my setup, I have the following `docker-compose.yml`, which runs gitlab-runner on my docker-host:
```
$ egrep -v "\#|^$" docker-compose.yml 
version: "3"
services:
  gitlab-runner:
    image: gitlab/gitlab-runner:alpine
    environment:
      - TZ=Europe/London
    volumes:
      - /home/containers-data/gitlab-runner/config:/etc/gitlab-runner
      - /home/containers-data/gitlab-runner/cache:/cache
      - /var/run/docker.sock:/var/run/docker.sock
```

My `gitlab-runner/config/config.toml` - on the same docker host - looks like this:
```
$ egrep -v "\#|^$" /home/containers-data/gitlab-runner/config/config.toml 
concurrent = 1
check_interval = 0
log_level = "debug"
[session_server]
  session_timeout = 1800
[[runners]]
  name = "NAAAAAAAAAAME"
  url = "https://gitlab.com"
  token = "TOOOOOOKEN"
  executor = "docker"
  [runners.custom_build_dir]
  [runners.cache]
    [runners.cache.s3]
    [runners.cache.gcs]
    [runners.cache.azure]
  [runners.docker]
    tls_verify = false
    image = "docker:latest"
    privileged = true
    oom_kill_disable = false
    disable_cache = false
    volumes = ["/certs/client","/cache"]
    shm_size = 0
```

My `gitlab-ci.yml` looks like this:
```
$  egrep -v "\#|^$" .gitlab-ci.yml
stages:
- build-and-push-multiarch-image
variables:
  DOCKERHUB_IMAGE: "simple-apache"
  DOCKERHUB_USERNAME: "kamranazeem"
  DOCKER_CLI_EXPERIMENTAL: "enabled"
  MULTIARCH_PLATFORMS: "linux/amd64,linux/arm64,linux/ppc64le,linux/s390x,linux/386,linux/arm/v7,linux/arm/v6"
  DOCKER_DRIVER: overlay2
  DOCKER_TLS_CERTDIR: "/certs"
  
job-build-and-push-multiarch-image:
  only:
  - master
  - tags
  stage: build-and-push-multiarch-image
  image: docker:latest
  services:
  - name: docker:dind
    command: ["--experimental"]
  script:
  - docker version
  - CONTAINER_FQN=${DOCKERHUB_USERNAME}/${DOCKERHUB_IMAGE}
  - 'echo "CONTAINER_FQN is set to: ${CONTAINER_FQN}"'
  - 'echo "DOCKER_CLI_EXPERIMENTAL is set to: ${DOCKER_CLI_EXPERIMENTAL}"'
  - 'echo "MULTIARCH_PLATFORMS is set to: ${MULTIARCH_PLATFORMS}"'
  - |-
    if [[ ! -z "${CI_COMMIT_BRANCH}" && "${CI_COMMIT_BRANCH}" == "master" ]]; then 
      echo "Found git commit on master branch with no tag. Setting docker image tag as: 'latest'" 
      TAG=${CONTAINER_FQN}:latest
    fi  
    if [[ ! -z "${CI_COMMIT_TAG}" ]]; then 
      echo "Found git tag. Setting docker image tag as: '${CI_COMMIT_TAG}'" 
      TAG=${CONTAINER_FQN}:${CI_COMMIT_TAG}
    fi
    TAGS="-t ${TAG} -t ${CONTAINER_FQN}:${CI_COMMIT_SHORT_SHA}"
 
  - 'echo "Complete Docker image-name with tags are setup as: ${TAGS}"'
  - docker run --rm --privileged multiarch/qemu-user-static --reset -p yes
  - BUILDX_VERSION_URL="https://github.com/docker/buildx/releases/latest"
  - |-
    BUILDX_VERSION=$(wget -S ${BUILDX_VERSION_URL} 2>&1 | grep 'location' \
      | sed 's/.*\(v[0-9]*.[0-9]*.[0-9]*\).*/\1/')
  - 'echo "BUILDX_VERSION is found to be: ${BUILDX_VERSION}"'
  - BUILDX_DOWNLOAD_URL="https://github.com/docker/buildx/releases/download"
  - BUILDX_FULL_URL="${BUILDX_DOWNLOAD_URL}/${BUILDX_VERSION}/buildx-${BUILDX_VERSION}.linux-amd64"
  - 'echo "BUILDX_FULL_URL is set to: ${BUILDX_FULL_URL}"'
  - mkdir -p $HOME/.docker/cli-plugins/
  - wget -O $HOME/.docker/cli-plugins/docker-buildx ${BUILDX_FULL_URL} 
  - chmod a+x $HOME/.docker/cli-plugins/docker-buildx
  - echo ${DOCKERHUB_TOKEN} | docker login -u ${DOCKERHUB_USERNAME} --password-stdin
  - docker context create tls-environment
  - docker buildx create --name multiarch-builder --driver docker-container --use
  - docker buildx inspect --bootstrap
  - docker buildx build --platform ${MULTIARCH_PLATFORMS} --push ${TAGS} .
```

One clarification: I am not using specific images, such as "docker:19.03.13" or "docker-19.03.13-dind". I understand that the recommendation to use specific version tags with these images is just to prevent docker from introducing some new breaking change in future. I get it and that is not a problem at the moment (IMO). That is why I used only docker:latest and docker:dind.

OK. So, now my job seems to be working with docker:dind to the point where it tries to run "docker buildx create ...". I can't find proper documentation on how to create a new buildx context when the previous context is a TLS based context. I used this link: [https://about.gitlab.com/releases/2019/07/31/docker-in-docker-with-docker-19-dot-03/](https://about.gitlab.com/releases/2019/07/31/docker-in-docker-with-docker-19-dot-03/) to get things going with TLS until this point in time, where I am stuck with buildx.

Please note that another version of my gitlab-ci.yml was working properly (i.e. creating multiarch images of my choice), when I was using gitlab's shared runners. I just wanted to get this done through my own runner, and that is where the problem is. 

I must be missing something.

Here is the version of gitlab-ci.yml which worked beautifully when I used gitlab's shared runners:

```
$  egrep -v "\#|^$" .gitlab-ci.yml.working 
stages:
- build-and-push-multiarch-image
variables:
  DOCKERHUB_IMAGE: "simple-apache"
  DOCKERHUB_USERNAME: "kamranazeem"
  DOCKER_CLI_EXPERIMENTAL: "enabled"
  MULTIARCH_PLATFORMS: "linux/amd64,linux/arm64,linux/ppc64le,linux/s390x,linux/386,linux/arm/v7,linux/arm/v6"
  
job-build-and-push-multiarch-image:
  only:
  - master
  - tags
  stage: build-and-push-multiarch-image
  image: docker:latest
  services:
  - name: docker:dind
    command: ["--experimental"]
  script:
  - docker version
  - CONTAINER_FQN=${DOCKERHUB_USERNAME}/${DOCKERHUB_IMAGE}
  - 'echo "CONTAINER_FQN is set to: ${CONTAINER_FQN}"'
  - 'echo "DOCKER_CLI_EXPERIMENTAL is set to: ${DOCKER_CLI_EXPERIMENTAL}"'
  - 'echo "MULTIARCH_PLATFORMS is set to: ${MULTIARCH_PLATFORMS}"'
  - |-
    if [[ ! -z "${CI_COMMIT_BRANCH}" && "${CI_COMMIT_BRANCH}" == "master" ]]; then 
      echo "Found git commit on master branch with no tag. Setting docker image tag as: 'latest'" 
      TAG=${CONTAINER_FQN}:latest
    fi  
    if [[ ! -z "${CI_COMMIT_TAG}" ]]; then 
      echo "Found git tag. Setting docker image tag as: '${CI_COMMIT_TAG}'" 
      TAG=${CONTAINER_FQN}:${CI_COMMIT_TAG}
    fi
    TAGS="-t ${TAG} -t ${CONTAINER_FQN}:${CI_COMMIT_SHORT_SHA}"
 
  - 'echo "Complete Docker image-name with tags are setup as: ${TAGS}"'
  - docker run --rm --privileged multiarch/qemu-user-static --reset -p yes
  - BUILDX_VERSION_URL="https://github.com/docker/buildx/releases/latest"
  - |-
    BUILDX_VERSION=$(wget -S ${BUILDX_VERSION_URL} 2>&1 | grep 'location' \
      | sed 's/.*\(v[0-9]*.[0-9]*.[0-9]*\).*/\1/')
  - 'echo "BUILDX_VERSION is found to be: ${BUILDX_VERSION}"'
  - BUILDX_DOWNLOAD_URL="https://github.com/docker/buildx/releases/download"
  - BUILDX_FULL_URL="${BUILDX_DOWNLOAD_URL}/${BUILDX_VERSION}/buildx-${BUILDX_VERSION}.linux-amd64"
  - 'echo "BUILDX_FULL_URL is set to: ${BUILDX_FULL_URL}"'
  - mkdir -p $HOME/.docker/cli-plugins/
  - wget -O $HOME/.docker/cli-plugins/docker-buildx ${BUILDX_FULL_URL} 
  - chmod a+x $HOME/.docker/cli-plugins/docker-buildx
  - docker buildx create --name multiarch-builder --driver docker-container --use
  - docker buildx inspect --bootstrap
  - echo ${DOCKERHUB_TOKEN} | docker login -u ${DOCKERHUB_USERNAME} --password-stdin
  - docker buildx build --platform ${MULTIARCH_PLATFORMS} --push ${TAGS} .
```

Any help will be appreciated. Thanks.

**Comment by tonistiigi** [comment]
Are you looking for docs on `docker context create` ? It is in https://docs.docker.com/engine/context/working-with-contexts/

**Comment by KamranAzeem** [comment]
Thank you for the link to docker context documentation. I am afraid I could not find anything related to my problem. It simply says that one can maintain different contexts to talk to different docker environments. Just like kubernetes contexts. Remember buildx documentation does not mention that it has capability to create a context. Also, the buildx documentation on this link [https://docs.docker.com/buildx/working-with-buildx/](https://docs.docker.com/buildx/working-with-buildx/) says:

> Docker 19.03 also features a new docker context command that you can use to provide names for remote Docker API endpoints. Buildx integrates with docker context to ensure all the contexts automatically get a default builder instance. You can also set the context name as the target when you create a new builder instance or when you add a node to it.

If this is true, then my default docker context should get the default builder instance. Instead it just throws this error, which -the error - is not clear. 

Here is the latest screenshot with the error.
![Screenshot from 2020-10-16 23-21-50](https://user-images.githubusercontent.com/4216369/96309930-99bbc500-1006-11eb-8f2b-a09aaa5be69f.png)


I am still not sure what am I supposed to do to get this to work.

**Comment by KamranAzeem** [comment]
Note: I added `docker buildx install` and `docker context ls` commands to my  `.gitlab-ci.yml` file - for debugging.

**Comment by tonistiigi** [comment]
> $ docker buildx create --name multiarch-builder --driver docker-container --use
could not create a builder instance with TLS data loaded from environment. Please use `docker context create <context-name>` to create a context for current environment and then create a builder instance with `docker buildx create <context-name>`


In the example above you make a context called `tls-environment` but you do not provide it to the `buildx create` command like the error tells you to. `docker buildx create --name multiarch-builder --driver docker-container --use tls-environment`

**Comment by tonistiigi** [comment]
Also, I'm not sure if your context actually works and if you have tested it (as you don't pass the tls info when creating it).

This is the example for the tls case from `docker context create --help`

```
$ docker context create my-context --description "some description" --docker "host=tcp://myserver:2376,ca=~/ca-file,cert=~/cert-file,key=~/key-file"
```

**Comment by KamranAzeem** [comment]
Hello @tonistiigi . Thank you very much for this:

> In the example above you make a context called tls-environment but you do not provide it to the buildx create command like the error tells you to. docker buildx create --name multiarch-builder --driver docker-container --use tls-environment

It solved my problem. Lovely! Thanks!

![Screenshot from 2020-10-17 12-09-25](https://user-images.githubusercontent.com/4216369/96334533-d1ac2200-1071-11eb-817a-0c078f47df49.png)

**Comment by axk7812** [comment]
> > $ docker buildx create --name multiarch-builder --driver docker-container --use
> > could not create a builder instance with TLS data loaded from environment. Please use `docker context create <context-name>` to create a context for current environment and then create a builder instance with `docker buildx create <context-name>`
> 
> In the example above you make a context called `tls-environment` but you do not provide it to the `buildx create` command like the error tells you to. `docker buildx create --name multiarch-builder --driver docker-container --use tls-environment`

To be fair the documentation isn't explicit enough. It just says 

> `docker buildx create <context-name>`

Rather it should probably say

> `docker buildx create <builder-name> --use <context-name>`

**Comment by crazy-max** [comment]
https://github.com/docker/buildx/blob/master/docs/reference/buildx_create.md#buildx-create

**Comment by ldemailly** [comment]
hi there, sorry to necro this, but I'm kind of curious why 
```
docker buildx create --use
```
as typically done/documented doesn't work while
```
docker context create foo
docker buildx create --use foo
```
does work (without extra params set etc)


doing an inspect though maybe yields a clue: default context and foo are exactly the same settings except for:
```json
        "Storage": {
            "MetadataPath": "\u003cIN MEMORY\u003e",
            "TLSPath": "\u003cIN MEMORY\u003e"
        }
```
default ^ vs foo:
```json
        "Storage": {
            "MetadataPath": "/root/.docker/contexts/meta/2c26b48ff...some...hash...886266e7ae",
            "TLSPath": "/root/.docker/contexts/tls/2c26b48ff...same...hash...886266e7ae"
        }
```

**Comment by Karreg** [comment]
> hi there, sorry to necro this, but I'm kind of curious why
> 
> ```
> docker buildx create --use
> ```
> 
> as typically done/documented doesn't work while
> 
> ```
> docker context create foo
> docker buildx create --use foo
> ```
> 
> does work (without extra params set etc)
> 
> doing an inspect though maybe yields a clue: default context and foo are exactly the same settings except for:
> 
> ```json
>         "Storage": {
>             "MetadataPath": "\u003cIN MEMORY\u003e",
>             "TLSPath": "\u003cIN MEMORY\u003e"
>         }
> ```
> 
> default ^ vs foo:
> 
> ```json
>         "Storage": {
>             "MetadataPath": "/root/.docker/contexts/meta/2c26b48ff...some...hash...886266e7ae",
>             "TLSPath": "/root/.docker/contexts/tls/2c26b48ff...same...hash...886266e7ae"
>         }
> ```

Thanks for pointing out this. I have the same question.
Looks like undocumented magic.
And I still haven't been able to work out how to inject CA certificates in this context to make it work...
