### ISSUE TITLE
BUILDX_NO_DEFAULT_LOAD warning when unset

### ISSUE THREAD

**Issue by ttshivers** [docker/buildx#416]
If the env `BUILDX_NO_DEFAULT_LOAD` is not set and no exports are specified, it generates the following warning:
```
invalid non-bool value for BUILDX_NO_DEFAULT_LOAD
```

It would be nice to treat `BUILDX_NO_DEFAULT_LOAD` being unset as false to prevent this warning.

https://github.com/docker/buildx/blob/a11cc8840e6c358e0fa3939dd80903e8a29327a0/build/build.go#L853-L860

Perhaps something like:
```go
func noDefaultLoad() bool {
	v, ok := os.LookupEnv("BUILDX_NO_DEFAULT_LOAD")
	if !ok {
		return false
	}
	b, err := strconv.ParseBool(v)
	if err != nil {
		logrus.Warnf("invalid non-bool value for BUILDX_NO_DEFAULT_LOAD: %s", v)
	}
	return b
}
```

**Comment by tonistiigi** [comment]
#390

**Comment by ttshivers** [comment]
> #390

Thanks. Hope that change or an equivalent one is merged in soon.
