### ISSUE TITLE
RUN on s390x extremely slow (doesn't finish)

### ISSUE THREAD

**Issue by e-desouza** [docker/buildx#417]
If we remove the RUN, there's no problem (as there's no emulation happening), but as soon as the RUN is added, even for something as simple as `ls`, the build never finishes. ppc64le, arm64 etc don't have this problem. I doubt this is a regression, as this probably never worked successfully.

```bash
mkdir test && cd test && cat <<EOF > Dockerfile

FROM ubuntu
RUN ls
WORKDIR /src
COPY . .
EOF
```

and then
```bash
docker buildx build --platform linux/s390x,linux/arm64 -t test:latest .
```

**Comment by crazy-max** [comment]
You can test with QEMU from https://github.com/tonistiigi/binfmt that is made for running containers:

```
$ docker run -it --rm tonistiigi/binfmt:latest --version
binfmt/8703596 qemu/v6.0.0 go/1.16.5
```
