### ISSUE TITLE
--shm-size in docker build for Mac is not accepting the values indicated

### ISSUE THREAD

**Issue by rpesciotta** [docker/buildx#418]
- [x] I have tried with the latest version of my channel (Stable)
  - [x] I have uploaded Diagnostics
  - Diagnostics ID: 80E045E9-84C3-4BA1-A4EE-2A443EA5AFF8/20201016192548

### Expected behavior
`--shm-size=XXX` should set /dev/shm to the desired value

### Actual behavior
any value for `--shm-size` sets the value to 64M, only

### Information
  - macOS Version: macOS Catalina 10.15.7
  - docker for mac version: 2.4.0.0 (48506) Stable

### Steps to reproduce the behavior
  1. Use the sample Dockerfile, that stores the allocated size inside /dev/shm during build time in a temp file that can be read on the container when running
```
FROM busybox
RUN df -kh /dev/shm > /tmp/output
CMD cat /tmp/output
```
  2. Build the image passing the `--shm-size` tag
```
docker build --shm-size=1g -t test .
[+] Building 1.6s (6/6) FINISHED
=> [internal] load build definition from Dockerfile
=> => transferring dockerfile: 111B
=> [internal] load .dockerignore
=> => transferring context: 2B
=> [internal] load metadata for docker.io/library/busybox:latest
=> CACHED [1/2] FROM docker.io/library/busybox@sha256:a9286defaba7b3a519d585ba0e37d0b2cbee74ebfe590960b0b1d6a5e97d1e1d
=> [2/2] RUN df -kh /dev/shm > /tmp/output
=> exporting to image
=> => exporting layers
=> => writing image sha256:2f450e57281dca99454df4ad8becd0fcb2e1153470b5ed365aa946042d001605
=> => naming to docker.io/library/test
```
  3. Run the generated image, which will print the size of /dev/shm stored in the temporary text file during build
```
docker run test
Filesystem                Size      Used Available Use% Mounted on
shm                      64.0M         0     64.0M   0% /dev/shm
```

Tried with different values for the `--shm-size` parameter, but in all cases only 64M is allocated to /dev/shm.

**Comment by rpesciotta** [comment]
Additional information: the same docker version on macOS 10.15.6 works fine!

**Comment by rpesciotta** [comment]
I have upgraded to Docker Desktop 2.5.0.0 (49427) Stable and the behavior is exactly the same.
I also tried to add the following configuration to the Docker Engine, but the behavior was exactly the same, whether I use --shm-size or not during build:
```
{
  "features": {
    "buildkit": true
  },
  "experimental": true,
  "default-shm-size": "1g"
}
```

Here's the full version info:
![image](https://user-images.githubusercontent.com/1410836/98143163-0b31b980-1ec9-11eb-8ac1-08fb62f83622.png)

**Comment by rpesciotta** [comment]
Upgraded to Docker Desktop 2.5.0.1, still the same problem.

**Comment by Octogonapus** [comment]
I am having the same trouble on Fedora Linux with kernel `5.9.8-100.fc32.x86_64`
Docker version:
```
Client:
 Version:           19.03.11
 API version:       1.40
 Go version:        go1.14.3
 Git commit:        42e35e6
 Built:             Sun Jun  7 21:16:58 2020
 OS/Arch:           linux/amd64
 Experimental:      false

Server:
 Engine:
  Version:          19.03.11
  API version:      1.40 (minimum version 1.12)
  Go version:       go1.14.3
  Git commit:       42e35e6
  Built:            Sun Jun  7 00:00:00 2020
  OS/Arch:          linux/amd64
  Experimental:     true
 containerd:
  Version:          1.3.3
  GitCommit:        
 runc:
  Version:          1.0.0-rc10+dev
  GitCommit:        fbdbaf85ecbc0e077f336c03062710435607dbf1
 docker-init:
  Version:          0.18.0
  GitCommit:
```

This build file with `DOCKER_BUILDKIT=0`:
```
FROM ubuntu:18.04
RUN df -h /dev/shm && sleep 10
```
Shows `/dev/shm` has size `2.0G`.

This build file with `DOCKER_BUILDKIT=1`:
```
# syntax=docker/dockerfile:experimental
FROM ubuntu:18.04
RUN df -h /dev/shm && sleep 10
```
Shows `/dev/shm` has size `64m`.

Seems like a bug to me. Please let me know if there is anything else I can do to help with this issue, or if there is any known workaround.

**Comment by rpesciotta** [comment]
Great finding @Octogonapus !
I changed this in my system and it worked fine.
Looks like a bug to me, especially when it happens in different platforms...

**Comment by crazy-max** [comment]
Same is required by docker/build-push-action#263 but as I said this is currently not supported by buildkit. cc @tonistiigi.

> Tried with different values for the `--shm-size` parameter, but in all cases only 64M is allocated to /dev/shm.

This is because the impl [is ignored](https://github.com/docker/buildx/blob/ad95d6ba048c0b24a77cdf3a19161c98d077f955/commands/build.go#L274-L275) on buildx.

**Comment by ezpuzz** [comment]
I use the `--shm-size` flag and the `shm_size` docker-compose options to specify a cache size for use with `yarn`

workaround is disabling buildkit

**Comment by felipecrs** [comment]
I'm with buildx 0.7.1 here. What should I do to make it work?

**Comment by SerhatG** [comment]
> I'm with buildx 0.7.1 here. What should I do to make it work?

I just had the same issue. Find out that the BuildKit version with the fix is not available yet for production versions.
A way to still make it work without disabling BuildKit is by using `tmpfs` instead.
If I gathered correctly `shm` is nothing else then a `tmpfs` mount specifically on `/dev/shm` with a size set.
So adding `--mount=type=tmpfs,target=/dev/shm` to any `RUN` command that needs it should work.
Do note that I haven't set a size, so it can use as much as possible.

PS: Know it's an old comment, but it might help others.
