### ISSUE TITLE
failed to solve with frontend dockerfile.v0: failed to build LLB: executor failed running [/bin/sh -c "npm, install"]: runc did not terminate sucessfully

### ISSUE THREAD

**Issue by Cyberodd** [docker/buildx#423]
- [ ] I have tried with the latest version of my channel (Stable or Edge)
  - [ ] I have uploaded Diagnostics
  - Diagnostics ID:

### Information
  - Is it reproducible?Yes
  - Is the problem new?first time using it but based on internet search results, it seems so
  - Did the problem appear with an update?
  - A reproducible case if this is a bug, Dockerfiles with reproduction inside is best.
-->
  - Windows Version:
  - Docker Desktop Version:
  - Are you running inside a virtualized Windows e.g. on a cloud server or on a mac VM:

### Steps to reproduce the behavior

  1. ...
  2. ...

**Comment by Cyberodd** [comment]
Added the ":dev" after the image name

**Comment by SeanFacer** [comment]
Also seeing this issue

**Comment by systackid** [comment]
Me also seeing this error while rebuilding the docker images without using the cache

My Dockerfile:

```
FROM node:latest
WORKDIR /app
ADD package*.json /.
RUN npm install
ADD . .
CMD node index.js
```

And then running the build command:
`$ docker build -t myapp:latest .
`
(which myapp is the latest images I created)
```
$ docker images
REPOSITORY          TAG                 IMAGE ID            CREATED             SIZE
myapp               latest              6986f9e445a3        6 hours ago         979MB
```

**Comment by nixnux86** [comment]
Me also seeing this error while rebuilding the docker images without using the cache

My Dockerfile:

```
FROM node:latest
WORKDIR /app
ADD package*.json /.
RUN npm install
ADD . .
CMD node index.js
```

And then running the build command:
`$ docker build -t myapp:latest .
`
(which myapp is the latest images I created)
```
$ docker images
REPOSITORY          TAG                 IMAGE ID            CREATED             SIZE
myapp               latest              6986f9e445a3        6 hours ago         979MB
```

**Comment by nixnux86** [comment]
> Me also seeing this error while rebuilding the docker images without using the cache
> 
> My Dockerfile:
> 
> ```
> FROM node:latest
> WORKDIR /app
> ADD package*.json /.
> RUN npm install
> ADD . .
> CMD node index.js
> ```
> 
> And then running the build command:
> `$ docker build -t myapp:latest . `
> (which myapp is the latest images I created)
> 
> ```
> $ docker images
> REPOSITORY          TAG                 IMAGE ID            CREATED             SIZE
> myapp               latest              6986f9e445a3        6 hours ago         979MB
> ```

To add more info, here is my environment:
Windows Version: Microsoft Windows 10 Pro - 10.0.18363 N/A Build 18363
Docker Desktop Version: 19.03.13
Are you running inside a virtualized Windows e.g. on a cloud server or on a mac VM: No

**Comment by adriantang** [comment]
I also facing this issue, any solution??

**Comment by sjc2870** [comment]
encounter this issue recently , does anybody know how to solve it ?

**Comment by sjc2870** [comment]
Encounter this issue recently , does anybody know how to solve it ?

**Comment by systackid** [comment]
I fixed the problem, there was a typo in Dockerfile
`ADD package*.json /.`

should be
`ADD package*.json ./`

You might have different typo, but please double check for any miss-typed.

**Comment by om-baji** [comment]
any fix on this??

i am creating a devcontainer for a next js app 

FROM node:18

WORKDIR /usr/src/app

COPY ./package*.json ./

RUN npm install

COPY . .

CMD [ "npm", "run", "dev" ]

i tried changing node version but it didnt work
