### ISSUE TITLE
How do I get the SHA / Container ID of failed builds

### ISSUE THREAD

**Issue by sindre-nistad** [docker/buildx#424]
- [x] I have tried with the latest version of my channel (Stable or Edge)
  - [x] I have uploaded Diagnostics
  - Diagnostics ID: 186430DE-AC01-457C-A70E-BEDB4F520049/20201020074455

### Expected behavior
Be able to find the container ID of failed builds, so that I can log enter them interactively, and debug them.

### Actual behavior
`=> ERROR [build x/n] RUN <failed command>`

### Information

  - macOS Version: 10.15.7

### Diagnostic logs

```
Docker for Mac: version...

```

### Steps to reproduce the behavior

  1. ...
  2. ...

**Comment by tonistiigi** [comment]
Follow updates on this in https://github.com/moby/buildkit/issues/1472 . Current best workaround is to set `--target` to point to a previous command.
