### ISSUE TITLE
What exactly can cache from and cache to do with remote registries (self own custom registries)?

### ISSUE THREAD

**Issue by no1melman** [docker/buildx#435]
So from the documentation here https://github.com/docker/buildx#--cache-fromnametypetypekeyvalue

obviously a good point about docker is the layer caching, when you specify a remote for the cache from and cache to, two questions

  1. Is that for the layer caching as well?
  2. can you just specify the remote registry? or does it need to be remote registry and image name...

**Comment by tonistiigi** [comment]
1. Yes remote caching is for layers/instructions
2. You need to specify image name where you are importing from/exporting to

**Comment by no1melman** [comment]
Thanks for that, do you always need to do `docker buildx build` or can the commands be forwarded through to `docker build` ? I'm immediately guessing, absolutely not. But just thought I would clarify

**Comment by tonistiigi** [comment]
`DOCKER_BUIDLKIT=1 docker build` can import cache and supports creating images with inline cache. `docker buildx install` can replace the `docker build` with `docker buildx build`

**Comment by no1melman** [comment]
So when you say `docker buildx install` reeplaces `docker build` what does that mean for the arguments that you usually pass to `buildx`, how they interpreted by `docker build` or how do you take advantage of the `--cache-from` `--cache-to`

**Comment by crazy-max** [comment]
@no1melman It installs buildx as a 'docker builder' alias and can be removed with `docker buildx uninstall`
