### ISSUE TITLE
error when KUBECONFIG contains more than one file

### ISSUE THREAD

**Issue by ms-lolo** [docker/buildx#437]
my `KUBECONFIG` contains a `:` delimited list of config files for `kubectl` to load. I think this is causing issues.

```bash
$ docker buildx create    \
  --driver kubernetes     \  
  --driver-opt replicas=3 \
  --use
```
```bash
$ docker buildx ls         
NAME/NODE           DRIVER/ENDPOINT             STATUS PLATFORMS
gallant_mahavira *  kubernetes                         
  gallant_mahavira0 unix:///var/run/docker.sock cannot determine Kubernetes namespace, specify manually: stat /home/$USER/.kube/config:/home/$USER/.kube/microk8s.config: no such file or directory
default             docker                              
  default           default              
```

I have yet to get a working k8s version running so not sure if I am just missing something obvious.

**Comment by N9q** [comment]
> my `KUBECONFIG` contains a `:` delimited list of config files for `kubectl` to load. I think this is causing issues.
> 
> ```shell
> $ docker buildx create    \
>   --driver kubernetes     \  
>   --driver-opt replicas=3 \
>   --use
> ```
> 
> ```shell
> $ docker buildx ls         
> NAME/NODE           DRIVER/ENDPOINT             STATUS PLATFORMS
> gallant_mahavira *  kubernetes                         
>   gallant_mahavira0 unix:///var/run/docker.sock cannot determine Kubernetes namespace, specify manually: stat /home/$USER/.kube/config:/home/$USER/.kube/microk8s.config: no such file or directory
> default             docker                              
>   default           default              
> ```
> 
> I have yet to get a working k8s version running so not sure if I am just missing something obvious.

**Comment by ms-lolo** [comment]
did you mean to write something in your reply, @N9q ?
