### ISSUE TITLE
Raspi4b Ubuntu 20.04 aarch64, "docker: 'buildx' is not a docker command."

### ISSUE THREAD

**Issue by Thrizian** [docker/buildx#439]
Hi,

Thank you for building this awesome experimental plugin. It seems to be exactly what i need for my project. I am attempting to set up a [AnsibleNAS](https://github.com/davestephens/ansible-nas) on a Pi4b. Of course some(surprisingly not all) of the containers being set up with the ansible playbook were made to run on a different architecture than the one i'm running. And i figured it might be a challenge to see if buildx made it possible to set this up (despite the fact i'm quite new at docker).

I have followed the steps needed to set up docker experimental features and am expecting the command `docker buildx ls` to return to me a list of architectures however the response i get is: 

```
$  docker buildx ls
docker: 'buildx' is not a docker command.
See 'docker --help'
```
Which is weird considering the docker info returns to me that the buildx plugin is available as well as the experimental features being enabled on both the server and client side.

```
ubuntu@data-tank:~$ docker info
Client:
 Debug Mode: false
 Plugins:
  app: Docker Application (Docker Inc., v0.8.0)
  buildx: Build with BuildKit (Docker Inc., v0.4.2-tp-docker)

Server:
 Containers: 18
  Running: 11
  Paused: 0
  Stopped: 7
 Images: 20
 Server Version: 19.03.13
 Storage Driver: zfs
  Zpool: tank
  Zpool Health: ONLINE
  Parent Dataset: tank/docker
  Space Used By Parent: 5051387904
  Space Available: 5803338575872
  Parent Quota: no
  Compression: lz4
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 8fba4e9a7d01810a393d5d25a3621dc101981175
 runc version: dc9208a3303feef5b3839f4323d9beb36df0a9dd
 init version: fec3683
 Security Options:
  apparmor
  seccomp
   Profile: default
 Kernel Version: 5.4.0-1022-raspi
 Operating System: Ubuntu 20.04.1 LTS
 OSType: linux
 Architecture: aarch64
 CPUs: 4
 Total Memory: 7.628GiB
 Name: data-tank
 ID: BRXT:64JZ:S7IM:ENUX:YJAA:4ZSC:QQQD:2IRU:AB3Y:EPLM:RYOY:EWWB
 Docker Root Dir: /var/lib/docker/data
 Debug Mode: false
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: true
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false
```

Is this a classic case of [PEBCAC](https://en.wiktionary.org/wiki/PEBCAC#English) or am i running into a bug? Am I wrong to think that buildx could help me run a container in a different architecture? Does buildx only work on the build side of things? Could someone point me in the right direction?

**Comment by tonistiigi** [comment]
If you got the buildx binary with DockerCE you need to enable experimental on cli side https://github.com/docker/buildx#docker-ce . I can't see it from the output you posted but it is visible if you run `docker version`. (FYI @thaJeztah )

Try running the plugin binary directly to see if all the permission bit etc are set correctly and you have binary for correct architecture. Note that if you can't figure it out, buildx binary can be called directly as well with all the same commands.

**Comment by Thrizian** [comment]
Hi @tonistiigi,

Thanks a lot for the reply. I would like to let you know that my docker version output is as follows:
```ubuntu@data-tank:~/test$ docker version
Client: Docker Engine - Community
 Version:           19.03.13
 API version:       1.40
 Go version:        go1.13.15
 Git commit:        4484c46
 Built:             Wed Sep 16 17:03:40 2020
 OS/Arch:           linux/arm64
 Experimental:      true

Server: Docker Engine - Community
 Engine:
  Version:          19.03.13
  API version:      1.40 (minimum version 1.12)
  Go version:       go1.13.15
  Git commit:       4484c46
  Built:            Wed Sep 16 17:02:11 2020
  OS/Arch:          linux/arm64
  Experimental:     true
 containerd:
  Version:          1.3.7
  GitCommit:        8fba4e9a7d01810a393d5d25a3621dc101981175
 runc:
  Version:          1.0.0-rc10
  GitCommit:        dc9208a3303feef5b3839f4323d9beb36df0a9dd
 docker-init:
  Version:          0.18.0
  GitCommit:        fec3683
```

It seems i can run the buildx binary directly.
```ubuntu@data-tank:~/ansible-nas$ ~/.docker/cli-plugins/docker-buildx/buildx ls
NAME/NODE DRIVER/ENDPOINT STATUS  PLATFORMS
default * docker
  default default         running linux/arm64, linux/arm/v7, linux/arm/v6```

i think the permissions are set correctly. 
```
ubuntu@data-tank:~/.docker/cli-plugins/docker-buildx$ ls -l
total 109360
-rwxr-xr-x 1 ubuntu ubuntu 57346245 Nov  6 10:51 buildx
-rw-rw-r-- 1 ubuntu ubuntu 54633368 Aug 22 05:20 buildx-v0.4.2.linux-arm64
```

however i cannot run `docker buildx` commands 
```
ubuntu@data-tank:~/test$ docker buildx ls
docker: 'buildx' is not a docker command.
See 'docker --help'
```

**Comment by tonistiigi** [comment]
`~/.docker/cli-plugins/docker-buildx/buildx` path should be `~/.docker/cli-plugins/docker-buildx`

**Comment by Thrizian** [comment]
There is no buildx directory. The `buildx ls` command lists the available builds from the buildx binary
```
ubuntu@data-tank:~/.docker/cli-plugins/docker-buildx$ cd buildx
-bash: cd: buildx: Not a directory
```

**Comment by tonistiigi** [comment]
`~/.docker/cli-plugins/docker-buildx` needs to be the path to the binary itself.

**Comment by Thrizian** [comment]
Ah, great, thanks! let me try that.

**Comment by Thrizian** [comment]
Great success! Thanks a lot! Where can i buy you a drink?

**Comment by enthusiasticgeek** [comment]
I also noticed that one has to do `sudo chmod a+x ${USER}/.docker/cli-plugins/docker-buildx`
