### ISSUE TITLE
Push to Sonatype nexus fails

### ISSUE THREAD

**Issue by felixoi** [docker/buildx#457]
I'm using the `docker/setup-buildx-action` with the push option enabled, which should push to a private sonatype nexsus docker registry. I'm getting the error
```
buildx call failed with: failed to solve: rpc error: code = Unknown desc = unexpected status: 400 HTTP method POST is not supported by this URL
```
just pushing using the `load: true` option with `docker push` afterwards works without problems tho.
I suspect buildx to be the problem here.

**Comment by crazy-max** [comment]
@felixoi Do you have a link to your repo/workflow?

**Comment by felixoi** [comment]
@crazy-max 
Broken: https://github.com/SpongePowered/sponge-docs-theme/blob/master/.github/workflows/build.yml
Working (with push afterwards): https://github.com/SpongePowered/sponge-docs-theme/blob/103f660b14434f5532686b860958006c8eb8b4e9/.github/workflows/build.yml

**Comment by crazy-max** [comment]
@felixoi Looks like [an issue with Nexus registry](https://issues.sonatype.org/browse/NEXUS-18546?focusedCommentId=939077&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-939077) while [pushing the manifest](https://github.com/SpongePowered/sponge-docs-theme/runs/1470499259?check_suite_focus=true#step:6:182) `docker-registry.spongepowered.org/sponge-docs-theme:master`.

**Comment by felixoi** [comment]
We actually fixed it.

We redirected based on the user agent
```
if ($http_user_agent ~* ".*docker.*") {
        proxy_pass http://registry;
}
```
but it seems like buildx is using a different user agent which does not contain docker for pushing the manifest.
So the question is now what user agent is it using?

**Comment by crazy-max** [comment]
@felixoi Maybe `.*containerd.*`? WDYT @tonistiigi?

**Comment by felixoi** [comment]
Whatever it is, having it in the documentation somewhere would be nice.
I expect it to contain docker without any documentation.

**Comment by tonistiigi** [comment]
User-agent value is not part of the distribution specification.

**Comment by felixoi** [comment]
So this question is wrong in this repo? Where does it belong then?
