### ISSUE TITLE
multi platform with multi tags, buildx error

### ISSUE THREAD

**Issue by yywing** [docker/buildx#459]
docker buildx build --platform linux/amd64,linux/arm64 --push --pull -t xxxxxx/test:1 -t xxxxxx/test:2 -f nginx.Dockerfile .

```bash
 => ERROR merging manifest list xxxxxxx/test:1,xxxxxx/test:2         1.5s
------
 > merging manifest list xxxxxxx/test:1,xxxxxxx/test:2:
------
```

**Comment by yywing** [comment]
And I try to push to dockerhub, and I found build success， but only push the first tag.

**Comment by morlay** [comment]
buildkit issue.

create builder with `--driver-opt=image=moby/buildkit:v0.8.0`

**Comment by petethepig** [comment]
> create builder with --driver-opt=image=moby/buildkit:v0.8.0

This didn't work for me. Does anyone know of some other workaround? regular `docker tag` / `docker push` commands only work with one arch

**Comment by petethepig** [comment]
I figured it out. Here's the workaround I'm using right now:
```shell
docker buildx build --tag foo/bar:1.0.0 --platform linux/amd64,linux/arm64 .
docker manifest inspect foo/bar:1.0.0
# returns a json with 2 shas:
# {
#    "schemaVersion": 2,
#    "mediaType": "application/vnd.docker.distribution.manifest.list.v2+json",
#    "manifests": [
#       {
#          "mediaType": "application/vnd.docker.distribution.manifest.v2+json",
#          "size": 1992,
#          "digest": "sha256:c3ab8ff13720e8ad9047dd39466b3c8974e592c2fa383d4a3960714caef0c4f2",
#          "platform": {
#             "architecture": "arm64",
#             "os": "linux"
#          }
#       },
#       {
#          "mediaType": "application/vnd.docker.distribution.manifest.v2+json",
#          "size": 1992,
#          "digest": "sha256:974e592c2fa383d4a3960714caef0c4f2c3ab8ff13720e8ad9047dd39466b3c8",
#          "platform": {
#             "architecture": "amd64",
#             "os": "linux"
#          }
#       }
#    ]
# }
# replace shas with the ones you got from the previous command:
docker manifest create foo/bar:latest \
  foo/bar@sha256:c3ab8ff13720e8ad9047dd39466b3c8974e592c2fa383d4a3960714caef0c4f2 \
  foo/bar@sha256:974e592c2fa383d4a3960714caef0c4f2c3ab8ff13720e8ad9047dd39466b3c8

```

^ this will first build a multi-arch image with tags `1.0.0` and `latest`

**Comment by morlay** [comment]
@petethepig which version of buildx you used?

**Comment by petethepig** [comment]
@morlay 
```
$ docker buildx version
github.com/docker/buildx v0.5.1-docker 11057da37336192bfc57d81e02359ba7ba848e4a
```

**Comment by morlay** [comment]
@petethepig strange. 

do you create a new builder with 

`docker buildx create --use --driver-opt=image=moby/buildkit:v0.8.0` 

it works well https://github.com/kiali/kiali/pull/3405#issuecomment-725795067
multi tag published https://quay.io/repository/kiali/kiali?tag=latest&tab=tags

**Comment by petethepig** [comment]
not sure if it matters, but I also use 2 separate machines like this:
```shell
docker buildx create --use --name mybuilder --driver-opt=image=moby/buildkit:v0.8.0 --platform linux/arm64
docker buildx create --append --name mybuilder secondmachine --driver-opt=image=moby/buildkit:v0.8.0 --platform linux/amd64
```

**Comment by morlay** [comment]
@petethepig I use 2 separate machines too. multi tag publishing works well. 

try with `moby/buildkit:v0.8.1`?

**Comment by petethepig** [comment]
@morlay thanks! I'll try it soon, not today, but in the next few days.

**Comment by yywing** [comment]
> moby/buildkit:v0.8.1

not work for me - -
