### ISSUE TITLE
Add build option "--hostname" for buildx to be able to customize hostname during build image

### ISSUE THREAD

**Issue by ShemTovYosef** [docker/buildx#474]
Hi,

As part of this task: https://github.com/moby/buildkit/issues/1301 buildkit now supports for customizing hostname like this:
buildctl build --frontend=dockerfile.v0 --local dockerfile=. --local context=. **--opt hostname=testtest**

I want to ask to add this ability to buildx itself to be able to use it like:
docker build --hostname=testtest -t host .

Thanks,
Yosef

**Comment by tonistiigi** [comment]
I guess we can start by adding a build-arg with `BUILDKIT_` prefix like we do for some other options.

**Comment by hinews** [comment]
Hi @tonistiigi 

At this moment can we call buildx by specifying buildkit options, i.e., if I want to call "--opt hostname=testtest" of buildctl by buildx, is any way to do it?
Like this one but it's not working:
docker buildx create --use --name builder-with-opts  --driver docker-container --driver-opt hostname=testtest

**Comment by tonistiigi** [comment]
we shouldn't set it per builder, but per build. `docker buildx build --build-arg BUILDKIT_SANDBOX_HOSTNAME= .`

**Comment by hinews** [comment]
I got regarding the name for parameter 
Wondering how to run it today without this change by using buildx

**Comment by hinews** [comment]
@jingxiaolu could you comment if it's possible to use hostname customization by configuring buildx or needs to use buildctl directly?

**Comment by ShemTovYosef** [comment]
ping if someone interested to implement it

**Comment by ShemTovYosef** [comment]
Any updates on this issue?

**Comment by ShemTovYosef** [comment]
Or any workaround how to pass buildkit options from buildx?

**Comment by li-zhixin** [comment]
Any updates on this issue?

**Comment by ShemTovYosef** [comment]
HI @jingxiaolu 
Maybe you will have a time to help with it and finish the final step?

**Comment by totszwai** [comment]
So how do we set hostname with this?

**Comment by ShemTovYosef** [comment]
Just to use build arg https://github.com/moby/buildkit/pull/2373
