### ISSUE TITLE
Push moby/buildkit:buildx-stable-1-rootless

### ISSUE THREAD

**Issue by AkihiroSuda** [docker/buildx#479]
https://github.com/docker/buildx/blob/v0.5.1/driver/bkimage/bkimage.go

Currently, rootful image points to "moby/buildkit:buildx-stable-1" while rootless points to  "moby/buildkit:v0.6.2-rootless".

Can we tag "moby/buildkit:v0.8.1-rootless" as "moby/buildkit:buildx-stable-1-rootless" and specify that in `bkimage.go`?

**Comment by tonistiigi** [comment]
`moby/buildkit:buildx-stable-1-rootless` has been created

**Comment by crazy-max** [comment]
I think it should be automated through CI on buildkit repo or change default tags here? (https://github.com/docker/buildx/issues/419#issuecomment-737732837)

**Comment by tonistiigi** [comment]
I do some manual testing before `buildx-stable-1` tag usually so I can be the next day sometimes. Not a big issue as just one simple command to run (as long as someone remembers to ping me).

**Comment by tonistiigi** [comment]
Also there could be a release where we choose to do `buildx-stable-2` instead.

**Comment by AkihiroSuda** [comment]
Thanks, opened https://github.com/docker/buildx/pull/480 to use the new image.

**Comment by crazy-max** [comment]
> I do some manual testing before `buildx-stable-1` tag usually so I can be the next day sometimes. Not a big issue as just one simple command to run (as long as someone remembers to ping me).

Ok got it!
