### ISSUE TITLE
docker build doesn't appear to respect memory limit

### ISSUE THREAD

**Issue by daveisfera** [docker/buildx#483]
- [X] I have tried with the latest version of my channel (Stable or Edge)
  - [X] I have uploaded Diagnostics
  - Diagnostics ID: C18223FD-44DC-4ACD-B197-B660FC33917F/20201217162954

### Expected behavior
`docker build` would respect `--memory` and `--memory-swap` like before

### Actual behavior
Builds keep crashing because of OOM killer

### Information
  - macOS Version: 11.0.1

### Diagnostic logs
This isn't in Docker Desktop anymore

### Steps to reproduce the behavior
Run a build that requires a lot of memory (like a large `webpack` bundle)

**Comment by crazy-max** [comment]
Duplicate https://github.com/docker/buildx/issues/292 https://github.com/docker/buildx/issues/359
