### ISSUE TITLE
imagetools create should support copying images between repositories

### ISSUE THREAD

**Issue by crazy-max** [docker/buildx#486]
It's [currently not possible to create a new image based on source images with multiple repositories](https://github.com/docker/buildx/blob/d1a46faf8475564fbb27c9228b79a806e59b8f65/commands/imagetools/create.go#L79):

```
multiple repositories currently not supported, found map[docker.io/crazymax/diun:{} localhost:5000/name/app:{}]
```

**Comment by sylr** [comment]
Seconded, I'm currently doing two separate builds to push to 2 different repos.

Doing that results on having two different sha256 for the multi-arch image despite the layer of both being identical.
