### ISSUE TITLE
Crash when Comment on EXPOSE  line

### ISSUE THREAD

**Issue by tqh** [docker/buildx#487]
If you have a line
`EXPOSE 8080 #Some info`
docker build works, but docker buildx crashes with
...
failed to solve: rpc error: code = Unknown desc = failed to solve with frontend dockerfile.v0: failed to create LLB definition: Invalid containerPort: #

**Comment by crazy-max** [comment]
@tqh 

> `failed to solve: rpc error: code = Unknown desc = failed to solve with frontend dockerfile.v0: failed to create LLB definition: Invalid containerPort: #`

This is the expected behavior:

```
$ docker run --rm -i hadolint/hadolint < Dockerfile
/dev/stdin:37:13 unexpected '#' expecting '\', a new line followed by the next instruction, a port range optionally followed by the protocol (udp/tcp), a port with its protocol (udp/tcp), a valid port number, a variable, or at least one space
```

See also https://github.com/hadolint/hadolint/wiki/DL3011.

> docker build works

Not for me with `docker build` (19.03.14):

```
Step 10/15 : EXPOSE 8080 # Some info
Invalid containerPort: #
```

**Comment by tqh** [comment]
Reran the build, and you are right. It is just that docker build is much more silent about the error.
