### ISSUE TITLE
issue in building dockerfile

### ISSUE THREAD

**Issue by harsh6768-svg** [docker/buildx#507]
ERROR [internal] load metadata for docker.io/library/python:3.6                                                                                                        30.0s 
------
 > [internal] load metadata for docker.io/library/python:3.6:
------
failed to solve with frontend dockerfile.v0: failed to create LLB definition: failed to do request: Head https://registry-1.docker.io/v2/library/python/manifests/3.6: dial tcp 3.211.199.249:443: i/o timeout
why Im getting this error someone help???

**Comment by tonistiigi** [comment]
Looks like a network issue communicating with the registry.

**Comment by harsh6768-svg** [comment]
@tonistiigi thanks

**Comment by wrewolf** [comment]
Have same issue, but I can download manifest by curl

**Comment by malith1992** [comment]
> Looks like a network issue communicating with the registry.

How to fix the issue ?
