### ISSUE TITLE
Buildx failing to build for arm/v7 platform on arm64 machine

### ISSUE THREAD

**Issue by antoninbas** [docker/buildx#511]
I have the following builder, which should be able to build images for arm64 and arm/v7:
```
Name:   mybuild
Driver: docker-container

Nodes:
Name:      mybuild0
Endpoint:  unix:///var/run/docker.sock
Status:    running
Platforms: linux/arm64, linux/arm/v7, linux/arm/v6
```

I have the following Dockerfile:
```
FROM ubuntu:20.04
RUN date && sleep 10
```

I I run `sudo docker buildx build --platform linux/arm64 --pull .`, the image builds without issue. However, if I try to run `sudo docker buildx build --platform linux/arm/v7 --pull .`, I get the following:
```
 => ERROR [2/2] RUN date && sleep 10                                                                                                                                                                                                     0.3s
------
 > [2/2] RUN date && sleep 10:
#5 0.173 Tue May 26 11:21:31 UTC 1970
#5 0.175 sleep: cannot read realtime clock: Operation not permitted
```

I have confirmed that I can run containers without issue on my arm64 host, for either architecture:
```bash
####
$ sudo docker run --platform linux/arm/v7 ubuntu:20.04 bash -c "date && sleep 10 && date"
Wed Jan 20 03:01:54 UTC 2021
Wed Jan 20 03:02:04 UTC 2021
####
$ sudo docker run --platform linux/arm64 ubuntu:20.04 bash -c "date && sleep 10 && date"
Wed Jan 20 03:02:31 UTC 2021
Wed Jan 20 03:02:41 UTC 2021
#### failure expected, can't run amd64 binaries on arm64 host
$ sudo docker run --platform linux/amd64 ubuntu:20.04 bash -c "date && sleep 10 && date"
standard_init_linux.go:219: exec user process caused: exec format error
```

I saw multiple reports online pointing to an issue with libseccomp and recommending to update both docker and libseccomp on the host. However, both of them were recent "enough" in my case (20.10.2 for docker, 2.4.3-1ubuntu1 for libseccomp2). I even tried to install the most recent version of libssecomp - 2.5.1 - to no avail.

What's very interesting is if I start using `ubuntu:18.04` as my base image - instead of `ubuntu:20.04` - the buildx build can succeed without issue.

**Comment by antoninbas** [comment]
Note that `sudo DOCKER_BUILDKIT=1 docker build --platform linux/arm/v7 .` works fine, so that's what I am using for now.

**Comment by tonistiigi** [comment]
What version of buildkit are you using. `docker run -it --rm $(docker inspect  -f {{.Image}} buildx_buildkit_ mybuild0) --version` . Can't reproduce on my side.

**Comment by antoninbas** [comment]
I installed everything yesterday using `get-docker.sh`

```bash
$ docker run -it --rm $(docker inspect -f {{.Image}} buildx_buildkit_mybuild0) --version
buildkitd github.com/moby/buildkit v0.8.1 8142d66b5ebde79846b869fba30d9d30633e74aa
```

```bash
$ docker version
Client: Docker Engine - Community
 Version:           20.10.2
 API version:       1.41
 Go version:        go1.13.15
 Git commit:        2291f61
 Built:             Mon Dec 28 16:17:56 2020
 OS/Arch:           linux/arm64
 Context:           default
 Experimental:      true

Server: Docker Engine - Community
 Engine:
  Version:          20.10.2
  API version:      1.41 (minimum version 1.12)
  Go version:       go1.13.15
  Git commit:       8891c58
  Built:            Mon Dec 28 16:15:55 2020
  OS/Arch:          linux/arm64
  Experimental:     false
 containerd:
  Version:          1.4.3
  GitCommit:        269548fa27e0089a8b8278fc4fc781d7f65a939b
 runc:
  Version:          1.0.0-rc92
  GitCommit:        ff819c7e9184c13b7c2607fe6c30ae19403a7aff
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0
```

```bash
$ uname -a
Linux antrea-build-1 5.4.0-42-generic #46-Ubuntu SMP Fri Jul 10 00:24:02 UTC 2020 aarch64 aarch64 aarch64 GNU/Linux
```

**Comment by tonistiigi** [comment]
@thaJeztah Only difference I see between moby and buildkit seccomp profiles is `pidfd*` that isn't likely to be an issue. Are you sure docker's profile is used instead containerd's one in v0.8.1?

**Comment by antoninbas** [comment]
Sorry for the delay, I missed your question earlier. Here is the output:
```
$ docker run --privileged --rm tonistiigi/binfmt
Unable to find image 'tonistiigi/binfmt:latest' locally
latest: Pulling from tonistiigi/binfmt
c6bd8deb4c33: Pull complete
9d3f65ed5a10: Pull complete
Digest: sha256:df15403e06a03c2f461c1f7938b171fda34a5849eb63a70e2a2109ed5a778bde
Status: Downloaded newer image for tonistiigi/binfmt:latest
{
  "supported": [
    "linux/arm64",
    "linux/arm/v7",
    "linux/arm/v6"
  ],
  "emulators": null
}
```

By the way, I was able to reproduce this on an AWS EC2 ARM instance, so this doesn't seem specific to my environment. Here are the steps:

1. Create an EC2 instance. Use the `Ubuntu Server 20.04 LTS (HVM)` AMI (check the `64-bit (Arm)` option!). For the instance type, I used `a1.large` but `a1.medium` should work just as well.
2. SSH to the instance (username is `ubuntu` by default)
3. Install the latest docker version with `get-docker.sh` and add `ubuntu` user to `docker` group
4. Create the builder: `docker buildx create --name mybuild; docker buildx use mybuild; docker buildx inspect --bootstrap`. This should give the following output:
```
Name:   mybuild
Driver: docker-container

Nodes:
Name:      mybuild0
Endpoint:  unix:///var/run/docker.sock
Status:    running
Platforms: linux/arm64, linux/arm/v7, linux/arm/v6
```
5. Create a Dockerfile in a new directory with the following contents:
```
FROM ubuntu:20.04
RUN date && sleep 10
```
6. Run `docker buildx build --platform linux/arm64 --pull .` --- This works
7. Run `docker buildx build --platform linux/arm/v7 --pull .` --- This fails!

**Comment by tonistiigi** [comment]
https://github.com/moby/buildkit/pull/1955
