### ISSUE TITLE
Build succesfully on my pi but fail with buildx and qemu on github action 

### ISSUE THREAD

**Issue by tygerlord** [docker/buildx#512]
I can build on target host with classic build but fail with buildx build on github action

https://github.com/tygerlord/docker-domoticz-dev/actions/runs/503707899

Help welcome,

**Comment by tygerlord** [comment]
Perhaps due to cmake

I continue to investigate

**Comment by tonistiigi** [comment]
PTAL https://gitlab.kitware.com/cmake/cmake/-/issues/20568

**Comment by tygerlord** [comment]
Ok, seems related to 'cmake'. I close the issue for now.

**Comment by tygerlord** [comment]
Successfully build cmake under buildx with add to Dockerfile:

ENV CFLAGS=-D_FILE_OFFSET_BITS=64
ENV CXXFLAGS=-D_FILE_OFFSET_BITS=64
