### ISSUE TITLE
Why docker build can not distinguish flag "output"?

### ISSUE THREAD

**Issue by tintinlam007** [docker/buildx#513]
1. My operation system is Ubuntu 20.04
2. My docker version is 18.09.6
sudo docker version
Client:
 Version:           18.09.6
 API version:       1.39
 Go version:        go1.10.8
 Git commit:        481bc77
 Built:             Sat May  4 02:35:57 2019
 OS/Arch:           linux/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          18.09.6
  API version:      1.39 (minimum version 1.12)
  Go version:       go1.10.8
  Git commit:       481bc77
  Built:            Sat May  4 01:59:36 2019
  OS/Arch:          linux/amd64
  Experimental:     false

2. make install reports error: 
sudo make install
./hack/binaries
+ DOCKER_BUILDKIT=1
+ docker build --target binaries --output type=local,dest=./bin/ .
unknown flag: --output
See 'docker build --help'.
make: *** [Makefile:5: binaries] Error 125

Thank you!!

**Comment by thaJeztah** [comment]
The output option was added in docker 19.03, older versions didn't have that flag. Note that docker 18.09 reached EOL two years ago, and is no longer maintained, so I'd recommend updating to a supported version.

Closing this ticket, because of the above, but feel free to continue the conversation
