### ISSUE TITLE
failed to solve with frontend dockerfile.v0: failed to read dockerfile: open /tmp/buildkit-mount946775422/dockfile: no such file or directory

### ISSUE THREAD

**Issue by tintinlam007** [docker/buildx#514]
1. OS: Ubuntu 20.04

2. Docker version: 20.10.2

3. The command:
sudo docker buildx build --file dockfile --output type=local,dest=./my-golang-rocksdb-4.13-arm64.tar.gz --platform linux/arm64 --tag my/golang:rocksdb-4.13-arm64 .

4. The dockerfile:
FROM my/golang:rocksdb-4.13

5. The result:
[+] Building 0.0s (1/2)                                                        
 => [internal] load build definition from dockfile                        0.0s
 => => transferring dockerfile: 2B                                        0.0s
error: failed to solve: rpc error: code = Unknown desc = failed to solve with frontend dockerfile.v0: failed to read dockerfile: open /tmp/buildkit-mount946775422/dockfile: no such file or directory

Thank you !

**Comment by tonistiigi** [comment]
Means that you don't have file called `dockfile` in your working directory.

**Comment by anirugu** [comment]
Thanks @tonistiigi I finally solve this.
