### ISSUE TITLE
failed to create LLB definition

### ISSUE THREAD

**Issue by tintinlam007** [docker/buildx#515]
s@ubuntu:~/dev/docker-test$ ./build-command.sh 
WARN[0000] No output specified for docker-container driver. Build result will only remain in the build cache. To push result image into registry use --push or to load image into docker use --load 
[+] Building 0.1s (3/3) FINISHED                                               
 => [internal] load build definition from dockerfile                      0.0s
 => => transferring dockerfile: 89B                                       0.0s
 => [internal] load .dockerignore                                         0.0s
 => => transferring context: 2B                                           0.0s
 => ERROR [internal] load metadata for localhost:5000/hyperledger/golang  0.0s
------
 > [internal] load metadata for localhost:5000/hyperledger/golang:rocksdb-4.13:
------
error: failed to solve: rpc error: code = Unknown desc = failed to solve with frontend dockerfile.v0: failed to create LLB definition: failed to do request: Head http://localhost:5000/v2/hyperledger/golang/manifests/rocksdb-4.13: dial tcp 127.0.0.1:5000: connect: connection refused
s@ubuntu:~/dev/docker-test$ cat ./build-command.sh 
export DOCKER_BUILDKIT=0
export COMPOSE_DOCKER_CLI_BUILD=0
sudo docker buildx build --platform linux/arm64 .

============================================
My OS is  Ubuntu20.04, docker version is 20.10.2. I has an docker registry locally, and the comand "buildx" seems to load the metadata from the tag which end by colon?
When I copy+paste the address without the last colon(http://localhost:5000/v2/hyperledger/golang/manifests/rocksdb-4.13) on to explorer, it can respond metadata!

Thand you!!

**Comment by tonistiigi** [comment]
If you want builder running in a container to have access to the registry at `localhost` you need to run it in host network namespace. `buildx create --driver-opt network=host`
