### ISSUE TITLE
Copy with wildcards is not working as expected

### ISSUE THREAD

**Issue by kDanil** [docker/buildx#519]
- [x] I have tried with the latest version of Docker Desktop
  - [x] I have tried disabling enabled experimental features
  - [x] I am using the Docker WSL2 Backend
  - [x] I am using the Docker Hyper-V Backend

Latest Doker Desktop
Docker version 20.10.2, build 2291f61

### Actual behavior

`COPY integration_tests/*/*.csproj ./` is resulting into error   
```
docker/for-win#8 [internal] load build context
docker/for-win#8 sha256:204e936fdd2093e170c6c0a374647f9397af1c00993bb3347960c112160b8a1d
docker/for-win#8 transferring context: 105B done
docker/for-win#8 ERROR: error from sender: readdir: open integration_tests\*: The filename, directory name, or volume label syntax is incorrect.
```
but `COPY integration_tests/* ./` is working just fine

### Expected behavior

`COPY integration_tests/*/*.csproj ./` should copy all files with extension `.csproj` from all subdirectories 

### Information

I have a docker file with command described above which is working fine on many machines, but not on my brand new Dell laptop. I'm running Win10 Pro and have tried WSL2 and Hyper-V backends with no success.
I reinstall Docker twice, and read every suggestions from internet, but failed to fix it.
I have tried different images, but result is the same. 

Any ideas? 

### Steps to reproduce the behavior
Folder structure:
..
--Dockerfile
--integration_tests
----A
------A.test.csproj
----B
------B.test.csproj

Docker file like this will reproduce issue for me:

```
FROM mcr.microsoft.com/dotnet/core/sdk:3.0-alpine AS build-image
WORKDIR /app

COPY integration_tests/*/*.csproj ./ 
```

Thanks

**Comment by tonistiigi** [comment]
Duplicate https://github.com/moby/buildkit/issues/1900
