### ISSUE TITLE
buildx ignore local repository

### ISSUE THREAD

**Issue by VladoPortos** [docker/buildx#522]
I have strange issue. I use local docker repository:

Entry in /etc/hosts:
`192.168.0.232 registry registry.cube.local`

```
ubuntu@control01:~/openfaas_scripts/build/mailme$ nslookup registry.cube.local
Server:         127.0.0.53
Address:        127.0.0.53#53

Non-authoritative answer:
Name:   registry.cube.local
Address: 192.168.0.232
```

```
ubuntu@control01:~/openfaas_scripts/build/mailme$ resolvectl query registry.cube.local
registry.cube.local: 192.168.0.232

-- Information acquired via protocol DNS in 2.8ms.
-- Data is authenticated: yes
```

I tested tag and push to registry and that worked fine:

```
ubuntu@control01:~/openfaas_scripts/build/mailme$ curl https://registry.cube.local:5000/v2/_catalog     
{"repositories":["my-ubuntu"]}
```

However running:
`docker buildx build .  --progress=plain --platform=linux/arm64 --output=type=registry,push=true --tag registry.cube.local:5000/mailme:latest`

Fails with:

```
#25 exporting to image
#25 sha256:e8c613e07b0b7ff33893b694f7759a10d42e180f2b4dc349fb57dc6b71dcab00
#25 exporting layers done
#25 exporting manifest sha256:0875dd210a5077c696c44ae52b496b9be9598cf52509fc99901b1890a48b50bb 0.0s done
#25 exporting config sha256:7b8387e2868248f5485f931c21c19c490bba4a0cfbc7bbd9b6c66c9794b0f1ac
#25 exporting config sha256:7b8387e2868248f5485f931c21c19c490bba4a0cfbc7bbd9b6c66c9794b0f1ac 0.1s done
#25 pushing layers 0.0s done
#25 ERROR: failed to do request: Head https://registry.cube.local:5000/v2/mailme/blobs/sha256:5eed6c177177da043a0b227e629050c9a5b70dbff434d02c7303da47a1d0f26b: dial tcp: lookup registry.cube.local on 1.1.1.1:53: no such host
------
 > exporting to image:
------
error: failed to solve: rpc error: code = Unknown desc = failed to do request: Head https://registry.cube.local:5000/v2/mailme/blobs/sha256:5eed6c177177da043a0b227e629050c9a5b70dbff434d02c7303da47a1d0f26b: dial tcp: lookup registry.cube.local on 1.1.1.1:53: no such host
```
Why is it looking in DNS and ignoring /etc/hosts ? 

My nsswitch use files first:

`hosts:          files dns`

I can't explain from where it took the 1.1.1.1:53 is that hardcoded in or something ? I removed that DNS from host and it still ask 1.1.1.1, whats going on ?

**Comment by VladoPortos** [comment]
Ok I'm bit closer:

I can add custom DNS to /etc/docker/daemon.json and it will use these instead 1.1.1.1 which docker took from who knows where... Issue still exists though, as thsi way the entries in  /etc/hosts are ignored ( reading from 192.168.0.1, which is systemd-resolve ) this is super annoying

**Comment by VladoPortos** [comment]
And bit closer again.

So, the buildx is running in container, it therefore make sense that it have its own /etc/hosts and no certificate for private registry... now only to find some permanent way to "patch" that stuff in :D

**Comment by tonistiigi** [comment]
You can run buildkit container with host network with `--driver-opt network=host`. For custom registry config can use `--config` but for certificate files currently need to copy them into container yourself or build a modified buildkit image that adds your certificates.

**Comment by VladoPortos** [comment]
Thanks @tonistiigi I solved the issue wit following from older posts here ( I would credit the person, I just can't find it at the moment )

```
BUILDER=$(sudo docker ps | grep buildkitd | cut -f1 -d' ')
sudo docker cp YOUR-CA.crt $BUILDER:/usr/local/share/ca-certificates/
sudo docker exec $BUILDER update-ca-certificates
sudo docker restart $BUILDER
```
 That added certificate and manual edit of mounted /etc/hosts to know where my registry is and than it worked fine. 
 
 Whole ordeal is related bit to OpenFaas which use buildx and the commands are baked in faas-cli so I did not want to go and edit source code for that :D
