### ISSUE TITLE
Reference Stored Secrets in Dockerfile

### ISSUE THREAD

**Issue by clairmont32** [docker/buildx#525]
Hi, sorry if I missed the previous issue if this is a dupe (I did briefly search). I noticed that there are no docs or blog posts on using a previously stored secret with `docker secret create` in a Dockerfile using buildkit. Is this something currently doable or can be a feature request? 

It seems like it would be a great security feature for Dockerfiles since you wouldn't need to have the secret in a file each time the image is built.

**Comment by tonistiigi** [comment]
`docker secret create` creates a secret in swarm cluster that can be used inside the swarm services. A builder can't see these secrets. If you really want to use it you may be able to run your client inside the swarm service, but then you need to figure out a plan how to connect to buildkit API (eg. expose a socket or run in host network).

**Comment by clairmont32** [comment]
Gotcha. Thanks for the response. I guess really the only way to do secrets within Dockerfiles is to reference a text file as the source?
