### ISSUE TITLE
Use buildx to build on remote server (tcp + tls)

### ISSUE THREAD

**Issue by Leletir** [docker/buildx#543]
Hi,

I'm trying to use buildx to send build to a remote server (running docker 20.10.3). The daemon is exposed via TCP and securized via TLS.

First, I've created a context: 
```bash
docker context create tls-context --description "Test for TLS" --docker "host=tcp://$BUILDER_IP:2376,ca=ca.pem,cert=cert.pem,key=key.pem"
```

It works as I can use: 
```bash
docker -c  tls-context ps
```

Once done, I'm creating a builder instance: 
```bash
docker buildx create --name tls-builder --use tls-context
```

Which gave me:

```bash
docker buildx ls
NAME/NODE      DRIVER/ENDPOINT  STATUS   PLATFORMS
tls-builder *  docker-container
  tls-builder0 tls-context      inactive
tls-context    docker
  tls-context  tls-context      running  linux/amd64, linux/386
default        docker
  default      default          running  linux/amd64, linux/386
```

Furthermore, if I try to create a builder instance with the docker driver:
```bash
docker buildx create --name tls-builder2 --use tls-context --driver docker
```

I have the following error: ```error: failed to find driver "docker"```

Is it possible to create a remote builder with the docker driver ?

To give you more context, I'm trying to launch a build from a CI system (gitlab-ci) to a remote docker daemon (exposed via TCP + TLS) and enjoy the cache on this remote server. I will push the image from the server hosting the builder directly to the repository.

**Comment by tonistiigi** [comment]
I don't understand. What was the problem you hit with using the container driver? You can't create instances of "docker" driver because only one is builtin to docker. If you want to use the one from your tls-context then just run `docker buildx use tls-context`
