### ISSUE TITLE
Docker build fail .token_seed: unexpected end of JSON input

### ISSUE THREAD

**Issue by mariusdkm** [docker/buildx#547]
I was building my docker image on MacOS 11.2.1, when I came across the following issue:
If i remember correctly I stopped a build process in the middle, and after changing something I ran it again.
(My build file contains 3 stages.)

```
Failed to solve with frontend dockerfile.v0: failed to create LLB definition: rpc error: code = Unknown desc = failed to parse /Users/myusername/.docker/.token_seed: unexpected end of JSON input
```

Build command:
`docker build -f webserver/Dockerfile.webserver . -t webserver`
Docker version:
`Docker version 20.10.0, build 03fa4b8`
And I have `DOCKER_BUILDKIT` set to `1`

In order to fix this I had tried:
* Deleting all local Images.
* `Clean / Purge data` from the Docker app
* And of course restarting docker multiple times...
* Deleting `token_seed.lock`
* Logging in and out in the Docker app

In the end the solution was to delete `.token_seed` and `.token_seed.lock` inside of `/Users/myusename/.docker`

**Comment by tonistiigi** [comment]
Can you report what was the contents of `.token_seed`

**Comment by mariusdkm** [comment]
I'm sorry, but I just deleted the `.token_seed` file and everything worked fine after that.

**Comment by jongiddy** [comment]
I saw this problem too. The `.token_seed` file was empty. This occurred at around the same time as I had a full disk condition, so may be related to that.

**Comment by ndepal** [comment]
I just had the same issue, also after running out of disk space. Deleting `~/.docker/.token_seed` and `~/.docker/.token_seed.lock` did the trick. I'm using `Docker version 20.10.2, build 20.10.2-0ubuntu1~18.04.2`

**Comment by crazy-max** [comment]
Fixed by moby/buildkit#2050

**Comment by kevintcaron** [comment]
A note to mac users with this issue.  
When you go to /Users/myusename/.docker you may need to "Press Command + Shift + . (period)" to reveal hidden files.  For me, my .token_seed and .token_seed.lock files did not appear to exist until I used the command to show hidden files.
Once you can see them, deleting both files as suggested by @mariusdkm works pwrfectly!

**Comment by huanlirui** [comment]
> 给有此问题的 mac 用户的说明。 当您转到 /Users/myusename/.docker 时，您可能需要“按 Command + Shift + .（句点）”来显示隐藏文件。对我来说，在我使用命令显示隐藏文件之前，我的 .token_seed 和 .token_seed.lock 文件似乎并不存在。 看到它们后，按照建议删除这两个文件@mariusdkm作品！

thanks! thanks! thanks!  I can leave work early ！
