### ISSUE TITLE
Daemonless + Rootless builds?

### ISSUE THREAD

**Issue by springroll12** [docker/buildx#548]
Does buildx support building without a buildkit daemon? My understanding is that it does not. This would be a great asset for those looking to build in Kubernetes.

So far the only buildkit-based image generator I've seen that does this is genuinetools/img and it does not have all the nifty cache features that buildx does.

Also, I understand that buildkit (buildkit client or daemon?) can run in unprivileged mode.. is the same true of buildx?

**Comment by AkihiroSuda** [comment]
Daemonless + Rootless is here, but not integrated to BuildX CLI 
 https://github.com/moby/buildkit/blob/master/examples/kubernetes/job.rootless.yaml
