### ISSUE TITLE
Mismatch in TARGETARCH for Apple Silicon M1

### ISSUE THREAD

**Issue by tunecrew** [docker/buildx#550]
I have a development dockerfile being used on both M1 and Intel (macOS) machines.

Because of this, it needs to `COPY` some libraries between build stages that sit in architecture-specific directories, .e.g `usr/lib/x86-linux-gnu`.

In order to do this I have been trying to use the built-in `TARGETARCH` variable, however, the following problem occurs:

```
docker/for-mac#30 0.446 uname -m: aarch64
docker/for-mac#30 0.446 TARGETARCH: arm64
```

In the base image that I'm working with, `python:3.9.2-slim-buster`, the directory is `/usr/lib/aarch64-linux-gnu`. Using `TARGETARCH` as follows breaks, because `TARGETARCH` is reporting `arm64` instead of `aarch64`

```
COPY --from=build-base /usr/lib/${TARGETARCH}-linux-gnu/mylib.so /usr/lib/${TARGETARCH}-linux-gnu/
```

A short term fix would be to either pass the correct ARCH as a build argument from a build script, or to use some conditional based shell renaming in the dockerfile inside of a `RUN` command, but these both feel hacky.

Any thoughts? Am I missing something obvious?

**Comment by tonistiigi** [comment]
We use the architecture names as defined by Go https://gist.github.com/asukakenji/f15ba7e588ac42795f421b48b8aede63#a-list-of-valid-goarch-values and some normalizations as defined in https://github.com/containerd/containerd/blob/master/platforms/platforms.go#L80-L96 . There are a million exceptions of different systems using different names, eg. look at https://github.com/tonistiigi/xx/pull/14/files#diff-2e3d3a4d78f2753f9464b79e8ac808928efdaeb5e0976104bad6f360448ad856 for my effort to bring some sanity into it. You need to use conversions for your specific case where needed.

Not that it matters in this case but Apple also uses `arm64` as architecture name in M1.
