### ISSUE TITLE
Docker produces different images when building a Rust program on macOS (Docker Desktop) versus on Ubuntu

### ISSUE THREAD

**Issue by felix-pb** [docker/buildx#554]
### Information
  - [x] I have tried with the latest version of Docker Desktop*
  - [x] I have tried disabling enabled experimental features
  - [ ] I have uploaded Diagnostics
  - Diagnostics ID:

The problem is easily reproducible on my devices:
* macOS Version: `10.15.7` or `11.2.2`** + Docker Desktop Version: `3.1.0`
* Ubuntu Version: `18.04.4` + Docker Version: `19.03.6`

*Note that I cannot upgrade to Docker Desktop Version `3.2.0` because of [issue docker/for-mac#5406](https://github.com/docker/for-mac/issues/5406).
**Note that I tested this on two different macOS laptops, one running Catalina and one running Big Sur.

### Steps to reproduce the behavior
I'm using the latest stable version of Cargo (Rust's package manager): `1.50.0`.
  1. Create a new Rust project:
```
cargo new --bin playground && cd playground/
```
  2. Update `src/main.rs` with the following content:
```rust
use std::time::SystemTime;

fn main() {
    let now = SystemTime::now();
    println!("{:?}", now);
}
```
  3. Create a `Dockerfile` in the project's root directory and add the following content:
```Dockerfile
FROM rust:1.50 as builder
WORKDIR /usr/src
RUN cargo new --bin playground
WORKDIR /usr/src/playground
COPY Cargo.toml .
COPY Cargo.lock .
RUN cargo build --release
RUN rm -rf src
COPY src src
RUN cargo build --release

FROM ubuntu:18.04
COPY --from=builder /usr/src/playground/target/release/playground /usr/local/bin/playground
CMD [ "playground" ]
```
  4. Build the image:
```
docker build --tag playground_image .
```
  5. Run the container:
```
docker run --interactive --rm --name playground_container playground_image
```

### Actual behavior
When following the steps outlined above on macOS with Docker Desktop, I get the system time, e.g.:
```
SystemTime { tv_sec: 1614652600, tv_nsec: 426791496 }
```
However, when following the same steps on Ubuntu, I get the default Rust program output:
```
Hello, world!
```
It appears that the executable generated by the first `RUN cargo build --release` is cached when building on Ubuntu such that the second `RUN cargo build --release` doesn't do anything (while it rebuilds the executable on macOS).

### Expected behavior
I'm not sure which of two outputs is the "right" one, but I'm assuming that Docker Desktop should mimic the image built directly on the Docker Engine. As far as I understand, Docker should not produce different images when building the same thing on two different operating systems? Is this a bug in Docker Desktop or do I misunderstand how Docker is supposed to work?

Note that I can get consistent behavior on both operating systems if I fix the issue by adding `RUN cargo clean` before the second `RUN cargo build --release`. However, I still think it's problematic that I get different images without this fix.

**Comment by felix-pb** [comment]
Thanks for the quick reply @stephen-turner. I tried `DOCKER_BUILDKIT=1 docker build --tag playground_image .` on Ubuntu, but I get the same result as in the report above (i.e. `Hello, world!`). However, that's consistent with the explanation of buildkit you gave:

> It is true that buildkit optimises more intelligently, so that it will skip commands that don't contribute to the final output [...]

As per the report, it appears that the second `RUN cargo build --release` is skipped/optimized away on Ubuntu, and not on macOS. So for this particular case, it's the opposite: Docker Desktop is performing an extra step compared to Ubuntu. That said, I don't know if it has anything to do with buildkit.

**Comment by tonistiigi** [comment]
I'm not super familiar with the internals of rust compiler but the issue in here seems to be that `cargo build` does a timestamp comparison of the old source files (even if they are completely different what looks odd to me) and if they are not newer then doesn't actually recompile them but just returns old result. So it is a matter of how quickly the steps execute inside the builder. I assume there is a flag in cargo to avoid it, or maybe you are supposed to run `cargo clean`. I assume you have same problem for example when switching git branches.

 I tested it by adding `touch main.rs` before the second compile and it always worked correctly then(showing time). If I don't do that then the contents of `main.rs` is correct but if I run the binary straight after `cargo build` I can see that the build step actually ignored the source file.

**Comment by felix-pb** [comment]
@tonistiigi: Thanks for the reply! I'm not sure how `cargo build` works under the hood, but I think this is an issue with how docker uses caching. That said, I'm not so sure anymore that this is a Docker Desktop vs Docker Engine problem. On my laptop (running macOS v11.2.3 and Docker v3.1.0), I tried the following:

1. In the Docker Desktop dashboard, I clicked on "Clean / Purge data".
2. I performed the steps outlined above and I got `Hello, world!`, which is NOT the macOS behaviour I described in my original report.
3. I inserted an extra new line character at the end of `src/main.rs` (such that the file is 8 lines instead of 7). I then repeated the same `docker build`/`docker run` commands and I got `SystemTime { tv_sec: <num>, tv_nsec: <num> }`.
4. I kept the extra new line and I went back in the Docker Desktop dashboard and I clicked again on "Clean/Purge data". After that, I repeated again the same `docker build`/`docker run` commands and I got  `Hello, world!`.
5. I deleted the extra new line character (such that the file is back to 7 lines) and I ran again `docker build`/`docker run` and got `SystemTime { tv_sec: <num>, tv_nsec: <num> }`.

From the experiment above, it seems like the final image depends on what was cached initially (i.e. after purging data).
- I got opposite results in steps 2 and 5 although the app state is identical in those steps (`main.rs` = 7 lines).
- I got opposite results in steps 3 and 4 although the app state is identical in those steps (`main.rs` = 8 lines).

I only tried this on macOS, but I'll try it on Ubuntu later.

**Comment by tonistiigi** [comment]
Yes, this makes sense. Cargo only compares the source file timestamp to the timestamp of the last cargo-build (at least that is how I see it). So if you build first time then the files you create in dockerfile are newer(or at least depends on builder speed). Now if you modify your local source file and rebuild again the timestamp of your local files has changed so they are newer than previous cargo cache and so now the cargo-build executes again.

**Comment by felix-pb** [comment]
@tonistiigi: I'm afraid I don't understand your argument. I should specify that after step 3, if I simply remove the inserted new line and rebuild/rerun, I get `Hello, world!` again. I don't see how the source file timestamps fit with this.

Also, I just confirmed that this is not a Docker Desktop (macOS) vs Docker Engine (Ubuntu) problem. I performed the same 5 steps on Ubuntu (simply replacing "Clean/Purge data" with `docker system purge -a`) and I got identical results.

**Comment by felix-pb** [comment]
I still think this is an issue with docker caching and not with cargo, but I'm ready to be convinced otherwise. However, if we do agree that it's a docker issue, the title and original report or no longer accurate. Should we close this issue and open a new one? Or should I simply update the title/report of this issue?

**Comment by tonistiigi** [comment]
These commands simulate the behavior. You can just run them in `docker run -it --rm rust:1.50` container without a builder (or in your host if you want to)

```
# set up source
mkdir src
cat <<EOT >src/main.rs
use std::time::SystemTime;

fn main() {
    let now = SystemTime::now();
    println!("{:?}", now);
}
EOT

cargo new --bin playground && cd playground/
# note that hello-world is newer than hello-time

cargo build --release
./target/release/playground
# prints Hello, world!

# copy over your original sources, keeping timestamp
cp -a ../src/main.rs src/
cargo build --release
./target/release/playground
# prints Hello, world!
# cargo did not pick up your code changes

# now to your second build with change case
touch ../src/main.rs
# just update timestamp, same as code change
# repeat previous steps
cp -a ../src/main.rs src/
cargo build --release
./target/release/playground
# now prints SystemTime { tv_sec: 1615446442, tv_nsec: 696704700 }

```

**Comment by felix-pb** [comment]
@tonistiigi: Thanks, the commands above show the  timestamp-check behaviour of cargo pretty well. Now I'm trying to understand how that ties with docker. Earlier you said: 

> So if you build first time then the files you create in dockerfile(with cargo new) are newer(or at least depends on builder speed). Now if you modify your local source file and rebuild again the timestamp of your local files has changed so they are newer than previous cargo cache(cargo new did not run again so it still has old timestamps) and so now the cargo-build executes again.

If I understand correctly, the Dockerfile's `COPY` command will preserve the original timestamp (a bit like `cp -a`) for the copied file inside the container, right? I did a quick test that seems to confirm this, but I just want to be sure.

If that's correct, it explains most of it but there is still two cases I'm confused about.

## First case:

1. Run `docker system purge -a` or click on "Clean/Purge data" on Docker Desktop.
2. Run `docker build -t playground .`.
3. Run `docker run -it --rm playground`. The output should be `Hello, world!`. That makes sense per the above.
4. Run `touch src/main.rs` (locally). This updates the file's modified timestamp.
5. Re-build and re-run. The output should be `Hello, world!` again. This would make sense if docker, unlike cargo, caches on content only and ignores the updated timestamp, hence from the point of the view of the builder nothing has changed. This seems to be the cache as the step shows `CACHED` but I'd like to be sure.

## Second case:
1-3. Same as above.
4. Add a new line to `src/main.rs` (locally). This updates the file's modified timestamp but also modifies its content!
5. Re-build and re-run. The output should include the timestamp. This makes sense because (1) for docker the file content has changed which will invalidate _its_ cache for that step and (2) for cargo the file timestamp has changed which will invalidate _its_ cache. Hence, the correct output.
6. Remove the new line in `src/main.rs` (locally). Now the file content is back to the original but its timestamp is updated.
7. Re-build and re-run. The output is `Hello, world!` again. This one is more confusing... unless docker has cached layers for the `COPY src src` for both with _and_ without the extra new line. I thought that each step would cache the latest change only, but it seems like it keeps a history. Is that right?

Assuming that's all correct, then yeah I believe this is neither a bug with docker nor cargo. But rather, it's just a weird quirk of how they interact. If that's the case, we can close this issue. Thanks for your help, much appreciated!

**Comment by tonistiigi** [comment]
The timestamp handling rules are so that they are preserved but excluded from the instruction cache calculation. This may look weird at first when looking at your case but something that practically works in most cases. Eg. if you just do a new `git clone` of the repo you still want to get the previous cache.

That explains that when you revert the content back you also get the cache from the initial run again.
