### ISSUE TITLE
When BuildX will finish Beta period?

### ISSUE THREAD

**Issue by leniartek** [docker/buildx#555]
Hello,
is there any timeline to finish Beta period of BuildX and move it to GA?

Thanks,
Piotr

**Comment by tonistiigi** [comment]
buildx does not require experimental opt-in since Docker 20.10

We have defined `buildx bake` as a command that we plan to update quite a lot. Other than that I don't expect any backward-incompatible changes.

**Comment by leniartek** [comment]
Thanks a lot @tonistiigi thats a good news!
