### ISSUE TITLE
How to get entitlement=insecure and driver=docker?

### ISSUE THREAD

**Issue by TinoDidriksen** [docker/buildx#559]
Docker version 20.10.5; buildx version v0.5.1-docker

I have run `docker buildx create --use --name insecure-builder --buildkitd-flags '--allow-insecure-entitlement security.insecure'` to create an insecure builder. However I also need to build FROM local images, which requires `--driver docker`, but that yields `error: failed to find driver "docker"`

Other issues mention that the default instance uses docker driver. But when trying to modify that to include insecure, I get `error: default is a reserved name and cannot be used to identify builder instance`

I need priviledged builds because of various glibc+seccomp issues that keep cropping up, most recently that some images can't even run apt-get without an error, which naturally makes everything break. But the images that I build are sometimes incremental updates of other images built the day before. All images are local-only.

So how can I have both `--allow-insecure-entitlement security.insecure` and `--driver docker`?

**Comment by tonistiigi** [comment]
You need to enable it in the dockerd config file for docker driver:

```
{ "builder": {"Entitlements": {"security-insecure": true }}}
```

**Comment by TinoDidriksen** [comment]
Thank you, that works. That's undocumented, as far as I can see. I can't find any mention of that in [docs](https://docs.docker.com/engine/reference/commandline/dockerd/#daemon-configuration-file) or Google. But then I guess this is all experimental, given that it requires labs syntax.

**Comment by tonistiigi** [comment]
@TinoDidriksen It is only on labs atm but feel free to make docs update PR.
