### ISSUE TITLE
New Output Color is nearly invisible on Powershell

### ISSUE THREAD

**Issue by alancummings** [docker/buildx#560]
- [x] I have tried with the latest version of Docker Desktop
  - [x] I have tried disabling enabled experimental features
  - [ ] I have uploaded Diagnostics

### Actual Behavior
The color code for some lines renders the output nearly invisible. 
I have modified my powershell background to be black instead of the default dark blue -- I suspect the output would be **actually** invisible with the default background.

### Expected Behavior
The output should be legible for all user choices of screen background

### Information
I am on docker engine version 20.10.5 on Windows 10, using WSL2, on a local machine.
This occurred with the most recent upgrade.

### Steps to reproduce the behavior
Any Dockerfile will do -- just run `docker build`

I have attached a screenshot snip.
![Screenshot 2021-03-11 160201](https://user-images.githubusercontent.com/7685482/110817490-42074a00-8284-11eb-961c-9b3e3da136c1.png)

**Comment by bubbleguuum** [comment]
Also problematic with `urxvt`. For now I'm using `--progress=plain` to remove color, as a workaround.

**Comment by ericparton** [comment]
This is also an issue on any terminal with a black background, which is the default in many terminal implementations. This is going to be really painful really soon, since v2 of docker compose is scheduled to get released at the end of October and it uses buildkit by default

**Comment by crazy-max** [comment]
@thedeec1 https://github.com/moby/buildkit/pull/2368 has been merged. Just needs to merge changes on buildx.

**Comment by Arkwell** [comment]
This definitely still isn't fixed, and shouldn't be closed, with newest versions of everything installed the text is still impossible to read when working with Docker and Windows PowerShell.
![docker-issue](https://user-images.githubusercontent.com/3460272/193641796-d6fce93c-5baa-4856-ae4f-f73cd20db27b.png)

**Comment by crazy-max** [comment]
@Arkwell https://github.com/docker/buildx/issues/596#issuecomment-1255108542
