### ISSUE TITLE
docker buildx imagetools create: Does not set os.version

### ISSUE THREAD

**Issue by sjackman** [docker/buildx#563]
The source image `ghcr.io/brewsci/bio/ssm:1.4-x86_64_linux` has the `os.version` field set.
The output image created by `docker buildx imagetools create`, has `architecture` and `os` set correctly, but not `os.version`.

The source image is https://github.com/orgs/brewsci/packages/container/bio/ssm/1482751
```console
$ curl -s -H 'Authorization: Bearer' -H 'Accept: application/vnd.oci.image.manifest.v1+json' 'https://ghcr.io/v2/brewsci/bio/ssm/manifests/1.4-x86_64_linux' | jq .config
{
  "mediaType": "application/vnd.oci.image.config.v1+json",
  "digest": "sha256:38e6e8b622108194ee99310c23179d26d1c1165d5fe8a28690347dc136cb6b3c",
  "size": 216
}
$ curl -s -L -H 'Authorization: Bearer' 'https://ghcr.io/v2/brewsci/bio/ssm/blobs/sha256:38e6e8b622108194ee99310c23179d26d1c1165d5fe8a28690347dc136cb6b3c'
{
  "architecture": "amd64",
  "os": "linux",
  "os.version": "2.23",
  "rootfs": {
    "type": "layers",
    "diff_ids": [
      "sha256:0df103c3cb82df7776c77644a32b89aa44f911a579967d203472dcf785024c49"
    ]
  }
}
```

The output image is missing `os.version`:
```console
$ docker buildx imagetools create --dry-run ghcr.io/brewsci/bio/ssm:1.4-x86_64_linux | jq '.manifests[].platform'
{
  "architecture": "amd64",
  "os": "linux"
}
```

**Comment by tonistiigi** [comment]
hmm, where is the spec that says that `os.version` is a valid field in image config? Checked both docker and oci.

Normally the solution for this would be to use a file with a json descriptor as input but that case is lacking test coverage so not sure if all fields do work correctly there atm.

**Comment by sjackman** [comment]
> hmm, where is the spec that says that os.version is a valid field in image config?

The platform object is describe in `application/vnd.oci.image.index.v1+json`
https://github.com/opencontainers/image-spec/blob/master/image-index.md#image-index-property-descriptions

`application/vnd.oci.image.config.v1+json` has `architecture` and `os`. It's seems odd and perhaps an unintentional omission that it doesn't also have `variant` and `os.version`.
https://github.com/opencontainers/image-spec/blob/master/config.md#properties

**Comment by tonistiigi** [comment]
> The platform object is describe in application/vnd.oci.image.index.v1+json

Yes, that's a different object. That's why indexes created by builldx also support it. 

You can always propose changes to the spec, otherwise, I don't think buildx should look for undocumented fields.

**Comment by sjackman** [comment]
Fair enough. Thanks for the clarification, Tõnis!
