### ISSUE TITLE
Aarch64 build of docker image fails to load with format error

### ISSUE THREAD

**Issue by suityou01** [docker/buildx#566]
I have a docker image buildx of redislabs/rejson using platform switch linux/arm64 that fails on container load giving the following error

> standard_init_linux.go:219: exec user process caused: exec format error

I am using docker version 19.03 on Ubuntu 18.04 LTS

bootstrap inspect gives

```Name:   nubuilder
Driver: docker-container

Nodes:
Name:      nubuilder0
Endpoint:  unix:///var/run/docker.sock
Status:    running
Platforms: linux/amd64, linux/arm64, linux/riscv64, linux/ppc64le, linux/386, linux/arm/v7, linux/arm/v6, linux/s390x```

buildx command line that completes without errors is

```docker buildx build --platform linux/arm64 -t 192.168.1.5/my_arm_64_image:1 . --load```

On the arm64 server

```uname - m

aarch64
```

**Comment by tonistiigi** [comment]
If you need to build/run using qemu emulation, it needs to be installed in your system.

https://github.com/tonistiigi/binfmt#installing-emulators is recommended approach.
