### ISSUE TITLE
docs split follow-ups

### ISSUE THREAD

**Issue by tonistiigi** [docker/buildx#571]
Follow-ups to #506 :

- Add link to the bottom of readme to the commands documentation, eg. before the "Contributing" section, so that people reading through the page know where to go next. Link either to the Documentation TOC on the top or to https://github.com/docker/buildx/blob/master/docs/reference/buildx.md
- In the pages flag descriptions are in the section "Examples" for some reason. They should be in a section that describes the options. If there are related examples for the whole command they can be in a separate section. 
- The flag description titles should start with the flag name for easy discovery (and would be good if they are sorted). Reference docs should allow the user to quickly find documentation for a specific flag when they don't quite understand what it does or what arguments it takes. Currently, the user needs to either read through the whole page to find the information they are looking for, or at least all the titles and solve a riddle to understand if that is describing the flag they are looking for. 

@thaJeztah

**Comment by tonistiigi** [comment]
I can do this myself: Would be good to have "Related commands" section. Eg. "install" should provide link to "uninstall" and vice versa. ls -> create, rm, inspect. start -> stop, create etc.

**Comment by crazy-max** [comment]
Note for myself, update links on Docker actions repos.
