### ISSUE TITLE
Feature request: Support for tracing

### ISSUE THREAD

**Issue by nigelgbanks** [docker/buildx#573]
It would be nice if one could use https://github.com/moby/buildkit#opentracing-support with `buildx` rather than installing buildkit on the host.

**Comment by tonistiigi** [comment]
You can trace the buildkitd with `buildx create --driver-opt env.JAEGER_TRACE=0.0.0.0:6831 --driver-opt network=host`. If you point to jaeger container directly then don't need host network. Buildx client side can't be traced atm.
