### ISSUE TITLE
Cache id seems to ignore variables

### ISSUE THREAD

**Issue by schneith** [docker/buildx#580]
I am trying to build an image for two different platforms (amd64/aarch64). To speed up the builds I want to cache some build artifacts in a separate cache for each platform. For this I'm using the variable ${TARGETPLATFORM} as part of the cache id:

Dockerfile:
```Dockerfile
FROM --platform=$TARGETPLATFORM ubuntu as builder

ARG TARGETPLATFORM

RUN --mount=target=/test,type=cache,id=builder-${TARGETPLATFORM} \
    mkdir -p /test && echo "${TARGETPLATFORM}" >> /test/platform
    
RUN --mount=target=/test,type=cache,id=builder-${TARGETPLATFORM} \
    cat /test/platform
```

It seems is that the two builds (amd64/aarch64) are using the same cache as I verified using the following steps:

Build for platform amd64:
```bash
docker buildx prune
docker buildx build . --progress plain  --platform amd64
```
The file /test/platform contains:
```
linux/amd64
```

Now I run a second build for aarch64 with:
```bash
docker buildx build . --progress plain  --platform aarch64
```
The file now contains:
```
linux/amd64
linux/arm64
```
but I would expect it to only contain the last line if the variable in the cache id would be used. The build log shows the cache id properly substituted:
```
#5 [builder 2/3] RUN --mount=target=/test,type=cache,id=builder-linux/arm64     mkdir -p /test && echo "linux/arm64" >> /test/platform
#5 sha256:23a567a436cf2193a73e523999b11e7227f56bb597e1abc9546de3eeacc12c9b
#5 DONE 0.2s

#6 [builder 3/3] RUN --mount=target=/test,type=cache,id=builder-linux/arm64     cat /test/platform
#6 sha256:ce98a19098430a7d2bf49390b19b97e0834f834f2eb300bb45a2634baad3897c
#6 0.166 linux/amd64
#6 0.166 linux/arm64
#6 DONE 0.2s
```

Is that intended behavior that the variable in the cache id has no effect?

**Comment by tonistiigi** [comment]
`--mount` does not currently accept variables. https://github.com/moby/buildkit/issues/815

You can use a unique subdir per platform or `from=` pointing to a different stage as a workaround for your case atm.
