### ISSUE TITLE
CLI: In a terminal with a dark background, the output is difficult to read.

### ISSUE THREAD

**Issue by niftyhack** [docker/buildx#596]
- [x] I have tried with the latest version of Docker Desktop
  - [ ] I have tried disabling enabled experimental features
  - [x] I have uploaded Diagnostics
  - Diagnostics ID: F422FCD1-9103-499F-B66B-A21B08AF9789/20210419073651 (uploaded)

### Expected behavior

I don't know since when this change has been in place, but in the past the output text was either not coloured or coloured in such a way that it was easily readable even in a terminal with a dark background.

### Actual behavior

In a terminal with a dark background, some output is difficult to read (dark blue, dark grey), e.g. in `docker build`. A screenshot: https://imgur.com/a/QSH3l1Y

### Information

  - macOS Version: Catalina 10.15.7 (19H114)
  - Intel chip or Apple chip:
  - Docker Desktop Version: 20.10.5, build 55c4c88 (reinstalled via homebrew today)
  - Terminal is iTerm2 Build 3.3.9

**Comment by svenmauch** [comment]
Hi, first of all sorry for digging up this issue, this is just the only open one that I could find.

Text is still dark blue and illegible in Linux terminals with a black background. Could it be an issue with Docker Compose v2.5.0 itself or is this still in need of being resolved?

**Comment by nk9** [comment]
This is an accessibility issue, since it happens when Dark Mode is enabled (which is a macOS accessibility feature). Wanted to make sure this wasn't overlooked, sorry for the ping @crazy-max. What needs to happen for this to be resolved?

**Comment by petrklus** [comment]
Hi,

just wondering - the same is happening in the default Terminal app on Mac OS when using some of the dark themes - for example, the very popular green-on-black theme called Homebrew. This happening regardless of the OS theme.

**Comment by crazy-max** [comment]
This has been fixed since Buildx v0.9.0 with `BUILDKIT_COLORS` and `NO_COLOR` env vars: https://github.com/docker/buildx/blob/v0.9.0-rc1/docs/guides/color-output.md

```shell
$ BUILDKIT_COLORS="run=123,20,245:error=yellow:cancel=blue:warning=white" docker buildx build .
$ NO_COLOR=1 docker buildx build .
```

**Comment by Arkwell** [comment]
I wouldn't call this "fixed" if I am still searching around in Oct 2022 for how to fix this.
![docker-issue](https://user-images.githubusercontent.com/3460272/193642315-a615ad70-7551-4dd7-876e-a596b40ca65c.png)

**Comment by crazy-max** [comment]
@Arkwell Hard to tell without the full command and also what version of buildx `docker buildx version`?

**Comment by deepskyblue86** [comment]
Is there any ticket or plan to e.g. leverage `COLORFGBG` or provide a default for terminals with dark background?
