### ISSUE TITLE
No longer supports --network with docker build

### ISSUE THREAD

**Issue by lmtyler** [docker/buildx#597]
- [ X] I have tried with the latest version of Docker Desktop
  - [ X] I have tried disabling enabled experimental features
  - [ X] I have uploaded Diagnostics
  - Diagnostics ID:

### Expected behavior
I expect this to work
`docker build --network foo .`
### Actual behavior
`docker build --network foo .
Error response from daemon: network mode "foo" not supported by buildkit`
### Information

  - macOS Version: 10.15.7 (19H524)
  - Intel chip or Apple chip: 2.4 GHz 8-Core Intel Core i9
  - Docker Desktop Version: 3.2.2 (61853)

### Steps to reproduce the behavior

  1. docker create network foo
  2. docker build --network foo .

**Comment by tonistiigi** [comment]
(exact) duplicate #591
