### ISSUE TITLE
Q: With bake/compose, howto do cache-to registry  

### ISSUE THREAD

**Issue by hansbogert** [docker/buildx#606]
How do you set a cache-to when using bake icw docker-compose files?
I tried to augment the docker-compose configuration with an hcl file, i.e.,

```
docker buildx bake -f docker-compose.1.yml -f docker-compose.2.yml -f docker-bake.hcl
```

where the hcl would have a target name which also would be a service in the docker-compose files, and the hcl would have the cache-to attribute, alas that doesn't work:

```
docker buildx bake -f docker-compose.yml -f docker-compose.build.yml -f docker-compose.test.yml -f docker-bake.hcl

error: failed to solve: rpc error: code = Unknown desc = specifying multiple cache exports is not supported currently
```

**Comment by hansbogert** [comment]
Well that was quite a journey, the environment variable `BUILDKIT_INLINE_CACHE=1` apparently causes an implicit `cache-to`.

**Comment by leighst-anchorage** [comment]
@hansbogert does this mean that when using cache-to it is not necessary to specify BUILDKIT_INLINE_CACHE?

**Comment by leighst-anchorage** [comment]
Thanks for the response !
