### ISSUE TITLE
docker buildx - tag as latest

### ISSUE THREAD

**Issue by ozbillwang** [docker/buildx#616]
My image build process like this:

```
docker buildx build --platform linux/arm/v7,linux/arm64/v8,linux/amd64  --push -t demo:1.0.2 .
```

Now, after verify, this image with tag `1.0.2` is ok, so I want to tag it as `latest`. 

what should I do? I don't want to rebuild it and I don't have other Arch environment to pull the images, such as `ARM`.

How to tag all multi-arch images with tag `1.0.2` to latest?

**Comment by tonistiigi** [comment]
`build -t demo:1.0.2 -t demo:latest`

`docker buildx imagetools create -t demo:latest demo:1.0.2`

**Comment by ozbillwang** [comment]
then how to push it to hub.docker.com?

**Comment by tonistiigi** [comment]
`--push`

**Comment by ozbillwang** [comment]
perfect, will try these options. Thanks a lot
