### ISSUE TITLE
simplify controlling plain output

### ISSUE THREAD

**Issue by tonistiigi** [docker/buildx#62]
Some CI systems run through terminal even if they really shouldn't and setting the `--progress=plain` flag in scripts is hard. We should also provide an environment variable that is much easier to configure for the `auto` behavior. Maybe we could just detect `CONTINUOUS_INTEGRATION=1` directly but some users may prefer tty output even in ci.

`BUILDKIT_PROGRESS_PLAIN=1`
`BUILDKIT_PROGRESS=plain`

@tiborvass

**Comment by tiborvass** [comment]
-1 on honoring `CONTINUOUS_INTEGRATION`.
+1 on `BUILDKIT_PROGRESS=plain`, hoping we won't need more of those `BUILDKIT_*` env vars.

**Comment by velcrine** [comment]
Hy where is the documentation for all these ENV options. It seems only developers are aware of these options

**Comment by mbuotidem** [comment]
ENV options docs : https://docs.docker.com/build/building/env-vars/
