### ISSUE TITLE
How to tag all platforms

### ISSUE THREAD

**Issue by elrik75** [docker/buildx#625]
Hi,

I've an image built in 2 platforms (amd64 + arm/v7). After checking that both images work, I would like to tag both as `stable`.
As tags should be only a link to an already built image, I guess it should be possible to do it from any platform.
So I would like to do something like `docker buildx tag image:latest image:stable` or any equivalent command.
It seems impossible to do that, do I miss something? If not, what could be another workflow ?

Thanks

**Comment by tonistiigi** [comment]
`docker buildx imagetools create -t new old`
