### ISSUE TITLE
Allow building for current client platform

### ISSUE THREAD

**Issue by tonistiigi** [docker/buildx#63]
There should be a simple way to build for the platform that is invoking the build. Eg. I want to build a binary for my current system. `docker build --platform=CURRENT` ?

@tiborvass

**Comment by tiborvass** [comment]
`CURRENT` is confusing. I'd suggest something like `--platform=CLIENT`.

**Comment by tiborvass** [comment]
Actually, the consistent vocabulary here would be `local`. So let's do `--platform=LOCAL`. Maybe for simplicity we should do `--platform=local` lowercase, or anycase.
