### ISSUE TITLE
linux/arm/v7 actually builds on `arm6l`?

### ISSUE THREAD

**Issue by martijnversluis** [docker/buildx#630]
I setup a Github action to build and push Docker images for Raspberry PI. I specify `linux/arm/v7` [as target platform](https://github.com/martijnversluis/home_app/blob/4bc5c50ab3fd0dbfe530af58587ada316e2f52fd/.github/workflows/dockerimage.yml#L13). 

However, when I run `uname -m` inside `Dockerfile` [it prints `arm6l`](https://github.com/martijnversluis/home_app/runs/2787369454?check_suite_focus=true#step:7:102). 

I do actually need to build for Raspberry Pi 2B, which is `arm7l`. Is that possible with buildx?

**Comment by tonistiigi** [comment]
There is only one emulator for arm. `uname -m` prints whatever the emulator wants to show there. They probably show the lowest compatible version.

**Comment by martijnversluis** [comment]
Would you know of any way to circumvent this?

I'm trying to install NodeJS using ASDF. It uses `uname -m` to determine architecture and construct a download URL for the binary. However, that download only exists for `arml7`, not for `arml6`, so ASDF fails by claiming the download is not available.
