### ISSUE TITLE
Suggestion on how to improve cross CPU docker builds with the Dockerfile

### ISSUE THREAD

**Issue by qdm12** [docker/buildx#632]
I noticed that, if you build for multiple architectures, common steps running on the build platform (with `FROM --platform=${BUILDPLATFORM} ...`) are ran for all architectures although they are the same.

Building them only once for all architectures should save quite a bit of time in CIs, especially where layer caching is not available. 

The build could then branch out for each CPU architecture as soon as it encounters an `ARG TARGETPLATFORM` or a `COPY` from an emulated stage that was not running with `--platform=${BUILDPLATFORM}`.

I wrote a blog post about it: [**here**](https://qqq.ninja/blog/post/dockerfile-improvement-for-cross-building/)

with more details on the current situation, problem and possible solution.

There is also a [Reddit discussion thread](https://www.reddit.com/r/docker/comments/o009e9/suggestion_on_how_to_improve_cross_cpu_docker/) with no other apparent solution to it though.

Let me know if I'm wrong though, or if there is an existing solution for such case! Thanks!

**Comment by tonistiigi** [comment]
Thanks, but the issue tracker is not a good place for this. Feel free to post in `#buildkit` slack and also check out https://github.com/tonistiigi/xx
