### ISSUE TITLE
buildx build does not take advantage of layers that already exist from docker pull plataform

### ISSUE THREAD

**Issue by patrickelectric** [docker/buildx#633]
Doing `docker pull --platform linux/arm/v7 farm/potato:chips`
Before doing `docker buildx build --platform linux/arm/v7 --builder arm-builder --network host . -t patrickelectric/potato:chips --push --progress=plain`
Does not help with cache and the build is done from scratch, the result is terrible for system that builds and try to deploy consistent docker based in a series of existent layers.

**Comment by tonistiigi** [comment]
Pulling an image has no effect on your build cache. If you don't have local cache you can set remote cache sources with `--cache-from` if they are properly prepared. Platform has nothing to do with this.
