### ISSUE TITLE
Support RISCV64

### ISSUE THREAD

**Issue by qdm12** [docker/buildx#643]
There is the dependency `github.com/prometheus/procfs` which added support for riscv64 in `v0.6.0` (https://github.com/prometheus/procfs/commit/910e68572b35da779e4f84cfa5261b0a67532d05)
Currently trying to build for riscv64:

```sh
GOARCH=riscv64 go build  ./cmd/buildx
```

will fail with

```
/go/pkg/mod/github.com/prometheus/procfs@v0.1.3/cpuinfo.go:71:9: undefined: parseCPUInfo
```

buildx probably depends on many dependencies using versions before v0.6.0 so it's more of a long shot than something that can be fixed in a single PR I believe. Although

```sh
go get github.com/prometheus/procfs@v0.6.0
go mod tidy
```

Fixes the build, but probably in a risky-ish way I guess. Not a priority issue at all, but I thought it would be useful to track it.

**Comment by tonistiigi** [comment]
Procfs was updated in #565 https://github.com/docker/buildx/commit/d40a6082faa2b8a4e3b16c57fbd396cd5a95919e#diff-b318e1e6bbcc59892bb6b4298564b051c6f6d5d848878d14aab856509ff0625cR333

Added CI validation in #652

**Comment by qdm12** [comment]
Ah indeed, sorry for the mistake, I was using the latest release v0.5.1. Any plan to make another release sometime by the way? Thanks!
