### ISSUE TITLE
Is there an official docker buildx docker image?

### ISSUE THREAD

**Issue by maniator** [docker/buildx#647]
I know that there is a dockerhub image for docker (`docker:latest`) and there is one for docker in docker (`docker:dind`) but is there one for running buildx (without having to run n number of commands to do so?)

I build one that works pretty well (for me at least) and I decided to push it to dockerhub reg here: https://hub.docker.com/r/maniator/dind-buildx

Is there anything wrong with that?

What type of attribution do I need to add?

**Comment by crazy-max** [comment]
@maniator https://github.com/docker/buildx/issues/553#issuecomment-787440551

**Comment by maniator** [comment]
> @maniator [#553 (comment)](https://github.com/docker/buildx/issues/553#issuecomment-787440551)

Those images seem a little big.
Is there any way to make them smaller?

**Comment by crazy-max** [comment]
Don't think so. https://github.com/crazy-max/docker-docker is based on the official image + buildx + buildkit + docker-compose.

**Comment by maniator** [comment]
> Don't think so. https://github.com/crazy-max/docker-docker is based on the official image + buildx + buildkit + docker-compose.

Why is docker compose needed in that image?
I feel like it could be something separate

**Comment by crazy-max** [comment]
Feel free to fork my repo.

**Comment by crazy-max** [comment]
We could also provide a scratch image with buildx binaries you could use with a `COPY --from` def. Will think about that.

**Comment by maniator** [comment]
@crazy-max that PR does not really close this issue... Does it?
