### ISSUE TITLE
Docker layer cache is not invalidated by changing build secret values.

### ISSUE THREAD

**Issue by Milesjpool** [docker/buildx#651]
- [ x] I have tried with the latest version of Docker Desktop
  - [ x] I have tried disabling enabled experimental features
  - [ x] I have uploaded Diagnostics
  - Diagnostics ID: 5CEA1D7C-269B-413A-A830-694AD7D2423A/20210628143401

### Expected behavior

Executing a Docker build, which references a [build secrets](https://docs.docker.com/develop/develop-images/build_enhancements/#new-docker-build-secret-information) file, and then re-running that build with new file content should invalidate the cache at that layer and build a new image from that point onwards.

### Actual behavior

On re-running a build, after updating the content of the secrets file, the layer-cache is hit incorrectly and the resulting image is identical.

### Information
  - Is it reproducible? 
    - Yes
  - Is the problem new? 
    - Issue seen in docker versions 20.10.2 and 20.10.7, both on Mac and in our Linux CI environment.
  - Did the problem appear with an update?
    - No - this only appeared after starting to use the _build secrets_ feature. 
  - A reproducible case if this is a bug, Dockerfiles FTW.
``` Dockerfile
# syntax=docker/dockerfile:1.2

FROM alpine

WORKDIR /test

RUN --mount=type=secret,id=my_secret,dst=/test/secret \
  cat /test/secret

RUN --mount=type=secret,id=my_secret,dst=/test/secret \
  cp /test/secret /test/out

RUN cat /test/out
```
``` shell
echo a > $PWD/secret
DOCKER_BUILDKIT=1 docker build --secret id=my_secret,src=$PWD/secret .
echo b > $PWD/secret
DOCKER_BUILDKIT=1 docker build --secret id=my_secret,src=$PWD/secret .
```
  - macOS Version: 11.1 (20C69)
  - Intel chip or Apple chip: Intel chip
  - Docker Desktop Version: Version 3.4.0 (3.4.0.5223)

### Steps to reproduce the behavior

  1. Copy the above Dockerfile into an empty directory
  2. Run the above script in that directory
  3. Note that despite different secret values, the resulting image hash is identical

**Comment by tonistiigi** [comment]
This is expected to avoid information leak about the secret value. To force a cache update either change the secret path or define an extra build-arg that you modify together with the secret value.

**Comment by sadams** [comment]
@tonistiigi thanks for info. From your message I think I understand what's happening and how to fix it:

Dockerfile:
```dockerfile
FROM alpine
ARG DUMMY_JUST_TO_SCOPE_SECRET_LAYER
WORKDIR /test

RUN --mount=type=secret,id=my_secret,dst=/test/secret \
  cp /test/secret /test/out
```

test.sh
```sh
echo a > /tmp/secreta
DOCKER_BUILDKIT=1 docker build --secret id=my_secret,src=/tmp/secreta -t test-a -q --build-arg 'DUMMY_JUST_TO_SCOPE_SECRET_LAYER=a' .
echo b > /tmp/secretb
DOCKER_BUILDKIT=1 docker build --secret id=my_secret,src=/tmp/secretb -t test-b -q --build-arg 'DUMMY_JUST_TO_SCOPE_SECRET_LAYER=b' .
echo -n "a -> "
docker run -it --rm test-a cat /test/out
echo
echo -n "b -> "
docker run -it --rm test-b cat /test/out
```

Which gives: 
```
a -> a

b -> b
```

But, this does feel like something that could be handled by docker when `mount=type=secret` by keeping a hash of the secrets file or something similar?

**Comment by Milesjpool** [comment]
Just to confirm, changing just the secret path (unless you mean the id) doesn't result in a cache update. I second with @sadams's last point - as it appears there's otherwise no clean, external way to update the secrets in an image.
 
``` shell
echo a > $PWD/secreta
DOCKER_BUILDKIT=1 docker build --secret id=my_secret,src=$PWD/secreta .
echo b > $PWD/secretb
DOCKER_BUILDKIT=1 docker build --secret id=my_secret,src=$PWD/secretb .
```

Adding the unused arg seems inelegant, but it's an adequate workaround for now.

**Comment by tonistiigi** [comment]
@Milesjpool Sorry, I meant the path (or any other property) in Dockerfile flag, not in `build --secret`.
