### ISSUE TITLE
Certificate / Networking issues when using buildx to build off alpine for ARM64

### ISSUE THREAD

**Issue by m90** [docker/buildx#660]
I'm trying to add an ARM64 build to a Docker image I maintain. I have set up buildx to do so and can use the setup just fine to build the `amd64` version of the image. When I try to target `arm64` my build will "randomly" fail at different stages. I am building this image in CircleCI using a Remote Docker engine.

The Dockerfile is relatively simple and looks like:

```Dockerfile
FROM alpine:3.14

WORKDIR /root

RUN apk add --update ca-certificates docker openrc gnupg
RUN rc-update add docker boot

RUN wget https://dl.min.io/client/mc/release/linux-amd64/mc && \
  chmod +x mc && \
  mv mc /usr/bin/mc

COPY src/backup.sh src/entrypoint.sh /root/
RUN chmod +x backup.sh && mv backup.sh /usr/bin/backup \
  && chmod +x entrypoint.sh

ENTRYPOINT ["/root/entrypoint.sh"]
```

I can now see two different failures when trying to build this repeatedly:

1. `apk add --update ca-certificates docker openrc gnupg` fails at installing `ca-certificates` with no error message other than `Exit 1`
2. Sometimes `apk add` succeeds. In these cases `wget` will _always_ fail with `Connection reset by peer`

The interesting part is: when I use a `http` URL instead of a `https` one when calling `wget` I can brute force my way into a successful build in those cases where `apk add` succeeds.

The Docker version used in CircleCI is 20.10.6, I am setting `DOCKER_BUILDKIT='1'` and `DOCKER_CLI_EXPERIMENTAL='enabled'`. My build command looks like:

```Makefile
DOCKER_TAG ?= local

.PHONY: build
build:
	@docker context create docker-volume-backup
	@docker buildx create docker-volume-backup --name docker-volume-backup --use
	@docker buildx inspect --bootstrap
	@docker buildx build --platform linux/arm64,linux/amd64 -t offen/docker-volume-backup:$(DOCKER_TAG) .
```

When I run this locally on Ubuntu 20 (Docker 20.10.7), running the `apk` command always succeeds, but I still cannot use `https` with `wget`.

**Comment by m90** [comment]
This seems to be fixed by magically running

```
docker run --rm --privileged linuxkit/binfmt:v0.8
```

before doing anything else.

See: https://gitlab.alpinelinux.org/alpine/aports/-/issues/12406

**Comment by crazy-max** [comment]
You can test with QEMU from https://github.com/tonistiigi/binfmt that is made for running containers:

```shell
$ docker run -it --rm tonistiigi/binfmt:latest --version
binfmt/8703596 qemu/v6.0.0 go/1.16.5
$ docker run -it --rm tonistiigi/binfmt:latest --uninstall qemu-*
$ docker run --rm --privileged tonistiigi/binfmt --install all
```

Just tested myself with your Dockerfile and works fine.
