### ISSUE TITLE
Cannot create builder instance with --driver docker

### ISSUE THREAD

**Issue by ahgraber** [docker/buildx#665]
I'm trying to build local images with buildx.  If I create a builder instance with 
```
docker buildx create --name mybuilder --driver docker --use
```
I get an error: `error: failed to find driver "docker"`

I'm on Docker Desktop Version 3.5.1 (3.5.1.7) for MacOS.  I get this error regardless of whether I enable "experimental features" or not.

Am I missing something?

**Comment by tonistiigi** [comment]
You can't create new instances of docker driver. Every Docker installation that has embedded Buildkit is automatically one builder. If you want to add a new remote Docker endpoint to the list add a `docker context` and BuildKit will allow you to switch to it.

The error message could be more clear though.

**Comment by ahgraber** [comment]
Thanks for the insight.  

May want to consider updating the documentation - the `buildx create` [docs](https://docs.docker.com/engine/reference/commandline/buildx_create/#driver) imply that `--driver docker` is valid.
