### ISSUE TITLE
Host key error with private git submodule

### ISSUE THREAD

**Issue by tscholak** [docker/buildx#668]
Hi, I've got a case where a GitHub repository uses a private git submodule, `git@github.com:org/private_repo.git`, also from GitHub:
```
#2 10.49 Cloning into '/var/lib/buildkit/runc-overlayfs/snapshots/snapshots/2/fs/private_repo'...
#2 10.58 Host key verification failed.
#2 10.58 fatal: Could not read from remote repository.
#2 10.58
#2 10.58 Please make sure you have the correct access rights
#2 10.58 and the repository exists.
#2 10.58 fatal: clone of 'git@github.com:org/private_repo.git' into submodule path '/var/lib/buildkit/runc-overlayfs/snapshots/snapshots/2/fs/private_repo' failed
```
Access to private github repos requires not only the ssh secrets to be passed on to the build context, it also requires the ssh known-hosts file. The builder has only the former and doesn’t know which key to use for github.com.
Can this be resolved?

**Comment by morlay** [comment]
May consider use https with auth instead? `GITHUB_TOKEN` could pass by `--build-arg`

```
ARG GITHUB_USER
ARG GITHUB_TOKEN

RUN git config --global url.https://${GITHUB_USER}:${GITHUB_TOKEN}@github.com/.insteadOf https://github.com/
RUN git config --global url.https://${GITHUB_USER}:${GITHUB_TOKEN}@github.com/.insteadOf git@github.com:
```

or clone outside Dockerfile and COPY them.

**Comment by tonistiigi** [comment]
If this is a clone inside dockerfile then you need to prepare`known_hosts` as part of your build (as you need to install openssh for example). Eg. https://medium.com/@tonistiigi/build-secrets-and-ssh-forwarding-in-docker-18-09-ae8161d066 shows one way. If it is a git build context it should be handled automatically with #581.

**Comment by tscholak** [comment]
This is a private git submodule to a repository that I build with
```

docker buildx build \
		--builder $(BUILDKIT_BUILDER) \
		--ssh default=$(SSH_AUTH_SOCK) \
		-f Dockerfile \
		--tag $(IMAGE_NAME):$(GIT_HEAD_REF) \
		--tag $(IMAGE_NAME):cache \
		--cache-from type=registry,ref=$(IMAGE_NAME):cache \
		--cache-to type=inline \
		--push \
	git@github.com:$(ORG)/$(REPO)#$(GIT_HEAD_REF)
```
If I'm not mistaken, this means that the buildx builder needs to clone the private submodule, and that must fail unless the credentials (presumably including the `known_hosts` file) are passed on to the builder correctly and completely.

**Comment by tscholak** [comment]
What builder image and docker version should I use to make this work?
