### ISSUE TITLE
Network address/port contention during bake?

### ISSUE THREAD

**Issue by ciaranmcnulty** [docker/buildx#678]
Apologies in advance for the imprecise title. I think I have a fairly generic issue around networking but will dive into some of the Java details

I have a system with 3-4 Wiremock containers, which host Wiremock extensions. As part of their build (`mvn package`) they run their tests, which involve binding to port 8080

When I `buildx build`, or `bake` just one of the images it builds fine. If I try and `bake` them all together, the containers start complaining they can't bind to that address (`com.github.tomakehurst.wiremock.common.FatalStartupException: java.lang.RuntimeException: java.net.BindException: Address already in use`)

This is in a CI environment, `buildx ls` just before the bake shows the following:

```
37NAME/NODE       DRIVER/ENDPOINT             STATUS   PLATFORMS
38funny_dhawan *  docker-container                     
39  funny_dhawan0 unix:///var/run/docker.sock inactive 
40default         docker                               
41  default       default                     running  linux/amd64, linux/386
```

Interestingly, `bake`ing on my local M1 Mac completes the build in parallel just fine.

I don't have enough of an understanding of how networking is handled inside a bake to understand how I can resolve this - for now we can build the containers not in parallel but it would be great to understand what's going on here

**Comment by griffous** [comment]
Hi Ciaranmcnulty,

We hit the same problem some months back, and learned that the buildkit docker container (which your `docker-container` builder uses) does not have `CNI` networking enabled by default. This means that each RUN command executes in a shared network context within the buildkit docker container: they're sharing a network stack.
For outbound connections this is fine, but you'll hit problems if multiple concurrent RUN commands each try to bind the same unix/TCP sockets.

The solution for us was to build our own buildkitd container with CNI networking configured and enabled. Our Dockerfile builds upon the official upstream buildkit instances, and simply adds CNI binaries and config.

Dockerfile:
```
ARG BUILDKIT_TAG
ARG CNI_VERSION=v0.9.1
ARG TARGETOS=linux
ARG TARGETARCH=amd64

FROM moby/buildkit:"${BUILDKIT_TAG}" AS buildkit_upstream_tag

FROM buildkit_upstream_tag
ARG CNI_VERSION
ARG TARGETOS
ARG TARGETARCH
ARG BUILDKIT_TAG
ENV BUILDKIT_TAG="${BUILDKIT_TAG}"
ENV CNI_VERSION="${CNI_VERSION}"

RUN echo "BUILDKIT_TAG=[${BUILDKIT_TAG}], CNI_VERSION=[${CNI_VERSION}]"
RUN apk add --no-cache curl iptables

WORKDIR /opt/cni/bin
RUN curl -Ls https://github.com/containernetworking/plugins/releases/download/$CNI_VERSION/cni-plugins-${TARGETOS}-${TARGETARCH}-${CNI_VERSION}.tgz | tar xzv
COPY cni.json /etc/buildkit/cni.json
RUN ls -al /etc/buildkit && buildkitd --version
```

The `cni.json` file comes from https://github.com/moby/buildkit/blob/master/hack/fixtures/cni.json

Finally create your buildx instance with something like this to use your custom image:
`docker buildx create --name "${builderFullName}" --driver-opt image=local/buildkit:"${BUILDKIT_BUILDER_TAG}" --buildkitd-flags '--oci-worker-net=cni --oci-worker-gc-keepstorage 200000' --use`

I hope this helps?
