### ISSUE TITLE
Failed to solve with frontend dockerfile.v0: failed to create LLB definition

### ISSUE THREAD

**Issue by kuharan** [docker/buildx#680]
It was all working fine till yesterday until I saw this. And even till today, I am unable to fix this. 

**Environment:**

Windows 10.
Docker version 20.10.7, build f0df350

**Error Details:**

```> Executing task: docker build --pull --rm -f "Dockerfile" -t idealoctopotato:latest "." <

[+] Building 9.6s (4/4) FINISHED
 => [internal] load build definition from Dockerfile                                                                       0.5s 
 => => transferring dockerfile: 32B                                                                                        0.0s 
 => [internal] load .dockerignore                                                                                          0.8s 
 => => transferring context: 2B                                                                                            0.0s 
 => ERROR [internal] load metadata for public.ecr.aws/lambda/python:3.8                                                    8.5s 
 => [auth] aws:: lambda/python:pull token for public.ecr.aws                                                               0.0s 
------
 > [internal] load metadata for public.ecr.aws/lambda/python:3.8:
------
failed to solve with frontend dockerfile.v0: failed to create LLB definition: unexpected status code [manifests 3.8]: 403 Forbidden
The terminal process "C:\Windows\System32\cmd.exe /d /c docker build --pull --rm -f "Dockerfile" -t idealoctopotato:latest "."" terminated with exit code: 1.

Terminal will be reused by tasks, press any key to close it.```

**Comment by crazy-max** [comment]
@kuharan Looks like something flawky on public ECR.

**Comment by Mozart409** [comment]
I still have the same problem? Any fixes?

**Comment by kuharan** [comment]
@Mozart409 I changed the repository to `amazon/aws-lambda-python:3.8` and it started working.

**Comment by Mozart409** [comment]
> @Mozart409 I changed the repository to `amazon/aws-lambda-python:3.8` and it started working.

I will try that. Thank you 😄

**Comment by UlucFVardar** [comment]
same problem again. I change image with written before, it works!

**Comment by pingsutw** [comment]
same problem again

**Comment by aflansburg** [comment]
On M1 Mac I notice at times I have to just restart Docker desktop and the error clears. ¯\_(ツ)_/¯

**Comment by jost-kuenzel** [comment]
> On M1 Mac I notice at times I have to just restart Docker desktop and the error clears. ¯_(ツ)_/¯

@aflansburg, same here! Restart helps..

**Comment by wbudd** [comment]
> On M1 Mac I notice at times I have to just restart Docker desktop and the error clears. ¯\\_(ツ)_/¯

I can confirm the same solution works on Linux too: `sudo systemctl restart docker`

**Comment by Unintendedz** [comment]
If you're using WSL, maybe the problem is the docker-desktop credential; try to delete `"credsStore": "desktop.exe"` in `~/.docker/config.json`

**Comment by JoshuaSunsheng** [comment]
Or before docker-compose build, run the following commands to inenable buildkit.

```
export DOCKER_BUILDKIT=0
export COMPOSE_DOCKER_CLI_BUILD=0
```

**Comment by sebsto** [comment]
You have to be authenticated to access `public.ecr.aws`

I ran this command and it worked for me 
```
aws ecr-public get-login-password --region us-east-1 | docker login --username AWS --password-stdin public.ecr.aws
```

Doc : https://docs.aws.amazon.com/AmazonECR/latest/public/public-registries.html#public-registry-auth

**Comment by sebsto** [comment]
You might have to be authenticated to access `public.ecr.aws`

I ran this command and it worked for me 
```
aws ecr-public get-login-password --region us-east-1 | docker login --username AWS --password-stdin public.ecr.aws
```

Doc : https://docs.aws.amazon.com/AmazonECR/latest/public/public-registries.html#public-registry-auth

You might also have an old token cached that prevent anonymous pulls 

>An unauthenticated pull is a pull without an auth token. You can confirm whether there is an auth token in your Docker configuration by checking your ~/.docker/config.json file. If you’ve previously authenticated to Amazon ECR Public but you want to perform an unauthenticated pull, you can logout using the docker logout public.ecr.aws command which will remove the auth token from your Docker configuration file.

**Comment by niklaslrks** [comment]
For me this issue occured with different images from different repos. So far it always worked to manually pull the image with `docker pull` and afterwards build the image from the Dockerfile.

**Comment by chn217** [comment]
> You might have to be authenticated to access `public.ecr.aws`
> 
> I ran this command and it worked for me
> 
> ```
> aws ecr-public get-login-password --region us-east-1 | docker login --username AWS --password-stdin public.ecr.aws
> ```
> 
> Doc : https://docs.aws.amazon.com/AmazonECR/latest/public/public-registries.html#public-registry-auth
> 
> You might also have an old token cached that prevent anonymous pulls
> 
> > An unauthenticated pull is a pull without an auth token. You can confirm whether there is an auth token in your Docker configuration by checking your ~/.docker/config.json file. If you’ve previously authenticated to Amazon ECR Public but you want to perform an unauthenticated pull, you can logout using the docker logout public.ecr.aws command which will remove the auth token from your Docker configuration file.

This is the only fix working for me.

**Comment by annjawn** [comment]
> On M1 Mac I notice at times I have to just restart Docker desktop and the error clears. ¯_(ツ)_/¯

Happens on M2 Mac as well. Restarting the Docker daemon seems to resolve it.

**Comment by CasperKristiansson** [comment]
Same thing here, happened on M2 Mac and just restarting the application works

**Comment by osw4l** [comment]
> On M1 Mac I notice at times I have to just restart Docker desktop and the error clears. ¯_(ツ)_/¯

I did it, the way is restarting on Apple silicon, I confirm

**Comment by Tristin-C** [comment]
I ran into the same problem on windows, using the docker desktop version which is the latest version and has not yet been fixed

**Comment by Tristin-C** [comment]
> I ran into the same problem on windows, using the docker desktop version which is the latest version and has not yet been fixed

It goes up and down, you modify the mirror source, and then you're done, which is weird

**Comment by thebirdgr** [comment]
`sudo docker systemctl restart docker`
 this helped me. We have a private registry as well as use aws' one. Might have needed a restart
