### ISSUE TITLE
add a new architecture to existing image

### ISSUE THREAD

**Issue by qsvtr** [docker/buildx#699]
is it possible to add a new architecture to an existing image (without modifying tag)?

like 
`docker buildx build --plateform linux/amd64 --push`
`docker buildx build --plateform linux/arm64 --push`

I need to make two differents pushes

**Comment by tonistiigi** [comment]
You can merge newly built images with https://github.com/docker/buildx/blob/master/docs/reference/buildx_imagetools_create.md#append
