### ISSUE TITLE
bake does not support compose profiles

### ISSUE THREAD

**Issue by dudicoco** [docker/buildx#718]
When using a compose file with profiles, `bake` throws an error.

Example file:
```yaml
version: '3.9'

services:
  app:
    image: test:latest
    build: .
    profiles:
      - test
```

Output:
```sh
$ docker buildx bake
[+] Building 0.0s (0/0)
error: services.app Additional property profiles is not allowed
```

**Comment by crazy-max** [comment]
@dudicoco Should have been fixed since buildx 0.6.0. What's the output of `docker buildx version`?

**Comment by dudicoco** [comment]
@crazy-max `github.com/docker/buildx v0.5.1-docker 11057da37336192bfc57d81e02359ba7ba848e4a`

I'm using docker desktop latest version on mac - `3.5.2 (66501)`, was the latest buildx version not released with Docker Desktop yet?

**Comment by crazy-max** [comment]
@dudicoco

> I'm using docker desktop latest version on mac - `3.5.2 (66501)`, was the latest buildx version not released with Docker Desktop yet?

Not yet yes but you can download and install latest release from GitHub Releases page: https://github.com/docker/buildx#binary-release

**Comment by dudicoco** [comment]
Thanks @crazy-max, that solved the issue.
