### ISSUE TITLE
opition to build multiplatform not parallel

### ISSUE THREAD

**Issue by Lukas1818** [docker/buildx#722]
Exist an option to build the different platforms after each other instead of parallel?

The compiler, which does compile the software if the image is build, does already use all available treads. Because of this the parallel build of the platforms slow down the build process.

**Comment by crazy-max** [comment]
@Lukas1818 You can limit the number of parallel build steps that can run at the same time with `max-parallelism` opt in [BuildKit config](https://github.com/moby/buildkit/blob/master/docs/buildkitd.toml.md):

```toml
# /etc/buildkit/buildkitd.toml
[worker.oci]
  max-parallelism = 1
```

```console
$ docker buildx create --config /etc/buildkit/buildkitd.toml --use
$ docker buildx build ...
```

**Comment by Lukas1818** [comment]
This does work
Thanks

**Comment by stan-irl** [comment]
doesnt work for me either
