### ISSUE TITLE
Q: --cache-to for multi-stage build

### ISSUE THREAD

**Issue by northtyphoon** [docker/buildx#73]
After building a multi-stage dockerfile with `--cache-to` option, I notice only the final stage layers were saved to the `--cache-to` destination. How can I also cache the intermediate build stage layers? Do I have to use `--target` to build and cache each stage one by one?

**Comment by tiborvass** [comment]
@northtyphoon You can add `mode=max` option to `--cache-to` as explained in https://github.com/docker/buildx#--cache-tonametypetypekeyvalue

Feel free to open a PR to clarify the docs if you think it can be made more obvious!
