### ISSUE TITLE
docker buildx bake error with DOCKER_HOST

### ISSUE THREAD

**Issue by zorion79** [docker/buildx#730]
Docker version on Mac, Windows and Ubuntu - 2.10.8
At Friday morning all worked fine. Then I update all computers on latest version. When I run command on windows or Mac, with DOCKER_HOST on Ubuntu server I given error.

```
docker buildx bake --pull --file docker-compose.yml --progress=plain
error: failed to get status: rpc error: code = Unavailable desc = connection error: desc = "transport: Error while dialing cannot connect to the Docker daemon. Is 'docker daemon' running on this host?: context canceled"
```

All another commands working fine. Docker context didn't help.

**Comment by Aposhian** [comment]
I get this same error, but with a regular docker context over SSH:
```
docker --context=mycontext buildx bake
```
