### ISSUE TITLE
Support for build - test - push workflow

### ISSUE THREAD

**Issue by francisdb** [docker/buildx#733]
For https://github.com/hseeberger/scala-sbt we have an extra test step between building and pushing. There we validate that the images work as expected.

As I understand it there is no way to have a 2-step process for building and pushing, and using the default `docker push` will fail as it does not find the images.
Also we need to add the push argument depending on the pr-or-not fact

Maybe a docker `docker buildx push` command can be added, with the user repeating the `--platform` argument to pick the correct images?
Any other workarounds for this?

This is similar to #724

**Comment by crazy-max** [comment]
Similar to https://github.com/docker/build-push-action/issues/269. I will add some doc on build-push-action repo with this use case.

**Comment by crazy-max** [comment]
@flotwig https://github.com/docker/build-push-action/blob/master/docs/advanced/test-before-push.md should help
