### ISSUE TITLE
docker buildx with remote ssh context cause error after it was updated from 0.5.1 to 0.6

### ISSUE THREAD

**Issue by drefixs** [docker/buildx#737]
Hello everyone :)

I have some truble after update the client of buildx from 0.5.1 to 0.6.1

- I have a remote ubuntu server with installed last version of docker-ce (Server Version: 20.10.7
- from the client side i add this server through the next command
```
docker context create --docker host=${BUILDKIT_SERVER_SSH_URL} remote-buildkit
```
- after that I use docker buildx create command to create the builder node
```
docker buildx create --use --name hosted-builder--driver docker-container
docker buildx inspect localbuild --bootstrap
```
- then i run simple docker buildx build . 
- when I use 0.5.1 version all working perfect :)
- when I update buildx client to 0.6.1 version I have the next error
```
docker --debug buildx build .
...
[+] Building 0.0s (0/0)
WARN[0000] commandConn.CloseWrite: commandconn: failed to wait: signal: killed
WARN[0000] commandConn.CloseRead: commandconn: failed to wait: signal: killed
WARN[0000] commandConn.CloseWrite: commandconn: failed to wait: signal: killed
[+] Building 0.0s (0/0)
error: failed to get status: rpc error: code = Unavailable desc = connection error: desc = "transport: failed to write client preface: write |1: broken pipe"
74637 v0.6.1-docker /usr/local/lib/docker/cli-plugins/docker-buildx --debug buildx build --platform linux/amd64 .
github.com/moby/buildkit/client.(*Client).solve.func4
	/go/src/github.com/docker/buildx/vendor/github.com/moby/buildkit/client/solve.go:249
golang.org/x/sync/errgroup.(*Group).Go.func1
	/go/src/github.com/docker/buildx/vendor/golang.org/x/sync/errgroup/errgroup.go:57
runtime.goexit
	/usr/local/go/src/runtime/asm_amd64.s:1371
```

- this bug is reproducing with server 19 and 20 docker-ce version (I try to update the serve docker)
- this bug also as well is reproducing with OSX client with buildx 0.6.1 and in circleci runner with 0.6.1 of buildx client with the agent running with alpine image with 0.5.1 all this work perfect
- I also try to change network to **host** and **default** for buildx create builder buildkit node instance.

buildx/vendor/github.com/moby/buildkit/client/solve.go:249

My investigation led me to these changes
https://github.com/docker/buildx/pull/635#issuecomment-901479760

**Comment by drefixs** [comment]
Tested your changes all works as expected with master version thanks

**Comment by spurin** [comment]
Old/closed thread but to confirm, this is still an issue with the version of buildx supplied with Docker Desktop for Mac (M1) (Buildx 0.6.1).  Encountered the same issue today and the latest update of Docker Desktop didn't resolve.  

Binary taken from the Github repo releases section however, works perfectly 😊
