### ISSUE TITLE
[question] where to find intermediate image hashes?

### ISSUE THREAD

**Issue by JoseAlban** [docker/buildx#742]
With previous build version, output was like:
```
   ---> 765cfcf954df
  Step 10/23 : LABEL x y
   ---> Running in 4308f6df75e0
  Removing intermediate container 4308f6df75e0
   ---> 243ea29f0af4
  Step 11/23 : LABEL x y
   ---> Running in f004bb8891a0
  Removing intermediate container f004bb8891a0
   ---> 2933ea408331
  Step 12/23 : WORKDIR x
   ---> Running in 5693682b7487
  Removing intermediate container 5693682b7487
   ---> bf5451a99860
```

With new build version (aka buildx), output is like:
```
=> [stage-1 1/9] FROM docker.io/x
0.0s
 => [build-worker 1/7] FROM docker.io/x
0.0s
 => CACHED [build-worker 2/7] WORKDIR x
0.0s
 => CACHED [build-worker 3/7] COPY x y                                                                                                                                                    0.0s
```

How do i find out the intermediate image hash, so that I can `docker run` and debug further?

**Comment by AkihiroSuda** [comment]
There is no docker-runnable image hash.

A workaround is to run `RUN sleep infinity` in Dockerfile and then run `sudo nsenter -a -t $PID_OF_SLEEP sh` on the host for opening a debug shell.

**Comment by tonistiigi** [comment]
> A workaround is to run RUN sleep infinity in Dockerfile and then run sudo nsenter -a -t $PID_OF_SLEEP sh on the host for opening a debug shell.

Or to use `--target` to build the Dockerfile up to the point that you wish to debug.
