### ISSUE TITLE
unable to build private git repository with ssh access

### ISSUE THREAD

**Issue by stalb** [docker/buildx#77]
**Problem**:

If you have a private git repository you access using ssh key, you are not able to build it directly using buildx.

`docker buildx build  git@github.com:xxxx/yyyy.git`  fails with permission denied, Could not read from remote repository...

Of course he normal build command works `docker build  git@github.com:xxxx/yyyy.git` 

**Expected behavior**:

`docker buildx build  git@github.com:xxxx/yyyy.git` should be able to use the ssh key or the ssh-agent in order to download the private project and then build the project.

Docker buildx version:
```
github.com/docker/buildx v0.2.0 91a2774376863c097ca936bf5e39aa3db0c72d0f
```

Docker version:
```
Client: Docker Engine - Community
 Version:           19.03.0-beta4
 API version:       1.40
 Go version:        go1.12.4
 Git commit:        e4666ebe81
 Built:             Tue May 14 12:47:08 2019
 OS/Arch:           linux/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          19.03.0-beta4
  API version:      1.40 (minimum version 1.12)
  Go version:       go1.12.4
  Git commit:       e4666ebe81
  Built:            Tue May 14 12:45:43 2019
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.2.5
  GitCommit:        bb71b10fd8f58240ca47fbb579b9d1028eea7c84
 runc:
  Version:          1.0.0-rc6+dev
  GitCommit:        2b18fe1d885ee5083ef9f0838fee39b62d653e30
 docker-init:
  Version:          0.18.0
  GitCommit:        fec3683
```

**Comment by crazy-max** [comment]
Fixed since 0.6.0
