### ISSUE TITLE
failed to solve with frontend dockerfile.v0: failed to create LLB definition: the Dockerfile cannot be empty

### ISSUE THREAD

**Issue by phdykd** [docker/buildx#771]
Hi,
I am trying to repeat to learn the Docker by following the link here. 
https://docs.docker.com/get-started/02_our_app/
I am getting this error "failed to solve with frontend dockerfile.v0: failed to create LLB definition: the Dockerfile cannot be empty"
Recommendations posted before did not help. Any help would be appreciated. 

![image](https://user-images.githubusercontent.com/72084102/133537138-5a61dd2a-8493-4792-838e-388a9628e94b.png)
![image](https://user-images.githubusercontent.com/72084102/133537192-49c49aa4-250f-4e7e-9181-0a8dd9b328eb.png)
![image](https://user-images.githubusercontent.com/72084102/133537228-f9cefaf8-e29a-427f-a8cf-7cd3e624e7a0.png)

**Comment by tonistiigi** [comment]
As it is visible from your last screenshot, the `Dockerfile` is actually empty. So maybe you forgot to save or issue with your editor.
