### ISSUE TITLE
Push to GitHub fails - unexpected status: 401 Unauthorized

### ISSUE THREAD

**Issue by mgoltzsche** [docker/buildx#780]
On my machine pushes to the GitHub Container Registry fail with `error: failed to solve: unexpected status: 401 Unauthorized` when using `docker buildx build ... --push`. However I can push to GitHub using the same credentials when I use `docker push`. When pushing to DockerHub using `buildx` (in the same way I'd push to GitHub) it also works fine. It looks like buildx/BuildKit is not providing credentials with the request to push to GitHub for some reason.
This is related to #327.
FWIW I verified that pushes to the GitHub Container Registry fail no matter if the tag exists already within the repo or if I use a new tag.
Also I noticed that buildx logs `#34 [auth] docker.io/mgoltzsche/someimage:pull,push token for registry-1.docker.io` before pushing the image to DockerHub, indicating that it authenticated successfully prior to the push operation, but when doing the same operation using a GitHub Container Registry image ref the authentication log message does not appear at all.
Therefore it seems that there's a credential mapping bug in buildx somewhere.

**Steps to reproduce**
To give an example:
```
$ docker login docker.pkg.github.com ... # succeeds
$ docker login docker.io ... # succeeds
$ docker build -t docker.pkg.github.com/mgoltzsche/some-project/some-image:latest . # succeeds
$ docker push docker.pkg.github.com/mgoltzsche/some-project/some-image:latest # succeeds
$ docker buildx create --name=mybuilder
$ docker buildx build --push --builder=mybuilder --platform=linux/arm64/v8,linux/amd64 --force-rm -t docker.io/mgoltzsche/some-image:latest . # succeeds
$ docker buildx build --push --builder=mybuilder --platform=linux/arm64/v8,linux/amd64 --force-rm -t docker.pkg.github.com/mgoltzsche/some-project/some-image:latest . # fails
[+] Building 1.8s (0/1)
[+] Building 5.4s (99/99) FINISHED
...
=> CACHED [linux/arm64 someimage 4/4] COPY conf/cni /etc/cni                                                                                                  0.0s
 => ERROR exporting to image                                                                                                                                   0.3s
 => => exporting layers                                                                                                                                        0.0s
 => => exporting manifest sha256:a3b80292ded4fbea1560599c6bda2dbb95a4168f1eac82480417b21ed5706116                                                              0.0s
 => => exporting config sha256:fe93133216e8a662a799cdf5a53ddd3f65ee36310d00b62149873b20d16a2dec                                                                0.0s
 => => exporting manifest sha256:96af90b430af39c2d99ce7469a750608566197127aed7cc65466a56458f03ec0                                                              0.0s
 => => exporting config sha256:b62dfa392111b646b545d9d4fc9299e6582b35cb6836f33ed1b33137b2d9064b                                                                0.0s
 => => exporting manifest list sha256:3461f66111e97f3087f40020f9e00f21e7ab5d5fafd8112a2306ef1b0f3b0c9d                                                         0.0s
 => => pushing layers
------
 > exporting to image:
------
error: failed to solve: unexpected status: 401 Unauthorized
```

**Environment:**
OS: Ubuntu 20.04
Docker version:
```
$ docker version
Client: Docker Engine - Community
 Version:           20.10.8
 API version:       1.41
 Go version:        go1.16.6
 Git commit:        3967b7d
 Built:             Fri Jul 30 19:54:27 2021
 OS/Arch:           linux/amd64
 Context:           default
 Experimental:      true

Server: Docker Engine - Community
 Engine:
  Version:          20.10.8
  API version:      1.41 (minimum version 1.12)
  Go version:       go1.16.6
  Git commit:       75249d8
  Built:            Fri Jul 30 19:52:33 2021
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.4.9
  GitCommit:        e25210fe30a0a703442421b0f60afac609f950a3
 runc:
  Version:          1.0.1
  GitCommit:        v1.0.1-0-g4144b638
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0
```
Buildx version: github.com/docker/buildx v0.6.1-docker 260d07a9a19b03df969787496419a0808a27ac61
BuildKit version: buildkitd github.com/moby/buildkit v0.9.0 c8bb937807d405d92be91f06ce2629e6202ac7a9

**Comment by crazy-max** [comment]
@mgoltzsche `docker.pkg.github.com` is deprecated and will sunset soon. I suggest to [migrate to GitHub Container Registry](https://docs.github.com/en/packages/getting-started-with-github-container-registry/migrating-to-github-container-registry-for-docker-images) instead. See also https://docs.github.com/en/packages/learn-github-packages/configuring-a-packages-access-control-and-visibility.

**Comment by mgoltzsche** [comment]
Oh, thanks for the hint! :sweat_smile:
