### ISSUE TITLE
Cannot COPY from a RUN that uses a cache type

### ISSUE THREAD

**Issue by zg** [docker/buildx#788]
In a watered down example, I'm trying to use `COPY` to shift the contents of `/root` from one stage into the next in a multi-stage build. When I list the contents of `/root` in the resulting image, the directory is empty. Here is the Dockerfile:

```
# syntax = docker/dockerfile:1.2
FROM alpine AS stage1

RUN --mount=type=cache,target=/root touch /root/hello.txt

FROM alpine

COPY --from=stage1 /root /root
```

**Comment by tonistiigi** [comment]
Cache mounts do not persist in the image. They are only available to the `RUN` command that has the mount. If you want files to persist you need to copy them to somewhere else.

**Comment by zg** [comment]
Thanks!
