### ISSUE TITLE
failed to solve with frontend dockerfile.v0: failed to create LLB definition: dockerfile parse error line 2: COPY requires at least two arguments, but only one was provided. Destination could not be determined.

### ISSUE THREAD

**Issue by unfamousfox** [docker/buildx#821]
> FROM python:3.7-slim
> COPY C:\Users\Fra\Desktop\Fra\uni\Tesi\Python
> WORKDIR C:\Users\Fra\angular-map
> ENV PYTHONUNBUFFERED 1
> RUN pip3 install -r /code/requirements.txt
> CMD ["python","app.py"]

I keep getting this error, what can i do to solve this?

**Comment by bjornsnoen-nav** [comment]
As the error says, `COPY` takes two arguments, the first is the source, the second is the destination. If you just want to add your file to the currently set `WORKDIR` you can use `ADD` instead of `COPY`

**Comment by tonistiigi** [comment]
> If you just want to add your file to the currently set WORKDIR you can

If you just want to add your file to the currently set WORKDIR you should use `.` as the destination.
