### ISSUE TITLE
Using gha cache with `mode=max` fails with 400 error

### ISSUE THREAD

**Issue by hertzg** [docker/buildx#841]
Hello, I have recently started using `cahe-to "type=gha,mode=max,scope=..."` to cache all the layers and the following error seemed to persist only for specific builds (consistently failing on the same). After removeing the `mode=max`  the issues went away but obviousely not everything is cached.

Failing builds with `mode=max`:
* https://github.com/hertzg/rtl_433_docker/actions/runs/1455213857
* https://github.com/hertzg/rtl_433_docker/actions/runs/1451049139
* https://github.com/hertzg/rtl_433_docker/actions/runs/1446674498

Passing build after removing `mode=max`
* https://github.com/hertzg/rtl_433_docker/actions/runs/1457410662

```
#130 exporting cache
#130 preparing build cache for export
#130 preparing build cache for export 121.0s done
#130 writing layer sha256:06be072867b08bb9aef2e469533d0d0d6a85f97c2aabcaf5103d78c217977918
#130 writing layer sha256:06be072867b08bb9aef2e469533d0d0d6a85f97c2aabcaf5103d78c217977918 0.1s done
#130 writing layer sha256:08980434c63c0751ea69086b9c8282a5b2784f78643934cf62036ae07e94b943
#130 writing layer sha256:08980434c63c0751ea69086b9c8282a5b2784f78643934cf62036ae07e94b943 0.1s done
...
redacted to keep it short
...
#130 writing layer sha256:d91065fb02477295b9823f300711ac850313d3b6a81a6ca1f8d214f8700b8b2e
#130 writing layer sha256:d91065fb02477295b9823f300711ac850313d3b6a81a6ca1f8d214f8700b8b2e 4.0s done
#130 ERROR: error writing layer blob: error committing cache 37887: failed to parse error response 400: <!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01//EN""http://www.w3.org/TR/html4/strict.dtd">
<HTML><HEAD><TITLE>Bad Request</TITLE>
<META HTTP-EQUIV="Content-Type" Content="text/html; charset=us-ascii"></HEAD>
<BODY><h2>Bad Request</h2>
<hr><p>HTTP Error 400. The request is badly formed.</p>
</BODY></HTML>
: invalid character '<' looking for beginning of value
------
 > exporting cache:
------
error: failed to solve: error writing layer blob: error committing cache 37887: failed to parse error response 400: <!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01//EN""http://www.w3.org/TR/html4/strict.dtd">
<HTML><HEAD><TITLE>Bad Request</TITLE>
<META HTTP-EQUIV="Content-Type" Content="text/html; charset=us-ascii"></HEAD>
<BODY><h2>Bad Request</h2>
<hr><p>HTTP Error 400. The request is badly formed.</p>
</BODY></HTML>
: invalid character '<' looking for beginning of value
Error: buildx failed with: : invalid character '<' looking for beginning of value
```

**Comment by hertzg** [comment]
Maybe @tonistiigi & @crazy-max Any hints or suggestions? I'd be happy to provide more info if required

**Comment by tonistiigi** [comment]
@hertzg Could you run a custom version of buildkit that logs out what request (parameters) causes this issue in https://github.com/moby/buildkit/blob/324fc9333bb63a2bf95f341a8d92639f9aa8348c/vendor/github.com/tonistiigi/go-actions-cache/cache.go#L440

@dhadka @chrispat Any ideas what this could be? Seems to come from https://github.com/tonistiigi/go-actions-cache/blob/4d48f2ff622acbb68ad134425c8df3096fec0229/cache.go#L272

**Comment by hertzg** [comment]
@tonistiigi I could yes I'm not sure I know how exactly thou, I assume I need a built image if `moby/buildx` for that commit so I could use it  with `docker buildx create .... --driver-opt image=...`? If so could you help with the image that I could pull?

**Comment by tonistiigi** [comment]
@hertzg I pushed an image with additional logs. `tonistiigi/buildkit:gha-logs` https://github.com/moby/buildkit/compare/master...tonistiigi:gha-request-logs . Set it as buildkit image and report back. You also need to enable debug, if you use docker's actions then just enable the debug mode in github actions. If you call `buildx create` manually then you need to set `--buildkitd-flags '--debug'`

**Comment by hertzg** [comment]
Thanks for the instructions, I've setup a [branch with those changes](https://github.com/hertzg/rtl_433_docker/pull/43/files) (incl. actions debug), the [build is running](https://github.com/hertzg/rtl_433_docker/actions/runs/1499243767), this might take an hour to finish. 

I'll report back with the reuslts.

**Comment by hertzg** [comment]
[First attempt](https://github.com/hertzg/rtl_433_docker/actions/runs/1499243767/attempts/2): failed with timeouts, [I've restarted ](https://github.com/hertzg/rtl_433_docker/actions/runs/1499243767/attempts/3)it to see if its flakiness.

**Comment by hertzg** [comment]
@tonistiigi I [managed reproduce it again](https://github.com/hertzg/rtl_433_docker/actions/runs/1500908897) I don't see any new error messages so far.

**Comment by tonistiigi** [comment]
@dhadka @chrispat Could it be that after `POST` request gets hit by rate-limiting, the retry receives 400? Could it at least not return an HTML error? It seems to be missing all the API headers, as if some kind of proxy responded with 400.

**Comment by hertzg** [comment]
@dhadka @chrispat gentle bump 😊

**Comment by chrispat** [comment]
@kmkumaran can you have some one take a look here?

**Comment by dhadka** [comment]
Is the retry logic safe?  From what I can tell, it seems like the request is getting interrupted before getting to the cache API (we're seeing a Client Disconnected error).

I'm not a Go developer, but I do see it's creating a reader for the JSON object:

```
req, err := http.NewRequest("POST", c.url(fmt.Sprintf("caches/%d", id)), bytes.NewReader(dt))
```

Does it need to reset that Reader to the start of the content (i.e., a `Reset`)?

**Comment by tonistiigi** [comment]
@dhadka That could be the issue indeed. Thanks for the pointer. I'll update that logic.

**Comment by tonistiigi** [comment]
https://github.com/tonistiigi/go-actions-cache/pull/12

**Comment by hertzg** [comment]
@tonistiigi Any builds you'd like me to try out?

**Comment by tonistiigi** [comment]
moby/buildkit#2506

test build `tonistiigi/buildkit:pr2506`

**Comment by hertzg** [comment]
I am no longer able to reproduce the issue with `tonistiigi/buildkit:pr2506` buildkit image. 🎉

**Comment by hertzg** [comment]
@tonistiigi I see that the PR has been merged and approed, Unfortunately I'm unaware of the release cyles of buildkit, could you hint me in the correct direction where I could find when to expect the next release that would include this change? 🙌

**Comment by tonistiigi** [comment]
@hertzg We will probably not do another patch release just for this unless something else comes up as well. You can use the master branch image(or pin it to digest for safety). cc @crazy-max

**Comment by tonistiigi** [comment]
fixed in moby/buildkit#2506

**Comment by hertzg** [comment]
Thanks for all the great work everyone involved 🙌 

For general reference this is the digest I'm going for 
```
moby/buildkit@sha256:b8d8458bbab41b575614801826d3e0f50e93d8730aaf68431713e3bdb4378744
```

**Comment by hertzg** [comment]
SInce I've started using the pinned release I noticed a lot of timeout errors.

With messages similar to:
```
buildx failed with: error: failed to solve: error writing layer blob: error committing cache 66034: maximum timeout reached
buildx failed with: error: failed to solve: maximum timeout reached
```

Is this an issue on the cache side or ... ?

Links:
* https://github.com/hertzg/rtl_433_docker/actions/runs/1556513194/attempts/1
* https://github.com/hertzg/rtl_433_docker/actions/runs/1551797481/attempts/1
* https://github.com/hertzg/rtl_433_docker/actions/runs/1551797481/attempts/2

**Comment by dhadka** [comment]
@hertzg Yes, this is on the cache side.  I'm seeing requests getting rate limited.  There's a limit on the number of caches that can be created every 5 minute window, and this action can exceed that if the number of layers and/or matrix build is large.  We're looking to increase that limit as long as it doesn't impact the health of the cache service.

**Comment by tonistiigi** [comment]
> error committing cache 66034: maximum timeout reached

Atm the cache library will retry with a backoff but if the service does not return in 5 min then you get an error like this.

**Comment by hertzg** [comment]
@dhadka Thanks for the detailed explanation, what would be the recommended solution here other than reducing the amount of jobs?

@tonistiigi As I understand it now, the whole build is getting marked as failed because the rate limiting window and total timeout are very close to each other (both 5min). Would increasing the timeout help and not make the build fail?

**Comment by hertzg** [comment]
As of current state, I had to disable it as it's just failing the builds and always needs restarts😞

**Comment by bishal-pdMSFT** [comment]
@hertzg we will be looking into relaxing the rate limit. But we need to carefully evaluate the extra load it will bring on the system. I will update you with an ETA.

**Comment by hertzg** [comment]
Hello agian from the new Year, (hopefully) after all the festivities :) 
@bishal-pdMSFT Where can we track the progress for evaluation?

**Comment by bishal-pdMSFT** [comment]
@hertzg apologize for the delay, but the good new is that we are rolling out a change to increase the rate limit threshold. This should allow buildx action to cache layers with higher level of parallelization. cc @t-dedah to keep you in loop when rollout is complete.

Would love to hear back on whether this helps in reducing the `429`s.

**Comment by t-dedah** [comment]
@hertzg We have increased the RU limit from 450 to 700 on all the rings. This should reduce the number 429s significantly. 

We saw a significant reduction in 429 after increasing the RU limit as shown in below images.

## Before
<img width="1219" alt="1" src="https://user-images.githubusercontent.com/59823596/157044464-c0c64c03-158b-465f-8de7-66e5cf269475.png">

## After
<img width="1341" alt="2" src="https://user-images.githubusercontent.com/59823596/157044478-478ebec6-a5c2-4783-9eb3-f4531108f4c5.png">

**Comment by hertzg** [comment]
@t-dedah I'm seeing timeouts and builds still failing right after enabling `mode=max`

https://github.com/hertzg/rtl_433_docker/runs/5523758504?check_suite_focus=true

**Comment by t-dedah** [comment]
Hi @hertzg There is still a limit on number of requests we can make to seal and reserve cache. We have almost doubled that limit but if any action breaches that limit, we will still get a 429. 
The current limit is set to 700 for both seal and reserve cache so 350 for each seal and reserve cache. If you have can help with a number which you think will be enough for `mode=max` then we can test and see how to get as close as possible to that limit. 

[The reasoning behind the new 700 limit](https://github.com/github/c2c-actions/issues/3764#issuecomment-997039132)

**Comment by tonistiigi** [comment]
@t-dedah @dhadka I'll try to give some more background on where I think our requests come from.

Let's say the user is doing a build that touches, for example, 50 blobs/layers in total(with Github cache users usually would export all intermediate layers as well, not only the final result layers so this can grow fast). If that build is mostly cached, for example updated only 1 layer we will create a new "manifest" blob with links to these 50 layers. We will push the manifest and new layer, but most importantly we still need to make a request for all the old 49 blobs just to check if they still exists. We will make a request for all of them, Github will answer that record exists and we can continue. This needs to happen for all builds and some repositories make a lot of builds in a single workflow or very complex(multi-platform) builds with lots of layers.

If there would be an endpoint we could use just to check that a cache key exists that would not be rate-limited(or with a much higher limit) it would be much less likely to hit these limits. That endpoint does not need to provide a download link or reserve a key like the current requests do. It could also be a batch endpoint to check multiple keys together. Maybe even just endpoint to list all current keys would be manageable as keys should be small and not take much room even if there are a lot of them.

Another way would be for us to somehow remember that the cache key existed and not check it more often than some timeframe. But for that, we would need some kind of external storage/database where we could keep these records.

> [The reasoning behind the new 700 limit](https://github.com/github/c2c-actions/issues/3764#issuecomment-997039132)

Looks like this is a private repository.

**Comment by dhadka** [comment]
> If there would be an endpoint we could use just to check that a cache key exists that would not be rate-limited(or with a much higher limit) it would be much less likely to hit these limits.

If you're using the [cache toolkit module](https://github.com/actions/toolkit/blob/main/packages/cache), then read and writes are handled in separate calls (`restoreCache` vs `saveCache`).  But `restoreCache` checks if the cache exists + downloads the content.

Inside `restoreCache`, it makes a call to [`cacheHttpClient.getCacheEntry`](https://github.com/actions/toolkit/blob/d1abf7dc74ea38ed6c5552491cdf8b695b813722/packages/cache/src/cache.ts#L81) that can be used to just check if the record exists:

```
  const cacheEntry = await cacheHttpClient.getCacheEntry(keys, paths, {
    compressionMethod
  })
  if (!cacheEntry?.archiveLocation) {
    // Cache not found
    return undefined
  }
```

Although this is getting into some of the internal implementation.  Perhaps we need to add another top-level function alongside `restoreCache` and `saveCache` that just checks if the cache exists.

This `GET` operation also has a higher rate limit (900).  Although now that the seal/reserve limit was increased (300 -> 700), it's not much higher :smile: @t-dedah can we please look into increasing this limit?

**Comment by tonistiigi** [comment]
I think this is the same https://github.com/tonistiigi/go-actions-cache/blob/master/api.md#get-cache we already use. We don't actually pull the cache in the case described above but the request we make contains a download link. I'm not sure if adding this download link there is a reason you need to rate-limit this request.

**Comment by t-dedah** [comment]
Hi @tonistiigi We already have a `GET` call which is also being used in [Load function](https://github.com/moby/buildkit/blob/324fc9333bb63a2bf95f341a8d92639f9aa8348c/vendor/github.com/tonistiigi/go-actions-cache/cache.go#L201), so will it be possible for you to use that to check if the layer exists and only then make a `reserve` call if necessary. We can also increase the RU limit for `GET` in order to handle the increased load with this change.

**Comment by tonistiigi** [comment]
I believe this is the same call I linked earlier and I think this is the one that most likely gets the limit error as these are the most common requests we send.

The way to avoid these requests would be to add an endpoint that would return all existing cache keys for a scope so we don't need to check them individually. Or add another `GET` style request that wouldn't return a download link and would instead allow higher limits(as this endpoint should be safer as it can't cause excess traffic).

Additional question: Are the limits per workflow step or more global? I assume they are for the whole workflow/repo/user. If they are not we might be able to save some requests by caching the "exist" results locally in case there are repeated builds inside the same workflow step.

**Comment by t-dedah** [comment]
> I believe this is the same call I linked earlier and I think this is the one that most likely gets the limit error as these are the most common requests we send.

The [logs shared above](https://github.com/docker/buildx/issues/841#issuecomment-979074748) shows that 429 is due to the POST call.


>  Are the limits per workflow step or more global?

The limit is for a particular user which would mean its linked to the repo rather than to a workflow run.


> The way to avoid these requests would be to add an endpoint that would return all existing cache keys for a scope so we don't need to check them individually. Or add another GET style request that wouldn't return a download link and would instead allow higher limits(as this endpoint should be safer as it can't cause excess traffic).
 
 The addition of a new API might take some time but we can try increasing the limit for GET call. Ill get back to you on this one after dicussing with my team.

**Comment by t-dedah** [comment]
Hi @tonistiigi

Summary:-

1. You can use `GET` api to check if the cache exists so we dont have to make multiple `Reserve` calls. The limit for `GET` is 900 which should we enough and we can also increase this further, if needed. If the cache key doesnt exist then you can reserve that layer only.

2. In the future we will also have a `LIST` api which will further reduce the number of `REST` calls needed. This API is in planning stage at the moment.
