### ISSUE TITLE
Building dockerfile for amd64 and amr64 works on new M1 chip but not on Intel CPU

### ISSUE THREAD

**Issue by zilinjak** [docker/buildx#843]
Hello, 
I was trying to build dockerfile using buildx.
Command Im using to build it is `docker buildx build --platform linux/arm64`
On M1 macbook all was working fine but was taking ages so I decided to try my Intel i5 10600K if its any faster.
It is faster, but Im getting compile errors that Im not getting on M1
Docker version `Docker version 20.10.8, build 3967b7d`
Dockerfile can be found in attachments.

[Dockerfile.txt](https://github.com/docker/buildx/files/7550464/Dockerfile.txt)
Error are made by commands on lines:  4,5,15 (can be more, tes

**Comment by tonistiigi** [comment]
What errors are you getting? Are they related to builder?
