### ISSUE TITLE
when use --driver kubernetes,Whether the k8s pod can be self-destructed?

### ISSUE THREAD

**Issue by gitfxx** [docker/buildx#855]
We are now using the -- Driver Kubernetes to build the image in the cluster. We want the pod to be destroyed automatically after the image is built. Does Buildx support it now?
The only way to clear it now seems to be by buildx rm --instance Builder.

**Comment by tonistiigi** [comment]
You need to run `rm` the same way you needed to run `create` before building.

**Comment by gitfxx** [comment]
@tonistiigi ok，thanks。  this issue can be closed.
