### ISSUE TITLE
Question : How can I build a multi-arch image once and then push it to dockerhub and ECR?

### ISSUE THREAD

**Issue by abhinavGupta16** [docker/buildx#876]
I want to build a multiarch image **once** and then push the same image to dockerhub and ECR. It is possible, if yes how?

I am currently building my image using `buildx`.

**Comment by kirooshu** [comment]
You can always tag the image for both repositories, something similar to this:

```
docker buildx build --pull --push \
--platform linux/amd64,linux/arm64 \
-t "123456789.dkr.ecr.us-east-1.amazonaws.com/some-image" \
-t "docker.io/some-image"
-f Dockerfile \
.
```
