### ISSUE TITLE
Error: Failed to Solve: Authorization Status: 401: authorization failed

### ISSUE THREAD

**Issue by prayritkhanna** [docker/buildx#878]
Hello...

I've been trying to build and push docker buildx images using multiple platforms to DockerHub.

```
sudo docker buildx create --name mybuilder
```
After successfully creating a builder instance, I then began to run:

```
sudo docker buildx build --platform linux/amd64,linux/arm64 -t docker.io/xxx/test:test1 --push  .
```
I'm running into the issue... 
```
=> [1/6] FROM docker.io/library/ubuntu:20.04@sha256:626ffe58f6e7566e00254b638eb7e0f3b11d4da9675088f4781a50ae288f3322                                                                     0.0s
 => => resolve docker.io/library/ubuntu:20.04@sha256:626ffe58f6e7566e00254b638eb7e0f3b11d4da9675088f4781a50ae288f3322                                                                     0.0s
 => CACHED [2/6] RUN apt-get update     &&     DEBIAN_FRONTEND=noninteractive     apt-get install --assume-yes --no-install-recommends         build-essential         ca-certificates    0.0s
 => CACHED [3/6] RUN locale-gen en_US.UTF-8                                                                                                                                               0.0s
 => CACHED [4/6] RUN update-locale LC_ALL=en_US.UTF-8 LANG=en_US.UTF-8                                                                                                                    0.0s
 => CACHED [5/6] RUN DEBIAN_FRONTEND=noninteractive     apt-get install --assume-yes --no-install-recommends         iasl                                                                 0.0s
 => CACHED [6/6] RUN rm -rf /var/lib/apt/lists/*                                                                                                                                          0.0s
 => ERROR exporting to image                                                                                                                                                              0.4s
 => => exporting layers                                                                                                                                                                   0.0s
 => => exporting manifest sha256:a53a7a44f3ca8b933e577b5b1b0fce10a02e2718f83c38edd2c2791bc04babe4                                                                                         0.0s
 => => exporting config sha256:1229aaa181cd0ea0b734d919720452adbac53cd5b425ecccda83832569ce6cc9                                                                                           0.0s
 => => pushing layers                                                                                                                                                                     0.3s
------
 > exporting to image:
------
error: failed to solve: authorization status: 401: authorization failed
```

I have successfully pushed am image using ```docker push .``` so I know nothing is wrong on the DockerHub side.

After researching this issue for the past few days, I've found a few answers online to fix this but nothing seems to work for me.

I'm currently using:
```
 Version:           20.10.11
 API version:       1.41
 Go version:        go1.16.9
 Git commit:        dea9396
 Built:             Thu Nov 18 00:37:06 2021
 OS/Arch:           linux/amd64
 Context:           default
 Experimental:      true

Server: Docker Engine - Community
 Engine:
  Version:          20.10.11
  API version:      1.41 (minimum version 1.12)
  Go version:       go1.16.9
  Git commit:       847da18
  Built:            Thu Nov 18 00:35:15 2021
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.4.12
  GitCommit:        7b11cfaabd73bb80907dd23182b9347b4245eb5d
 runc:
  Version:          1.0.2
  GitCommit:        v1.0.2-0-g52b36a2
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0
```
And Buildx:
```github.com/docker/buildx v0.6.3-docker 266c0eac611d64fcc0c72d80206aa364e826758d```

Also, I was also able to successfully login to my dockerHub account through CLI. 

Btw... I'm using Ubuntu 20.04 Focal!

Thanks so much!

**Comment by crazy-max** [comment]
@prayritkhanna Can you show the buildkit logs: `docker logs buildx_buildkit_mybuilder0`?

**Comment by prayritkhanna** [comment]
@crazy-max Here is the output of the log:

`time="2021-12-08T22:22:17Z" level=info msg="auto snapshotter: using overlayfs"
time="2021-12-08T22:22:17Z" level=warning msg="using host network as the default"
time="2021-12-08T22:22:17Z" level=info msg="found worker \"egw9d5nmmzesiyzho5xbayckn\", labels=map[org.mobyproject.buildkit.worker.executor:oci org.mobyproject.buildkit.worker.hostname:ccd9e9ba1a40 org.mobyproject.buildkit.worker.snapshotter:overlayfs], platforms=[linux/amd64 linux/arm64 linux/riscv64 linux/ppc64le linux/s390x linux/386 linux/mips64le linux/mips64 linux/arm/v7 linux/arm/v6]"
time="2021-12-08T22:22:17Z" level=warning msg="skipping containerd worker, as \"/run/containerd/containerd.sock\" does not exist"
time="2021-12-08T22:22:17Z" level=info msg="found 1 workers, default=\"egw9d5nmmzesiyzho5xbayckn\""
time="2021-12-08T22:22:17Z" level=warning msg="currently, only the default worker can be used."
time="2021-12-08T22:22:17Z" level=info msg="running server on /run/buildkit/buildkitd.sock"
time="2021-12-08T22:26:45Z" level=error msg="/moby.buildkit.v1.Control/Solve returned error: rpc error: code = Unknown desc = authorization status: 401: authorization failed\n"
time="2021-12-08T22:33:20Z" level=error msg="/moby.buildkit.v1.Control/Solve returned error: rpc error: code = Unknown desc = authorization status: 401: authorization failed\n"
time="2021-12-09T13:47:29Z" level=info msg="stopping server"
buildkitd: context canceled
time="2021-12-09T14:17:03Z" level=info msg="auto snapshotter: using overlayfs"
time="2021-12-09T14:17:03Z" level=warning msg="using host network as the default"
time="2021-12-09T14:17:03Z" level=info msg="found worker \"egw9d5nmmzesiyzho5xbayckn\", labels=map[org.mobyproject.buildkit.worker.executor:oci org.mobyproject.buildkit.worker.hostname:ccd9e9ba1a40 org.mobyproject.buildkit.worker.snapshotter:overlayfs], platforms=[linux/amd64 linux/arm64 linux/riscv64 linux/ppc64le linux/s390x linux/386 linux/mips64le linux/mips64 linux/arm/v7 linux/arm/v6]"
time="2021-12-09T14:17:03Z" level=warning msg="skipping containerd worker, as \"/run/containerd/containerd.sock\" does not exist"
time="2021-12-09T14:17:03Z" level=info msg="found 1 workers, default=\"egw9d5nmmzesiyzho5xbayckn\""
time="2021-12-09T14:17:03Z" level=warning msg="currently, only the default worker can be used."
time="2021-12-09T14:17:03Z" level=info msg="running server on /run/buildkit/buildkitd.sock"
time="2021-12-09T15:22:16Z" level=error msg="/moby.buildkit.v1.Control/Solve returned error: rpc error: code = Unknown desc = failed to read dockerfile: error from sender: lstat thinclient_drives: permission denied\n"
time="2021-12-09T15:22:27Z" level=error msg="/moby.buildkit.v1.Control/Solve returned error: rpc error: code = Unknown desc = no build stage in current context\n"
time="2021-12-09T15:23:47Z" level=error msg="/moby.buildkit.v1.Control/Solve returned error: rpc error: code = Unknown desc = authorization status: 401: authorization failed\n"
time="2021-12-09T15:31:01Z" level=error msg="/moby.buildkit.v1.Control/Solve returned error: rpc error: code = Unknown desc = authorization status: 401: authorization failed\n"`

**Comment by crazy-max** [comment]
@prayritkhanna I see that you're using `sudo docker buildx build ...`. Are you also logged in using sudo? `sudo docker login`?

**Comment by prayritkhanna** [comment]
@crazy-max yes.. I have tried to use `docker buildx build` and received an error that the command is unrecognizable..  I read online in a SO answer to use SUDO to resolve this issue.

**Comment by prayritkhanna** [comment]
Oh wow @crazy-max... I needed to use `sudo docker login` for it to work..! Thank you so much for your help!

I really feel like an idiot right now 😄

**Comment by acekingke** [comment]
I have use docker login, but still got error:
```
 => ERROR exporting to image                                                                                                                                     6.6s
 => => exporting layers                                                                                                                                          2.1s
 => => exporting manifest sha256:58b3be45176fe36afe353b85fa14ede3cc303cc54be14c792c32ab94a613fe56                                                                0.0s
 => => exporting config sha256:bcab80bbe253b78261246c3e7548f76bcfea30d9b68acdb14fcd0c2ad36eba52                                                                  0.0s
 => => exporting manifest sha256:84e94c8b2706f00ebaf1d933ce141af862c920aa7611566fbc858a39ddb3e898                                                                0.0s
 => => exporting config sha256:95306018fde137aaf9a64d7045949ffc392f967f6f8e0bfbee38343c0d89ee78                                                                  0.0s
 => => exporting manifest list sha256:0292abf3b48cbeb1ac0a26e902deaf8e9807e18a76701ef2a4df92d7cb84ff7f                                                           0.0s
 => => pushing layers                                                                                                                                            4.4s
 => [auth] aceking/mysql-operator:pull,push token for registry-1.docker.io                                                                                       0.0s
 => [auth] aceking/mysql-operator:pull,push token for registry-1.docker.io                                                                                       0.0s
 => [auth] aceking/mysql-operator:pull,push token for registry-1.docker.io                                                                                       0.0s
 => [auth] aceking/mysql-operator:pull,push token for registry-1.docker.io                                                                                       0.0s
 => [auth] aceking/mysql-operator:pull,push token for registry-1.docker.io                                                                                       0.0s
 => [auth] aceking/mysql-operator:pull,push token for registry-1.docker.io                                                                                       0.0s
 => [auth] aceking/mysql-operator:pull,push token for registry-1.docker.io                                                                                       0.0s
 => [auth] aceking/mysql-operator:pull,push token for registry-1.docker.io                                                                                       0.0s
 => [auth] aceking/mysql-operator:pull,push token for registry-1.docker.io                                                                                       0.0s
 => [auth] aceking/mysql-operator:pull,push token for registry-1.docker.io                                                                                       0.0s
------
 > exporting to image:
------
ERROR: failed to solve: authorization status: 401: authorization failed
```
