### ISSUE TITLE
"docker build" should skip unused stages but does not

### ISSUE THREAD

**Issue by gaspardpetit** [docker/buildx#879]
- [x] I have tried with the latest version of Docker Desktop
  - [x] I have tried disabling enabled experimental features
  - [x] I have uploaded Diagnostics
  - Diagnostics ID: 06AA9AA2-D7DD-4A37-B8D9-243DAE52B96C/20211208011707

### Actual behavior
The following Dockerfile fails to build with the two following commands:

```Dockerfile
FROM mcr.microsoft.com/windows/nanoserver:1909 as windows-base

FROM windows-base as should-be-skipped
RUN "exit 255"

FROM windows-base as production
````

```bash
docker build --target production -t test .
docker build --target=production -t test .
docker build -t test .
```

The output, in all cases is
```
The command 'cmd /S /C "exit 255"' returned a non-zero code: 255
```

### Expected behavior
The expected behaviour should be that the last stage (`production`), when selected, should skip the creation of the intermediate stage (`should-be-skipped`). When not explicitly targeted, it should still be skipped since the selected stage should be the last one defined in the `Dockerfile` and the intermediate stage is not needed to assemble the last stage.

We use intermediate stages to run tests. The impact for us is that the test stage can never be skipped even when targeting the `production` stage.

The following `Dockerfile` works as expected with docker for Linux:

```Dockerfile
FROM alpine as linux-base

FROM linux-base as should-be-skipped
RUN "exit 255"

FROM linux-base as production
```

Results in:
```
 => [internal] load build definition from Dockerfile
 => => transferring dockerfile: 153B
 => [internal] load .dockerignore
 => => transferring context: 2B
 => [internal] load metadata for docker.io/library/alpine:latest
 => [auth] library/alpine:pull token for registry-1.docker.io
 => [linux-base 1/1] FROM docker.io/library/alpine@sha256:21a3deaa0d32a8057914f36584b5288d2e5ecc984380bc0118285c70fa8c9300
 => => resolve docker.io/library/alpine@sha256:21a3deaa0d32a8057914f36584b5288d2e5ecc984380bc0118285c70fa8c9300
 => => sha256:e7d88de73db3d3fd9b2d63aa7f447a10fd0220b7cbf39803c803f2af9ba256b3 528B / 528B
 => => sha256:c059bfaa849c4d8e4aecaeb3a10c2d9b3d85f5165c66ad3a4d937758128c4d18 1.47kB / 1.47kB
 => => sha256:59bf1c3509f33515622619af21ed55bbe26d24913cedbca106468a5fb37a50c3 2.82MB / 2.82MB
 => => sha256:21a3deaa0d32a8057914f36584b5288d2e5ecc984380bc0118285c70fa8c9300 1.64kB / 1.64kB
 => => extracting sha256:59bf1c3509f33515622619af21ed55bbe26d24913cedbca106468a5fb37a50c3
 => exporting to image
 => => exporting layers
 => => writing image sha256:35e223a20dbce8c0b81d3257f8cad0c7b2b35d8e18eadfec7eeb7de86a472e7b
 => => naming to docker.io/library/test
```

### Information

  - Windows Version: Version	10.0.19042 Build 19042
  - Docker Desktop Version: 4.3.0 (71786) (engine 20.10.11)
  - WSL2 or Hyper-V backend?  WSL2
  - Are you running inside a virtualized Windows e.g. on a cloud server or a VM: no

**Comment by tonistiigi** [comment]
What is the full output? I assume that output is not from buildx/buildkit as buildkit doesn't support wcow (except some cross compile cases).

**Comment by gaspardpetit** [comment]
Thanks for taking a look. I am not too sure whose team this falls under. I use the docker client which comes with Docker Desktop for Windows. I'd think that it uses the underlying docker windows service to build - I heard about buildx which is part of the effort to split the building of images and the running if I got that correctly. 

The full output looks like this:

```
> docker build -t test .
Sending build context to Docker daemon  5.632kB
Step 1/4 : FROM mcr.microsoft.com/windows/nanoserver:1909 as windows-base
 ---> 8ad8cde68ea6
Step 2/4 : FROM windows-base as should-be-skipped
 ---> 8ad8cde68ea6
Step 3/4 : RUN "exit 255"
 ---> Running in 59bb1f67fecc
The command 'cmd /S /C "exit 255"' returned a non-zero code: 255
```

As you can see, the build fails because it executed a stage which I would have expected to be pruned,  On linux, `docker build` will skip unused stages and, apart from being a nice optimization, it enables a couple of use cases like having a time-consuming unit-testing stage that you just target when needed.

My expectation is that the stage should only get built if it is inherited from the final target, or if needed by executed operations (ex. `copy --from=`).

**Comment by tonistiigi** [comment]
Yes, this is the output of the old docker build implementation. The ability to skip over unused stages is a buildkit-only feature not available there. Old builder always goes through all dockerfile commands from start to end.

**Comment by gaspardpetit** [comment]
I see, and BuildKit is not available for Windows. I'll close this issue considering it's a known limitation of the old builder. Thanks for your time!

**Comment by tonistiigi** [comment]
https://github.com/moby/buildkit/issues/616 https://github.com/microsoft/Windows-Containers/issues/34
