### ISSUE TITLE
docker build ??

### ISSUE THREAD

**Issue by abcdbdocker** [docker/buildx#882]
I'm calling build with the Python Docker API and there is an error saying I can't find dist but I have it in my current directory Build (Fileobj =dockefile,pull=True,tag="{0}/{1}". Format (tag),rm=True,nocache=True,decode=True,timeout=5

file_dist_str = """

The FROM nginx: 1.20.0 - alpine

COPY dist /usr/share/nginx/html

EXPOSE {1}

""".format(sou_path,port)

dockefile = BytesIO(dockefile_str.encode("utf8"))

Error message:

{'errorDetail': {'message': 'ADD failed: file not found in build context or excluded by .dockerignore: stat dist: file does not exist'}, 'error': 'ADD failed: file not found in build context or excluded by .dockerignore: stat dist: file does not exist'}

Am I missing any arguments when I call the build method?

**Comment by crazy-max** [comment]
@abcdbdocker You should ask to the author of this API. This repository is about the buildx builder component.
