### ISSUE TITLE
Apple M1 linux/amd64 not working?

### ISSUE THREAD

**Issue by FerusAndBeyond** [docker/buildx#886]
I am trying to create a docker image for a virtual machine with linux amd64 from an apple m1.

I create a builder:

`docker buildx create --use --name my_builder --platform linux/amd64`

and `docker buildx use my_builder`

Then I use it with:

`docker buildx bake --push --no-cache`

But the generated image is still arm64 and not amd64.

If I do:

`docker buildx bake --push --no-cache --set=target.platform="linux/amd64"`

Then I get: `error: could not find any target matching 'target'`

What am I doing wrong?

**Comment by crazy-max** [comment]
@FerusAndBeyond `target` must be a valid target in your bake definition or you can override with:

```console
docker buildx bake --push --no-cache --set=*.platform=linux/amd64
```

**Comment by FerusAndBeyond** [comment]
@crazy-max Tried that also, then I get: `zsh: no matches found: --set=*.platform=linux/amd64`

**Comment by crazy-max** [comment]
What's the output of `docker buildx inspect`?

**Comment by FerusAndBeyond** [comment]
This:

```
Name:   my_builder
Driver: docker-container

Nodes:
Name:      my_builder0
Endpoint:  unix:///var/run/docker.sock
Status:    running
Platforms: linux/amd64*, linux/arm64, linux/riscv64, linux/ppc64le, linux/s390x, linux/386, linux/mips64le, linux/mips64, linux/arm/v7, linux/arm/v6
```

**Comment by tonistiigi** [comment]
`*` need to be escaped/single-quoted in shell. `*` was just example as you didn't post your target name in bake file. Normally you just want to use the name directly.

**Comment by crazy-max** [comment]
Yes like @tonistiigi said. What's the content of your bake file btw? That would help.

**Comment by FerusAndBeyond** [comment]
@tonistiigi @crazy-max Using single-quote around the asterisk made it work and the produced image is now for amd64! Thanks :)
