### ISSUE TITLE
Bake : Allowed "/" in target names collides with bake --push option

### ISSUE THREAD

**Issue by MaximeWeyl** [docker/buildx#888]
The docker-bake.hcl file allows target names to contain "/" (in my case the target name was the same as the tag I planned to use).
However, this breaks the --push option because it is a shorthand for ```--set=*.output=type=registry```, and * does not match slashes wich results on this error, which took me time to understand since I did not use the * syntax myself :

```
error: could not find any target matching '*'
````

A simple workaround for me was to prevent using slashes in my target name. 

However I think it would be more consistent to prevent using slashes in the target name right from the beginning, or to find a way to make it compatible with the push option.

**Comment by tonistiigi** [comment]
@crazy-max I think not allowing slashes would be a way to go for this. If we want to do selectors by target name in hcl in the future it would be problematic as well(eg. `dockerfile = target.othername.dockerfile`).
