### ISSUE TITLE
[feature request] - static download link to latest stable version (..../download/vlatest/latest.linux.amd64)

### ISSUE THREAD

**Issue by SnickCH** [docker/buildx#899]
**Situation**
I'm building automated images on a weekly base for my own use. At the moment I have to change the download link manually, each time there is a new version, because the version number is in the download link. At the moment I have to handle it with variables that I change manually (${BUILDX_VERSION}=

Generic: https://github.com/docker/buildx/releases/download/v${BUILDX_VERSION}/buildx-v${BUILDX_VERSION}.linux-amd64"
Example:  https://github.com/docker/buildx/releases/download/v0.7.1/buildx-v0.7.1.linux-amd64

**Feature Request**
Add an additional download link that is static for the actual versions, something like:
https://github.com/docker/buildx/releases/download/vStable/buildx-vStable.linux-amd64 for the stable version
https://github.com/docker/buildx/releases/download/vLatest/buildx-vLatest.linux-amd64 for the latest version (unstable etc.)

With this, it would be much easier to automate, because it doesn't matter which version is the actual one.

**Comment by crazy-max** [comment]
@SnickCH You can use our [buildx-bin image](https://github.com/docker/buildx#from-dockerfile) for that purpose.

**Comment by SnickCH** [comment]
@crazy-max Thank you very much for the input - I missed this part somehow (sorry) and will take a look at it on the weekend.

Still I think it would be a good thing to have a static download link to the newest version, for what ever reason people like to have a way to download the latest stable version in an automated way.

**Comment by SnickCH** [comment]
@crazy-max I tested it and works perfect for my container. 

Therefore I close this feature request, because I have a solution. Thank you very much for your great work with buildx
