### ISSUE TITLE
multi arch build fails on cross compile

### ISSUE THREAD

**Issue by omerh** [docker/buildx#900]
I am trying to build a nodejs project multi arch, that on my mac works.
when trying to run in on a linux server and build on arm64 an amd64 image or on amd64 build an ar64 image it fails with the following error:

```
   6 | >>> RUN npm install --no-optional --production
error: failed to solve: process "/dev/.buildkit_qemu_emulator /bin/sh -c npm install --no-optional --production" did not complete successfully: exit code: 1
```

Running on docker-ce `Version:          20.10.8`
buildx `github.com/docker/buildx v0.6.1-docker 260d07a9a19b03df969787496419a0808a27ac61`

Please assist

**Comment by crazy-max** [comment]
@omerh Missing emulators on your linux server I guess:

```shell
$ docker run --privileged --rm tonistiigi/binfmt --install all
```

**Comment by omerh** [comment]
Found it.
Yes, you are correct! Thanks
