### ISSUE TITLE
Building docker-compose files may choke on env_files with spaces

### ISSUE THREAD

**Issue by jcfj** [docker/buildx#903]
Quick problem reproducer:
```bash
echo '{"services":{"scratch":{"build":".","env_file":["env"]}},"version":"3"}' >docker-compose.yaml
echo FROM alpine >Dockerfile
echo asdf=bsdf -csdf >env
docker buildx bake
```
Fails with
```
[+] Building 0.0s (0/0)                                                                                                                                                      
error: unexpected character "-" in variable name near "-csdf\n"
```
but builds and runs fine with `docker-compose build`.
The problem is likely that the env parser treats the env file as space separated, where it is actually line separated (and anyway bake shouldn't have to care, since the env file is only used during execution).

**Comment by tonistiigi** [comment]
@crazy-max Is it just compose behavior because I don't think we do any env parsing?

**Comment by tonistiigi** [comment]
> Reading the source, I should probably re-report this bug against compose-go?

If you can reproduce with compose-go as well then yes. Seems to me as well that the relevant code is in there.
