### ISSUE TITLE
`buildx bake` complains about undefined `default` network

### ISSUE THREAD

**Issue by hiimdoublej-swag** [docker/buildx#906]
My compose file is like this
```yaml
version: "3"
services:
  test:
    build: .
    networks:
    - default
```
The `default` network here is okay, even though it's not defined in a `network` .
`docker-compose up` does just fine and no errors.
However, if I try `docker buildx bake -f docker-compose.yml`, it will complain about the "undefined" network.
```
[+] Building 0.0s (0/0)
error: service "test" refers to undefined network default: invalid compose project
```
IMHO the `default` network should've been fine since 
1) It is the default network created when using docker compose.
2) Running `docker-compose up` on the same file doesn't show an error, proving that it is a valid compose file.

So I think this is a bug ? If it is please do let me know how I can be helpful to get this fixed. Thanks.

**Comment by hiimdoublej-swag** [comment]
Just recognized that this is more of an issue with `compose-go` rather than `buildx`.
I've created a new issue there. https://github.com/compose-spec/compose-go/issues/216
This issue is considered closed.

**Comment by ndeloof** [comment]
This issue is caused by bake intentionally skipping the compose model normalization:
https://github.com/docker/buildx/blob/master/bake/compose.go#L39
