### ISSUE TITLE
failed commit on ref "index-sha256:49ec4d...": unexpected status: 404 Not Found

### ISSUE THREAD

**Issue by gitfxx** [docker/buildx#910]
buildx-version:v0.7.2
buildkit:v0.9.1

I encountered this error while building with -- Driver Kubernetes
I wonder what caused this error

> [2022-01-10 15:04:00.630] #31 exporting to image
> [2022-01-10 15:04:00.630] #31 exporting layers done
> [2022-01-10 15:04:00.630] #31 exporting manifest sha256:950c18c49c2fc3c0e1c0dd9b30f35cd912baa561379f9bdcb84a5cad361fc069 done
> [2022-01-10 15:04:00.630] #31 exporting config sha256:845eaefc2913870ba3a3ce7857234ef46d4c7311144c4e1850dd0b455276e52d done
> [2022-01-10 15:04:00.630] #31 exporting manifest list sha256:49ec4d77efe346bd066fd78f047a78a306db2b1cbde3b84b4d6bc99e244674cb done
> [2022-01-10 15:04:00.630] #31 pushing layers
> [2022-01-10 15:04:00.891] #31 pushing layers 0.2s done
> [2022-01-10 15:04:00.891] #31 pushing manifest for image.xxx.cn/xxx/xxx
> [2022-01-10 15:04:01.465] #31 pushing manifest for image.xxx.cn/xxx/xxx 0.3s done
> [2022-01-10 15:04:01.465] #31 ERROR: failed commit on ref "index-sha256:49ec4d77efe346bd066fd78f047a78a306db2b1cbde3b84b4d6bc99e244674cb": unexpected status: 404 Not Found
> [2022-01-10 15:04:01.465] 
> [2022-01-10 15:04:01.465] #28 [linux/arm64 builder 3/4] COPY . .
> [2022-01-10 15:04:03.387] #28 DONE 4.1s
> [2022-01-10 15:04:03.387] ------
> [2022-01-10 15:04:03.387]  > exporting to image:
> [2022-01-10 15:04:03.387] ------
> [2022-01-10 15:04:03.387] Error: failed to solve: failed commit on ref "index-sha256:49ec4d77efe346bd066fd78f047a78a306db2b1cbde3b84b4d6bc99e244674cb": unexpected status: 404 Not Found
> [2022-01-10 15:04:03.387] Usage:

the builder pod logs:

> time="2022-01-08T03:19:25Z" level=debug msg="remove content" key="sha256:49ec4d77efe346bd066fd78f047a78a306db2b1cbde3b84b4d6bc99e244674cb"
> time="2022-01-08T03:19:25Z" level=debug msg="removed content" digest="sha256:49ec4d77efe346bd066fd78f047a78a306db2b1cbde3b84b4d6bc99e244674cb"
> time="2022-01-10T06:40:05Z" level=debug msg="checking and pushing to" spanID=f6f99c1fcfa5b9e5 traceID=43a747ee75aac2461d02915bfb3b9862 url="https://image.xxx.cn/v2/xxxx/xxx/manifests/sha256:49ec4d77efe346bd066fd78f047a78a306db2b1cbde3b84b4d6bc99e244674cb"
> time="2022-01-10T06:40:05Z" level=debug msg="unexpected response" body="{\"errors\":[{\"code\":\"NOT_FOUND\",\"message\":\"http status code: 404, body: {\\\"errors\\\":[{\\\"code\\\":\\\"MANIFEST_UNKNOWN\\\",\\\"message\\\":\\\"manifest unknown\\\",\\\"detail\\\":{\\\"Name\\\":\\\"ccos-ops/coc-sys-mgt\\\",\\\"Revision\\\":\\\"sha256:49ec4d77efe346bd066fd78f047a78a306db2b1cbde3b84b4d6bc99e244674cb\\\"}}]}\\n\"}]}\n" resp="&{404 Not Found 404 HTTP/1.1 1 1 map[Connection:[keep-alive] Content-Type:[application/json; charset=utf-8] Date:[Mon, 10 Jan 2022 06:40:05 GMT] Server:[nginx/1.17.8] Set-Cookie:[sid=32c9797dfec0dc723bdd625f420194ad; Path=/; HttpOnly] Strict-Transport-Security:[max-age=15724800; includeSubDomains] Vary:[Accept-Encoding] X-Request-Id:[11f9f4f49c898738ce3b4309e9a9e1d9]] 0xc0070743f0 -1 [chunked] false true map[] 0xc000895400 0xc0026de370}" spanID=f6f99c1fcfa5b9e5 traceID=43a747ee75aac2461d02915bfb3b9862

**Comment by ArnaudPalgen** [comment]
@gitfxx I have the same issue. Did you solve this problem ?

**Comment by gitfxx** [comment]
> @gitfxx I have the same issue. Did you solve this problem ?

It's fixed. It's a problem at harbor,

**Comment by FBIanderson** [comment]
what is the root cause , i met this problem
