### ISSUE TITLE
nested `inherits` only affects first target

### ISSUE THREAD

**Issue by maxheld83** [docker/buildx#912]
it appears that `inherits` cannot be nested, or, (for me: worse), it only affects the *first* target.

For example `docker buildx bake --print --file FILE` on:

```hcl
target "grandparent" {
  output = ["type=docker"]
}

target "parent" {
  inherits = ["grandparent"]
  args = {
    FOO = "bar"
  }
}

target "child 1" {
  inherits = ["parent"]
}

target "child 2" {
  inherits = ["parent"]
}

group "default" {
  targets = [
    "child 1",
    "child 2"
  ]
} 
```

```
{
  "group": {
    "default": {
      "targets": [
        "child 1",
        "child 2"
      ]
    }
  },
  "target": {
    "child 1": {
      "context": ".",
      "dockerfile": "Dockerfile",
      "args": {
        "FOO": "bar"
      },
      "output": [
        "type=docker"
      ]
    },
    "child 2": {
      "context": ".",
      "dockerfile": "Dockerfile",
      "args": {
        "FOO": "bar"
      }
    }
  }
}
```

My expectation would have been that either:

- **both** child 1 and 2 inherit `output`
- **neither** inherit `output` and the parser tells me that I can't nest `inherits`

Took me a while to figure this out 🙃

(Amazing work on bake -- love it ❤️)

**Comment by crazy-max** [comment]
@maxheld83 Which buildx version?

**Comment by crazy-max** [comment]
Ok after investigating it looks like if the inherited target has already been visited it's skipped:

https://github.com/docker/buildx/blob/2b4d305c58234508669b3a797a983ca08e8ff4d1/bake/bake.go#L408-L410

We should add the the main target to that visited key I think so it would work for grouped targets too. cc @tonistiigi
