### ISSUE TITLE
Multi-arch build using `--platform` and `--build-arg`

### ISSUE THREAD

**Issue by yellowmamba** [docker/buildx#922]
Hi there,

I'm having some confusion around using `--build-arg` in conjunction with `--platform`. Here's an example of Dockerfile

```
ARG ARCH
RUN curl "https://awscli.amazonaws.com/awscli-exe-linux-${ARCH}.zip" -o "awscliv2.zip" \
```

When I build for `amd64` and `arm64`, I do this

```
docker buildx build --platform=linux/amd64,linux/arm64 --build-arg ARCH=x86_64,aarch64 -t my-multi-arch-image .
```

The result of the curl command is either platform is
```
RUN curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64,aarch64.zip" -o "awscliv2.zip"
```

According to docs,
```
--build-arg stringArray
--platform stringArray
```

I thought they both use comma-separated syntax, am I understanding it incorrectly?

**Comment by morlay** [comment]
Here real world example

You could use `case $(uname -m)` to define the correct file.
https://github.com/istio/tools/blob/master/docker/build-tools/Dockerfile#L265-L271

or just use the platform build arg `TARGETARCH`:
https://github.com/istio/tools/blob/master/docker/build-tools/Dockerfile#L691

**Comment by yellowmamba** [comment]
Yeah I am not a big fan of having conditional logic in Dockerfile. `TARGETARCH` unfortunately does not return the exact value I need in my RUN command. I'm more looking for an successful example of using `--build-arg` alongside `--platform` as documented in buildx.

**Comment by crazy-max** [comment]
@yellowmamba https://github.com/docker/buildx/pull/717#issuecomment-912455049

**Comment by morlay** [comment]
> `TARGETARCH` unfortunately does not return the exact value I need in my RUN command

have to use `case ${TARGETARCH}` in `RUN` of `Dockerfile`. 

`--build-arg` only support pass same value for different platforms now.

**Comment by crazy-max** [comment]
https://pkg.go.dev/github.com/spf13/pflag#StringArray
> StringArray defines a string flag with specified name, default value, and usage string. The return value is the address of a []string variable that stores the value of the flag. The value of each argument will not try to be separated by comma. Use a StringSlice for that. 

https://pkg.go.dev/github.com/spf13/pflag#StringSlice
> StringSlice defines a string flag with specified name, default value, and usage string. The return value is the address of a []string variable that stores the value of the flag. Compared to StringArray flags, StringSlice flags take comma-separated value as arguments and split them accordingly. For example:
>
> ```
> --ss="v1,v2" --ss="v3"
> ```
>
> will result in
>
> ```
> []string{"v1", "v2", "v3"}
> ```

**Comment by morlay** [comment]
@crazy-max I think he just want this for different platforms.

```Dockerfile
# TARTETARCH=amd64
RUN curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"

# TARTETARCH=arm64
RUN curl "https://awscli.amazonaws.com/awscli-exe-linux-aarch64.zip" -o "awscliv2.zip"
```

In this case, could be simple without `--build-arg`

```Dockerfile
RUN curl "https://awscli.amazonaws.com/awscli-exe-linux-$(uname -m).zip" -o "awscliv2.zip"
```

**Comment by crazy-max** [comment]
@morlay Yes exactly `TARGETARCH` is the way to go if the arch matches the one in the filename you want to download otherwise use `case ${TARGETARCH}` or `case ${TARGETPLATFORM}` like https://github.com/crazy-max/docker-docker/blob/782b584781cd0130798a6640c37d40476c532a10/Dockerfile-20.10#L17-L23.

**Comment by crazy-max** [comment]
Also you can simply use the official [AWS CLI version 2 Docker image](https://hub.docker.com/r/amazon/aws-cli):

```dockerfile
COPY --from=amazon/aws-cli /usr/local/bin/aws /usr/local/bin/aws
```
