### ISSUE TITLE
Error response from daemon: cgroup-parent for systemd cgroup should be a valid slice named as "xxx.slice"

### ISSUE THREAD

**Issue by boredazfcuk** [docker/buildx#935]
Hi,

I've upgraded my system to Debian Bullseye and now I can no longer build containers as I get this error:

```
 => ERROR [internal] booting buildkit                                                                                                                                           0.0s
 => => starting container buildx_buildkit_builder0                                                                                                                        0.0s
------
 > [internal] booting buildkit:
------
error: Error response from daemon: cgroup-parent for systemd cgroup should be a valid slice named as "xxx.slice"
```
Docker info:
```
Client: Docker Engine - Community
 Version:           20.10.12
 API version:       1.41
 Go version:        go1.16.12
 Git commit:        e91ed57
 Built:             Mon Dec 13 11:45:37 2021
 OS/Arch:           linux/amd64
 Context:           default
 Experimental:      true

Server: Docker Engine - Community
 Engine:
  Version:          20.10.12
  API version:      1.41 (minimum version 1.12)
  Go version:       go1.16.12
  Git commit:       459d0df
  Built:            Mon Dec 13 11:43:46 2021
  OS/Arch:          linux/amd64
  Experimental:     true
 containerd:
  Version:          1.4.12
  GitCommit:        7b11cfaabd73bb80907dd23182b9347b4245eb5d
 runc:
  Version:          1.0.2
  GitCommit:        v1.0.2-0-g52b36a2
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0
```

My container details from `docker inspect buildx_buildkit_builder0`:
https://pastebin.com/uqq6ZMZX

A bit of Googling tells me that Bullseye has implemented cgroups v2.

Things I've tried that haven't worked...

Reverting to cgroups v1, by editing /etc/default/group with the two lines beneath, running `update-grub` and then rebooting
```
GRUB_CMDLINE_LINUX_DEFAULT="systemd.unified_cgroup_hierarchy=0"
GRUB_CMDLINE_LINUX="systemd.unified_cgroup_hierarchy=0"
```

Editing /etc/docker/daemon.json to add the line beneath and then restarting the docker service:
```
   "exec-opts": ["native.cgroupdriver=systemd"],
```

Any other ideas?

Thanks.

**Comment by boredazfcuk** [comment]
Hi, 
I've managed to fix this today.
My `/etc/apt/sources.list.d/docker.list` was still specifying the Docker apt repository as:
```
deb [arch=amd64] https://download.docker.com/linux/debian buster stable
```
so Docker was running on the Buster version, not Bullseye.

I removed docker-ce, updated `/etc/apt/sources.list.d/docker.list` to:
```
deb [arch=amd64] https://download.docker.com/linux/debian bullseye stable
```
I then did `apt update && apt upgrade` which upgraded container.io. I then re-installed reinstalled docker-ce.

Docker was started with `"exec-opts": ["native.cgroupdriver=systemd"],` in daemon.json and the buildkit container still failed to start with the error:
```
cgroup-parent for systemd cgroup should be a valid slice named as "xxx.slice"
```

I then recreated my builder:
```
docker buildx rm builder
docker buildx create --use --name builder tcp://builder:2375 --platform linux/amd64,linux/386,linux/arm/v6,linux/arm64,linux/arm/v7 --driver-opt env.BUILDKIT_STEP_LOG_MAX_SIZE=10000000,env.BUILDKIT_STEP_LOG_MAX_SPEED=1000000000

```
connected to the builder machine and re-imported the certificates:
```
BUILDER=$(docker ps -a | grep buildkit | cut -f1 -d' ')
docker container start $BUILDER
docker cp /etc/docker/registry/certs/domain.crt $BUILDER:/usr/local/share/ca-certificates/
docker exec $BUILDER update-ca-certificates
docker restart $BUILDER
unset BUILDER
```

and now everything is working OK again.

Hope this helps someone else in the same situation.

**Comment by bencwallace** [comment]
For anyone else who comes across this, I had the same issue and deleting the container in the error message (`buildx_buildkit_builder0` above) with `docker container rm <container_name>` fixed it for me.

**Comment by tfriedel** [comment]
This fixed it for me:
```docker buildx rm builder```
I had the issue after upgrading ubuntu 20.04 to 22.04 to 24.04.
