### ISSUE TITLE
If a `docker-compose.yml` and `docker-bake.hcl` both exist, then `buildx bake` will read the `docker-compose.yml`.

### ISSUE THREAD

**Issue by gabrieldemarmiesse** [docker/buildx#936]
I'm aware that there are options to change the file being read by buildx. I'm just discussing the defaults. 

If both file exist, it makes sense to read the docker-bake.hcl since this file can only be read by buildx. 

There is no workflow where the docker-bake.hcl exists the user doesn't want the docker-bake.hcl to be used by buildx. For this reason, buildx should try to find a docker-bake.hcl first and then, fallback to a docker-compose.yml if it doesn't exist.

**Comment by tonistiigi** [comment]
When both files exist it doesn't prefer the compose file over hcl file but reads both. Eg. as if you typed `bake -f docker-bake.hcl -f docker-compose.yml `. The values in HCL take precedence, so if you define a "default" group there it will overwrite the implicit default group in compose file.

**Comment by gabrieldemarmiesse** [comment]
Thank you for the clarification! I should be able to make the workflow work without the -f flag now. Have a great day and thank you for this amazing tool!
