### ISSUE TITLE
Bulk Edit Tags

### ISSUE THREAD

**Issue by driverpt** [docker/buildx#941]
Bulk Edit Tags from an existing Manifest List, auto-propagating to child manifests.

We want to add custom tags when a given Manifest List gets promoted to certain environment.

e.g.:

`foo:someversion` by adding `staging-123456`, the child images should also get the same tag

**Comment by crazy-max** [comment]
You can use [`imagetools create`](https://github.com/docker/buildx/blob/master/docs/reference/buildx_imagetools_create.md):

```shell
docker buildx imagetools create --tag foo:staging-123456 foo:someversion
```
