### ISSUE TITLE
Ability to build multi-platform images not in parallel

### ISSUE THREAD

**Issue by timorkal** [docker/buildx#942]
Hello,

I am using the docker buildx to build multi-platform images (aka: amd64/arm64...).
Because I am targeting specific device for building my arm images, I am overwhelming it with builds.
So my question is, is there an ability/switch to perform only 1 build at each time on specific device, so the next platform will wait till the first platform build will end?

**Comment by crazy-max** [comment]
@timorkal https://github.com/docker/buildx/issues/722#issuecomment-895148966
