### ISSUE TITLE
buildx error with "docker-php-ext-install" on linux

### ISSUE THREAD

**Issue by giu1io** [docker/buildx#944]
Hi,

When I try to build the following Dockerfile

```
FROM php:7.4.27-fpm-alpine3.15

RUN docker-php-ext-install pdo pdo_mysql
```

with this buildx command: 
```
docker buildx create --platform linux/amd64,linux/arm64/v8 --use
docker buildx build --platform linux/arm64 --tag test-pdo:latest .
```

from a `linux/amd64` host I get the following error:

```
 => ERROR [2/2] RUN docker-php-ext-install pdo pdo_mysql                                                                                                                     0.2s
------
 > [2/2] RUN docker-php-ext-install pdo pdo_mysql:
#5 0.187 tar: Child returned status 1
#5 0.188 tar: Error is not recoverable: exiting now
------
Dockerfile:3
--------------------
   1 |     FROM php:7.4.27-fpm-alpine3.15
   2 |
   3 | >>> RUN docker-php-ext-install pdo pdo_mysql
   4 |
--------------------
error: failed to solve: process "/dev/.buildkit_qemu_emulator /bin/sh -c docker-php-ext-install pdo pdo_mysql" did not complete successfully: exit code: 2
```
Ubuntu 20.04
Docker version `20.10.12, build e91ed57`
Buildx version `github.com/docker/buildx v0.7.1-docker 05846896d149da05f3d6fd1e7770da187b52a247`

------
The same Dockerfile builds correctly with the same buildx command on Docker for Mac. On the Linux host the `linux/amd64` build with buildx finishes correctly.

Docker for Mac versions (tested on both Intel Mac and Apple Silicon Mac)
Docker version `20.10.11, build dea9396`
Buildx version `github.com/docker/buildx v0.7.1 05846896d149da05f3d6fd1e7770da187b52a247`

---------

Thank you in advance!

**Comment by crazy-max** [comment]
@giu1io Have you followed https://github.com/docker/buildx#building-multi-platform-images, in particularly?:

```shell
docker run --privileged --rm tonistiigi/binfmt --install all
```

**Comment by giu1io** [comment]
> @giu1io Have you followed https://github.com/docker/buildx#building-multi-platform-images, in particularly?:
> 
> ```shell
> docker run --privileged --rm tonistiigi/binfmt --install all
> ```

I did not run that command. I missed the line where it says "While Docker Desktop comes preconfigured with binfmt_misc support for additional platforms...". That explains why it was working on Docker Desktop. 

I ran it now and it works correctly. Thank you for your help!
