### ISSUE TITLE
Buildx should respect `DOCKER_BUILDKIT=0`

### ISSUE THREAD

**Issue by felipecrs** [docker/buildx#957]
In order to retain compatibility, the buildx should respect the `DOCKER_BUILDKIT=0` environment variable, so that the following statement is valid for people who also uses buildx as their default builder:

> If you know the environment where you plan to deploy the container built with this extension, you can build the image with `DOCKER_BUILDKIT=0 docker build --memory=4096m --build-arg AUTO_MEM_CALCULATION=true` so that the database is created with 4GB of memory allocated.

Taken from https://github.com/oracle/docker-images/blob/3c7f1e004f7e1404c290536b95dabcae1fba7237/OracleDatabase/SingleInstance/extensions/prebuiltdb/README.md#limitations

The alternative is to of course run:

```console
$ docker buildx uninstall

$ DOCKER_BUILDKIT=0 docker build --memory=4096m --build-arg AUTO_MEM_CALCULATION=true

$ docker buildx install
```

Which I believe is not very nice. If Buildx cannot work without Buildkit, it can simply fallback to docker's default builder if `DOCKER_BUILDKIT=0`.

**Comment by tonistiigi** [comment]
Buildx is buildkit-only and does not depend on Docker CLI/daemon. Opting-in to buildx is an opt-in for buildkit as well. With `docker build` command we will continue to understand `DOCKER_BUILDKIT=0` even in the current master version where the default has switched to buildx.

**Comment by felipecrs** [comment]
In other words, are you saying that at some time a new version of docker will be released which will fix this issue (independently on buildx)?

**Comment by felipecrs** [comment]
Just to be clear, I don't mean that `docker buildx build` should respect `DOCKER_BUILDKIT=0`. I mean that `docker build` (with `docker buildx install`) should.

**Comment by tonistiigi** [comment]
The next version of Docker cli will not require `docker buildx install` to make buildx default for `docker build`.

**Comment by felipecrs** [comment]
Nice, but will it honor `DOCKER_BUILDKIT=0` to disable buildkit?
