### ISSUE TITLE
'buildx' is not a docker command on Windows 10

### ISSUE THREAD

**Issue by smurfpandey** [docker/buildx#96]
I am trying to build multi-arch images following this article: https://engineering.docker.com/2019/04/multi-arch-images/,
Updated the docker desktop to edge release. But `docker buildx ls` command is not working. It's throwing error:
```
docker: 'buildx' is not a docker command.
See 'docker --help'
```

I am on docker desktop for windows. 
Docker Desktop version: 2.0.5.0 (35318)
Engine: 19.03.0-rc2

OS: Windows 10 Pro, Version 1803

**Comment by tonistiigi** [comment]
I believe you need to set `experimental: enabled` in the CLI conf since rc2 (or get the release build from this repo that doesn't need it). @tiborvass

**Comment by atenni** [comment]
I'm working through the same article on Docker Desktop for Mac and had to export the following environment variable to get it to work:

```bash
export DOCKER_CLI_EXPERIMENTAL=enabled
```

**Comment by rvdh** [comment]
As stated in [the release notes for Docker Desktop for Mac](https://docs.docker.com/docker-for-mac/edge-release-notes/) and [Docker Desktop for Windows](https://docs.docker.com/docker-for-windows/edge-release-notes/): 

* Docker Desktop includes the buildx plugin (currently experimental).
* Selecting the Experimental features checkbox on the Docker Desktop Preferences Daemon page enables experimental features in the Docker daemon and the Docker CLI.

**Comment by johnjansen** [comment]
> As stated in [the release notes for Docker Desktop for Mac](https://docs.docker.com/docker-for-mac/edge-release-notes/) and [Docker Desktop for Windows](https://docs.docker.com/docker-for-windows/edge-release-notes/):
> 
> * Docker Desktop includes the buildx plugin (currently experimental).
> * Selecting the Experimental features checkbox on the Docker Desktop Preferences Daemon page enables experimental features in the Docker daemon and the Docker CLI.

its the multistate checkbox thats confusing people

**Comment by smurfpandey** [comment]
I created config.json file with below content in `.docker` folder in user directory & it worked.

```
{ "experimental":"enabled" }
```
