### ISSUE TITLE
How to push to private registry when using kubernetes buildx driver

### ISSUE THREAD

**Issue by gboer** [docker/buildx#960]
We are deploying buildx into kubernetes and can successfully build our images without any problems. However, we'd like to be able to push the images from buildx to our private registry and that's where things go wrong. We can specify the buildx configuration, to use specific client certs to connect to the registry (as far as I understand the documentation [here](https://github.com/moby/buildkit/blob/master/docs/buildkitd.toml.md)), but it is unclear how those client certs end up in the buildx pods. There are no configuration parameters for that anywhere.

Are we missing something here or does this simply not work/do we have to do something manually?

The error that we're getting is this:
```
[image-name] exporting to image:

------

error: failed to solve: rpc error: code = Unknown desc = unexpected status: 403 Forbidden
```

**Comment by tonistiigi** [comment]
https://github.com/docker/buildx/blob/master/docs/guides/custom-registry-config.md

**Comment by gboer** [comment]
ah, thanks @tonistiigi! We found out that it automatically copies the docker registry access that we have locally before creating the buildx instances. So it turned out that we didn't need to do anything ourselves. Really neat that it works that way. Just unfortunate that it isn't documented clearly anywhere (as far as I could see at least).
