### ISSUE TITLE
"No output specified for" warning should be handled for named contexts

### ISSUE THREAD

**Issue by crazy-max** [docker/buildx#968]
Warning for [no output specified](https://github.com/docker/buildx/blob/5939a23af6f0a1f4d818da659c477850b8cb6bd2/build/build.go#L627) should not be displayed if named context input is being used as dependency for another target that has a defined output:

```hcl
# docker-bake.hcl

target "base" {
  dockerfile = "baseapp.Dockerfile"
  args = {
    basefoo = "bar"
  }
}

target "app" {
  contexts = {
    baseapp = "target:base"
  }
}
```

```dockerfile
# Dockerfile
FROM baseapp
RUN echo "Hello world"
```

```dockerfile
# baseapp.Dockerfile
FROM alpine
WORKDIR /src
```

```
$ docker buildx bake --set app.tags=user/app:latest --set app.output=type=cacheonly app
...
#12 [app 1/2] RUN echo "Hello world"
#12 CACHED
WARNING: No output specified for docker-container driver. Build result will only remain in the build cache. To push result image into registry use --push or to load image into docker use --load
```

Not linked to this issue but if `len(opt) > 1` we should display the target name in the warning message.

cc @tonistiigi

**Comment by tonistiigi** [comment]
Yeah, either show warning if none of the targets have exports or if some of the targets set by the user don't have exports.
