### ISSUE TITLE
Platform darwin, what the? Since when? Is this for real?

### ISSUE THREAD

**Issue by brad-jones** [docker/buildx#97]
In the readme there is mention of building for multiple platforms:

> When invoking a build, the --platform flag can be used to specify the target platform for the build output, (e.g. linux/amd64, linux/arm64, darwin/amd64).

Is this suggesting that docker can now run natively on MacOs? Similar to building and running a native Windows container instead of running a Linux container inside a virtual machine.

I did a quick google but couldn't find anything obvious, I would have assumed something as major as this would have had plenty of advertisement so I am guessing it's not the holy grail I thought it was, so what does `darwin/amd64` do in the context of `docker buildx build --platform`?

**Comment by tonistiigi** [comment]
Doing `--platform=darwin/amd64` doesn't necessarily mean that containers need to run in darwin. With multi-stage builds you can do cross-compilation to the platform that was requested with the flag. Usually, you would use `--platform=darwin/amd64` with `--output` to get mac binaries as creating a darwin image has very limited use.

Eg. `moby/buildkit` and buildx images/release are built for 8 architectures(including for Darwin) in travis directly from the Dockerfile  with travis being able to only run linux/amd64 containers. Or you can look at https://github.com/tonistiigi/wasm-cli-plugin that does `--platform wasi/wasm` while you can't directly `docker run` the webassembly images (yet).
