### ISSUE TITLE
Support for starting buildkit with entitlements

### ISSUE THREAD

**Issue by andrewrynhard** [docker/buildx#99]
As the title suggests, I'd like to run a build with `docker buildx build --network=host`, but I'm seeing:

```
failed to solve: rpc error: code = Unknown desc = network.host is not allowed
```

It looks like we need to set the proper entitlement, but `docker buildx create` does not expose that option.

**Comment by tonistiigi** [comment]
`network=host` is considered insecure, you need to pass `--buildkitd-flags '--allow-insecure-entitlement network.host'` on creating a builder.
