### ISSUE TITLE
cli usage output looks wrong with builder persistent flag

### ISSUE THREAD

**Issue by crazy-max** [docker/buildx#990]
Usage output looks wrong for every command with `--builder` flag being printed for each of them:

```
$ docker buildx ls --help

Usage:  docker buildx ls

List builder instances
Usage of buildx:
      --builder string
```

```
$ docker buildx inspect --help

Usage:  docker buildx inspect [NAME]

Inspect current builder instance

Options:
      --bootstrap        Ensure builder has booted before inspecting
      --builder string   Override the configured builder instance
Usage of buildx:
      --builder string
```

Here `Usage of buildx` section should not be there. After taking a quick look, it seems linked to [`defaultUsage` func in pflag](https://github.com/spf13/pflag/blob/d5e0c0615acee7028e1e2740a11102313be88de1/flag.go#L766-L783).

Redirecting stderr to null removes it:

```
$ docker buildx inspect --help 2>/dev/null

Usage:  docker buildx inspect [NAME]

Inspect current builder instance

Options:
      --bootstrap        Ensure builder has booted before inspecting
      --builder string   Override the configured builder instance
```

Any idea @thaJeztah?

**Comment by crazy-max** [comment]
It looks better if buildx is used in standalone:

```
$ docker buildx inspect --help
Inspect current builder instance

Usage:
  buildx inspect [NAME] [flags]

Flags:
      --bootstrap   Ensure builder has booted before inspecting
  -h, --help        help for inspect

Global Flags:
      --builder string   Override the configured builder instance
```

So might be linked to the way docker cli configures cobra for plugins?

**Comment by thaJeztah** [comment]
> So might be linked to the way docker cli configures cobra for plugins?

Quite possible; I know there were some quirks with global flags at the time (as "global" no longer is "global" if it's a plugin). I don't recall the details though 🤔

**Comment by crazy-max** [comment]
Fixed in https://github.com/docker/compose-cli/pull/2149
