### ISSUE TITLE
buildx doesn't favor native builders over qemu ones

### ISSUE THREAD

**Issue by Romain-Geissler-1A** [docker/buildx#999]
Hi,

I have a setup like this:

- One docker context named `aarch64` where running on a native aarch64 machine, but where qemu is installed (so it technically supports `x86_64` as well.
- One docker context named `x86_64` running on a native x86_64 machine.

I build a new builder like this:

```
docker buildx create --append --bootstrap --platform Linux/aarch64,Linux/x86_64 --driver docker-container --name Linux.aarch64-Linux.x86_64 aarch64
docker buildx create --append --bootstrap --name Linux.aarch64-Linux.x86_64 x86_64
```

Resulting in something like this:

```
> docker buildx ls
NAME/NODE                     DRIVER/ENDPOINT  STATUS  PLATFORMS
Linux.aarch64-Linux.x86_64    docker-container
  linux.aarch64-linux.x86_640 aarch64          running linux/arm64*, linux/amd64*, linux/riscv64, linux/ppc64le, linux/s390x, linux/386, linux/mips64le, linux/mips64
  linux.aarch64-linux.x86_640 x86_64           running linux/amd64, linux/amd64/v2, linux/amd64/v3, linux/386
aarch64                       docker
  aarch64                     aarch64          running linux/arm64, linux/amd64, linux/riscv64, linux/ppc64le, linux/s390x, linux/386
x86_64                        docker
  x86_64                      x86_64           running linux/amd64, linux/386
default *                     docker
```

and then I run a multi arch build like this:

`docker buildx build --pull --builder=Linux.aarch64-Linux.x86_64 --platform=Linux/aarch64,Linux/x86_64 --output=type=image,push=false .`

And for a reason I don't get, this runs *BOTH* builds on the aarch64 machine, so one of the build is slow. While there is a native x86 machine. Why doesn't buildx try to favor native builders over qemu ones ?

Note, I am using this buildx:

```
> docker buildx version 
github.com/docker/buildx v0.8.0 c8f7c1e93ffa9cfcf926cd3e6450af957f235b07
```

Cheers,
Romain

**Comment by Romain-Geissler-1A** [comment]
By the way, both node inside the builder seem to have the same name `linux.aarch64-linux.x86_640`, is it expected ? Should't there be a `linux.aarch64-linux.x86_641` ?

**Comment by tonistiigi** [comment]
They run on the aarch machine because you set `--platform Linux/x86_64` when creating it. Only set `--platform` when you  want to change the priority of the builder nodes and signal that you wish to use this node for building specific platform when multiple are available.

On `ls` output, you see platforms with manual priority override signified with `*`.

**Comment by Romain-Geissler-1A** [comment]
Ah sorry, I thought --plateform had to be given once at the creation of the builder, listing all possible architectures the builder will support (and not juste the node being added).

It works now, I am doing this:

```
docker buildx create --append --bootstrap --platform Linux/aarch64 --driver docker-container --name Linux.aarch64-Linux.x86_64 --node aarch64 aarch64
docker buildx create --append --bootstrap --platform Linux/x86_64 --name Linux.aarch64-Linux.x86_64 --node x86_64 x86_64
docker buildx build --pull --builder=Linux.aarch64-Linux.x86_64 --platform=Linux/aarch64,Linux/x86_64 --output=type=image,push=false .
```
